"""The flavoured `S` axiomatics — `\\cE_G` and its BPS quiver constraint.

**This suite is written to BE the axiom statements**, one test per statement,
so that it can be read as the axiomatics rather than as a regression net.  Each test's name is the claim; its docstring is
the claim in the paper's notation; its body decides it.

The setting.  As soon as a quiver has `N` identical nodes it
has a manifest `SU(N)` symmetry, so a quiver with groups of `N_a` nodes carries
`G = ∏_a SU(N_a)` — and one may as well package the group of nodes as a single
node carrying the `N_a`-dimensional irrep `r_a`.  Then, with `μ^w` the central
character of the maximal torus at the weight `w`,

    E^{(s;r)}_\\fq(X_γ)  =  ∏_{w ∈ r} E^{(s)}_\\fq(μ^w X_γ) ,

`\\cE_G ⊂ \\cG` is generated by the `E^{(s;r)}_\\fq(X_γ)^{±1}`, and the
flavoured BPS quiver constraint replaces the node charge monomials by
sequences:

    S  =  1  -  \\fq Σ_a χ_{r_a}(μ) X_{γ_a}  +  O(\\fq^2) .

What is EMERGENT and what is ENFORCED (the audit — a green check is
evidence only where the property is not built in):

* **Enforced** — the leading data.  The recursion solves for exactly it, so
  `verify_leading_data` is a regression guard on the arithmetic, never evidence
  about the conjectures.  It is here, and labelled, for that reason alone.
* **Emergent** — that each `Ω(γ)` is a `G`-character.  `Ω` is forced weight by
  weight, independently, with no Weyl symmetry imposed anywhere in the
  recursion; that the answer is nevertheless `W`-invariant is the substantive
  claim `S ∈ \\cE_G`.
* **Independent** — agreement with the **unfolded** quiver, run through the
  unflavoured engine `bps_factor_spectrum.BPSFactorSpectrum`.  The two share
  the univariate ray arithmetic and nothing else: this one recurses on the
  reduced cone with a weight grading, that one on the enlarged cone with no
  notion of flavour at all.

Run:  `python3 run_tests.py`
"""
import random
import sys

sys.path.insert(0, ".")

from bps_factor_spectrum import (
    BPSFactorSpectrum,
    acyclic_node_order,
    charge_series,
    mean_rank_key,
)
from habiro import HabiroElement
from flavoured_factor_spectrum import (
    FlavouredFactorSpectrum,
    FlavouredQuiver,
    FlavourSpace,
    build_flavoured_spectrum_generator,
    canonical_spectrum_generator,
    unfolded_spectrum_generator,
)

H0 = HabiroElement.zero()
H1 = HabiroElement.one()


# --------------------------------------------------------------------------
# the corpus
# --------------------------------------------------------------------------
#
# Every entry is UNFOLDABLE — its node reps are fundamentals, which is the
# author's ruling on what happens in reality (2026-09-13: *"the node irreps are
# fundamentals of SU(N_a) in reality"*) — and that is exactly what supplies the
# independent ground truth, since the unfolded object is then an ordinary BPS
# quiver.

CORPUS = [
    # (name, reduced exchange matrix, SU(N) per node, cone cutoff)
    ("A2, SU(2) on node 0",      [[0, 1], [-1, 0]],               [2, 1], 4),
    ("A2, SU(2) on node 1",      [[0, 1], [-1, 0]],               [1, 2], 4),
    ("A2, SU(2) x SU(2)",        [[0, 1], [-1, 0]],               [2, 2], 4),
    ("A2, SU(3) on node 0",      [[0, 1], [-1, 0]],               [3, 1], 4),
    ("A2, SU(2) x SU(3)",        [[0, 1], [-1, 0]],               [2, 3], 3),
    ("Kronecker-2, SU(2)",       [[0, 2], [-2, 0]],               [2, 1], 4),
    ("A1 x A1, SU(2) x SU(2)",   [[0, 0], [0, 0]],                [2, 2], 4),
    ("A3 linear, SU(2) middle",  [[0, 1, 0], [-1, 0, 1], [0, -1, 0]], [1, 2, 1], 3),
    ("A3 linear, SU(2) end",     [[0, 1, 0], [-1, 0, 1], [0, -1, 0]], [2, 1, 1], 3),
    ("3-cycle, SU(2)",           [[0, 1, -1], [-1, 0, 1], [1, -1, 0]], [2, 1, 1], 3),
]


def _quiver(entry):
    _, B, fac, D = entry
    return FlavouredQuiver(B, fac), D


def _same(a, b):
    keys = set(a) | set(b)
    return all(a.get(k, H0) == b.get(k, H0) for k in keys)


def _random_piece_key(seed):
    rng = random.Random(seed)
    memo = {}

    def key(*args):
        if args not in memo:
            memo[args] = rng.random()
        return memo[args]

    return key


# --------------------------------------------------------------------------
# the flavour space: weights and characters
# --------------------------------------------------------------------------

def test_weights_and_characters_round_trip_including_virtual_ones():
    """`decompose` inverts `irrep_weights`, on products and on signed sums.

    The `R(G)`-valued bookkeeping rests on this: a `W`-invariant weight function
    is the weight diagram of a unique virtual character.  Certified machinery
    (`SUNZPlusRing.from_abelian`), exercised here on the product groups this
    module actually builds.
    """
    for factors, reps in (
        ([2, 2], [((), ()), ((1,), ()), ((), (1,)), ((1,), (1,)), ((2,), (2,))]),
        ([3, 2], [((1,), ()), ((1, 1), (1,)), ((2, 1), (2,))]),
        ([4], [((1,),), ((1, 1),), ((2, 1),)]),
    ):
        F = FlavourSpace(factors)
        for r in reps:
            assert F.decompose(F.irrep_weights(r)) == {r: 1}, (factors, r)
        a, b = reps[-1], reps[0]
        wa, wb = F.irrep_weights(a), F.irrep_weights(b)
        mix = {k: wa.get(k, 0) - 2 * wb.get(k, 0) for k in set(wa) | set(wb)}
        got = FlavourSpace(factors).decompose(mix)
        want = {a: 1, b: -2} if a != b else {a: -1}
        assert got == {k: v for k, v in want.items() if v}, (factors, got)


def test_decompose_honest_fails_on_a_non_invariant_weight_function():
    """A weight function that is not `W`-invariant is not a virtual character,
    and is refused rather than projected onto the invariants."""
    F = FlavourSpace([2])
    fn = {(1,): 1}                      # one weight of the fundamental, alone
    assert not F.is_weyl_invariant(fn)
    try:
        F.decompose(fn)
    except ValueError:
        return
    raise AssertionError("decompose accepted a non-invariant weight function")


# --------------------------------------------------------------------------
# the definition
# --------------------------------------------------------------------------

def test_the_generator_is_the_product_of_E_s_over_the_weights_of_r():
    """`E^{(s;r)}_\\fq(X_γ) = ∏_{w∈r} E^{(s)}_\\fq(μ^w X_γ)`.

    Read off a one-node quiver, where the constraint forces `S` to be the
    generator itself: with `Ω(γ) = χ_r` at spin `0` and nothing at any `nγ`,
    `n ≥ 2`, the element built IS `E^{(0;r)}_\\fq(X_γ)`, and its weight-`w`
    component is the ordinary `E_\\fq` series — the flavoured generator is
    therefore exactly the stated product, with the weights entered with
    multiplicity.
    """
    for N in (2, 3, 4):
        Q = FlavouredQuiver([[0]], [N])
        eng = FlavouredFactorSpectrum(Q, 4)
        eng.run()
        fund = Q.flavour.fundamental(0)
        assert eng.multiplicities() == {(1,): {fund: {0: 1}}}, N
        S = eng.spectrum_generator()
        ray = charge_series({0: 1}, 4)          # one E_𝖖 factor, spin 0
        for w in Q.flavour.irrep_weights(fund):
            for n in range(1, 5):
                got = S.get(((n,), Q.flavour.scale(w, n)), H0)
                assert got == ray[n], (N, w, n)


def test_the_flavoured_constraint_is_the_unfolded_bps_quiver_constraint():
    """`χ_{r_a}(μ) X_{γ_a} = Σ_{w∈r_a} X_{γ_a+w}`.

    So the flavoured leading data at a node is the unflavoured leading data of
    the unfolded quiver, node by node — which is why flavoured uniqueness is
    inherited rather than new, and why the unfolded `S` is legitimate ground
    truth for the flavoured one.
    """
    for entry in CORPUS:
        Q, D = _quiver(entry)
        eng = FlavouredFactorSpectrum(Q, D)
        _, _, labels = Q.unfold()
        want = {}
        for a, w in labels:                     # one unfolded node per weight
            k = tuple(1 if i == a else 0 for i in range(Q.rank))
            want.setdefault(k, {})[w] = want.setdefault(k, {}).get(w, 0) - 1
        for k, block in want.items():
            assert eng.target(k) == block, (entry[0], k)


# --------------------------------------------------------------------------
# the positive control
# --------------------------------------------------------------------------

def test_trivial_flavour_reproduces_the_unflavoured_engine_bit_for_bit():
    """`G` trivial ⇒ `\\cE_G = \\cE` and the flavoured `S` IS the unflavoured one.

    The positive control (the design notes, "Positive controls before trusting any
    scan"): the flavoured recursion must degenerate exactly, not approximately.
    """
    for B, D in (([[0, 1], [-1, 0]], 4),
                 ([[0, 2], [-2, 0]], 4),
                 ([[0, 1, -1], [-1, 0, 1], [1, -1, 0]], 3)):
        n = len(B)
        Q = FlavouredQuiver(B, [1] * n)
        eng = FlavouredFactorSpectrum(Q, D)
        eng.run()
        flat = {k: v for (k, w), v in eng.spectrum_generator().items()}
        charges = [tuple(1 if j == i else 0 for j in range(n)) for i in range(n)]
        ref = BPSFactorSpectrum(B, charges, D, order="lex")
        ref.run()
        assert flat == ref.spectrum_generator(), B
        # The only irrep of a trivial `G` is the trivial one, so `Ω(γ, r)`
        # collapses onto the unflavoured `Ω(γ)`.
        triv = Q.flavour.trivial_irrep()
        assert eng.multiplicities() == \
            {k: {triv: om} for k, om in ref.multiplicities().items()}, B


# --------------------------------------------------------------------------
# the independent ground truth
# --------------------------------------------------------------------------

def test_S_equals_the_unfolded_S_on_every_flavoured_quiver():
    """`S ∈ \\cE_G` computed on the reduced cone equals the `S` of the unfolded
    BPS quiver, pushed forward to `(gauge charge, flavour weight)`.

    INDEPENDENT: the unfolded side has no notion of flavour at all — it is an
    ordinary BPS quiver whose nodes happen to be the weights, run through the
    unflavoured engine.  Exact equality of every coefficient, not agreement to
    some order.
    """
    for entry in CORPUS:
        Q, D = _quiver(entry)
        assert Q.unfoldable(), entry[0]
        S = build_flavoured_spectrum_generator(Q, D)
        gt = unfolded_spectrum_generator(Q, D)
        assert set(S) == set(gt), entry[0]
        assert _same(S, gt), entry[0]


# --------------------------------------------------------------------------
# the substantive claim
# --------------------------------------------------------------------------

def test_omega_is_a_virtual_character_of_G_at_every_charge():
    """Each `Ω(γ)` is `W`-invariant, i.e. lies in `R(G) ⊗ P` — so `S ∈ \\cE_G`.

    EMERGENT, and the reason the flavoured axiomatics has content: the
    recursion forces `Ω` at each flavour weight **independently**, because the
    `μ` are central and of `\\fq`-degree zero.  Nothing imposes Weyl symmetry.
    That the forced answer is a character every time is the claim.
    """
    for entry in CORPUS:
        Q, D = _quiver(entry)
        eng = FlavouredFactorSpectrum(Q, D)
        eng.run()
        assert eng.verify_omega_is_a_character() == [], entry[0]
        for k, per_rep in eng.multiplicities().items():
            assert per_rep, (entry[0], k)


def test_omega_carries_higher_irreps_at_composite_charges():
    """The reps occurring in `S` are more general than the node reps.

    The node data is the fundamental of `SU(2)`; the derived multiplicities
    reach the adjoint and beyond.  This is what makes `R(G)`-valued
    bookkeeping necessary rather than decorative — and it is where reps with
    repeated weights, which no unfolded quiver can carry at a node, actually
    appear.
    """
    Q = FlavouredQuiver([[0, 1], [-1, 0]], [2, 1])
    eng = FlavouredFactorSpectrum(Q, 5)
    eng.run()
    seen = {rep[0] for per in eng.multiplicities().values() for rep in per}
    assert (1,) in seen, seen           # the fundamental, from the node
    bigger = {lam for lam in seen if lam and lam[0] >= 2}
    assert bigger, f"only node-level reps occurred: {seen}"


def test_repeated_weight_reps_occur_in_the_derived_multiplicities():
    """A rep with a repeated weight cannot sit at a NODE, but does occur in `Ω`.

    Node reps are fundamentals in reality, and a fundamental
    has all weight multiplicities one — which is why every corpus entry unfolds.
    The *derived* multiplicities are not so constrained: with the `SU(3)`
    fundamental at a node, `Ω` reaches the adjoint `(2,1)`, whose zero weight
    has multiplicity two.

    This is the sharp reason the `R(G)`-valued bookkeeping is necessary rather
    than decorative: that multiplicity cannot be recorded as a set of unfolded
    nodes, because two of them would carry the same charge.
    """
    Q = FlavouredQuiver([[0, 1], [-1, 0]], [3, 1])
    eng = FlavouredFactorSpectrum(Q, 5)
    eng.run()
    F = Q.flavour
    repeated = []
    for per in eng.multiplicities().values():
        for rep in per:
            mults = F.irrep_weights(rep).values()
            if max(mults) > 1:
                repeated.append(rep)
    assert repeated, "no derived rep had a repeated weight"
    assert any(rep[0] == (2, 1) for rep in repeated), repeated


def test_omega_mixes_spin_and_flavour():
    """`Ω(γ) ∈ R(G) ⊗ P` with both factors non-trivial.

    Not merely a rep times `χ_0`, and not merely a spin times the trivial rep:
    there are charges where the multiplicity is a higher-spin multiplet carrying
    a non-trivial flavour rep — the `R(G) ⊗ R(SU(2)_spin)` content a BPS
    multiplicity is supposed to have.
    """
    Q = FlavouredQuiver([[0, 1, 0], [-1, 0, 1], [0, -1, 0]], [1, 2, 1])
    eng = FlavouredFactorSpectrum(Q, 4)
    eng.run()
    mixed = [(k, rep) for k, per in eng.multiplicities_by_spin().items()
             for (rep, two_s) in per
             if two_s > 0 and any(lam for lam in rep)]
    assert mixed, "every Omega was either spin-0 or flavour-trivial"


# --------------------------------------------------------------------------
# the flavoured PBW factorization, and what its index set must be
# --------------------------------------------------------------------------

def test_S_does_not_depend_on_the_order_on_charge_spin_irrep():
    """The flavoured PBW conjecture: the factorization
    `∏_{γ,s,r} E^{(s;r)}_\\fq(X_γ)^{Ω(γ,s,r)}` may be taken in any total order
    on `Γ_+ × ½N × Irr(G)`, and `S` does not depend on the choice.

    The order is honoured **globally**, not merely within each degree: a
    `piece_key` sends the engine down `_run_insert`, which keeps the factors in
    a `piece_key`-sorted list and inserts each newly discovered one at its own
    position — before lower-degree factors when the order says so.  That
    matters, because the conjecture quantifies over all total orders and the
    degree-compatible ones are a thin subset of them.
    """
    for entry in CORPUS[:6]:
        Q, D = _quiver(entry)
        base = build_flavoured_spectrum_generator(Q, D)
        for seed in range(4):
            S = build_flavoured_spectrum_generator(
                Q, D, piece_key=_random_piece_key(seed))
            assert set(S) == set(base) and _same(S, base), (entry[0], seed)


def test_a_degree_compatible_order_agrees_with_the_general_route():
    """The two routes agree where both apply.

    `_run_append` (no `piece_key`) places whole charges degree by degree;
    `_run_insert` honours an arbitrary order.  Handed a key that sorts by
    degree first — a degree-compatible order, where the general route reduces
    to the special one — they must produce the same `S` and the same `Ω`.
    """
    for entry in CORPUS[:6]:
        Q, D = _quiver(entry)
        append = FlavouredFactorSpectrum(Q, D)
        append.run()
        insert = FlavouredFactorSpectrum(
            Q, D, piece_key=lambda k, two_s, r: (sum(k), k, two_s, r))
        insert.run()
        assert _same(append.spectrum_generator(),
                     insert.spectrum_generator()), entry[0]
        assert append.multiplicities_by_spin() == \
            insert.multiplicities_by_spin(), entry[0]


def test_the_order_moves_the_factor_content_so_the_previous_test_has_teeth():
    """`S` is order-independent; its FACTORIZATION is not.

    Without this the order-independence test would be vacuous — it would be
    comparing a computation with itself.  At least one corpus entry must yield
    genuinely different `Ω` under different orders.  With the order honoured
    globally the spread is wide: 5 to 8 distinct factor contents from 8 random
    orders, against 2 when the order was applied only within each degree.
    """
    moved = 0
    for entry in CORPUS:
        Q, D = _quiver(entry)
        contents = set()
        for seed in range(6):
            eng = FlavouredFactorSpectrum(Q, D,
                                          piece_key=_random_piece_key(seed))
            eng.run()
            contents.add(repr(sorted(
                (k, sorted(map(str, v.items())))
                for k, v in eng.multiplicities_by_spin().items())))
        if len(contents) > 1:
            moved += 1
    assert moved >= len(CORPUS) - 2, f"order moved the content on only {moved}"


def test_a_weight_level_order_leaves_cE_G():
    """The index set of the flavoured PBW statement is `Irr(G)`, NOT the weights.

    NEGATIVE CONTROL.  Ordering the individual `E^{(s)}_\\fq(μ^w X_γ)` factors
    independently is a legitimate order in the ENLARGED `\\cE`, and indeed
    leaves `S` unchanged — but the resulting multiplicities are then not
    `G`-characters, so the factorization is not one in `\\cE_G`.  So a whole
    `E^{(s;r)}_\\fq(X_γ)` must be placed as a unit, and that requirement is not
    a convention: it is what the generator set of `\\cE_G` means.
    """
    broke = 0
    trials = 0
    for entry in (CORPUS[0], CORPUS[3], CORPUS[5], CORPUS[9]):
        Q, D = _quiver(entry)
        base = build_flavoured_spectrum_generator(Q, D)
        for seed in range(8):
            eng = FlavouredFactorSpectrum(
                Q, D, piece_key=_random_piece_key(seed), split_weights=True)
            eng.run()
            trials += 1
            assert _same(eng.spectrum_generator(), base), (entry[0], seed)
            if eng.verify_omega_is_a_character():
                broke += 1
    assert broke, ("no weight-level order broke the character property; the "
                   "negative control has no teeth")


# --------------------------------------------------------------------------
# the flavoured spec
# --------------------------------------------------------------------------

def test_the_strip_order_gives_one_generator_per_node_on_an_acyclic_quiver():
    """**The flavoured spec of an acyclic quiver is its node data.**

    On an acyclic flavoured quiver the source/sink strip order gives

        S  =  ∏_a E^{(0;r_a)}_\\fq(X_{γ_a}) ,

    exactly `rank` factors — one per REDUCED node, at spin `0`, carrying
    precisely that node's own rep `r_a` and nothing else.  This is the flavoured
    form of the repo's mantle statement (acyclic ⇒ topological product spec),
    and it is a spec in the working sense: finite, spin-`0`, positive.

    It also attains the floor.  At cone degree `1` the accumulated product is
    still empty, so every node must carry a factor in every order; `rank` is
    therefore the minimum and the strip reaches it.
    """
    acyclic = [e for e in CORPUS if e[0] != "3-cycle, SU(2)"]
    assert acyclic
    for name, B, fac, D in acyclic:
        Q = FlavouredQuiver(B, fac)
        n = Q.rank
        charges = [tuple(1 if j == i else 0 for j in range(n)) for i in range(n)]
        order = acyclic_node_order(B, charges)
        assert order is not None, name
        key = mean_rank_key(order)
        eng = FlavouredFactorSpectrum(
            Q, D, piece_key=lambda k, two_s, r, key=key: (key(k), k, two_s, r))
        eng.run()
        want = {tuple(1 if i == a else 0 for i in range(n)):
                {(Q.node_reps[a], 0): 1} for a in range(n)}
        assert eng.multiplicities_by_spin() == want, name
        assert eng.verify_omega_is_a_character() == [], name


def test_the_strip_honest_fails_on_a_quiver_that_is_not_acyclic():
    """Where the strip leaves a core it determines nothing, and says so.

    The flavoured mantle statement is about acyclic quivers; it is not silently
    extended to the rest.
    """
    B = [[0, 1, -1], [-1, 0, 1], [1, -1, 0]]
    charges = [(1, 0, 0), (0, 1, 0), (0, 0, 1)]
    assert acyclic_node_order(B, charges) is None


def test_the_flavoured_factorisation_is_shorter_than_the_unfolded_one():
    """`\\cE_G` packs each group of `N_a` unfolded factors into one generator.

    On an acyclic quiver both routes attain their own floor — one factor per
    node — so the counts are the number of REDUCED nodes against the number of
    UNFOLDED ones, `g` against `Σ_a dim r_a`.  This is where the flavoured
    construction is genuinely more economical; it is NOT more economical in the
    cone (see `flavoured_s_axioms.md` §7, where that claim is retracted).
    """
    for name, B, fac, D in (("A2, SU(2)", [[0, 1], [-1, 0]], [2, 1], 5),
                            ("A2, SU(3)", [[0, 1], [-1, 0]], [3, 1], 5),
                            ("A2, SU(2)xSU(3)", [[0, 1], [-1, 0]], [2, 3], 4)):
        Q = FlavouredQuiver(B, fac)
        n = Q.rank
        charges = [tuple(1 if j == i else 0 for j in range(n)) for i in range(n)]
        key = mean_rank_key(acyclic_node_order(B, charges))
        eng = FlavouredFactorSpectrum(
            Q, D, piece_key=lambda k, two_s, r, key=key: (key(k), k, two_s, r))
        eng.run()
        flavoured = sum(len(v) for v in eng.multiplicities_by_spin().values())

        Bu, chu, _ = Q.unfold()
        ref = BPSFactorSpectrum(Bu, chu, D, order="strip")
        ref.run()
        unfolded = sum(len(v) for v in ref.multiplicities().values())

        assert flavoured == n, (name, flavoured)
        assert unfolded == len(chu), (name, unfolded)
        assert flavoured < unfolded, (name, flavoured, unfolded)


# --------------------------------------------------------------------------
# uniqueness
# --------------------------------------------------------------------------

def test_no_single_generator_perturbation_of_S_satisfies_the_constraint():
    """Uniqueness of `S`, tested one generator at a time.

    `S·E^{(s;r)}_\\fq(X_γ)^{±1}` violates the flavoured BPS quiver constraint —
    either a non-positive power of `\\fq` appears away from the identity, or the
    `\\fq^1` coefficient stops matching the leading data — for every generator
    in the window.  That is the decidable, local form of *"there is a unique
    element of `\\cE_G` satisfying the constraint"*; it does not by itself
    settle the global statement.
    """
    Q = FlavouredQuiver([[0, 1], [-1, 0]], [2, 1])
    eng = FlavouredFactorSpectrum(Q, 4)
    eng.run()
    assert eng.constraint_violations() == []
    acc = eng._S
    reps = [Q.flavour.trivial_irrep(), Q.flavour.fundamental(0), ((2,), ())]
    checked = 0
    for k in ((1, 0), (0, 1), (1, 1), (2, 1)):
        for rep in reps:
            for two_s in (0, 1, 2):
                for exponent in (1, -1):
                    S2 = eng.times_generator(acc, k, rep, two_s, exponent)
                    assert eng.constraint_violations(S2), (k, rep, two_s, exponent)
                    checked += 1
    assert checked == 72, checked


def test_leading_data_is_reproduced():
    """`S = 1 - \\fq Σ_a χ_{r_a}(μ) X_{γ_a} + O(\\fq^2)` on the truncated cone.

    ENFORCED, not emergent (the audit): the recursion solves for
    exactly this, so a pass is a regression guard on the arithmetic and NOT
    evidence for any conjecture.  Stated here so that the distinction is on the
    record beside the tests that are evidence.
    """
    for entry in CORPUS:
        Q, D = _quiver(entry)
        eng = FlavouredFactorSpectrum(Q, D)
        eng.run()
        assert eng.verify_leading_data() == [], entry[0]


# --------------------------------------------------------------------------
# the datum
# --------------------------------------------------------------------------

def test_S_is_a_function_of_the_flavoured_quiver_alone():
    """`S[Q]` depends only on the flavoured quiver, up to relabelling of nodes.

    The property a dictionary keyed by *quivers with `G` symmetry* needs: the
    flavour assignment is an extra node colour, and permuting the nodes
    permutes `S` and nothing else.
    """
    B = [[0, 1, -1], [-1, 0, 1], [1, -1, 0]]
    fac = [2, 1, 3]
    perm = (2, 0, 1)                       # new node i is old node perm[i]
    Q = FlavouredQuiver(B, fac)
    Bp = [[B[perm[i]][perm[j]] for j in range(3)] for i in range(3)]
    Qp = FlavouredQuiver(Bp, [fac[perm[i]] for i in range(3)])
    D = 3
    S = build_flavoured_spectrum_generator(Q, D)
    Sp = build_flavoured_spectrum_generator(Qp, D)

    # The flavour coordinates are concatenated in node order, so permuting the
    # nodes permutes the weight blocks as well as the charge coordinates.
    F, Fp = Q.flavour, Qp.flavour

    def relabel(key):
        k, w = key
        new_k = tuple(k[perm[i]] for i in range(3))
        new_w = ()
        for i in range(3):
            src, wd = F.offsets[perm[i]], F.widths[perm[i]]
            new_w += tuple(w[src:src + wd])
        assert len(new_w) == Fp.dim
        return new_k, new_w

    assert len(S) == len(Sp)
    assert {relabel(key) for key in S} == set(Sp)
    for key, h in S.items():
        assert Sp[relabel(key)] == h, key


# --------------------------------------------------------------------------
# towards a dictionary of quivers with `G` symmetry
# --------------------------------------------------------------------------

def test_the_canonical_key_identifies_flavoured_quivers_up_to_relabelling():
    """The dictionary identity: `(canonical B, node colours in canonical order)`.

    The flavour datum is an extra node colour, so `quiver_enumeration`'s
    colour-refinement canonical form extends to flavoured quivers unchanged —
    which is what a dictionary of *quivers with `G` symmetry* needs.  Relabelling the nodes must not change the key; changing the
    flavour assignment must.
    """
    B = [[0, 1], [-1, 0]]
    swapped = [[0, -1], [1, 0]]                 # the same quiver, nodes swapped
    a = FlavouredQuiver(B, [2, 1])
    a_relabelled = FlavouredQuiver(swapped, [1, 2])
    assert a.canonical_key() == a_relabelled.canonical_key()

    keys = {}
    for fac in ([1, 1], [2, 1], [1, 2], [2, 2], [3, 1], [1, 3], [3, 2], [2, 3]):
        keys[tuple(fac)] = FlavouredQuiver(B, fac).canonical_key()
    assert len(set(map(str, keys.values()))) == len(keys), keys


def test_the_colour_preserving_automorphisms_are_the_flavoured_ones():
    """`|Aut|` drops exactly when the flavour assignment breaks a symmetry.

    `A1 × A1` has `|Aut(B)| = 2`.  With an `SU(2)` at each node the two remain
    interchangeable, so the flavoured group is still order 2 — a node's colour
    must name its factor's RANK, never the factor's index in the product, or
    this reports 1.  With `SU(2)` at one node only, or `SU(2)` and `SU(3)`, the
    symmetry is genuinely broken and the order is 1.
    """
    from quiver_enumeration import canonical_form
    B = [[0, 0], [0, 0]]
    assert canonical_form(B).aut_order == 2
    for fac, want in (([1, 1], 2), ([2, 2], 2), ([2, 1], 1), ([2, 3], 1)):
        got = FlavouredQuiver(B, fac).colour_preserving_aut_order()
        assert got == want, (fac, got, want)


def test_equal_canonical_key_implies_equal_S():
    """Dictionary soundness: one entry, one `S`.

    Over a family of flavoured quivers including relabelled copies, every group
    sharing a canonical key has one and the same `S` in canonical coordinates —
    so an entry may store a single `S` without a witness permutation.
    """
    families = []
    for B in ([[0, 1], [-1, 0]], [[0, -1], [1, 0]],
              [[0, 2], [-2, 0]], [[0, -2], [2, 0]], [[0, 0], [0, 0]]):
        for fac in ([1, 1], [2, 1], [1, 2], [2, 2]):
            families.append(FlavouredQuiver(B, fac))
    groups: dict[str, list] = {}
    for Q in families:
        groups.setdefault(str(Q.canonical_key()), []).append(Q)
    assert any(len(v) > 1 for v in groups.values()), "no key had two members"
    for key, members in groups.items():
        base = canonical_spectrum_generator(members[0], 4)
        for Q in members[1:]:
            assert _same(canonical_spectrum_generator(Q, 4), base), key


def test_the_key_is_finer_than_S_because_S_is_arrow_reversal_invariant():
    """`S(B) = S(−B)`: distinct entries may share an `S`, and that is expected.

    Reversing every arrow, `B ↦ −B`, is the opposite quiver.  `X_γ ↦ X_γ` is an
    **anti**-isomorphism `Q_\\fq(B) → Q_\\fq(−B)`, so it carries a product of
    `E^{(s)}` factors to the same factors in the REVERSED order — and `S` is
    order-independent.  So arrow-reversal invariance of `S` is a corollary of
    the PBW conjecture rather than anything about flavour, and it is why the
    canonical key is strictly finer than `S`.

    Checked unflavoured, where it is a statement about `S` alone, on quivers
    with `B` genuinely NOT isomorphic to `−B`; and then in the flavoured
    setting, where the colouring makes `(B, colours)` and `(−B, colours)`
    distinct entries that nevertheless share an `S`.
    """
    import quiver_enumeration as qe

    checked = 0
    for key in qe.enumerate_connected_quivers(5):
        n = len(key)
        if n != 3:
            continue
        neg = tuple(tuple(-x for x in row) for row in key)
        if qe.canonical_key(neg) == key:
            continue                    # isomorphic to its own opposite
        charges = qe.standard_nodes(n)
        a = BPSFactorSpectrum(key, charges, 3, order="lex")
        a.run()
        b = BPSFactorSpectrum(neg, charges, 3, order="lex")
        b.run()
        assert _same(a.spectrum_generator(), b.spectrum_generator()), key
        checked += 1
        if checked == 6:
            break
    assert checked == 6, checked

    # Flavoured: distinct entries, equal S.
    p = FlavouredQuiver([[0, 1], [-1, 0]], [2, 1])
    q = FlavouredQuiver([[0, 1], [-1, 0]], [1, 2])
    assert p.canonical_key() != q.canonical_key()
    assert _same(canonical_spectrum_generator(p, 4),
                 canonical_spectrum_generator(q, 4))


def test_a_shared_flavour_factor_honest_fails_rather_than_conflating():
    """Where the node colours are not a complete invariant, the key refuses.

    Two nodes in the fundamental of ONE `SU(2)` and two nodes in fundamentals
    of `SU(2) × SU(2)` have identical node colours and are different objects;
    telling them apart needs the node–factor incidence canonicalised jointly
    with the quiver, which is not built.  The case does not arise in the
    setting the construction is for.
    """
    shared = FlavouredQuiver([[0, 1], [-1, 0]], FlavourSpace([2]),
                             [((1,),), ((1,),)])
    assert shared.shares_a_flavour_factor()
    for call in (shared.canonical_key,
                 lambda: canonical_spectrum_generator(shared, 3)):
        try:
            call()
        except NotImplementedError:
            continue
        raise AssertionError("expected an honest failure on a shared factor")
    assert not FlavouredQuiver([[0, 1], [-1, 0]], [2, 2]).shares_a_flavour_factor()


TESTS = [
    test_weights_and_characters_round_trip_including_virtual_ones,
    test_decompose_honest_fails_on_a_non_invariant_weight_function,
    test_the_generator_is_the_product_of_E_s_over_the_weights_of_r,
    test_the_flavoured_constraint_is_the_unfolded_bps_quiver_constraint,
    test_trivial_flavour_reproduces_the_unflavoured_engine_bit_for_bit,
    test_S_equals_the_unfolded_S_on_every_flavoured_quiver,
    test_omega_is_a_virtual_character_of_G_at_every_charge,
    test_omega_carries_higher_irreps_at_composite_charges,
    test_repeated_weight_reps_occur_in_the_derived_multiplicities,
    test_omega_mixes_spin_and_flavour,
    test_S_does_not_depend_on_the_order_on_charge_spin_irrep,
    test_a_degree_compatible_order_agrees_with_the_general_route,
    test_the_order_moves_the_factor_content_so_the_previous_test_has_teeth,
    test_a_weight_level_order_leaves_cE_G,
    test_the_strip_order_gives_one_generator_per_node_on_an_acyclic_quiver,
    test_the_strip_honest_fails_on_a_quiver_that_is_not_acyclic,
    test_the_flavoured_factorisation_is_shorter_than_the_unfolded_one,
    test_no_single_generator_perturbation_of_S_satisfies_the_constraint,
    test_leading_data_is_reproduced,
    test_S_is_a_function_of_the_flavoured_quiver_alone,
    test_the_canonical_key_identifies_flavoured_quivers_up_to_relabelling,
    test_the_colour_preserving_automorphisms_are_the_flavoured_ones,
    test_equal_canonical_key_implies_equal_S,
    test_the_key_is_finer_than_S_because_S_is_arrow_reversal_invariant,
    test_a_shared_flavour_factor_honest_fails_rather_than_conflating,
]


if __name__ == "__main__":
    for fn in TESTS:
        fn()
        print(f"  PASS: {fn.__name__}")
    print(f"All {len(TESTS)} flavoured `S` axiom tests passed.")
