"""`S` for a BPS quiver with a non-Abelian flavour group `G` — the flavoured
`\\cE_G` construction.

**Provisional module / class name.**  `flavoured_factor_spectrum` /
`FlavouredFactorSpectrum` were chosen to sit beside `bps_factor_spectrum` /
`BPSFactorSpectrum`, whose construction this generalises.  Module and class
names are the author's call (the design notes, contract surface); both rename in one
command if a better one is ruled.

The unflavoured axioms
----------------------

From the paper (`\\cG`, `\\cE`, `E^{(s)}_\\fq` are the paper's own symbols):

* `\\cG` is the pro-nilpotent group of elements `1 + Σ_{γ∈Γ_+} g_γ(\\fq) X_γ`
  with `g_γ ∈ Z[\\fq, \\fq^{-1}, (1-\\fq^{2n})^{-1}]` — the Habiro-type ring
  carried here by `habiro.HabiroElement`;
* `E_\\fq(x) = (-\\fq x; \\fq^2)_∞^{-1}` and, for `s ∈ ½N`,

      E^{(s)}_\\fq(x) = ∏_{j=-s}^{s} E_\\fq((-1)^{2s} \\fq^{2j} x)^{(-1)^{2s}} ;

* `\\cE ⊂ \\cG` is the subgroup generated by `E^{(s)}_\\fq(X_γ)^{±1}`,
  `γ ∈ Γ_+`;
* the **BPS quiver constraint** is `S = 1 - \\fq Σ_i X_{γ_i} + O(\\fq^2)`, and
  `S` is conjecturally the unique element of `\\cE` satisfying it;
* **PBW factorization**: every `g ∈ \\cE` factors as
  `∏_{γ,s} E^{(s)}_\\fq(X_γ)^{Ω(γ,s)}` in any total order on `Γ_+ × ½N`, with
  integral exponents.

`bps_factor_spectrum.BPSFactorSpectrum` implements exactly this.  In its code
the multiplet is spelled `m_s(γ)`; that spelling is code-local and the
documents say `E^{(s)}_\\fq(X_γ)`.

The flavoured axioms
--------------------

Let `G` be a flavour group — in practice `G = ∏_a SU(N_a)`, with node `a`
carrying the `N_a`-dimensional irrep.  Write `μ^w` for the
character of the maximal torus at the weight `w`; the `μ` are **central** and
carry `\\fq`-degree zero.  Then for an irrep `r` of `G`

    E^{(s;r)}_\\fq(X_γ)  :=  ∏_{w ∈ r} E^{(s)}_\\fq(μ^w X_γ)

(the product over the weights of `r` **with multiplicity**), and `\\cE_G` is
the subgroup of the flavoured `\\cG` generated by the
`E^{(s;r)}_\\fq(X_γ)^{±1}` for `γ ∈ Γ_+`, `s ∈ ½N` and `r` an irrep of `G`.
The **flavoured BPS quiver constraint** is

    S  =  1  -  \\fq Σ_a χ_{r_a}(μ) X_{γ_a}  +  O(\\fq^2) ,

i.e. the node charge monomials `X_{γ_a}` of the unflavoured constraint are
replaced by the sequences `μ^w X_{γ_a}`, `w ∈ r_a`.  The flavoured PBW
factorization reads `g = ∏_{γ,s,r} E^{(s;r)}_\\fq(X_γ)^{Ω(γ,s,r)}`, so the
multiplicity `Ω(γ)` is valued in `R(G) ⊗ P` rather than in `P` alone
(`P` = palindromic `Z[\\fq^{±1}]`, `Z`-basis the `χ_s`) — a flavour-rep times
spin-rep multiplicity, which is what a BPS multiplicity physically is.

Why this is well defined, and what it costs
-------------------------------------------

`μ^w X_γ` is `X_{γ+w}` in the lattice enlarged by the flavour weights, and the
enlarged charges `γ + w`, `w ∈ r`, all pair to zero with one another (the
flavour directions are central and the gauge charge is shared).  So every
generator of `\\cE_G` is an ordinary product of commuting `E^{(s)}` factors in
the enlarged lattice, `\\cE_G ⊆ \\cE_enlarged`, and the flavoured constraint is
*literally* the enlarged one, since `χ_{r_a}(μ) X_{γ_a} = Σ_{w∈r_a} X_{γ_a+w}`.

Two consequences worth stating because they are easy to get wrong:

1. **Flavoured uniqueness is inherited**, not new.  What is substantive is
   `S_enlarged ∈ \\cE_G` — that the enlarged `S`'s PBW multiplicities, grouped
   by gauge charge, assemble into honest `G`-characters.  That is the claim
   this module's battery tests, against the enlarged engine as an independent
   ground truth.
2. **This is not a cost win by itself.**  The reduced cone is smaller, but the
   flavour weights return as fibres over each reduced cone point and the total
   accumulator size is unchanged.  The gains are that `Ω` is a `G`-character
   (the reps are the natural labels), that the dictionary key becomes the
   quiver-with-`G`-data rather than the unfolded quiver, and that node data
   with a repeated weight is expressible at all.  A `|W|`-fold saving is
   available by solving one `Ω` per Weyl orbit; it is **not** taken here, so
   that `Ω`'s Weyl invariance stays an *output* of the recursion and therefore
   evidence, rather than being imposed (the audit, enforced vs emergent).

Node reps with a repeated weight
--------------------------------

A rep whose weight multiplicities exceed one cannot be unfolded into a BPS
quiver — two nodes would carry the same charge.  The author's ruling
(2026-09-13) is that this *"will never effectively happen as the node irreps
are fundamentals of `SU(N_a)` in reality"*, and the battery follows that: every
tested node datum unfolds, which is what gives the tests their ground truth.
The implementation nevertheless accepts an arbitrary irrep at a node, because
it costs nothing — and because repeated weights do occur in the **derived**
`Ω` at composite charges, which is where the `R(G)` bookkeeping earns its keep.

Exactness
---------

Coefficients are `HabiroElement` throughout and the only truncation is along
the reduced positive cone; no `\\fq`-truncation is ever taken (the design notes,
"Exact arithmetic until the very end").
"""

from __future__ import annotations

import itertools
from typing import Callable, Sequence

from habiro import HabiroElement
from zplus_ring import AbelianZPlusRing, RElement, SUNZPlusRing

# One definition of the univariate ray arithmetic and of the forced-`Ω` step:
# both are reused verbatim from the unflavoured engine rather than restated.
# The flavoured recursion differs from it only in carrying a weight grading.
from bps_factor_spectrum import (
    BPSFactorSpectrum,
    charge_series,
    cone_simplex,
    expansion,
    spin_decompose,
)
from recursive_spectrum import q_pow

H0 = HabiroElement.zero()
H1 = HabiroElement.one()

Vec = tuple[int, ...]
Weight = tuple[int, ...]
#: An irrep of `G = ∏_i SU(N_i)`: one partition per simple factor.
Irrep = tuple[tuple[int, ...], ...]


# --------------------------------------------------------------------------
# the flavour group and its weights
# --------------------------------------------------------------------------

class FlavourSpace:
    """`G = ∏_i SU(N_i)`, with weights in concatenated torus coordinates.

    A weight of `SU(N)` is written in the coordinates `SUNZPlusRing.to_abelian`
    uses — `(w_1 - w_N, …, w_{N-1} - w_N)` for a `U(N)` weight `w` — so it is an
    element of `Z^{N-1}` and weights add componentwise.  **These coordinates are
    integral**: the half-integers that appear when a flavour direction is kept
    inside `Γ` and the node charges are averaged (the `(a, b, s)` labels of
    the `D_n`-chamber torus, the archived tree) never arise
    here, because `Γ` is the gauge lattice alone and the weights are carried
    separately.

    A weight of the product is the concatenation, so it lies in
    `Z^{Σ_i (N_i - 1)}`.  A factor with `N_i = 1` is trivial and contributes no
    coordinates, which is how an unflavoured node is expressed.
    """

    def __init__(self, factors: Sequence[int]):
        factors = tuple(int(n) for n in factors)
        if any(n < 1 for n in factors):
            raise ValueError(f"FlavourSpace: each SU(N) needs N >= 1, got {factors}")
        self.factors = factors
        self.rings = tuple(SUNZPlusRing(n) for n in factors)
        widths = [max(n - 1, 0) for n in factors]
        self.widths = tuple(widths)
        offs, acc = [], 0
        for w in widths:
            offs.append(acc)
            acc += w
        self.offsets = tuple(offs)
        self.dim = acc

    def __repr__(self) -> str:
        return f"FlavourSpace({list(self.factors)})"

    def is_trivial(self) -> bool:
        return self.dim == 0

    def zplus_ring(self):
        """`R(G) = ⊗_a R(SU(N_a))` as the repo's own `Z₊`-ring object.

        The canonical product ring, built with `zplus_ring.TensorZPlusRing`'s
        **n-ary** constructor — there is one product-ring object for a given
        flavour group, and consumers take it from here rather than assembling
        their own.  Trivial factors contribute nothing, so an unflavoured datum
        gives `TrivialZPlusRing` and a single non-trivial factor gives that
        factor itself rather than a one-term tensor product.
        """
        cached = getattr(self, "_zplus_ring", None)
        if cached is not None:
            return cached
        from zplus_ring import TensorZPlusRing, TrivialZPlusRing
        live = [r for r, n in zip(self.rings, self.factors) if n > 1]
        if not live:
            ring = TrivialZPlusRing()
        elif len(live) == 1:
            ring = live[0]
        else:
            ring = TensorZPlusRing(live)
        self._zplus_ring = ring
        return ring

    def _live_slots(self) -> tuple:
        """Indices of the factors that `zplus_ring()` keeps (those with `N > 1`)."""
        return tuple(i for i, n in enumerate(self.factors) if n > 1)

    def irrep_to_ring_key(self, rep: Irrep):
        """An `Irrep` (one partition per factor) ↦ a `zplus_ring()` basis key.

        The two are **not** the same object, and conflating them is a silent
        error rather than a loud one: `zplus_ring()` drops the trivial factors,
        so its keys are bare partitions (one live factor) or tuples over the
        live factors only (several), whereas an `Irrep` always carries one slot
        per factor.  `KAlgebra.r_label_decompose`'s second component is
        contractually a **basis element of `coefficient_ring()`**, so it is this
        key that must be handed back — an `Irrep` there passes
        `verify_section_is_single_irrep` (which only counts terms) while making
        `R.dim` and `forget()` raise and `to_R_form` emit ring-invalid data.
        """
        rep = self._normalise(rep)
        live = self._live_slots()
        if not live:
            return ()
        if len(live) == 1:
            return rep[live[0]]
        return tuple(rep[i] for i in live)

    def ring_key_to_irrep(self, key) -> Irrep:
        """Inverse of `irrep_to_ring_key`: re-insert the trivial factors."""
        live = self._live_slots()
        if not live:
            return self.trivial_irrep()
        if len(live) == 1:
            parts = {live[0]: tuple(key)}
        else:
            if len(key) != len(live):
                raise ValueError(
                    f"ring_key_to_irrep: expected {len(live)} live slots, "
                    f"got {key!r}")
            parts = {slot: tuple(k) for slot, k in zip(live, key)}
        return self._normalise(
            tuple(parts.get(i, ()) for i in range(len(self.factors))))

    @property
    def zero(self) -> Weight:
        return (0,) * self.dim

    def add(self, u: Weight, v: Weight) -> Weight:
        return tuple(a + b for a, b in zip(u, v))

    def scale(self, u: Weight, n: int) -> Weight:
        return tuple(n * a for a in u)

    # ----- irreps -------------------------------------------------------
    def trivial_irrep(self) -> Irrep:
        return tuple(() for _ in self.factors)

    def fundamental(self, index: int) -> Irrep:
        """The `N_index`-dimensional irrep of the `index`-th factor."""
        return tuple((1,) if i == index and self.factors[i] > 1 else ()
                     for i in range(len(self.factors)))

    def irrep_weights(self, rep: Irrep) -> dict[Weight, int]:
        """Weight diagram of `⊗_i χ_{λ_i}`, as `{weight: multiplicity}`."""
        rep = self._normalise(rep)
        per: list[dict[tuple[int, ...], int]] = []
        for ring, lam in zip(self.rings, rep):
            if ring.N == 1:
                per.append({(): 1})
                continue
            elt = RElement(ring, {ring.reduce(lam): 1})
            ab = ring.to_abelian(elt)
            per.append({tuple(int(x) for x in k): int(v)
                        for k, v in ab.terms.items() if v})
        out: dict[Weight, int] = {}
        for combo in itertools.product(*[sorted(d.items()) for d in per]):
            key = tuple(x for w, _ in combo for x in w)
            mult = 1
            for _, m in combo:
                mult *= m
            out[key] = out.get(key, 0) + mult
        return {k: v for k, v in out.items() if v}

    def irrep_dim(self, rep: Irrep) -> int:
        """`dim r` — from the `Z₊`-ring, which multiplies the per-factor dims.

        Delegated rather than computed by summing `irrep_weights`, which
        materialises the whole product weight diagram to add it up.
        """
        return self.zplus_ring().dim(self.irrep_to_ring_key(rep))

    def _normalise(self, rep: Irrep) -> Irrep:
        rep = tuple(tuple(int(x) for x in lam) for lam in rep)
        if len(rep) != len(self.factors):
            raise ValueError(
                f"irrep needs one partition per factor "
                f"({len(self.factors)}), got {len(rep)}: {rep}")
        return tuple(ring.reduce(lam) if ring.N > 1 else ()
                     for ring, lam in zip(self.rings, rep))

    # ----- the Weyl group ----------------------------------------------
    def weyl_images(self, w: Weight) -> list[Weight]:
        """The `W = ∏_i S_{N_i}` orbit of a weight, in these coordinates.

        A coordinate vector `(w_1-w_N, …, w_{N-1}-w_N)` lifts to the `U(N)`
        weight `(w_1-w_N, …, w_{N-1}-w_N, 0)`; `S_N` permutes the `N` entries;
        the result is projected back.  Exact, and independent of the lift.
        """
        per: list[list[tuple[int, ...]]] = []
        for i, n in enumerate(self.factors):
            if n <= 1:
                per.append([()])
                continue
            lo = self.offsets[i]
            piece = tuple(w[lo:lo + n - 1]) + (0,)
            seen = set()
            for perm in itertools.permutations(piece):
                proj = tuple(perm[j] - perm[n - 1] for j in range(n - 1))
                seen.add(proj)
            per.append(sorted(seen))
        return [tuple(x for p in combo for x in p)
                for combo in itertools.product(*per)]

    def is_weyl_invariant(self, fn: dict[Weight, int]) -> bool:
        """Is `fn` (a finitely-supported weight function) `W`-invariant?

        Equivalently — and this is why the test is stated this way — is `fn` the
        weight-multiplicity function of a **virtual character** of `G`?  For a
        finitely-supported function on the weight lattice the two are the same
        condition.
        """
        fn = {k: v for k, v in fn.items() if v}
        for w, v in fn.items():
            for u in self.weyl_images(w):
                if fn.get(u, 0) != v:
                    return False
        return True

    # ----- weights -> characters ---------------------------------------
    def decompose(self, fn: dict[Weight, int]) -> dict[Irrep, int]:
        """A `W`-invariant weight function as a virtual character of `G`.

        Factor by factor, through the certified `SUNZPlusRing.from_abelian`
        (which un-branches a Weyl-symmetric μ-Laurent into characters and
        accepts **signed** multiplicities).  Raises if `fn` is not `W`-invariant
        — an honest failure, never a silent projection.
        """
        fn = {k: int(v) for k, v in fn.items() if v}
        if not fn:
            return {}
        if not self.is_weyl_invariant(fn):
            raise ValueError(
                "decompose: weight function is not Weyl-invariant, so it is "
                "not the weight diagram of any virtual character of "
                f"{self!r}")
        return self._decompose_from(fn, 0)

    def _decompose_from(self, fn: dict[Weight, int], i: int) -> dict[Irrep, int]:
        if i == len(self.factors):
            assert set(fn) <= {()}
            c = fn.get((), 0)
            return {(): c} if c else {}
        ring = self.rings[i]
        # Factors `< i` have already been peeled off the front of every key, so
        # this factor's coordinates are the LEADING `widths[i]` of what is left
        # — not `offsets[i]` into the original key.  (Using the original offset
        # is silently right whenever at most one factor is non-trivial, and
        # wrong as soon as two are; it was caught by SU(2)xSU(2).)
        wd = self.widths[i]
        rest_of: dict[Weight, dict[tuple[int, ...], int]] = {}
        for w, c in fn.items():
            head = tuple(w[:wd])
            tail = tuple(w[wd:])
            rest_of.setdefault(tail, {})[head] = \
                rest_of.setdefault(tail, {}).get(head, 0) + c
        # For each irrep of this factor, the residual function on the rest.
        residual: dict[tuple[int, ...], dict[Weight, int]] = {}
        for tail, head_fn in rest_of.items():
            for lam, mult in self._factor_decompose(ring, head_fn).items():
                residual.setdefault(lam, {})[tail] = \
                    residual.setdefault(lam, {}).get(tail, 0) + mult
        out: dict[Irrep, int] = {}
        for lam, rest_fn in residual.items():
            for sub, c in self._decompose_from(
                    {k: v for k, v in rest_fn.items() if v}, i + 1).items():
                key = (lam,) + sub
                out[key] = out.get(key, 0) + c
        return {k: v for k, v in out.items() if v}

    @staticmethod
    def _factor_decompose(ring: SUNZPlusRing,
                          head_fn: dict[tuple[int, ...], int]
                          ) -> dict[tuple[int, ...], int]:
        head_fn = {k: v for k, v in head_fn.items() if v}
        if not head_fn:
            return {}
        if ring.N == 1:
            return {(): head_fn.get((), 0)} if head_fn.get((), 0) else {}
        ab = AbelianZPlusRing(rank=ring.N - 1)
        elt = RElement(ab, dict(head_fn))
        got = ring.from_abelian(elt, allow_virtual=True)
        return {tuple(k): int(v) for k, v in got.terms.items() if v}


# --------------------------------------------------------------------------
# the flavoured quiver
# --------------------------------------------------------------------------

class FlavouredQuiver:
    """A BPS quiver whose nodes carry irreps of a flavour group `G`.

    `S` depends only on the quiver (the paper's `S[Q]`), so the datum here is
    the exchange matrix together with the flavour assignment, and the node
    charges are the standard basis of `Γ`.  The datum is hashable and has a
    canonical form up to relabelling of the nodes, so that it can serve as a
    dictionary key the way the bare exchange matrix does in
    `quiver_enumeration`.

    Parameters
    ----------
    pairing
        The `g x g` antisymmetric exchange matrix of the **reduced** quiver —
        one node per flavoured node.
    flavour
        A `FlavourSpace`, or the sequence of `N_i` defining one.
    node_reps
        One `Irrep` per node.  The default is the author's *"in reality"* case:
        factor `a` is `SU(N_a)` and node `a` carries its fundamental.
    """

    def __init__(self, pairing: Sequence[Sequence[int]],
                 flavour: FlavourSpace | Sequence[int],
                 node_reps: Sequence[Irrep] | None = None):
        B = [[int(x) for x in row] for row in pairing]
        g = len(B)
        if any(len(row) != g for row in B):
            raise ValueError("pairing must be square")
        for i in range(g):
            for j in range(g):
                if B[i][j] != -B[j][i]:
                    raise ValueError("pairing must be antisymmetric")
        self.pairing = tuple(tuple(row) for row in B)
        self.rank = g
        self.flavour = (flavour if isinstance(flavour, FlavourSpace)
                        else FlavourSpace(flavour))
        if node_reps is None:
            if len(self.flavour.factors) != g:
                raise ValueError(
                    "default node_reps needs one SU(N) factor per node "
                    f"({g}), got {len(self.flavour.factors)}")
            node_reps = [self.flavour.fundamental(a) for a in range(g)]
        if len(node_reps) != g:
            raise ValueError(f"need one irrep per node ({g})")
        self.node_reps = tuple(self.flavour._normalise(r) for r in node_reps)
        self._weights = tuple(self.flavour.irrep_weights(r)
                              for r in self.node_reps)

    def __repr__(self) -> str:
        return (f"FlavouredQuiver(rank={self.rank}, {self.flavour!r}, "
                f"reps={list(self.node_reps)})")

    def key(self) -> tuple:
        """A hashable identity, NOT canonicalised — relabelling the nodes
        changes it.  Use `canonical_key()` for the dictionary identity."""
        return (self.pairing, self.flavour.factors, self.node_reps)

    def node_colours(self) -> tuple:
        """Each node's flavour datum, as a colour an isomorphism must preserve.

        An isomorphism of flavoured quivers is a node permutation **together
        with** an automorphism of `G` permuting its simple factors — so a
        node's colour must not name a factor by its position in the product.
        Naming it by position gets two things wrong: relabelling the nodes then
        changes the key, and `A1 × A1` with an `SU(2)` at each node reports no
        symmetry although the two nodes are plainly interchangeable.

        The colour of a node is therefore the multiset of `(N_i, λ)` over the
        simple factors it is non-trivially charged under — the factor's
        **rank** and the rep, never the factor's index.  That is comparable
        across quivers, which a dictionary key must be.

        **Complete exactly when no factor is shared** — see
        `shares_a_flavour_factor`, which `canonical_key` refuses on.
        """
        charged = [{i: lam for i, lam in enumerate(self.node_reps[a]) if lam}
                   for a in range(self.rank)]
        return tuple(tuple(sorted((self.flavour.factors[i], lam)
                                  for i, lam in charged[a].items()))
                     for a in range(self.rank))

    def shares_a_flavour_factor(self) -> bool:
        """Is some simple factor of `G` charged under by more than one node?

        In the author's stated setting this is `False`: each group of `N_a`
        identical nodes gets its own `SU(N_a)` and the reduced node carries its
        fundamental, so the node-to-factor map is injective on the factors that
        are used at all.
        """
        seen: set[int] = set()
        for a in range(self.rank):
            for i, lam in enumerate(self.node_reps[a]):
                if not lam:
                    continue
                if i in seen:
                    return True
                seen.add(i)
        return False

    def canonical_key(self) -> tuple:
        """The dictionary identity: the flavoured quiver up to node relabelling.

        `quiver_enumeration.canonical_form` with the flavour datum as the node
        colour — an entry is then the pair (canonical exchange matrix, node
        colours in canonical order).  Two flavoured quivers have the same key
        iff a node permutation carries one to the other preserving the reps,
        which is precisely when they have the same `S`.

        This is the key a **dictionary of quivers with `G` symmetry** would use; the flavour datum being just another node colour is
        why the design record's machinery extends to it without change.

        **Honest-fails when a flavour factor is shared between nodes.**  The
        node colours are then not a complete invariant — two nodes under one
        `SU(2)` and two nodes under `SU(2) × SU(2)` give identical node colours
        and are different objects — and separating them needs the node–factor
        incidence canonicalised jointly with the quiver, which is not built.
        Rather than return a key that silently conflates them, this refuses.
        The case does not arise in the setting the construction is for (one
        factor per node group).
        """
        from quiver_enumeration import canonical_form
        if self.shares_a_flavour_factor():
            raise NotImplementedError(
                "canonical_key: a flavour factor is charged under by more "
                "than one node, and the node colours are not a complete "
                "invariant there — the node-factor incidence would have to be "
                "canonicalised jointly with the quiver, which is not built")
        colours = self.node_colours()
        cf = canonical_form(self.pairing, colours=colours)
        return (cf.key, tuple(colours[cf.perm[i]] for i in range(self.rank)))

    def colour_preserving_aut_order(self) -> int:
        """`|Aut|` of the flavoured quiver — node symmetries preserving the reps.

        Smaller than the uncoloured `|Aut(B)|` whenever the flavour assignment
        breaks a symmetry of the bare exchange matrix.
        """
        from quiver_enumeration import canonical_form
        return canonical_form(self.pairing, colours=self.node_colours()).aut_order

    def node_weights(self, a: int) -> dict[Weight, int]:
        return dict(self._weights[a])

    def bracket(self, k: Vec, l: Vec) -> int:
        B = self.pairing
        return sum(k[i] * B[i][j] * l[j]
                   for i in range(self.rank) if k[i]
                   for j in range(self.rank) if l[j])

    # ----- the chart on `Gamma_gauge (+) P` ------------------------------
    def gauge_weight_chart(self) -> tuple[list[list[int]], list[Vec],
                                          list[tuple[int, Weight]]]:
        """Chart data on `Γ_gauge ⊕ P` — the flavour weight lattice as a FACTOR.

        The author's ruling, 2026-09-14: *"in order to place your algebra in a flavoured
        KAlgebra context, you need to have the weight lattice of the non-Abelian
        flavour as a factor of the overall charge lattice.  Then when looking
        for F's you can relax the gauge-N-ality connection and satisfy the
        axioms"*.

        Returns `(pairing, node_charges, labels)` for the BPS chart on the
        lattice `Γ_gauge ⊕ P`, `P = ⊕_a P(SU(N_a))` in `to_abelian`
        coordinates: the pairing is the reduced `B` on the gauge block and zero
        on the flavour block (the flavour directions are isotropic and pair to
        zero with the gauge ones), and the node charges are `e_a ⊕ w` for each
        weight `w` of node `a`'s rep.

        This is **not** `unfold()`.  The unfolded quiver's node charges span
        only a finite-index sublattice of this one — for a node under `SU(2)`
        they generate the difference of the two leaf charges, i.e. the *root*
        `2ω`, never the fundamental weight `ω` itself.  That index is exactly
        what manufactured the N-ality condition in `enlarged_charge`, the
        absence of a flavour-trivial section at a charge of non-zero N-ality,
        and the factor of two between the chart's `ker(B)` coordinates and
        `FlavourSpace` weights.  Here `ω` is a lattice point, so every
        `(γ, w)` is a charge, the trivial irrep sections every gauge charge,
        and the flavour ring embeds centrally in full.

        On a single `SU(N)` factor this reproduces the input that
        `src/bps/gf_bps_kalgebra.py::GfBPSKAlgebra` already takes —
        asserted, not claimed, in `tests/test_gbps_kalgebra.py`.
        """
        F = self.flavour
        g, d = self.rank, F.dim
        n = g + d
        pairing = [[0] * n for _ in range(n)]
        for i in range(g):
            for j in range(g):
                pairing[i][j] = int(self.pairing[i][j])
        charges: list[Vec] = []
        labels: list[tuple[int, Weight]] = []
        for a in range(g):
            for w in sorted(self.node_weights(a)):
                v = [0] * n
                v[a] = 1
                for j in range(d):
                    v[g + j] = w[j]
                charges.append(tuple(v))
                labels.append((a, w))
        return pairing, charges, labels

    def gf_chart_data(self):
        """Constructor data for `src/bps/gf_bps_kalgebra.py::GfBPSKAlgebra`.

        Returns `(pairing, node_charges, reflections, ring, mu_basis)` — the five
        arguments that class takes by hand — on the `Γ_gauge ⊕ P` chart of
        `gauge_weight_chart`.

        * `reflections` are the simple transpositions of `W = ∏_a S_{N_a}`,
          generated per factor in that factor's `to_abelian` coordinates
          `x_i = w_i − w_N`: `s_i` (`i < N−1`) swaps `x_i, x_{i+1}`, and the last
          one sends `x_j ↦ x_j − x_{N−1}` (`j < N−1`), `x_{N−1} ↦ −x_{N−1}`.  They
          act trivially on the gauge block.
        * `mu_basis` is the trailing unit vectors: `gauge_weight_chart` PLACES the
          weight lattice as a named block, so the alignment between `ker B` and the
          ring's weight coordinates is known by construction rather than solved for.

        For one simple factor this reproduces that class's own hand-written `SU(2)`
        and `SU(3)` matrices — asserted in `tests/test_gbps_kalgebra.py`, which is
        the check that the generated data is the established convention and not a
        parallel one.
        """
        F = self.flavour
        pairing, charges, _labels = self.gauge_weight_chart()
        g, d = self.rank, F.dim
        n = g + d

        def unit(i):
            return [1 if k == i else 0 for k in range(n)]

        reflections = []
        for a, N in enumerate(F.factors):
            if N <= 1:
                continue
            # offset within the FULL lattice: the weight block starts at `g`
            lo, wd = g + F.offsets[a], F.widths[a]
            for i in range(N - 1):
                M = [unit(k) for k in range(n)]        # identity
                if i < N - 2:
                    M[lo + i] = unit(lo + i + 1)
                    M[lo + i + 1] = unit(lo + i)
                else:                                   # the last transposition
                    for j in range(wd - 1):
                        row = unit(lo + j)
                        row[lo + wd - 1] -= 1
                        M[lo + j] = row
                    last = [0] * n
                    last[lo + wd - 1] = -1
                    M[lo + wd - 1] = last
                reflections.append([list(r) for r in M])

        mu_basis = [tuple(unit(g + j)) for j in range(d)]
        return pairing, charges, reflections, F.zplus_ring(), mu_basis

    # ----- unfolding ----------------------------------------------------
    def unfoldable(self) -> bool:
        """Can every node rep be split into distinct one-dimensional weights?

        False exactly when some node rep has a repeated weight, in which case
        two unfolded nodes would carry the same charge and the unfolded object
        is not a BPS quiver.  The author's ruling (2026-09-13) is that node reps
        are fundamentals in reality, so this is `True` on everything the
        battery covers — which is what supplies the ground truth.
        """
        return all(all(m == 1 for m in w.values()) for w in self._weights)

    def unfold(self) -> tuple[list[list[int]], list[Vec], list[tuple[int, Weight]]]:
        """The ordinary BPS quiver on `Σ_a dim r_a` nodes.

        Returns `(pairing, node_charges, labels)` where `labels[i] = (a, w)`
        names the node as the weight `w` of node `a`'s rep.  The pairing between
        unfolded nodes is the reduced pairing of their gauge charges, since the
        flavour directions are central; in particular nodes within one group
        commute and pair identically with everything else — the *"identical
        permutable nodes"* the flavoured datum packages.
        """
        if not self.unfoldable():
            raise ValueError(
                "unfold: a node rep has a repeated weight, so the unfolded "
                "nodes would not have distinct charges")
        labels: list[tuple[int, Weight]] = []
        for a in range(self.rank):
            for w in sorted(self._weights[a]):
                labels.append((a, w))
        n = len(labels)
        B = [[self.pairing[labels[i][0]][labels[j][0]] for j in range(n)]
             for i in range(n)]
        charges = [tuple(1 if j == i else 0 for j in range(n)) for i in range(n)]
        return B, charges, labels


# --------------------------------------------------------------------------
# the recursion
# --------------------------------------------------------------------------

class FlavouredFactorSpectrum:
    """`S ∈ \\cE_G` from flavoured leading data, on the reduced cone.

    The recursion is the unflavoured one of `BPSFactorSpectrum` carrying a
    weight grading: the accumulator is `{reduced cone point: {weight: Habiro}}`,
    and at each reduced cone point `Ω` is forced **independently at each
    weight** — legitimate because the `μ` are central and of `\\fq`-degree zero,
    so the `\\fq`-triangularity that forces `Ω` in the unflavoured case runs
    unchanged weight by weight.  `Ω`'s Weyl invariance is therefore never
    imposed; it comes out, and `multiplicities()` is where it is read.

    Parameters
    ----------
    quiver
        A `FlavouredQuiver`.
    cutoff
        Reduced-cone degree truncation `D`.  The only truncation.
    leading_data
        `reduced charge -> {weight: int}`, the prescribed `\\fq^1`-coefficient
        of `S`.  Default: `-χ_{r_a}` at the node charge `γ_a`, zero elsewhere —
        the flavoured BPS quiver constraint.
    piece_key
        `(charge, 2s, r) -> sortable` — **the index set is
        `Γ_+ × ½N × Irr(G)`**, one position per multiplet factor
        `E^{(s;r)}_\\fq(X_γ)^{Ω(γ,s,r)}`.  `S` is conjecturally independent of
        it (the flavoured PBW conjecture).  Pieces at one charge commute
        (`⟨γ,γ⟩ = 0`, flavour central), so placing them separately is licensed
        exactly as in the unflavoured engine.

        ⚠ **It is the index set that matters, and it is `Irr(G)`, not the
        weights.**  A whole `E^{(s;r)}` must be placed as one unit.  Ordering
        the individual weight factors `E^{(s)}_\\fq(μ^w X_γ)` independently
        still factors `S` — that is a factorization in the *enlarged* `\\cE` —
        but the resulting multiplicities are **not** `G`-characters, so it
        leaves `\\cE_G`.  Measured: on Kronecker-2 with `SU(2)` on one node a
        random weight-level order makes `Ω` fail Weyl invariance, and
        `multiplicities()` honest-fails rather than projecting.  That negative
        control is `split_weights=True` below.
    split_weights
        **Negative control only.**  Place individual weight factors rather than
        whole reps, ordered by `piece_key(charge, 2s, weight)`.  `S` is
        unchanged (it is order-independent in the enlarged `\\cE`), but `Ω`
        generally stops being a character — which is the evidence that the
        generator set of `\\cE_G` is doing real work.
    """

    def __init__(self, quiver: FlavouredQuiver, cutoff: int, *,
                 leading_data: Callable[[Vec], dict[Weight, int]] | None = None,
                 piece_key: Callable[..., object] | None = None,
                 split_weights: bool = False):
        if cutoff < 1:
            raise ValueError(f"cutoff must be >= 1, got {cutoff}")
        if split_weights and piece_key is None:
            raise ValueError("split_weights is a negative control; it needs a "
                             "piece_key(charge, 2s, weight) to order by")
        self.quiver = quiver
        self.rank = quiver.rank
        self.degree_cap = int(cutoff)
        self._piece_key = piece_key
        self._split_weights = bool(split_weights)
        self._leading = leading_data
        self.omega: dict[Vec, dict[Weight, dict[int, int]]] = {}
        #: `(charge, irrep, 2s, exponent)` in the order the generators were
        #: placed — the sequence a spec reading needs, since a spec is an
        #: ordered product and `Ω` alone is only a multiset.
        self.placements: list[tuple[Vec, Irrep, int, int]] = []
        self._placement_keys: list = []
        self._S: dict[Vec, dict[Weight, HabiroElement]] | None = None

    # ----- the constraint ----------------------------------------------
    def target(self, k: Vec) -> dict[Weight, int]:
        """The prescribed `\\fq^1`-coefficient of `S` at the reduced charge `k`."""
        if self._leading is not None:
            return {w: int(c) for w, c in self._leading(k).items() if c}
        if sum(k) == 1:
            a = k.index(1)
            return {w: -m for w, m in self.quiver.node_weights(a).items()}
        return {}

    # ----- the run ------------------------------------------------------
    def _readout(self, acc, degree: int):
        """`Ω` at every reduced cone point of one degree, forced by `acc`.

        Reading a whole degree before placing any of its factors is sound: a
        factor at a charge `k` of degree `d` contributes only at the multiples
        `nk`, `n ≥ 1`, hence only at degrees `≥ d`, and two distinct degree-`d`
        charges interact first at degree `2d`.  So no degree-`d` factor can
        change another degree-`d` readout.
        """
        fresh: list[tuple[Vec, dict[Weight, dict[int, int]]]] = []
        for k in cone_simplex(self.rank, self.degree_cap):
            if sum(k) != degree:
                continue
            here = acc.get(k, {})
            tgt = self.target(k)
            om_w: dict[Weight, dict[int, int]] = {}
            for w in set(here) | set(tgt):
                h = here.get(w)
                om = BPSFactorSpectrum._forced(
                    expansion(h) if h is not None else {}, tgt.get(w, 0))
                if om:
                    om_w[w] = om
            if om_w:
                fresh.append((k, om_w))
        return fresh

    def run(self) -> dict[Vec, dict[Weight, dict[int, int]]]:
        if self._piece_key is not None:
            return self._run_insert()
        return self._run_append()

    def _run_append(self) -> dict[Vec, dict[Weight, dict[int, int]]]:
        """No `piece_key`: place each charge's whole factor, in cone order."""
        F = self.quiver.flavour
        zero = tuple([0] * self.rank)
        acc: dict[Vec, dict[Weight, HabiroElement]] = {zero: {F.zero: H1}}
        self.omega = {}
        self.placements = []
        for d in range(1, self.degree_cap + 1):
            fresh = self._readout(acc, d)
            for k, om_w in fresh:
                self.omega[k] = om_w
            for k, om_w in fresh:
                for (rep, two_s), amount in self._omega_by_rep_spin(om_w).items():
                    self.placements.append((k, rep, two_s, amount))
                acc = self._factor_multiply(acc, k, d, om_w)
        self._S = acc
        return self.omega

    def _run_insert(self) -> dict[Vec, dict[Weight, dict[int, int]]]:
        """An ARBITRARY total order on `Γ_+ × ½N × Irr(G)`, honoured globally.

        The paper's PBW statement quantifies over *any* total order, not only
        the degree-compatible ones, so a factor discovered at degree `d` may
        have to be placed **before** factors already placed at lower degrees.
        That is what this mode does: factors are kept in a list sorted by
        `piece_key`, with cached prefix products, and each newly discovered
        factor is inserted at its sorted position with only the invalidated
        suffix rebuilt.

        Reading out at a higher degree stays correct after such an insertion
        because a degree-`d` factor contributes nothing below degree `d`, so
        every readout already taken is unaffected by where the new factor lands.

        (The degree-compatible special case is `_run_append`, which is cheaper
        and is what runs when no `piece_key` is given.  An earlier version of
        this module applied `piece_key` only *within* a degree — that silently
        tested a weaker statement than the conjecture makes.)
        """
        import bisect

        F = self.quiver.flavour
        zero = tuple([0] * self.rank)
        placed: list[tuple[Vec, dict[Weight, dict[int, int]], int]] = []
        self._placement_keys = []
        sort_keys: list = []
        prefix: list[dict[Vec, dict[Weight, HabiroElement]]] = [
            {zero: {F.zero: H1}}]
        self.omega = {}

        for d in range(1, self.degree_cap + 1):
            fresh = self._readout(prefix[-1], d)
            if not fresh:
                continue
            for k, om_w in fresh:
                self.omega[k] = om_w
            first = len(placed)
            for key, k, blk in self._pieces_of_degree(fresh):
                self._placement_keys.append((key, k, blk))
                at = bisect.bisect_left(sort_keys, key)
                sort_keys.insert(at, key)
                placed.insert(at, (k, blk, d))
                first = min(first, at)
            del prefix[first + 1:]
            for i in range(first, len(placed)):
                k, blk, deg = placed[i]
                prefix.append(self._factor_multiply(prefix[i], k, deg, blk))

        self._S = prefix[-1]
        # The spec reading: the generators in the order they were placed.
        # Under `split_weights` — the negative control — the pieces are single
        # weight factors and `Ω` is generally NOT a character, so there is no
        # rep labelling to read; `placements` stays empty rather than forcing a
        # decomposition that is meant to fail there.
        self.placements = []
        if not self._split_weights:
            for _key, k, blk in sorted(self._placement_keys, key=lambda t: t[0]):
                for (rep, two_s), amount in self._omega_by_rep_spin(blk).items():
                    self.placements.append((k, rep, two_s, amount))
        return self.omega

    def _pieces_of_degree(self, fresh):
        """The `(key, charge, weight-block)` factors discovered at one degree.

        One entry per generator `E^{(s;r)}_\\fq(X_γ)^{Ω(γ,s,r)}`, the rep kept
        whole — or, under `split_weights`, one per individual weight factor,
        which is the negative control.
        """
        out = []
        for k, om_w in fresh:
            if self._split_weights:
                for w, om in om_w.items():
                    for two_s, amount in spin_decompose(om).items():
                        piece = {j: amount for j in range(-two_s, two_s + 1, 2)}
                        out.append((self._piece_key(k, two_s, w), k, {w: piece}))
                continue
            for (rep, two_s), amount in self._omega_by_rep_spin(om_w).items():
                blk: dict[Weight, dict[int, int]] = {}
                for w, m in self.quiver.flavour.irrep_weights(rep).items():
                    blk[w] = {j: amount * m
                              for j in range(-two_s, two_s + 1, 2)}
                out.append((self._piece_key(k, two_s, rep), k, blk))
        return out

    # ----- Ω: weights -> (irrep, spin) ----------------------------------
    def _omega_by_rep(self, om_w: dict[Weight, dict[int, int]]
                      ) -> dict[Irrep, dict[int, int]]:
        """One `Ω(γ)`, from its weight expansion to a per-irrep `\\fq`-polynomial.

        Honest-fails (via `FlavourSpace.decompose`) if the weight function is
        not `W`-invariant — it never silently projects onto the invariants.
        """
        F = self.quiver.flavour
        by_q: dict[int, dict[Weight, int]] = {}
        for w, om in om_w.items():
            for j, c in om.items():
                if c:
                    by_q.setdefault(j, {})[w] = c
        per_rep: dict[Irrep, dict[int, int]] = {}
        for j, fn in by_q.items():
            for rep, c in F.decompose(fn).items():
                if c:
                    poly = per_rep.setdefault(rep, {})
                    poly[j] = poly.get(j, 0) + c
        per_rep = {r: {j: c for j, c in poly.items() if c}
                   for r, poly in per_rep.items()}
        return {r: poly for r, poly in per_rep.items() if poly}

    def _omega_by_rep_spin(self, om_w) -> dict[tuple[Irrep, int], int]:
        out: dict[tuple[Irrep, int], int] = {}
        for rep, poly in self._omega_by_rep(om_w).items():
            for two_s, amount in spin_decompose(poly).items():
                if amount:
                    out[(rep, two_s)] = amount
        return out

    # ----- the flavoured factor ----------------------------------------
    def _factor_series(self, om_w: dict[Weight, dict[int, int]], n_max: int):
        """`∏_{s,r} E^{(s;r)}_\\fq(X_γ)^{Ω(γ,s,r)}` along the ray, weight-graded.

        Written on weights rather than on irreps, which is the same product:
        `E^{(s;r)}_\\fq(X_γ) = ∏_{w∈r} E^{(s)}_\\fq(μ^w X_γ)`, so collecting the
        `E^{(s)}` factors by weight gives one ordinary charge series per weight,
        with content `Ω(γ)[w]`.  They all commute, so the ray factor is their
        weight-convolution.  Returns `[{weight: Habiro}] * (n_max+1)`, indexed by
        the multiple `n` of the reduced charge.
        """
        F = self.quiver.flavour
        out: list[dict[Weight, HabiroElement]] = [{} for _ in range(n_max + 1)]
        out[0] = {F.zero: H1}
        for w, om in sorted(om_w.items()):
            ray = charge_series(om, n_max)
            nxt: list[dict[Weight, HabiroElement]] = [{} for _ in range(n_max + 1)]
            for n1 in range(n_max + 1):
                block = out[n1]
                if not block:
                    continue
                for n2 in range(n_max + 1 - n1):
                    u = ray[n2]
                    if u.is_zero():
                        continue
                    shift = F.scale(w, n2)
                    dest = nxt[n1 + n2]
                    for W, h in block.items():
                        key = F.add(W, shift)
                        prev = dest.get(key)
                        dest[key] = h * u if prev is None else prev + h * u
            out = [{k: v for k, v in blk.items() if not v.is_zero()}
                   for blk in nxt]
        return out

    def _factor_multiply(self, acc, k0: Vec, deg0: int,
                         om_w: dict[Weight, dict[int, int]]):
        """`acc · (the ray factor at k0)`, truncated to the reduced cone."""
        F = self.quiver.flavour
        n_max = self.degree_cap // deg0
        ray = self._factor_series(om_w, n_max)
        out: dict[Vec, dict[Weight, HabiroElement]] = {}
        for k, block in acc.items():
            deg_k = sum(k)
            br = self.quiver.bracket(k, k0)
            for n in range(n_max + 1):
                if deg_k + n * deg0 > self.degree_cap:
                    break
                piece = ray[n]
                if not piece:
                    continue
                key_k = tuple(k[i] + n * k0[i] for i in range(self.rank))
                phase = q_pow(n * br) if br else None
                dest = out.setdefault(key_k, {})
                for W, h in block.items():
                    for W2, u in piece.items():
                        term = h * u
                        if phase is not None:
                            term = term * phase
                        key = F.add(W, W2)
                        prev = dest.get(key)
                        dest[key] = term if prev is None else prev + term
        return {k: {w: h for w, h in blk.items() if not h.is_zero()}
                for k, blk in out.items()
                if any(not h.is_zero() for h in blk.values())}

    # ----- readouts -----------------------------------------------------
    def spectrum_generator(self) -> dict[tuple[Vec, Weight], HabiroElement]:
        """`S` as `{(reduced charge, flavour weight): coefficient}`.

        The identity term sits at `((0,…,0), 0)`.  This is the flavoured `S`
        written on the enlarged lattice, which is the shape the unflavoured
        engine's `S` has and therefore the shape a comparison needs.
        """
        if self._S is None:
            self.run()
        out: dict[tuple[Vec, Weight], HabiroElement] = {}
        for k, blk in self._S.items():
            for w, h in blk.items():
                if not h.is_zero():
                    out[(k, w)] = h
        return out

    def multiplicities(self) -> dict[Vec, dict[Irrep, dict[int, int]]]:
        """`Ω(γ, r)` — at each reduced charge, a palindromic `\\fq`-polynomial
        per irrep of `G`.

        Raises if some `Ω(γ)` is not Weyl-invariant, i.e. is not a virtual
        character — an honest failure.  That it never does is the substantive
        flavoured claim (`S ∈ \\cE_G`), so this is the load-bearing readout.
        """
        if self._S is None:
            self.run()
        out: dict[Vec, dict[Irrep, dict[int, int]]] = {}
        for k, om_w in self.omega.items():
            per_rep = self._omega_by_rep(om_w)
            if per_rep:
                out[k] = per_rep
        return out

    def multiplicities_by_spin(self) -> dict[Vec, dict[tuple[Irrep, int], int]]:
        """`Ω(γ, s, r)` — the flavoured PBW exponents, keyed `(r, 2s)`."""
        if self._S is None:
            self.run()
        out: dict[Vec, dict[tuple[Irrep, int], int]] = {}
        for k, om_w in self.omega.items():
            here = self._omega_by_rep_spin(om_w)
            if here:
                out[k] = here
        return out

    # ----- the generators, as operations on a built `S` ------------------
    def generator_weight_content(self, rep: Irrep, two_s: int,
                                 exponent: int = 1) -> dict[Weight, dict[int, int]]:
        """`E^{(s;r)}_\\fq(X_γ)^{exponent}` as a per-weight `Ω` block.

        The generator is `∏_{w∈r} E^{(s)}_\\fq(μ^w X_γ)^{exponent}`, so at the
        weight `w` its content is `exponent·mult_r(w)·χ_s` — which is exactly
        what one ordinary ray factor of content `Ω[w]` means.  Independent of
        the charge, since a charge's self-bracket vanishes.
        """
        out: dict[Weight, dict[int, int]] = {}
        for w, m in self.quiver.flavour.irrep_weights(rep).items():
            out[w] = {j: exponent * m for j in range(-two_s, two_s + 1, 2)}
        return out

    def times_generator(self, acc, charge: Vec, rep: Irrep, two_s: int,
                        exponent: int = 1):
        """`acc · E^{(s;r)}_\\fq(X_charge)^{exponent}`, cone-truncated.

        The operation the uniqueness axiom is stated against: multiplying a
        candidate `S` by a single generator of `\\cE_G` and asking whether the
        BPS quiver constraint survives.
        """
        deg = sum(charge)
        if deg < 1:
            raise ValueError("charge must lie in the positive cone")
        return self._factor_multiply(
            acc, tuple(charge), deg,
            self.generator_weight_content(rep, two_s, exponent))

    def constraint_violations(self, acc=None) -> list[tuple[Vec, Weight, str]]:
        """Where a candidate `S` fails the flavoured BPS quiver constraint.

        Two conditions, both of them what `\\cE_G ∋ S = 1 - \\fq Σ_a χ_{r_a}(μ)
        X_{γ_a} + O(\\fq^2)` says: no coefficient carries a non-positive power
        of `\\fq` away from the identity, and the `\\fq^1` coefficients are the
        prescribed leading data.  Empty list = the constraint holds on the
        truncated cone.
        """
        if acc is None:
            if self._S is None:
                self.run()
            acc = self._S
        F = self.quiver.flavour
        zero = tuple([0] * self.rank)
        bad: list[tuple[Vec, Weight, str]] = []
        for k, blk in acc.items():
            for w, h in blk.items():
                if h.is_zero():
                    continue
                if (k, w) == (zero, F.zero):
                    if h != H1:
                        bad.append((k, w, "identity term != 1"))
                    continue
                neg = {e: c for e, c in expansion(h).items() if e <= 0 and c}
                if neg:
                    bad.append((k, w, f"non-positive \\fq powers {neg}"))
        for k in cone_simplex(self.rank, self.degree_cap):
            k = tuple(k)
            blk = acc.get(k, {})
            tgt = self.target(k)
            for w in set(tgt) | set(blk):
                got = expansion(blk[w]).get(1, 0) if w in blk else 0
                want = tgt.get(w, 0)
                if got != want:
                    bad.append((k, w, f"\\fq^1 = {got}, leading data says {want}"))
        return bad

    # ----- verifiers ----------------------------------------------------
    def verify_leading_data(self) -> list[tuple[Vec, Weight, str]]:
        """`S`'s `\\fq^1`-coefficient against the prescribed leading data.

        **Enforced, not emergent** — the recursion solves for exactly this, so
        this is a regression guard on the arithmetic and not evidence about the
        conjectures (the audit, the same caveat as unflavoured).
        """
        S = self.spectrum_generator()
        bad: list[tuple[Vec, Weight, str]] = []
        F = self.quiver.flavour
        zero = (tuple([0] * self.rank), F.zero)
        for (k, w), h in S.items():
            exp = expansion(h)
            if (k, w) == zero:
                if h != H1:
                    bad.append((k, w, "identity term != 1"))
                continue
            neg = {e: c for e, c in exp.items() if e <= 0 and c}
            if neg:
                bad.append((k, w, f"non-positive \\fq powers {neg}"))
        for k in cone_simplex(self.rank, self.degree_cap):
            tgt = self.target(tuple(k))
            for w, want in tgt.items():
                got = expansion(S.get((tuple(k), w), H0)).get(1, 0)
                if got != want:
                    bad.append((tuple(k), w,
                                f"\\fq^1 = {got}, leading data says {want}"))
        return bad

    def verify_omega_is_a_character(self) -> list[tuple[Vec, str]]:
        """Every `Ω(γ)` is `W`-invariant, i.e. a virtual character of `G`.

        **Emergent** — nothing in the recursion imposes it (`Ω` is forced weight
        by weight, independently), so a pass is genuine evidence for
        `S ∈ \\cE_G`.  This is the substantive flavoured claim.
        """
        F = self.quiver.flavour
        if self._S is None:
            self.run()
        bad: list[tuple[Vec, str]] = []
        for k, om_w in self.omega.items():
            by_q: dict[int, dict[Weight, int]] = {}
            for w, om in om_w.items():
                for j, c in om.items():
                    if c:
                        by_q.setdefault(j, {})[w] = c
            for j, fn in by_q.items():
                if not F.is_weyl_invariant(fn):
                    bad.append((k, f"\\fq^{j} weight function not W-invariant"))
        return bad


# --------------------------------------------------------------------------
# public entry points
# --------------------------------------------------------------------------

def build_flavoured_spectrum_generator(
    quiver: FlavouredQuiver, cutoff: int, *,
    leading_data: Callable[[Vec], dict[Weight, int]] | None = None,
    piece_key: Callable[[Vec, int, Weight], object] | None = None,
    with_multiplicities: bool = False,
):
    """`S ∈ \\cE_G` for a flavoured BPS quiver, from the flavoured constraint."""
    eng = FlavouredFactorSpectrum(quiver, cutoff, leading_data=leading_data,
                                  piece_key=piece_key)
    eng.run()
    S = eng.spectrum_generator()
    return (S, eng.multiplicities_by_spin()) if with_multiplicities else S


def canonical_spectrum_generator(quiver: FlavouredQuiver, cutoff: int):
    """`S` in the flavoured quiver's CANONICAL node coordinates.

    The dictionary-facing readout: two flavoured quivers related by a node
    relabelling give the identical dict, so entries can be compared without
    carrying a witness permutation.  Both the reduced charge and the flavour
    weight are transported, the weight because the torus coordinates are
    concatenated in node order.

    Requires `canonical_key`'s precondition (no shared flavour factor), since
    it uses the same node colouring.
    """
    from quiver_enumeration import canonical_form
    if quiver.shares_a_flavour_factor():
        raise NotImplementedError(
            "canonical_spectrum_generator: see FlavouredQuiver.canonical_key")
    F = quiver.flavour
    cf = canonical_form(quiver.pairing, colours=quiver.node_colours())
    eng = FlavouredFactorSpectrum(quiver, cutoff)
    eng.run()
    out: dict[tuple[Vec, Weight], HabiroElement] = {}
    for (k, w), h in eng.spectrum_generator().items():
        ck = tuple(k[cf.perm[i]] for i in range(quiver.rank))
        cw: Weight = ()
        for i in range(quiver.rank):
            src, wd = F.offsets[cf.perm[i]], F.widths[cf.perm[i]]
            cw += tuple(w[src:src + wd])
        out[(ck, cw)] = h
    return out


def unfolded_spectrum_generator(quiver: FlavouredQuiver, cutoff: int):
    """`S` of the **unfolded** quiver, relabelled onto `(reduced charge, weight)`.

    The independent ground truth: this runs the unflavoured engine
    (`BPSFactorSpectrum`) on the ordinary BPS quiver whose nodes are the
    weights of the node reps, then pushes each enlarged charge forward to its
    `(gauge charge, flavour weight)` pair.  The two engines share the ray
    arithmetic and nothing else — the flavoured one runs its recursion on the
    reduced cone with a weight grading, this one on the enlarged cone with no
    flavour notion at all.
    """
    F = quiver.flavour
    B, charges, labels = quiver.unfold()
    eng = BPSFactorSpectrum(B, charges, cutoff, order="lex")
    eng.run()
    out: dict[tuple[Vec, Weight], HabiroElement] = {}
    for k, h in eng.spectrum_generator().items():
        if h.is_zero():
            continue
        gauge = [0] * quiver.rank
        weight = F.zero
        for i, n in enumerate(k):
            if not n:
                continue
            a, w = labels[i]
            gauge[a] += n
            weight = F.add(weight, F.scale(w, n))
        key = (tuple(gauge), weight)
        prev = out.get(key)
        out[key] = h if prev is None else prev + h
    return {k: v for k, v in out.items() if not v.is_zero()}
