"""`GfBPSKAlgebra` -- the G-flavoured BPS realisation of A_q[T].

The BPS counterpart of `GfQuantumTorusKAlg`: the **Weyl-invariant
subalgebra of a `BPSKAlgebra`**, for a BPS quiver with `n` flavour nodes
carrying an `S_n` (more generally `Weyl(Phi)`) permutation symmetry, which
realises an `SU(n)` (single simple factor) global symmetry.

This generalises `SU2BPSKAlgebra` and *fixes* `SU3BPSKAlgebra`: the latter
builds the canonical basis from the cyclic `Z_3` (sub)group generated by an
order-3 `sigma`, but `SU(3)` needs the **full `S_3` Weyl group** (order 6).
A `Z_3`-invariant element is not `S_3`-invariant, so the `Z_3` construction
presents the wrong algebra (e.g. it returns `3 (x) 3 = 6 + 2*3bar` instead
of `6 + 3bar`).  Here the full Weyl group is supplied as Poisson
reflections (the node-pair transpositions) and the canonical basis is the
**Weyl character** weight diagram in the BPS F-basis -- which reproduces
`R(SU(n))` fusion exactly.

Data
----
* `pairing`, `node_charges`, `**bps_kwargs`: the underlying `BPSKAlgebra`.
* `reflections`: Poisson involutions `s_i` on `Gamma` generating the
  flavour Weyl group `W` (the `S_n` node permutations), acting on
  `ker B` as the reflection representation, with roots in `ker B`.
* `ring`: `R(T)^W` (the global form; rings: `SU2`/`SO3` rank-1, `SU3`).
* `mu_basis`: a `Z`-basis of `ker B` aligning it with the ring's
  `to_abelian` weight coordinates.

Canonical labels are dominant `W`-orbit representatives `gamma`; the basis
element `L_gamma` is the Weyl character of `chi_{lambda(gamma)}` in the
F-basis,  `L_gamma = sum_{weights mu} F_{gamma + phi(mu - lambda)}`.
`multiply` lifts both labels to F-elements, multiplies pairwise in the BPS
algebra, and peels the most-dominant character back out; `rho` is the BPS
half-monodromy then canonicalise; the trace is the BPS Schur trace
converted to `R(T)^W` via `from_abelian`.

Scope: integer ring-weight sector (the spinor sector raises); rings rank-1
(`SU2`/`SO3`), `SU3`, `SUNZPlusRing(N)` at any `N`, and **products of these**
via `zplus_ring.TensorZPlusRing`.

Product flavour groups
------------------------------------------------
`prod_a SU(N_a)` is the **block** generalisation of a single simple factor:
a product character's weight diagram is the outer product of the factors', so
its coordinates are the CONCATENATION of theirs, and dominance, the
orbit-ordering key and the weight<->label maps all act factor by factor.  The
chart is therefore a recursion over the ring
(`gf_quantum_torus_kalgebra._ring_is_dominant`, `_ring_dom_key`,
`_ring_wt_to_label`, `_ring_label_to_hw`), shared with `GfQuantumTorusKAlg`,
which carried an identical copy of the per-kind switch.  It is
**shape-preserving**: on a bare simple ring these return exactly what the
previous switches returned, so every single-factor result is unchanged.

What made a product possible at all was the missing torus embedding:
`TensorZPlusRing` had fusion, duality and dimension but no `to_abelian` /
`from_abelian`, and this class needs both (`_lift_to_F` reads the weight
diagram, `trace` un-branches the BPS Schur trace).  They are now on the ring,
peeled factor by factor through each factor's own `from_abelian`.

Constructor data for a flavoured quiver is generated by
`flavoured_factor_spectrum.FlavouredQuiver.gf_chart_data()` -- pairing and node
charges on `Gamma_gauge (+) P`, the simple transpositions of `W = prod_a S_{N_a}`,
the ring, and the `mu_basis` (known by construction, since that chart PLACES the
weight lattice as a named block).  For one simple factor it reproduces this
module's own hand-written `SU(2)` and `SU(3)` matrices, asserted in
`tests/test_gf_bps_kalgebra.py`.
"""

from __future__ import annotations

from fractions import Fraction
from typing import Sequence

import sys
import os

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from kalgebra import KAlgebra, Element
from bps_kalgebra import BPSKAlgebra
from zplus_ring import ZPlusRing, RElement, RPowerSeries, AbelianZPlusRing
from snf_kernel import decompose_in_basis
from laurent_poly import LaurentPoly
from gf_quantum_torus_kalgebra import (
    _matvec, _matmul, _brow, _solve_in_basis, _mat_inverse, _ring_torus_rank,
    _ring_kind, _ring_blocks, _ring_is_dominant, _ring_dom_key,
    _ring_wt_to_label, _ring_label_to_hw,
)


Vec = tuple[int, ...]
QVec = tuple[Fraction, ...]
Label = Vec


class GfBPSKAlgebra(KAlgebra):
    """`A_q[T]^W`, the G-flavoured BPS realisation (see module doc)."""

    def __init__(self, pairing, node_charges, reflections, ring, mu_basis,
                 **bps_kwargs):
        self._bps = BPSKAlgebra(pairing=pairing, node_charges=node_charges,
                                **bps_kwargs)
        n = self._bps.lattice.rank
        self._rank = n
        self._B = [[int(x) for x in row] for row in pairing]
        self._R = ring
        self._ring_kind = self._classify_ring(ring)

        self._ker_basis = [tuple(int(x) for x in v) for v in self._bps._ker_basis]
        self._sec_basis = [tuple(int(x) for x in v) for v in self._bps._sec_basis]
        self._gauge_rank = self._bps._gauge_rank
        self._flavour_rank = self._bps._flavour_rank

        # reflections: Poisson involutions permuting the spec
        self._reflections = [tuple(tuple(int(x) for x in row) for row in s)
                             for s in reflections]
        ident = tuple(tuple(1 if i == j else 0 for j in range(n)) for i in range(n))
        spec = [tuple(int(x) for x in g) for g in self._bps.spec]
        spec_set = set(spec)
        for idx, s in enumerate(self._reflections):
            if len(s) != n or any(len(row) != n for row in s):
                raise ValueError(f"reflection {idx} wrong shape")
            if _matmul(s, s) != ident:
                raise ValueError(f"reflection {idx} not an involution")
            sBs = [[sum(s[k][i] * self._B[k][l] * s[l][j]
                        for k in range(n) for l in range(n))
                    for j in range(n)] for i in range(n)]
            if sBs != self._B:
                raise ValueError(f"reflection {idx} not Poisson")
            if {tuple(_matvec(s, g)) for g in spec} != spec_set:
                raise ValueError(f"reflection {idx} does not permute the spec")

        self._W = self._generate_group(self._reflections)
        self._W_inv = [_mat_inverse(w) for w in self._W]

        self._mu_basis = [tuple(int(x) for x in v) for v in mu_basis]
        tr = _ring_torus_rank(self._R)
        if tr is None:
            raise NotImplementedError(f"unsupported ring {type(self._R).__name__}")
        if len(self._mu_basis) != tr:
            raise ValueError(f"mu_basis size {len(self._mu_basis)} != torus rank {tr}")
        if tr != self._flavour_rank:
            raise ValueError(
                f"flavour torus rank {tr} != rk(ker B) {self._flavour_rank}: the "
                "chart carries flavour the ring does not name (or vice versa).  "
                "A product group is fine — what is not is a RESIDUAL abelian "
                "flavour on top of the ring's weight lattice, which would be "
                "folded into the trivial character with no verifier catching it "
                "(the audit).  Grow the ring to "
                "TensorZPlusRing([AbelianZPlusRing(residual), …]) to cover it.")
        # The torus rank is computed by TWO independent routes — this module's
        # name-based `_ring_torus_rank` and (for a product) the ring's own
        # `factor_torus_ranks`, which probes each factor's identity image.  They
        # agree today on every ring in reach; if a new ring kind were added to
        # one and not the other, `_lift_to_F` would silently MIS-INDEX the shift
        # `kk[i] - wt[i]` rather than raise.  Cross-checked once here so that
        # becomes loud.
        ring_side = getattr(self._R, "torus_rank", None)
        if ring_side is not None and ring_side() != tr:
            raise ValueError(
                f"torus rank disagreement: _ring_torus_rank says {tr}, "
                f"{type(self._R).__name__}.torus_rank() says {ring_side()}")
        for w in self._mu_basis:
            if any(_brow(self._B, w, j) != 0 for j in range(n)):
                raise ValueError(f"mu_basis vector {w} not in ker B")
        for kv in self._ker_basis:
            _solve_in_basis(self._mu_basis, kv)
        for idx, s in enumerate(self._reflections):
            alpha = self._neg1_eig(s, n)
            try:
                _solve_in_basis(self._ker_basis, alpha)
            except ValueError:
                raise ValueError(f"reflection {idx}: root {alpha} not in ker B")

    # ----- setup helpers (shared shape with GfQuantumTorusKAlg) ----------

    @staticmethod
    def _classify_ring(ring) -> str:
        """Kept as the historical name; the chart itself is `_ring_*` below."""
        return _ring_kind(ring)

    def _generate_group(self, gens, cap=200000):
        n = self._rank
        I = tuple(tuple(1 if i == j else 0 for j in range(n)) for i in range(n))
        seen, frontier = {I}, [I]
        while frontier:
            cur = frontier.pop()
            for g in gens:
                nx = _matmul(cur, g)
                if nx not in seen:
                    seen.add(nx)
                    frontier.append(nx)
                    if len(seen) > cap:
                        raise ValueError(
                            f"flavour Weyl group exceeded the cap ({cap}) — this "
                            "is a BUDGET, not a finiteness verdict: for a product "
                            "flavour group the order is ∏_a N_a!, which multiplies "
                            "(SU(5)×SU(5) is 14400 and finite).  Raise `cap` if "
                            "that is intended.")
        return list(seen)

    @staticmethod
    def _neg1_eig(s, n) -> Vec:
        cols = [tuple(s[i][j] - (1 if i == j else 0) for i in range(n)) for j in range(n)]
        nz = [c for c in cols if any(x != 0 for x in c)]
        if not nz:
            raise ValueError("reflection is identity")
        a = nz[0]
        from math import gcd
        g = 0
        for x in a:
            g = gcd(g, abs(int(x)))
        return tuple(int(x) // g for x in a) if g > 1 else tuple(int(x) for x in a)

    # ----- flavour chart: one block per simple factor --------------------
    #
    # A PRODUCT flavour group `∏_a G_a` is the block generalisation of a single
    # simple factor: weight coordinates concatenate, so dominance, the
    # orbit-ordering key and the weight↔label maps all act factor by factor.
    # The recursion lives in `gf_quantum_torus_kalgebra` because
    # `GfQuantumTorusKAlg` carried an identical copy of the switch.  It is
    # shape-preserving: on a bare simple ring these return exactly what the
    # previous per-kind switches returned.

    def flavour_blocks(self) -> tuple:
        """`((kind, width), …)`, one entry per simple factor of `R`."""
        return _ring_blocks(self._R)

    def _is_dominant(self, wt) -> bool:
        return _ring_is_dominant(self._R, tuple(wt))

    def _dom_key(self, wt):
        return _ring_dom_key(self._R, tuple(wt))

    def _wt_to_label(self, wt):
        return _ring_wt_to_label(self._R, tuple(wt))

    def _label_to_hw(self, label) -> Vec:
        return _ring_label_to_hw(self._R, label)

    # ----- W-equivariant flavour weight ---------------------------------

    def _proj0(self, gamma) -> QVec:
        _, ker_c = decompose_in_basis(list(gamma), self._sec_basis, self._ker_basis)
        n = self._rank
        return tuple(Fraction(sum(ker_c[i] * self._ker_basis[i][k]
                                  for i in range(len(ker_c)))) for k in range(n))

    def _proj_kerB(self, gamma) -> QVec:
        n = self._rank
        acc = [Fraction(0)] * n
        for w, winv in zip(self._W, self._W_inv):
            wp = _matvec(w, self._proj0(_matvec(winv, gamma)))
            for k in range(n):
                acc[k] += wp[k]
        m = len(self._W)
        return tuple(a / m for a in acc)

    def _weight(self, gamma) -> QVec:
        return _solve_in_basis(self._mu_basis, self._proj_kerB(gamma), allow_fraction=True)

    def _weight_int(self, gamma) -> Vec:
        mu = self._weight(gamma)
        if any(x.denominator != 1 for x in mu):
            raise NotImplementedError(
                f"GfBPSKAlgebra: spinor sector (fractional weight {tuple(mu)}) "
                f"is out of scope")
        return tuple(int(x) for x in mu)

    def _phi(self, wt) -> Vec:
        n = self._rank
        return tuple(sum(int(wt[i]) * self._mu_basis[i][k] for i in range(len(wt)))
                     for k in range(n))

    def _ker_to_mu(self, ker_coords) -> Vec:
        """Express a flavour weight (in SNF ker-basis coords) in mu_basis
        coords (= the ring's to_abelian weight coords)."""
        n = self._rank
        flav = tuple(sum(int(ker_coords[i]) * self._ker_basis[i][k]
                         for i in range(len(ker_coords))) for k in range(n))
        return _solve_in_basis(self._mu_basis, flav)

    # ----- canonicalisation + lift --------------------------------------

    def _mu_action(self):
        """Each `w ∈ W` as a matrix on `mu_basis` (weight) coordinates.

        `_proj_kerB` is the `W`-average, hence `W`-equivariant, so
        `weight(w·γ) = M_w · weight(γ)`.  Measured `130/130` across
        `SU(2)`, `SU(3)`, `SU(2)×SU(2)`, `SU(2)×SU(3)` before being relied on.
        """
        cached = getattr(self, "_W_mu", None)
        if cached is not None:
            return cached
        r = len(self._mu_basis)
        out = []
        for w in self._W:
            cols = [_solve_in_basis(self._mu_basis, _matvec(w, v),
                                    allow_fraction=True)
                    for v in self._mu_basis]
            out.append(tuple(tuple(cols[j][i] for j in range(r)) for i in range(r)))
        self._W_mu = out
        return out

    def verify_mu_basis_blocks(self) -> bool:
        """`mu_basis` is ordered to match `coefficient_ring().factors`.

        For a PRODUCT flavour group nothing else pins that order, and getting it
        wrong is silent rather than loud: `TensorZPlusRing.to_abelian` emits
        CONCATENATED per-factor coordinates and every block helper slices by
        offset, so a permuted `mu_basis` would read factor `a`'s weights in
        factor `b`'s convention and simply return wrong labels.

        The decisive test is cheap, because `W = ∏_a W_a` acts factor-wise: each
        `w ∈ W` must be BLOCK-DIAGONAL on `mu_basis` coordinates with respect to
        the ring's factor widths.  A mis-ordered basis makes some `M_w` mix two
        blocks.  Vacuously true for a single simple factor.
        """
        widths = [w for _kind, w in _ring_blocks(self._R)]
        bounds, off = [], 0
        for w in widths:
            bounds.append((off, off + w))
            off += w
        for Mw in self._mu_action():
            for i, (lo_i, hi_i) in enumerate(bounds):
                for j, (lo_j, hi_j) in enumerate(bounds):
                    if i == j:
                        continue
                    for r in range(lo_i, hi_i):
                        for c in range(lo_j, hi_j):
                            if Mw[r][c] != 0:
                                return False
        return True

    def canonicalise(self, gamma: Vec) -> Label:
        """The dominant `W`-orbit representative of `gamma`.

        `_weight` is computed ONCE and transported through the orbit by the
        equivariance above, instead of once per group element.  That matters for
        a PRODUCT flavour group, where `|W| = ∏_a N_a!`: `_weight` itself averages
        over `W`, so the naive loop is `O(|W|²)` — measured 4.5 s per call at
        `|W| = 144` (`SU(4)×SU(3)`), and ~70 s at `SU(4)×SU(4)`.  Now `O(|W|)`.
        """
        gamma = self._check(gamma)
        wt0 = self._weight(gamma)
        best, best_key = None, None
        for w, Mw in zip(self._W, self._mu_action()):
            wt = tuple(sum(Mw[i][j] * wt0[j] for j in range(len(wt0)))
                       for i in range(len(wt0)))
            if not self._is_dominant(wt):
                continue
            key = self._dom_key(wt)
            if best is None or key > best_key:
                best, best_key = _matvec(w, gamma), key
        if best is None:
            raise ValueError(f"canonicalise: no dominant rep for {gamma}")
        return best

    def _lift_to_F(self, gamma: Label) -> dict[Vec, int]:
        """`L_gamma` as `{BPS F-label: multiplicity}` -- the Weyl character
        diagram anchored with highest weight at the dominant rep."""
        g = self.canonicalise(gamma)
        wt = self._weight_int(g)
        ab = self._R.to_abelian(self._R.basis_element(self._wt_to_label(wt)))
        out: dict[Vec, int] = {}
        for key, mult in ab.terms.items():
            kk = tuple(int(x) for x in key)
            shift = self._phi(tuple(kk[i] - wt[i] for i in range(len(wt))))
            pt = tuple(g[k] + shift[k] for k in range(self._rank))
            out[pt] = out.get(pt, 0) + mult
        return out

    # ----- the seven KAlgebra primitives --------------------------------

    def coefficient_ring(self) -> ZPlusRing:
        return self._R

    def identity(self) -> Label:
        return tuple([0] * self._rank)

    def rho(self, a: Label) -> Label:
        return self.canonicalise(self._bps.rho(self._check(a)))

    def rho_inverse(self, a: Label) -> Label:
        return self.canonicalise(self._bps.rho_inverse(self._check(a)))

    def multiply(self, a: Label, b: Label) -> Element:
        a, b = self._check(a), self._check(b)
        fa, fb = self._lift_to_F(a), self._lift_to_F(b)
        acc: dict[Vec, dict[int, int]] = {}
        for ga, ca in fa.items():
            for gb, cb in fb.items():
                cross = self._bps.multiply(ga, gb)
                for lab, lp in cross.terms.items():
                    labt = tuple(int(x) for x in lab)
                    slot = acc.setdefault(labt, {})
                    for e, c in lp._coeffs.items():
                        slot[e] = slot.get(e, 0) + ca * cb * c
        acc = {g: {e: c for e, c in d.items() if c} for g, d in acc.items()}
        acc = {g: d for g, d in acc.items() if d}
        return self._decompose_F_into_L(acc)

    def _decompose_F_into_L(self, terms) -> Element:
        remaining = {g: dict(d) for g, d in terms.items()}
        out: dict[Label, dict[int, int]] = {}
        while remaining:
            best, best_key = None, None
            for g in remaining:
                wt = self._weight(g)
                if any(x.denominator != 1 for x in wt) or not self._is_dominant(wt):
                    continue
                key = self._dom_key(wt)
                if best is None or key > best_key:
                    best, best_key = g, key
            if best is None:
                raise ValueError(f"_decompose: no in-scope dominant weight in "
                                 f"{list(remaining)} (spinor sector?)")
            label = self.canonicalise(best)
            chain = self._lift_to_F(label)
            if chain.get(best, 0) != 1:
                raise ValueError(f"_decompose: highest-weight mult != 1 at {best}")
            coef = dict(remaining[best])
            for g, m in chain.items():
                if g not in remaining:
                    raise ValueError(f"_decompose: W-invariance failure at {g}")
                slot = remaining[g]
                for e, c in coef.items():
                    nv = slot.get(e, 0) - m * c
                    if nv == 0:
                        slot.pop(e, None)
                    else:
                        slot[e] = nv
                if not slot:
                    del remaining[g]
            accd = out.setdefault(label, {})
            for e, c in coef.items():
                accd[e] = accd.get(e, 0) + c
            out[label] = {e: c for e, c in accd.items() if c}
            if not out[label]:
                del out[label]
        return Element({lab: LaurentPoly(d) for lab, d in out.items()})

    def trace(self, a: Label, K: int = 20, **kwargs) -> RPowerSeries:
        a = self._check(a)
        tr = _ring_torus_rank(self._R)
        from collections import defaultdict
        mu_coeffs: dict[int, dict[Vec, int]] = defaultdict(lambda: defaultdict(int))
        for gamma, mult in self._lift_to_F(a).items():
            bt = self._bps.trace(gamma, K=K, **kwargs)
            for q_exp, r_elt in bt.coeffs.items():
                for mu_basis, c in r_elt.terms.items():
                    ker_c = tuple(int(mu_basis[i]) if i < len(mu_basis) else 0
                                  for i in range(tr))
                    mu = self._ker_to_mu(ker_c)
                    mu_coeffs[q_exp][tuple(mu)] += mult * c
        out: dict[int, RElement] = {}
        ab_ring = AbelianZPlusRing(rank=tr)
        for q_exp, at_q in mu_coeffs.items():
            u1 = RElement(ab_ring, {k: c for k, c in at_q.items() if c != 0})
            if u1.is_zero():
                continue
            chi = self._R.from_abelian(u1, allow_virtual=True)
            if not chi.is_zero():
                out[q_exp] = chi
        return RPowerSeries(self._R, out, K)

    def r_label_decompose(self, label: Label):
        """Flavour-lift coordinate: section = `γ − φ(wt)` (the central
        remainder), single irrep key = `_wt_to_label(wt)` for the integral
        weight `wt`.  Invertible — `r_label_compose` reconstructs
        `canonicalise(section + φ(wt))`.  Raises on a non-central (spinor)
        section, as the section method does."""
        a = self.canonicalise(label)
        wt = self._weight_int(a)
        section = tuple(a[k] - self._phi(wt)[k] for k in range(self._rank))
        if any(x != 0 for x in self._weight(section)):
            raise NotImplementedError(
                "GfBPSKAlgebra.r_label_decompose: non-central section "
                "(spinor sector) not supported")
        return section, self._wt_to_label(wt)

    def r_label_compose(self, section: Label, r_basis_label) -> Label:
        wt = self._label_to_hw(r_basis_label)
        phi_wt = self._phi(wt)
        return self.canonicalise(
            tuple(section[k] + phi_wt[k] for k in range(self._rank)))


    # ----- convenience ---------------------------------------------------

    def character_label(self, ring_label) -> Label:
        return self.canonicalise(self._phi(self._label_to_hw(ring_label)))

    def ring_label_of(self, label: Label):
        return self._wt_to_label(self._weight_int(self.canonicalise(label)))

    def L(self, label: Label) -> Element:
        return Element.basis(self.canonicalise(label))

    def to_u1(self, elt: Element):
        """Lift an L-basis `Element` to the underlying `BPSKAlgebra` F-basis."""
        out: dict[Vec, LaurentPoly] = {}
        for label, lp in elt.terms.items():
            for g, mult in self._lift_to_F(self.canonicalise(label)).items():
                out[g] = (out[g] + lp * mult) if g in out else lp * mult
        out = {g: c for g, c in out.items() if not c.is_zero()}
        return self._bps, Element(out)

    def from_u1(self, bps_elt: Element) -> Element:
        terms: dict[Vec, dict[int, int]] = {}
        for lab, lp in bps_elt.terms.items():
            d = {e: c for e, c in lp._coeffs.items() if c != 0}
            if d:
                terms[tuple(int(x) for x in lab)] = d
        return self._decompose_F_into_L(terms)

    @property
    def bps(self) -> BPSKAlgebra:
        return self._bps

    @property
    def rank(self) -> int:
        return self._rank

    @property
    def gauge_rank(self) -> int:
        return self._gauge_rank

    @property
    def spec(self):
        return [tuple(int(x) for x in g) for g in self._bps.spec]

    def _check(self, a) -> Vec:
        a = tuple(int(x) for x in a)
        if len(a) != self._rank:
            raise ValueError(f"label length {len(a)} != rank {self._rank}")
        return a

    def __repr__(self) -> str:
        return (f"GfBPSKAlgebra(rank={self._rank}, |spec|={len(self._bps.spec)}, "
                f"gauge_rank={self._gauge_rank}, ring={self._R!r})")
