"""The acceptance check for a spec, and the crystalline content.

A *spec* is a finite ordered list of charges `[γ_1, …, γ_L]` with
`S = ∏_a E_𝖖(X_{γ_a})` — a finite exact certificate for the spectrum generator.
The enumerated dictionary accepts a candidate spec by an **axiom check**, not by
its origin:

1. **the BPS quiver constraint** — the coefficient of `S_spec := ∏ E_𝖖(X_{γ_a})`
   at every cone charge has empty non-positive `𝖖`-part, and `𝖖¹`-coefficient
   `−1` at the node charges and `0` elsewhere (swept over the WHOLE truncated
   cone, not the support — a spec with a node dropped is invisible on its
   support; a probe in the source repository);
2. **agreement with the crystalline `S`** — the element `bps_factor_spectrum`
   builds from that leading data — on the cone to the stated depth.

Membership in `𝓔` (the group generated by the quantum-dilogarithm multiplets)
is automatic for a product of `E_𝖖` factors; (1) is where a wrong spec fails
(negative controls: a node missing, a spurious charge, the reversed order —
pinned in `tests/test_spec_acceptance.py`), and (2) is the `S_cluster == S`
statement measured 2381/2381 on the previous dictionary
(`pronilpotent_group_conjecture.md` §6c).  A depth is a truncation, never a
certificate: the verdict carries its depth, as `factor_order_search.Result`
carries `confirmed_to`.

Both `S` are exact `{charge: HabiroElement}` (`recursive_spectrum.Theory.
S_from_spec` for the product, the factor engine for the crystalline one);
nothing is `𝖖`-truncated before the final read.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Sequence

from habiro import HabiroElement
from bps_factor_spectrum import build_spectrum_generator_from_factors, cone_simplex
from recursive_spectrum import Theory
from bps_quiver_tools import BPSQuiver
from quiver_enumeration import (Vec, source_sink_order, standard_nodes,
                                strongly_connected_components)

H0 = HabiroElement.zero()

Spectrum = dict[Vec, HabiroElement]


def spec_product(B: Sequence[Sequence[int]], spec: Sequence[Sequence[int]],
                 depth: int, *, keep_nahm_cache: bool = False) -> Spectrum:
    """`∏_a E_𝖖(X_{γ_a})` on the cone to `depth`, exact (Nahm sums).

    The Nahm-sum engine memoises per `(charge, spec)` in a module-level cache
    (`nahm_local._sket_habiro_cache`), which is never reused across different
    specs — so it is cleared here after every product unless
    `keep_nahm_cache=True`.  Left alone it grows ~12 MB/s over a dictionary
    build and OOM-killed the first `E = 7` run."""
    from nahm_local import clear_nahm_cache
    n = len(B)
    T = Theory("accept", [list(r) for r in B], standard_nodes(n), CONE=depth)
    try:
        return T.S_from_spec([tuple(int(x) for x in g) for g in spec])
    finally:
        if not keep_nahm_cache:
            clear_nahm_cache()


def crystalline_spectrum(B: Sequence[Sequence[int]], depth: int, *,
                         order: str = "lex", with_multiplicities: bool = False):
    """The crystalline `S` from the leading data (`order` only affects the
    factor content `Ω` and the cost, never `S`; `"lex"` is deterministic)."""
    n = len(B)
    return build_spectrum_generator_from_factors(
        [list(r) for r in B], standard_nodes(n), depth, order=order,
        with_multiplicities=with_multiplicities)


def leading_data_violations(S: Spectrum, n: int, depth: int
                            ) -> list[tuple[Vec, int, int]]:
    """Where `S` fails the BPS quiver constraint on the cone to `depth`:
    `(charge, exponent, coefficient)` for a nonzero coefficient at a
    `𝖖`-exponent `≤ 0`, or `(charge, 1, got − wanted)` for a wrong
    `𝖖¹`-coefficient.  Empty iff the constraint holds."""
    nodes = set(standard_nodes(n))
    bad: list[tuple[Vec, int, int]] = []
    for gamma in cone_simplex(n, depth):
        c = S.get(gamma, H0)
        low = c.expand(0)
        if not low.is_zero():
            # report the lowest offending exponent
            j = c.k_min()
            while j is not None and j <= 0 and c.coefficient(j) == 0:
                j += 1
            bad.append((gamma, j if j is not None else 0, c.coefficient(j) if j is not None else 0))
        want = -1 if gamma in nodes else 0
        got = c.coefficient(1)
        if got != want:
            bad.append((gamma, 1, got - want))
    return bad


def spectra_agree(S1: Spectrum, S2: Spectrum, n: int, depth: int) -> list[Vec]:
    """Charges on the cone to `depth` where the two exact spectra differ."""
    return [g for g in cone_simplex(n, depth) if S1.get(g, H0) != S2.get(g, H0)]


def strip_spec(B: Sequence[Sequence[int]]) -> list[Vec] | None:
    """For an acyclic quiver, the source/sink order spec — the node charges
    with sources first, `S = ∏ E_𝖖(X_{γ_a})` in that order (the strip
    default of the factor engine; `kalgebra.md` "S-finding").  `None` if `B`
    has a directed cycle."""
    order = source_sink_order(B)
    if order is None:
        return None
    nodes = standard_nodes(len(B))
    return [nodes[i] for i in order]


def spec_from_components(B: Sequence[Sequence[int]],
                         component_spec=None) -> list[Vec] | None:
    """A spec of `B` composed from the specs of its strongly connected
    components, concatenated in source-first order
    (`quiver_enumeration.strongly_connected_components`).

    A single-node component contributes its node charge.  A larger component
    is handed to `component_spec(sub)`, `sub` being its exchange matrix with
    the component's nodes in ascending order; it returns a spec in `sub`'s
    standard basis, or None, and the answer is embedded in `B`'s nodes.
    Returns None as soon as one component has no spec.  With
    `component_spec=None` no component of two or more nodes has one, so on an
    acyclic quiver this is `strip_spec` exactly, in the same order, and on a
    quiver with a directed cycle it is None.

    Why the concatenation is a spec (`strongly_connected_redesign.md` §1):
    green component specs compose to a green spec of `B`, a theorem (§1.1 —
    the source-peel lemma with the node replaced by a set of nodes); component
    specs that satisfy the BPS quiver constraint to depth `D` compose to a
    product satisfying it on `B`'s cone to the same depth (§1.2).  Only the
    DIRECTION of the arrows between components enters, never their
    multiplicities.  Nothing is verified here — a composed spec is a
    producer's output and is accepted like any other (`is_green_sequence`,
    `accept_spec`).
    """
    n = len(B)
    out: list[Vec] = []
    for comp in strongly_connected_components(B):
        if len(comp) == 1:
            v = [0] * n
            v[comp[0]] = 1
            out.append(tuple(v))
            continue
        if component_spec is None:
            return None
        sub = [[int(B[i][j]) for j in comp] for i in comp]
        cs = component_spec(sub)
        if cs is None:
            return None
        for g in cs:
            if len(g) != len(comp):
                raise ValueError(
                    f"component_spec returned the charge {tuple(g)} for a "
                    f"{len(comp)}-node component")
            v = [0] * n
            for a, node in enumerate(comp):
                v[node] = int(g[a])
            out.append(tuple(v))
    return out


def is_green_sequence(B: Sequence[Sequence[int]], spec: Sequence[Sequence[int]]) -> bool:
    """The cluster-side replay: does the spec mutate the standard-basis quiver
    to its negative (a genuine negating sequence)?  Recorded beside the axiom
    check, not used as the acceptance."""
    n = len(B)
    Q = BPSQuiver(charges=standard_nodes(n), frozen=[False] * n,
                  exchange_matrix=[list(r) for r in B])
    ok, _ = Q.verify_spectrum_generator([tuple(g) for g in spec])
    return bool(ok)


@dataclass
class Acceptance:
    ok: bool
    depth: int
    leading_ok: bool
    matches_crystalline: bool
    violations: list = field(default_factory=list)
    mismatches: list = field(default_factory=list)

    def as_dict(self) -> dict:
        return {
            "ok": self.ok, "depth": self.depth, "leading_ok": self.leading_ok,
            "matches_crystalline": self.matches_crystalline,
            "n_violations": len(self.violations), "n_mismatches": len(self.mismatches),
        }


def accept_spec(B: Sequence[Sequence[int]], spec: Sequence[Sequence[int]],
                depth: int, *, crystalline: Spectrum | None = None) -> Acceptance:
    """The acceptance check of the module doc, at `depth`.  Pass a cached
    `crystalline` spectrum (to at least `depth`) to avoid rebuilding it."""
    n = len(B)
    for g in spec:
        if len(g) != n or any(x < 0 for x in g) or not any(g):
            return Acceptance(False, depth, False, False,
                              violations=[("bad charge", tuple(g))])
    Sp = spec_product(B, spec, depth)
    viol = leading_data_violations(Sp, n, depth)
    if crystalline is None:
        crystalline = crystalline_spectrum(B, depth)
    mism = spectra_agree(Sp, crystalline, n, depth)
    return Acceptance(ok=(not viol and not mism), depth=depth,
                      leading_ok=not viol, matches_crystalline=not mism,
                      violations=viol, mismatches=mism)


def content_record(omega: dict[Vec, dict[int, int]]) -> dict[str, dict[str, int]]:
    """JSON-ready form of a factor content `{charge: {exponent: coeff}}`."""
    return {",".join(map(str, g)): {str(k): int(v) for k, v in sorted(om.items())}
            for g, om in sorted(omega.items(), key=lambda kv: (sum(kv[0]), kv[0]))}


# ---------------------------------------------------------------------------
# A green spec and its node-index sequence — the two directions of the
# replay (shard format 2 stores the sequence; the loader rebuilds the
# charges).  `sequence_from_spec` is `is_green_sequence`'s replay made to
# return the indices; `spec_from_sequence` is `BPSQuiver.build_spectrum_generator`.
# ---------------------------------------------------------------------------


def sequence_from_spec(B: Sequence[Sequence[int]], spec: Sequence[Sequence[int]]) -> list[int] | None:
    """The node indices mutated along the green replay of `spec` on the
    standard-basis quiver `B`, or None if some factor is not a current node
    charge (then the spec is not a negating sequence in this order).  Does
    NOT check the terminal condition — pair with `is_green_sequence`."""
    n = len(B)
    Q = BPSQuiver(charges=standard_nodes(n), frozen=[False] * n,
                  exchange_matrix=[list(r) for r in B])
    seq = []
    for g in spec:
        g = tuple(int(x) for x in g)
        idx = next((i for i, c in enumerate(Q.charges) if not Q.frozen[i] and tuple(c) == g), None)
        if idx is None:
            return None
        seq.append(idx)
        Q = Q.mutate(idx)
    return seq


def spec_from_sequence(B: Sequence[Sequence[int]], seq: Sequence[int]) -> list[Vec]:
    """The charges of the `E_q` factors along a node-index sequence."""
    n = len(B)
    Q = BPSQuiver(charges=standard_nodes(n), frozen=[False] * n,
                  exchange_matrix=[list(r) for r in B])
    return [tuple(int(x) for x in g) for g in Q.build_spectrum_generator(list(seq))]
