"""`SU3BPSKAlgebra` -- the SU(3)-flavoured BPS realisation of A_q[T].

**Retirement note (2026-06-13).**  The previous standalone implementation
built its canonical basis from the cyclic `Z_3` subgroup generated by an
order-3 `sigma` -- but `SU(3)` flavour is the invariant theory of the
*full* `S_3` Weyl group (order 6), and a `Z_3`-invariant element is not
`S_3`-invariant.  That class therefore presented the wrong algebra (e.g.
`3 (x) 3 = 6 + 2.3bar` instead of `6 + 3bar`, and `3 (x) 3bar = 8 + 3.1`
instead of `8 + 1`); its tests had the wrong multiplicities baked in, and
`su3_ad_kalg`'s iso certificate carried a `_TT2_FOLD_OVERCOUNT` correction
to reconcile against the over-count.

`SU3BPSKAlgebra` is now a thin specialisation of the general
`GfBPSKAlgebra` (the Weyl-invariant subalgebra of a `BPSKAlgebra` for an
`S_n`-symmetric quiver), with the full `S_3` supplied as the two node-pair
**transpositions** (which generate `S_3`; the old order-3 `sigma` is their
product and does *not* generate the group).  It now returns the correct
SU(3) fusion and is the direct BPS realisation of `SU3ADKAlg` (the
`[A_1, D_4]` AD theory).

See `gf_bps_kalgebra.GfBPSKAlgebra` for the construction; the worked quiver
is `_user_quiver()` below.
"""

from __future__ import annotations

import sys
import os

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from gf_bps_kalgebra import GfBPSKAlgebra
from zplus_ring import SU3ZPlusRing, RElement


Vec = tuple[int, ...]


def _u1_rank2_to_su3(u1_relt: RElement, target_ring: SU3ZPlusRing) -> RElement:
    """Convert a Weyl(`S_3`)-symmetric `(mu_1, mu_2)`-Laurent (over
    `AbelianZPlusRing(rank=2)`, fundamental-orbit basis) to the SU(3)
    `chi_(p,q)` basis.  Thin wrapper over `SU3ZPlusRing.from_abelian`
    (`allow_virtual=True`: Schur indices are virtual characters per
    q-order).  Retained for callers (`su3_ad_kalg.trace_word`)."""
    return target_ring.from_abelian(u1_relt, allow_virtual=True)


class SU3BPSKAlgebra(GfBPSKAlgebra):
    """SU(3)-flavoured BPS realisation: the full-`S_3`-invariant subalgebra
    of a `BPSKAlgebra` on an `S_3`-symmetric quiver.

    Parameters
    ----------
    pairing, node_charges, **bps_kwargs : the underlying `BPSKAlgebra`.
    reflections : the two node-pair transpositions (Poisson involutions
        generating the flavour Weyl group `S_3`).
    mu_basis : a `Z`-basis of `ker B` aligned with `SU3ZPlusRing`'s
        fundamental-orbit weight coordinates (the two flavour directions
        carrying the fundamental weights).
    """

    def __init__(self, pairing, node_charges, reflections, mu_basis, **bps_kwargs):
        super().__init__(pairing, node_charges, reflections, SU3ZPlusRing(),
                         mu_basis, **bps_kwargs)

    @property
    def _ker_to_fundorbit(self):
        """The `2x2` matrix taking SNF ker-basis coords to fundamental-orbit
        (`mu_basis`) coords -- the column-stacked image of `_ker_to_mu` on
        the ker-basis units.  Compat shim for `su3_ad_kalg.trace_word`."""
        r = len(self._mu_basis)
        cols = [self._ker_to_mu(tuple(1 if k == i else 0 for k in range(r)))
                for i in range(r)]
        return [[cols[j][i] for j in range(r)] for i in range(r)]


def _user_quiver() -> SU3BPSKAlgebra:
    """The `[A_1, D_4]` BPS quiver: one central gauge node + three flavour
    nodes at the SU(3) fundamental weights `(1,0)`, `(0,1)`, `(-1,-1)`, with
    the full `S_3` Weyl symmetry permuting them.  The direct BPS realisation
    of `SU3ADKAlg`."""
    return SU3BPSKAlgebra(
        pairing=[[0, 1, 0, 0],
                 [-1, 0, 0, 0],
                 [0, 0, 0, 0],
                 [0, 0, 0, 0]],
        node_charges=[(1, 0, 0, 0),
                      (0, 1, 1, 0),
                      (0, 1, 0, 1),
                      (0, 1, -1, -1)],
        reflections=[
            # tau_a: swap flavour weights (1,0) <-> (0,1)  (fix (-1,-1))
            [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]],
            # tau_b: swap (0,1) <-> (-1,-1)  (fix (1,0))
            [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, -1], [0, 0, 0, -1]],
        ],
        mu_basis=[(0, 0, 1, 0), (0, 0, 0, 1)],
    )


if __name__ == "__main__":
    A = _user_quiver()
    print(A, "|W| =", len(A._W))
    chi = A.character_label
    print("3 x 3   =", sorted(A.ring_label_of(l)
                              for l in A.multiply(chi((1, 0)), chi((1, 0))).terms))
    print("3 x 3bar=", sorted(A.ring_label_of(l)
                              for l in A.multiply(chi((1, 0)), chi((0, 1))).terms))
