"""
u1a1aodd_general.py
===================

General U1A1AoddKAlg(k) — u(1)-gauged [A_1, A_{2k+1}] AD theory for any k ≥ 1.

VALIDATED for k = 1, 2, 3, 4.  Bootstrap output:
  k=1: H=6,  primitive periods {L_1: 6,  L_2: 3},                              9 chord-gens, 28 cones
  k=2: H=8,  primitive periods {L_1: 8,  L_2: 8,  L_3: 4},                    20 chord-gens, 264 cones
  k=3: H=10, primitive periods {L_1: 10, L_2: 10, L_3: 10, L_4: 5},           35 chord-gens, 2860 cones
  k=4: H=12, primitive periods {L_1: 12, L_2: 12, L_3: 12, L_4: 12, L_5: 6},  54 chord-gens, 33592 cones

UNIVERSAL PATTERN: k+1 primitive chord families.  LAST family has period
k+2 (mod E with -1E cocycle).  Other families have period 2k+4 = H.

ARCHITECTURE:
  - k-universal: FiniteConeData framework, derived_multiply, trace_layer1
  - k-specific data: chord_charges + MULT_TABLE generated by bootstrap

BOOTSTRAP SCOPE — k ∈ {1, 2, 3, 4} ONLY (hand-discovered seeds):
  1. Build BPSKAlgebra for gauged-A_{2k+1} quiver
  2. Use the **hand-discovered** canonical seeds in `_canonical_seeds`:
       L_1: alternating (0,1,0,1,...,0,1)
       L_2: single 1 at start (1,0,...,0)
       L_3: zeros at odd, -1 at even (except 0), +1 at F (k ≥ 2)
       L_4: e_0 + e_{n-2}                  (k ≥ 3)
       L_5: L_3 + e_{n-3}                  (k ≥ 4)
  3. Generate MULT_TABLE via `_decompose` (greedy q-commuting search,
     `max_factors=4`).  At k ≤ 4 every Plücker daughter decomposes.

For k ≥ 5 the bootstrap WILL fail at `_bootstrap_chord_charges` /
`_decompose`: new primitive seed patterns must be discovered by hand
(or by an automated discovery loop — NOT IMPLEMENTED).  As k grows,
the auxiliary BPSKAlgebra becomes too slow to enumerate; an
RGKAlgebra-presented path is the planned route to higher k.

PATTERN OBSERVED (k=1, 2, 3, 4): k+1 primitive chord families.

USAGE:
  A = U1A1AoddKAlg(k=2)   # = U1OctaKAlg
  A = U1A1AoddKAlg(k=3)   # = U1DecagonKAlg
  A.multiply(label_a, label_b)
  A.trace_layer1(label)
"""
from __future__ import annotations
import sys, os
_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from itertools import product as iproduct
from kalgebra import KAlgebra, Element
from laurent_poly import LaurentPoly
from zplus_ring import TrivialZPlusRing
from cone_data import FiniteConeData, Cone
from cone_kalgebra import ConeKAlgebra
from bps_kalgebra import BPSKAlgebra


# ============================================================================
# k-specific seed construction (canonical patterns)
# ============================================================================

def _build_bps(k: int) -> BPSKAlgebra:
    """gauged-A_{2k+1} quiver: 2k+1 dynamical + 1 flavour = 2k+2 nodes."""
    n = 2 * k + 2
    B = [[0] * n for _ in range(n)]
    for i in range(n - 1):
        B[i][i+1] = 1; B[i+1][i] = -1
    node_charges = [tuple(1 if k_==i else 0 for k_ in range(n)) for i in range(2*k+1)]
    return BPSKAlgebra(pairing=B, node_charges=node_charges, verify="off")


def _canonical_seeds(k: int) -> list[tuple]:
    """The known canonical seeds for k = 1, 2, 3.  Higher k needs iteration."""
    n = 2 * k + 2  # BPS lattice dim
    seeds = []
    # L_1: alternating (0,1,0,1,...,0,1) — length n
    L_1_seed = tuple(0 if i % 2 == 0 else 1 for i in range(n))
    seeds.append(L_1_seed)
    # L_2: single 1 at start
    L_2_seed = tuple(1 if i == 0 else 0 for i in range(n))
    seeds.append(L_2_seed)
    if k >= 2:
        # L_3: zeros at odd positions, -1 at even positions (except 0),
        # +1 at F (last coord, position n-1).
        # F-direction (position n-1) ALWAYS gets +1 regardless of parity.
        def _l3_entry(i):
            if i == n - 1: return 1   # F direction always
            if i % 2 == 1: return 0
            if i == 0:     return 0
            return -1                  # even, positive, not n-1
        L_3_seed = tuple(_l3_entry(i) for i in range(n))
        seeds.append(L_3_seed)
    # L_4 (k ≥ 3): e_0 + e_{n-2}.  Pattern verified at k=3 (period 5,
    # the "last family" with -1E cocycle for k=3) and k=4 (period 12, the
    # "intermediate non-magnetic-pair family" for k=4).
    if k >= 3:
        L_4_seed = tuple(1 if i in (0, n-2) else 0 for i in range(n))
        seeds.append(L_4_seed)
    # L_5 (k ≥ 4): L_3 + e_{n-3}.  Discovered at k=4: the "last family"
    # with period k+2 and -1E cocycle.
    if k >= 4:
        L_3_seed_again = seeds[2]  # the L_3 we just built
        L_5_seed = tuple(
            L_3_seed_again[i] + (1 if i == n - 3 else 0)
            for i in range(n)
        )
        seeds.append(L_5_seed)
    return seeds


def _ρ_orbit_length(bps: BPSKAlgebra, seed: tuple, E_charge: tuple,
                    max_iters: int = 20) -> int:
    """Determine ρ-orbit length mod E for a seed."""
    n = len(seed)
    cur = seed; seen = [seed]
    for step in range(max_iters):
        cur = tuple(bps.rho(cur))
        for j, prev in enumerate(seen):
            d = tuple(cur[k_] - prev[k_] for k_ in range(n))
            for ke in range(-5, 6):
                if d == tuple(ke * E_charge[k_] for k_ in range(n)):
                    return step + 1 - j  # period
        seen.append(cur)
    raise RuntimeError(f"ρ-orbit didn't close in {max_iters} steps")


def _bootstrap_chord_charges(k: int) -> tuple[dict, tuple, BPSKAlgebra]:
    """Compute primitive chord charges for U1A1AoddKAlg(k).
    Returns (chord_charges dict {(a, i): charge_tuple}, E_charge, bps).

    SCOPE: k ∈ {1, 2, 3, 4}.  Higher k raises NotImplementedError —
    new primitive seeds must be hand-discovered (see module docstring)."""
    if k < 1:
        raise ValueError(f"k must be >= 1, got {k}")
    if k > 4:
        raise NotImplementedError(
            f"U1A1AoddKAlg bootstrap not implemented for k={k}: "
            f"_canonical_seeds only knows k <= 4 (seeds hand-discovered "
            f"from BPS exploration).  Higher k needs new seeds, ideally "
            f"derived from an RGKAlgebra presentation since the auxiliary "
            f"BPSKAlgebra becomes too slow at k >= 5."
        )
    bps = _build_bps(k)
    n = 2 * k + 2
    # E: alternating (1,0,1,0,...,1,0)
    E_charge = tuple(1 if i % 2 == 0 else 0 for i in range(n))

    seeds = _canonical_seeds(k)
    chord_charges = {}
    family_periods = {}
    for a, seed in enumerate(seeds, start=1):
        period = _ρ_orbit_length(bps, seed, E_charge)
        family_periods[a] = period
        # Build the ρ-orbit
        cur = seed
        chord_charges[(a, 0)] = seed
        for i in range(1, period):
            cur = tuple(bps.rho(cur))
            chord_charges[(a, i)] = cur
    return chord_charges, E_charge, bps, family_periods


# ============================================================================
# MULT_TABLE generation (per k)
# ============================================================================

def _qcommute(bps, c1, c2):
    return len(bps.multiply(c1, c2).terms) == 1


def _all_qcommute(bps, gens, facs):
    for i in range(len(facs)):
        for j in range(i+1, len(facs)):
            if facs[i] != facs[j] and not _qcommute(
                bps, gens[facs[i]], gens[facs[j]]):
                return False
    return True


def _is_E_multiple(diff, E_charge):
    n = len(diff)
    # diff = c·E means diff[i] = c if E[i] = 1 else 0
    nonzero_E_positions = [i for i in range(n) if E_charge[i] != 0]
    zero_E_positions = [i for i in range(n) if E_charge[i] == 0]
    for i in zero_E_positions:
        if diff[i] != 0: return None
    if not nonzero_E_positions: return None
    c = diff[nonzero_E_positions[0]]
    for i in nonzero_E_positions:
        if diff[i] != c: return None
    return c


def _decompose(gamma, chord_charges, primitives, E_charge, bps, max_factors=4):
    """Find γ = sum(L_a(i) charges) + e_E·E with factors all q-commuting.

    Greedy: tries n_facs = 0, 1, ..., max_factors and accepts the first
    q-commuting factorisation that reproduces γ mod E.  max_factors=4
    suffices for every chord-pair Plücker daughter observed at k ≤ 4;
    if you ever see this return None on a chord-pair input, the right
    fix is almost always a missing primitive seed (not a higher rank)."""
    n = len(gamma)
    for n_facs in range(0, max_factors + 1):
        for facs in iproduct(primitives, repeat=n_facs):
            if list(facs) != sorted(facs): continue
            if not _all_qcommute(bps, chord_charges, facs): continue
            fc = [0] * n
            for f in facs:
                fci = chord_charges[f]
                for k_ in range(n): fc[k_] += fci[k_]
            diff = tuple(gamma[k_] - fc[k_] for k_ in range(n))
            e_E = _is_E_multiple(diff, E_charge)
            if e_E is not None:
                return (e_E, list(facs))
    return None


def generate_mult_table(k: int):
    """Compute the chord-pair multiply table for U1A1AoddKAlg(k).
    Returns (chord_charges, E_charge, MULT_TABLE)."""
    chord_charges, E_charge, bps, family_periods = _bootstrap_chord_charges(k)
    # Wrap-around E-drift per family + the ρ(E)=E⁻¹ check — the only data the
    # closed-form ρ needs beyond the orbit shift `(a,i)→(a,i+1 mod P_a)`:
    # ρ(L_{a, P_a-1}) = E^{eps_wrap[a]}·L_{a, 0}.  Derived once from BPS (ground
    # truth).  (Previously `rho` did `(i+1)%P` with `e_E` UNCHANGED — dropping
    # both this wrap pickup AND the `E→E⁻¹` inversion, so ρ disagreed with BPS
    # on the wrap letters and on every `e_E≠0` label, failing the algebra-
    # automorphism axiom; see the audit note on the long-chord ρ/trace bug.)
    eps_wrap = _wrap_drift_from_bps(chord_charges, E_charge, bps, family_periods, k)
    primitives = sorted(chord_charges.keys())
    table = {}
    for g1 in primitives:
        c1 = chord_charges[g1]
        for g2 in primitives:
            c2 = chord_charges[g2]
            prod = bps.multiply(c1, c2)
            terms = []
            for chg, qcoef in prod.terms.items():
                coef_terms = sorted(qcoef._coeffs.items())
                dec = _decompose(chg, chord_charges, primitives, E_charge, bps, 4)
                if dec is None:
                    raise RuntimeError(
                        f"k={k}: failed to decompose {chg} from L_{g1}·L_{g2}. "
                        f"This means a primitive chord family is missing from "
                        f"`_canonical_seeds(k)` — extend it with the new seed "
                        f"by hand (BPS exploration), or move to an RGKAlgebra "
                        f"presentation for higher k."
                    )
                e_E, factors = dec
                for q_pow, q_coef in coef_terms:
                    terms.append((int(q_pow), int(e_E), tuple(factors), int(q_coef)))
            table[(g1, g2)] = terms
    return chord_charges, E_charge, MultTable(
        table, family_periods, E_charge, eps_wrap)


def _wrap_drift_from_bps(chord_charges, E_charge, bps, family_periods, k):
    """Per-family wrap E-drift `eps_wrap[a]` with `ρ(L_{a,P-1}) =
    E^{eps_wrap[a]}·L_{a,0}`, plus the `ρ(E)=E⁻¹` check — extracted from BPS
    (ground truth), exactly as the good-branch `u1a1aodd_kalg` does it via its
    oracle.  Raises if a wrap drift is not a clean E-power or `ρ(E)≠E⁻¹`."""
    n = len(E_charge)
    Esup = [j for j in range(n) if E_charge[j] != 0]
    if not Esup:
        raise AssertionError(f"k={k}: E_charge has empty support")
    eps = {}
    for a, P in family_periods.items():
        r = tuple(bps.rho(chord_charges[(a, P - 1)]))
        c0 = chord_charges[(a, 0)]
        diff = tuple(r[j] - c0[j] for j in range(n))
        m = diff[Esup[0]] // E_charge[Esup[0]]
        if any(diff[j] != m * E_charge[j] for j in range(n)):
            raise AssertionError(
                f"k={k}: wrap drift for family {a} is not a pure E-power: {diff}")
        eps[a] = m
    rE = tuple(bps.rho(tuple(E_charge)))
    if rE != tuple(-x for x in E_charge):
        raise AssertionError(f"k={k}: ρ(E) is not E⁻¹: {rE}")
    return eps


class MultTable:
    """Container for k-specific multiply table + metadata."""
    def __init__(self, table, family_periods, E_charge, eps_wrap=None):
        self.table = table
        self.family_periods = family_periods
        self.E_charge = E_charge
        # Per-family wrap-around E-drift: ρ(L_{a, P_a-1}) = E^{eps_wrap[a]}·L_{a, 0}
        # (with ρ(E)=E⁻¹).  The data the closed-form ρ needs beyond the orbit
        # shift; derived from BPS in `generate_mult_table`.
        self.eps_wrap = eps_wrap or {}

    def get(self, key, default=None):
        return self.table.get(key, default)

    def __getitem__(self, key):
        return self.table[key]

    def __contains__(self, key):
        return key in self.table


# ============================================================================
# General ConeData
# ============================================================================

class U1A1AoddConeData(FiniteConeData):
    """Generic FiniteConeData for U1A1AoddKAlg(k).
    E± labels use family index (max_family + 1) to avoid collision with L families."""

    def __init__(self, k: int, chord_charges, E_charge, mult_table, family_periods):
        self.k = k
        self.chord_charges = chord_charges
        self.E_charge = E_charge
        self.mult_table = mult_table
        self.family_periods = family_periods
        # E± family index = max chord family + 1
        max_fam = max(family_periods.keys())
        self.E_GEN = (max_fam + 1, 0)
        self.E_INV = (max_fam + 1, 1)
        # Extract MU_LETTER_QPOWER per chord generator (cocycle with E)
        self.MU_LETTER_QPOWER = {}
        from bps_kalgebra import BPSKAlgebra
        # We don't have BPS at runtime — use mult_table for L·L cocycle,
        # but for L·E we need the cocycle.  Compute it from the chord_charges
        # via mathematical formula: L_l · E = q^{2c} · E · L_l where c is the
        # cocycle.  Empirically for our chord families, parity-based:
        # for magnetic families, cocycle = -1 if i even else +1; non-magnetic 0.
        # We need to determine which families are magnetic.
        # Heuristic: a family is magnetic iff its ρ-orbit closes mod E with non-zero cocycle.
        # For simplicity here, we extract empirically via direct BPS evaluation at init.
        bps = _build_bps(k)
        for (a, i), chg in chord_charges.items():
            fwd = bps.multiply(chg, E_charge)
            bwd = bps.multiply(E_charge, chg)
            if len(fwd.terms) == 1 and len(bwd.terms) == 1:
                f_lp = list(fwd.terms.values())[0]
                b_lp = list(bwd.terms.values())[0]
                fq = list(f_lp._coeffs.keys())[0] if f_lp._coeffs else 0
                bq = list(b_lp._coeffs.keys())[0] if b_lp._coeffs else 0
                diff = fq - bq
                if diff % 2 != 0:
                    raise ValueError(
                        f"MU_LETTER_QPOWER: non-integer cocycle for L_{(a, i)} "
                        f"with E (literal q-diff = {diff}, expected even)"
                    )
                self.MU_LETTER_QPOWER[(a, i)] = diff // 2
            else:
                self.MU_LETTER_QPOWER[(a, i)] = 0
        self._mult_gens = tuple(sorted(chord_charges.keys()) + [self.E_GEN, self.E_INV])
        self._cones = None

    def mult_gens(self):
        return self._mult_gens

    def cones(self):
        if self._cones is None:
            V = list(self._mult_gens)
            neighbours = {
                v: frozenset(u for u in V if u != v and self.q_commute(v, u))
                for v in V
            }
            cliques = []
            def bk(R, P, X):
                if not P and not X:
                    cliques.append(R); return
                pivot = max(P | X, key=lambda u: len(P & neighbours[u]))
                for v in list(P - neighbours[pivot]):
                    bk(R | {v}, P & neighbours[v], X & neighbours[v])
                    P = P - {v}; X = X | {v}
            bk(frozenset(), frozenset(V), frozenset())
            self._cones = tuple(cliques)
        return self._cones

    def _is_L_letter(self, g):
        return g not in (self.E_GEN, self.E_INV)

    def q_commute(self, g, h):
        if g == h: return True
        # QTCone (Laurent E): E and E⁻¹ q-commute with cocycle 0.
        # The cancellation E · E⁻¹ = 1 is handled by the universal
        # `_torus_inverse_letter` collapse in
        # `ConeData._word_to_gens_powers`, not via cross_product.
        if {g, h} == {self.E_GEN, self.E_INV}: return True
        if self._is_L_letter(g) and self._is_L_letter(h):
            fwd = self.mult_table.get((g, h))
            return fwd is not None and len(fwd) == 1
        return True

    def cocycle(self, g, h):
        if g == h: return 0
        # E and E⁻¹ commute (cocycle 0) — torus direction.
        if {g, h} == {self.E_GEN, self.E_INV}: return 0
        if self._is_L_letter(g) and self._is_L_letter(h):
            fwd = self.mult_table.get((g, h)); bwd = self.mult_table.get((h, g))
            if fwd is None or len(fwd) != 1 or bwd is None or len(bwd) != 1:
                raise ValueError(f"cocycle: {g}, {h} not q-commuting")
            c_full = fwd[0][0] - bwd[0][0]
            assert c_full % 2 == 0
            return c_full // 2
        if g == self.E_GEN and self._is_L_letter(h): return -self.MU_LETTER_QPOWER[h]
        if h == self.E_GEN and self._is_L_letter(g): return self.MU_LETTER_QPOWER[g]
        if g == self.E_INV and self._is_L_letter(h): return self.MU_LETTER_QPOWER[h]
        if h == self.E_INV and self._is_L_letter(g): return -self.MU_LETTER_QPOWER[g]
        raise ValueError(f"cocycle undefined for ({g}, {h})")

    def cross_product(self, g, h):
        # Note: (E_GEN, E_INV) no longer reaches here — q-commute with
        # cocycle 0, cancellation via `_torus_inverse_letter`.
        if self._is_L_letter(g) and self._is_L_letter(h):
            terms = self.mult_table.get((g, h))
            if terms is None:
                raise ValueError(f"mult_table missing ({g}, {h})")
            out = []
            for (q_pow, e_E, factors, q_coef) in terms:
                word = list(factors)
                if e_E > 0: word.extend([self.E_GEN] * e_E)
                elif e_E < 0: word.extend([self.E_INV] * (-e_E))
                gens_set = frozenset(word)
                powers = {gx: word.count(gx) for gx in gens_set}
                phase = self.cone_label_phase(gens_set, powers)
                coef = q_coef * LaurentPoly({q_pow + phase: 1})
                out.append((coef, tuple(word)))
            return out
        raise ValueError(f"cross_product undefined for q-commuting ({g}, {h})")

    def to_cone_label(self, native_label):
        factors, e_E = native_label
        word = []
        for (a, i, exp) in sorted(factors):
            word.extend([(a, i)] * exp)
        if e_E > 0: word.extend([self.E_GEN] * e_E)
        elif e_E < 0: word.extend([self.E_INV] * (-e_E))
        if not word:
            for c in self.cones():
                if self.E_GEN in c: return (c, {g: 0 for g in c})
            return (self.cones()[0], {g: 0 for g in self.cones()[0]})
        gens_in_word = set(word)
        for cone in self.cones():
            if gens_in_word <= set(cone):
                powers = {g: word.count(g) for g in cone}
                return (cone, powers)
        raise ValueError(f"no cone for {native_label}: {gens_in_word}")

    def from_cone_label(self, gens, powers):
        factors_dict = {}; e_E = 0
        for g, p in powers.items():
            if p == 0: continue
            if g == self.E_GEN: e_E += p
            elif g == self.E_INV: e_E -= p
            else:
                a, i = g
                factors_dict[(a, i)] = factors_dict.get((a, i), 0) + p
        factors = tuple(sorted((a, i, p) for (a, i), p in factors_dict.items()))
        return (factors, e_E)

    # -- torus inverse letter (Laurent E direction; QTCone semantics) -----

    def _torus_inverse_letter(self, g):
        """E ↔ E⁻¹ pairing.  Universal cancellation collapse in
        `ConeData._word_to_gens_powers` replaces the previous
        cross_product Plücker handling."""
        if g == self.E_GEN: return self.E_INV
        if g == self.E_INV: return self.E_GEN
        return None

    # -- QTCone iter ------------------------------------------------------

    def iter_cones(self):
        """Yield QTCone instances per maximal cone, with
        `torus_gens = {E, E⁻¹} ∩ cone_gens`."""
        torus_all = frozenset({self.E_GEN, self.E_INV})
        for cone_gens in self.cones():
            yield Cone(self, cone_gens, torus_gens=torus_all & cone_gens)


# ============================================================================
# General KAlgebra
# ============================================================================

class U1A1AoddKAlg(ConeKAlgebra):
    """u(1)-gauged [A_1, A_{2k+1}] AD theory for any k ≥ 1.
    Bootstraps chord_charges and MULT_TABLE from BPS at __init__."""

    def __init__(self, k: int):
        self.k = k
        self.H = 2 * k + 4
        self._R = TrivialZPlusRing()
        chord_charges, E_charge, mult_table = generate_mult_table(k)
        self.chord_charges = chord_charges
        self.E_charge = E_charge
        self._mult_table = mult_table
        self._cone_data = U1A1AoddConeData(
            k, chord_charges, E_charge, mult_table, mult_table.family_periods,
        )

    def coefficient_ring(self): return self._R
    def identity(self): return ((), 0)

    def cone_data(self):
        return self._cone_data

    # `multiply` inherited from ConeKAlgebra.

    def rho(self, label):
        """ρ on a cone label `(factors, e_E)`: shift each chord
        `(a, i) → (a, i+1 mod P_a)`, accumulate the wrap E-drift at the
        last orbit element, and negate the E-power (`ρ(E)=E⁻¹`).

        The wrap drift + E-inversion are essential: without them ρ drops the
        periodicity μ/E-pickup and disagrees with BPS on the wrap letters and
        on every `e_E≠0` label (it then fails `verify_rho_is_automorphism` and
        corrupts the multi-letter trace — the same long-chord ρ/trace defect
        fixed in `U1HexagonKAlg`).  Matches the good-branch
        `u1a1aodd_kalg._rho_label_cone`; validated 0-mismatch vs BPS."""
        per = self._mult_table.family_periods
        eps = self._mult_table.eps_wrap
        new_factors = []
        drift = 0
        for (a, i, e) in label[0]:
            if i == per[a] - 1:
                drift += e * eps[a]
            new_factors.append((a, (i + 1) % per[a], e))
        return (tuple(sorted(new_factors)), -label[1] + drift)

    def rho_inverse(self, label):
        """Inverse of `rho`: shift `i → i-1 mod P_a`, accumulate the wrap drift
        when leaving the first orbit element, and invert the E-power."""
        per = self._mult_table.family_periods
        eps = self._mult_table.eps_wrap
        new_factors = []
        drift = 0
        for (a, i, e) in label[0]:
            if i == 0:
                drift += e * eps[a]
            new_factors.append((a, (i - 1) % per[a], e))
        return (tuple(sorted(new_factors)), -(label[1] - drift))

    def _mag_charge(self, label):
        factors, _ = label
        return sum(self._cone_data.MU_LETTER_QPOWER[(a, i)] * e
                   for (a, i, e) in factors)

    def trace_layer1(self, label):
        if self._mag_charge(label) != 0:
            return {}
        factors, e_E = label
        letters = [(a, i) for (a, i, exp) in factors for _ in range(exp)]
        gens_set = set(letters)
        cones = self._cone_data.cones()
        is_cone_mono = any(gens_set <= set(c) for c in cones) if gens_set else True
        if not is_cone_mono:
            half = len(letters) // 2
            def to_label(lst, e_E_local):
                from collections import Counter
                ctr = Counter(lst)
                f = tuple(sorted((a, i, e) for (a, i), e in ctr.items()))
                return (f, e_E_local)
            prod = self._cone_data.derived_multiply(
                to_label(letters[:half], e_E), to_label(letters[half:], 0))
            out = {}
            for sub_lbl, sub_coef in prod.terms.items():
                sub_trace = self.trace_layer1(sub_lbl)
                for ky, v in sub_trace.items():
                    contribution = sub_coef * v
                    out[ky] = out.get(ky, LaurentPoly({})) + contribution
            return {ky: v for ky, v in out.items() if not v.is_zero()}
        simplified = self._cone_data.simplify_trace_via_cone_data(self, label)
        return {ky: v for ky, v in simplified.terms.items() if not v.is_zero()}

    def trace(self, label, K=20):
        return self.trace_layer1(label)

    # ----- KAlgebra._canonical_rho2_orbit_rep override -------------------

    def _canonical_rho2_orbit_rep(self, label):
        """Closed-form ρ²-orbit representative (drift quotient).

        With the wrap-pickup-correct ρ (`ρ(E)=E⁻¹` + wrap E-drift), ρ² is
        **not** finite-order on a single chord: it shifts position
        `i → i+2 (mod P)` AND drifts the E-power by the accumulated wrap
        pickup, so the orbit runs off to `e = ±∞` (the default orbit walk
        would not terminate).  Per the `ConeKAlgebra` contract a closed-form
        canonical rep is required (cf. `U1SquareKAlg` / the good-branch
        `u1a1aodd_kalg`).  E-powers are ρ²-fixed (`ρ²(E)=E`); a single chord
        reduces by the drift quotient; multi-gen seeds are left as-is (their
        trace is read by charge, which is ρ²-invariant, so the final linear
        `Σ c_seed·Tr(seed)` is unaffected)."""
        factors, e = label
        if len(factors) == 0:
            return ((), e)                                  # E^e: ρ²-fixed
        if len(factors) == 1 and factors[0][2] == 1:
            from math import gcd
            a = factors[0][0]
            s = self._mult_table.family_periods[a]
            P = s // gcd(s, 2)                              # ρ²-period in position
            members, cur = [], label
            for _ in range(P):
                members.append(cur)
                cur = self.rho(self.rho(cur))               # ρ²
            D = cur[1] - e                                  # E-drift over one period
            if D == 0:                                      # finite orbit
                return min(members, key=lambda m: (m[0][0][1], m[1]))
            istar = min(m[0][0][1] for m in members)        # canonical position
            estar = next(m[1] for m in members if m[0][0][1] == istar)
            return (((a, istar, 1),), estar % abs(D))       # drift quotient
        return label                                        # multi-gen: leave as-is

    # ----- ConeKAlgebra._trace_residual (stub) ---------------------------

    def _trace_residual(self, seed_label, K):
        """Required abstract on ConeKAlgebra; currently a stub
        (trace returns Layer-1 dict directly).  Layer-2 closed forms
        for the seed families are research follow-up — mirrors the
        U1OctagonKAlg / U1DecagonKAlg pattern."""
        raise NotImplementedError(
            f"U1A1AoddKAlg(k={self.k})._trace_residual: trace returns "
            f"Layer-1 decomposition only; Layer-2 closed forms are "
            f"research follow-up."
        )

    # --------------------------------------------------------------------
    # Self-consistency: associativity verification
    # --------------------------------------------------------------------
    # As k grows, BPS computation becomes infeasible (f-solver, Schur).
    # Instead, the algebra is self-consistent iff multiply satisfies
    # associativity: (a · b) · c = a · (b · c).  This is the primary
    # consistency check that does NOT depend on BPS.

    def verify_associativity(self, sample_labels=None):
        """Check (a · b) · c = a · (b · c) on sample triples.
        Returns (n_ok, n_bad, list_of_failures)."""
        if sample_labels is None:
            # Default: single-letter generators from each chord family
            sample_labels = [(((a, 0, 1),), 0) for a in range(1, max(self._mult_table.family_periods.keys()) + 1)]
            sample_labels.append((((1, 1, 1),), 0))  # also non-zero offset
        n_ok = n_bad = 0
        fails = []
        for a in sample_labels:
            for b in sample_labels:
                for c in sample_labels:
                    # (a·b)·c
                    ab = self.multiply(a, b)
                    abc_left = Element({})
                    for lab_ab, coef_ab in ab.terms.items():
                        lab_abc = self.multiply(lab_ab, c)
                        for lab_out, coef_out in lab_abc.terms.items():
                            contribution = coef_ab * coef_out
                            if lab_out in abc_left.terms:
                                abc_left.terms[lab_out] = abc_left.terms[lab_out] + contribution
                            else:
                                abc_left.terms[lab_out] = contribution
                    # a·(b·c)
                    bc = self.multiply(b, c)
                    abc_right = Element({})
                    for lab_bc, coef_bc in bc.terms.items():
                        lab_abc = self.multiply(a, lab_bc)
                        for lab_out, coef_out in lab_abc.terms.items():
                            contribution = coef_bc * coef_out
                            if lab_out in abc_right.terms:
                                abc_right.terms[lab_out] = abc_right.terms[lab_out] + contribution
                            else:
                                abc_right.terms[lab_out] = contribution
                    # Compare (drop zero terms)
                    left = {k: v for k, v in abc_left.terms.items() if not v.is_zero()}
                    right = {k: v for k, v in abc_right.terms.items() if not v.is_zero()}
                    if left == right:
                        n_ok += 1
                    else:
                        n_bad += 1
                        if len(fails) < 3:
                            fails.append((a, b, c, left, right))
        return (n_ok, n_bad, fails)


if __name__ == "__main__":
    print("U1A1AoddKAlg general bootstrap test")
    print()
    for k in (2, 3):
        print(f"=== k={k} ===")
        A = U1A1AoddKAlg(k)
        print(f"  H = {A.H}")
        print(f"  primitive families: {sorted(A._mult_table.family_periods.items())}")
        print(f"  chord generators: {len(A.chord_charges)}")
        print(f"  cones: {len(A._cone_data.cones())}")
        # Sample multiply
        result = A.multiply((((1, 0, 1),), 0), (((1, 1, 1),), 0))
        print(f"  L_1(0)·L_1(1) = {dict(result.terms)}")
        # Sample trace
        tr = A.trace_layer1((((2, 0, 1),), 0))
        print(f"  Tr(L_2(0)) = {tr}")
        print()
