"""The Chekhov-Fock algebra Y_Delta of an ideal triangulation.

Definition:

  Y_Delta is the R-subalgebra of (X)_T Y(T) generated by edge variables
  y_e (one per edge of Delta), with commutation
       y_e y_f  =  lq^{sigma(e, f)} y_f y_e
  where sigma is the antisymmetric exchange matrix derived from the
  triangulation (cf. Triangulation.sigma()).

For each interior edge e there are two lifts e', e'' (one in each
adjacent triangle).  Since the lifts live in different tensor factors
they commute, so the Weyl bracket is just the product:
       y_e  =  [y_{e'} y_{e''}]  =  y_{e'} y_{e''}.

This module:
  * stores Y_Delta elements in canonical ORDERED form
        y^a = y_0^{a_0} y_1^{a_1} ... y_{n-1}^{a_{n-1}}
    in the canonical edge-index order of the triangulation, with
    half-Laurent coefficients;
  * implements addition and multiplication via the sigma matrix;
  * exposes the Weyl-normalized coefficient
        [y^a] = lq^{-(1/2) sum_{i<j} a_i a_j sigma(i,j)} y^a
    via :meth:`weyl_coefficient` (for matching outputs that use
    Weyl form);
  * provides :func:`project_triangle_monomial` -- the lift-parity check
    and edge-exponent collector that maps a tensor of per-triangle
    ordered Y(T) monomials into Y_Delta.

Self-contained: depends only on half_laurent and triangulation.
"""

from __future__ import annotations

from fractions import Fraction
from typing import Iterable, Mapping, Optional, Sequence

from half_laurent import HalfLaurent, ONE as HL_ONE
from triangulation import Triangulation


# Edge-exponent vector type
Charge = tuple[int, ...]


class YDelta:
    """Element of Y_Delta in canonical ordered form.

    Stored as dict[Charge, HalfLaurent] where Charge is an n_edges-tuple
    of integer exponents (one per edge in canonical edge-index order).
    """

    __slots__ = ("triangulation", "_terms")

    def __init__(
        self,
        triangulation: Triangulation,
        terms: Mapping[Charge, HalfLaurent] | None = None,
    ):
        clean: dict[Charge, HalfLaurent] = {}
        n_edges = triangulation.n_edges
        if terms is not None:
            for charge, coef in terms.items():
                if coef.is_zero():
                    continue
                if not (
                    isinstance(charge, tuple)
                    and len(charge) == n_edges
                    and all(isinstance(x, int) for x in charge)
                ):
                    raise TypeError(
                        f"charge must be a {n_edges}-tuple of ints, got {charge!r}"
                    )
                if charge in clean:
                    s = clean[charge] + coef
                    if s.is_zero():
                        del clean[charge]
                    else:
                        clean[charge] = s
                else:
                    clean[charge] = coef
        object.__setattr__(self, "triangulation", triangulation)
        object.__setattr__(self, "_terms", clean)

    # constructors

    @classmethod
    def zero(cls, triangulation: Triangulation) -> "YDelta":
        return cls(triangulation)

    @classmethod
    def one(cls, triangulation: Triangulation) -> "YDelta":
        zero_charge = (0,) * triangulation.n_edges
        return cls(triangulation, {zero_charge: HL_ONE})

    @classmethod
    def monomial(
        cls,
        triangulation: Triangulation,
        charge: Sequence[int],
        coef: HalfLaurent | int = 1,
    ) -> "YDelta":
        """Ordered-form monomial coef * y^charge."""
        if isinstance(coef, int):
            coef = HalfLaurent.from_int(coef)
        if coef.is_zero():
            return cls.zero(triangulation)
        return cls(triangulation, {tuple(charge): coef})

    @classmethod
    def weyl_monomial(
        cls,
        triangulation: Triangulation,
        charge: Sequence[int],
        weyl_coef: HalfLaurent | int = 1,
    ) -> "YDelta":
        """Weyl-normalized monomial weyl_coef * [y^charge].

        Internal storage is ordered, so we apply
            [y^a] = lq^{-(1/2) sum_{i<j} a_i a_j sigma(i,j)} y^a
        to convert.
        """
        if isinstance(weyl_coef, int):
            weyl_coef = HalfLaurent.from_int(weyl_coef)
        if weyl_coef.is_zero():
            return cls.zero(triangulation)
        ordered_coef = weyl_coef.shift(_weyl_correction(triangulation, charge))
        return cls(triangulation, {tuple(charge): ordered_coef})

    # accessors

    def is_zero(self) -> bool:
        return not self._terms

    def coefficient(self, charge: Sequence[int]) -> HalfLaurent:
        """Coefficient of y^charge in canonical ORDERED form."""
        return self._terms.get(tuple(charge), HalfLaurent.zero())

    def weyl_coefficient(self, charge: Sequence[int]) -> HalfLaurent:
        """Coefficient of [y^charge] (Weyl-normalized monomial).

        ordered_coef = lq^{-(1/2) sum_{i<j} a_i a_j sigma(i,j)} weyl_coef
        => weyl_coef = lq^{(1/2) sum_{i<j} a_i a_j sigma(i,j)} ordered_coef
        """
        ordered = self.coefficient(charge)
        if ordered.is_zero():
            return ordered
        # Negate the exponent shift used in weyl_monomial.
        return ordered.shift(-_weyl_correction(self.triangulation, charge))

    def cluster_coefficient(self, charge: Sequence[int]) -> HalfLaurent:
        """Coefficient of `cluster_X^charge`, where the X-monomial uses the
        no-1/2 X-relation `X_a X_b = lq^{a^T sigma b} X_{a+b}` matching
        `kcoulomb.bracket_int`.

        Formally:
            cluster_X_a := lq^{- sum_{i<j} a_i a_j sigma(i,j)} y^a
        (twice the Weyl correction).  This is a diagnostic view; whether
        it matches the cluster code's normalization is what we want to
        check.
        """
        ordered = self.coefficient(charge)
        if ordered.is_zero():
            return ordered
        # 2x the Weyl correction (i.e., no 1/2 factor in front).
        return ordered.shift(-2 * _weyl_correction(self.triangulation, charge))

    def triangle_weyl_coefficient(self, charge: Sequence[int]) -> HalfLaurent:
        """Coefficient of an X-monomial in the Z_3-equivariant normalization.

        The standard `weyl_coefficient` uses the Y_Delta-global correction
            e_global(a) = -(1/2) sum_{i<j (global edge-index)} a_i a_j sigma_Delta(i,j)
        which depends on the alphabetical edge-index ordering and is NOT
        Z_3-equivariant under triangulation symmetries.

        This accessor uses instead
            e_triangle(a) = sum_T -(1/2) sum_{p<q in T's positions} a_T[p] a_T[q] sigma_T(p,q)
        where for each triangle T, a_T is the restriction of a to T's edges
        (in T's CCW position order) and sigma_T = circulant antisymmetric
        +1 matrix (universal across triangles).  This sum is Z_3-invariant
        under triangulation symmetries: each per-triangle term is
        cyclic-shift-invariant within its own triangle, and summing over
        triangles is permutation-invariant.

        Verified on the 3 simple closed curves of the tetrahedral S^2_{0,4}:
        all 21 monomials have triangle_weyl_coefficient = 1, matching the
        cluster-code's F_p's all-1 pattern.
        """
        ordered = self.coefficient(charge)
        if ordered.is_zero():
            return ordered
        # Compute the per-triangle Weyl correction.
        e_triangle = _triangle_weyl_correction(self.triangulation, charge)
        # ordered = lq^{e_triangle} * triangle_weyl_coef
        # => triangle_weyl_coef = ordered * lq^{-e_triangle}
        return ordered.shift(-e_triangle)

    def items(self) -> list[tuple[Charge, HalfLaurent]]:
        """Ordered-form (charge, coefficient) pairs sorted by charge."""
        return sorted(self._terms.items())

    def weyl_items(self) -> list[tuple[Charge, HalfLaurent]]:
        """Weyl-form (charge, weyl_coefficient) pairs sorted by charge."""
        return [(c, self.weyl_coefficient(c)) for c, _ in self.items()]

    # arithmetic

    def __add__(self, other) -> "YDelta":
        if not isinstance(other, YDelta):
            return NotImplemented
        if other.triangulation is not self.triangulation:
            raise ValueError("YDelta operands must share the same triangulation")
        out = dict(self._terms)
        for c, v in other._terms.items():
            if c in out:
                s = out[c] + v
                if s.is_zero():
                    del out[c]
                else:
                    out[c] = s
            else:
                out[c] = v
        return _raw(self.triangulation, out)

    def __neg__(self) -> "YDelta":
        return _raw(self.triangulation, {c: -v for c, v in self._terms.items()})

    def __sub__(self, other) -> "YDelta":
        return self + (-other)

    def __mul__(self, other) -> "YDelta":
        if isinstance(other, int):
            other = HalfLaurent.from_int(other)
        if isinstance(other, HalfLaurent):
            if other.is_zero():
                return YDelta.zero(self.triangulation)
            return _raw(
                self.triangulation,
                {c: v * other for c, v in self._terms.items()},
            )
        if not isinstance(other, YDelta):
            return NotImplemented
        if other.triangulation is not self.triangulation:
            raise ValueError("YDelta operands must share the same triangulation")
        sigma = self.triangulation.sigma()
        out: dict[Charge, HalfLaurent] = {}
        for ca, va in self._terms.items():
            for cb, vb in other._terms.items():
                # ordered-form product:
                #     y^a y^b = lq^{- sum_{i<j} b_i a_j sigma(i,j)} y^{a+b}
                lq_pow = 0
                n = len(ca)
                for i in range(n):
                    bi = cb[i]
                    if bi == 0:
                        continue
                    for j in range(i + 1, n):
                        aj = ca[j]
                        if aj == 0:
                            continue
                        lq_pow -= bi * aj * sigma[i][j]
                new_c = tuple(ca[k] + cb[k] for k in range(n))
                new_v = (va * vb).shift(lq_pow)
                if new_v.is_zero():
                    continue
                if new_c in out:
                    s = out[new_c] + new_v
                    if s.is_zero():
                        del out[new_c]
                    else:
                        out[new_c] = s
                else:
                    out[new_c] = new_v
        return _raw(self.triangulation, out)

    __rmul__ = __mul__

    # equality

    def __eq__(self, other) -> bool:
        if not isinstance(other, YDelta):
            return NotImplemented
        return (
            self.triangulation is other.triangulation
            and self._terms == other._terms
        )

    def __hash__(self) -> int:
        return hash((id(self.triangulation), tuple(sorted(self._terms.items()))))

    # display

    def __repr__(self) -> str:
        if not self._terms:
            return "0"
        parts: list[str] = []
        for charge in sorted(self._terms):
            coef = self._terms[charge]
            mono_parts: list[str] = []
            for ei, e in enumerate(charge):
                if e == 0:
                    continue
                tag = f"y_{ei}"
                mono_parts.append(tag if e == 1 else f"{tag}^{e}")
            mono = " ".join(mono_parts) if mono_parts else "1"
            crep = repr(coef)
            if mono == "1":
                term = crep
            elif crep == "1":
                term = mono
            elif crep == "-1":
                term = f"-{mono}"
            else:
                term = f"({crep})*{mono}"
            if not parts:
                parts.append(term)
            else:
                if term.startswith("-"):
                    parts.append(f" - {term[1:]}")
                else:
                    parts.append(f" + {term}")
        return "".join(parts)


def _raw(triangulation: Triangulation, terms: dict[Charge, HalfLaurent]) -> YDelta:
    obj = YDelta.__new__(YDelta)
    object.__setattr__(obj, "triangulation", triangulation)
    object.__setattr__(obj, "_terms", terms)
    return obj


def _weyl_correction(triangulation: Triangulation, charge: Sequence[int]) -> Fraction:
    """Half-integer exponent c such that
            [y^charge] = lq^{c} y^charge,    c = -(1/2) sum_{i<j} a_i a_j sigma(i,j).
    """
    sigma = triangulation.sigma()
    s = 0
    n = len(charge)
    for i in range(n):
        ai = charge[i]
        if ai == 0:
            continue
        for j in range(i + 1, n):
            aj = charge[j]
            if aj == 0:
                continue
            s += ai * aj * sigma[i][j]
    return Fraction(-s, 2)


# Universal per-triangle sigma at positions (0=a, 1=b, 2=c) ccw.
# Encodes y_a y_b = lq y_b y_a etc.
_SIGMA_T = ((0, 1, -1), (-1, 0, 1), (1, -1, 0))


def _triangle_weyl_correction(triangulation: Triangulation, charge: Sequence[int]) -> Fraction:
    """Per-triangle Weyl correction summed across triangles.

        e_triangle(a) = sum_T -(1/2) sum_{p<q in {0,1,2}} a_T[p] a_T[q] sigma_T(p,q)

    where a_T is the charge restricted to T's 3 edges, in T's CCW position order
    (positions 0, 1, 2 = edges a, b, c of T).  sigma_T is the universal
    circulant +1 matrix.  Z_3-invariant under triangulation symmetries.
    """
    s = 0
    for triangle_edges in triangulation.triangle_edges:
        # a_T at positions 0, 1, 2 of T:
        a_T = [charge[ei] for ei in triangle_edges]
        for p in range(3):
            ap = a_T[p]
            if ap == 0:
                continue
            for q in range(p + 1, 3):
                aq = a_T[q]
                if aq == 0:
                    continue
                s += ap * aq * _SIGMA_T[p][q]
    return Fraction(-s, 2)


# ----------------------------------------------------------------------
# Projection: tensor of per-triangle ordered Y(T) monomials -> Y_Delta
# ----------------------------------------------------------------------


def project_triangle_monomial(
    triangulation: Triangulation,
    triangle_exps: Sequence[tuple[int, int, int]],
    coef: HalfLaurent,
) -> Optional[tuple[Charge, HalfLaurent]]:
    """Project one tensor of per-triangle ordered Y(T) monomials into Y_Delta.

    Args:
        triangulation : the ambient triangulation.
        triangle_exps : list of (i, j, k) tuples, one per triangle in the
                        triangulation's order; (i, j, k) are the exponents
                        on (y_a^T, y_b^T, y_c^T) in T's ccw edge order
                        (matching `Triangulation.triangle_edges`).
        coef          : the HalfLaurent coefficient of the global monomial.

    Returns:
        (charge, ordered_coefficient) on success, where charge is an
        n_edges-tuple of edge exponents in canonical edge-index order.

        The two lifts of an interior edge live in commuting tensor
        factors, so MERGING them introduces no lq-correction.  However,
        each triangle's monomial arrives in the triangle's CCW position
        order (y_a y_b y_c), while the global ordered form sorts the
        edges by canonical edge index; re-sorting the factors WITHIN
        each triangle (cross-triangle factors commute) picks up
        `lq^{sigma_T(p,q) x_p x_q}` per inverted pair.  Omitting this
        cross-edge reordering is invisible on single traces (a uniform
        monomial renormalization) but breaks Y_Delta products; it was
        found via the product relations of the intrinsic skein engine
        (see geometric_f.py).

        None if any interior edge fails the lift-parity check
        (its two lifts have different exponents), in which case the
        contribution is zero.
    """
    if len(triangle_exps) != triangulation.n_triangles:
        raise ValueError(
            f"expected {triangulation.n_triangles} triangle exponents, "
            f"got {len(triangle_exps)}"
        )

    # collect per-edge exponents from the two lifts, and the per-triangle
    # reorder correction (ccw position order -> global edge-index order)
    n_edges = triangulation.n_edges
    edge_exps: list[Optional[int]] = [None] * n_edges
    reorder_pow = 0
    for ti, exp_triple in enumerate(triangle_exps):
        i, j, k = exp_triple
        triangle_edge_ids = triangulation.triangle_edges[ti]
        for pos, e_id in enumerate(triangle_edge_ids):
            this_exp = (i, j, k)[pos]
            if edge_exps[e_id] is None:
                edge_exps[e_id] = this_exp
            else:
                if edge_exps[e_id] != this_exp:
                    return None  # parity mismatch -> contribution is zero
        # bubble the three factors into global edge order:
        # y_p^{x_p} y_q^{x_q} = lq^{sigma_T(p,q) x_p x_q} y_q^{x_q} y_p^{x_p}
        x = (i, j, k)
        for p in range(3):
            for q in range(p + 1, 3):
                if triangle_edge_ids[p] > triangle_edge_ids[q]:
                    reorder_pow += _SIGMA_T[p][q] * x[p] * x[q]

    # By construction every edge in a closed-sphere triangulation has two
    # lifts, so all entries are now filled.  Sanity-check.
    if any(e is None for e in edge_exps):
        raise AssertionError("edge_exps not fully filled (triangulation invariant)")

    return tuple(edge_exps), coef.shift(reorder_pow)
