"""`AbelianizedSU2KAlg` — pure SU(2) as the trace-zero subalgebra of the
abelianized pure-U(2) realisation `PureGAbeKAlgebra(u_n(2))`.

(Until 2026-09-19 the U(2) side was `PureUNKAlgebra(2)`, the closed-form
type-A keystone; that class was retired to the source repository's archive once
the (★)-route `L_{m,e}` builder made it obsolete — measured equal on 411/411
checks at U(2)/U(3) — and this wrapper now delegates to the general-`G`
class, through its `fold` so the lift lands in the canonical frame.  Same
public surface, same labels, same det-projection read-back.)

A **light wrapper**: a canonical basis element is the SU(2) 't Hooft–Wilson
line `L_{m,e}` (magnetic charge `m`, electric charge `e`), realised as the
pure-U(2) Kapustin label

    L_{m,e}  ↦  ((m, -m), (e, 0))                        (`_lift`)

— magnetic cocharacter `m·(1,-1)` (a multiple of the **adjoint**, i.e. the
trace-zero / SU(2) sublattice), electric a det-representative with
`λ₁ - λ₂ = e`.  All structure (`multiply`, `rho`, `trace`) is delegated to
`PureGAbeKAlgebra(u_n(2))` and read back through the **det-projection**

    ((M, -M), (λ₁, λ₂))  ↦  (M, λ₁ - λ₂)                 (`_project`)

which collapses the central U(1)/det charge (the SU(2) Weyl chamber is fixed
by folding `m<0 → -m` and, at `m=0`, `e → |e|`).  This is exactly "the
subalgebra of abelianized pure U(2) generated by `m` a multiple of the
adjoint", presented with clean `L_{m,e}` labels.

Canonical-label domain (one label per line, SU(2) Weyl chamber):

    {(m, e) : m ≥ 1, e ∈ ℤ}  ∪  {(0, e) : e ≥ 0}

`(0, e)` is the Wilson character `χ_e` (spin `e/2`); `(m, 0)` the bare
't Hooft line of magnetic charge `m`; `(m, e)` a dressed dyon.

Caveat (documented, not hidden): the inherited `trace` is the **U(2)**
Schur index — it carries the decoupled U(1) photon factor relative to pure
SU(2).  The companion `KAlgebraIso` to the BPS pure-SU(2) realisation is
therefore certified on the photon-independent structure
(`multiply`, `rho`, unit, round-trip); see `abelianized_su2_bps_iso.py`.
"""
from __future__ import annotations

import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from kalgebra import KAlgebra, Element, Label
from laurent_poly import LaurentPoly
from zplus_ring import ZPlusRing
from pure_g_abe_kalgebra import PureGAbeKAlgebra
from root_datum import u_n


__all__ = ["AbelianizedSU2KAlg", "su2_fold"]


def su2_fold(m: int, e: int) -> tuple[int, int]:
    """Fold an `(m, e)` into the SU(2) Weyl chamber / canonical domain.

    Weyl acts by `(m, e) ↦ (-m, -e)`; pick `m ≥ 0`, and at `m = 0` pick
    `e ≥ 0` (the residual reflection `χ_e = χ_{-e}`)."""
    if m < 0:
        m, e = -m, -e
    if m == 0 and e < 0:
        e = -e
    return (m, e)


class AbelianizedSU2KAlg(KAlgebra):
    """Pure SU(2) as the trace-zero (adjoint-magnetic) subalgebra of
    `PureGAbeKAlgebra(u_n(2))`, with 't Hooft–Wilson labels `(m, e)`.
    (`K` / `max_len` are accepted for source compatibility with the retired
    keystone's constructor and ignored: the general class builds lazily.)"""

    def __init__(self, K: int = 12, max_len: int = 2):
        self._u2 = PureGAbeKAlgebra(u_n(2))

    # -- label <-> U(2) lift ----------------------------------------------

    def _lift(self, label: Label) -> Label:
        """`(m, e) ↦ fold((m, -m), (e, 0))` — the pure-U(2) Kapustin label in
        the general class's canonical frame."""
        m, e = label
        return self._u2.fold((m, -m), (e, 0))

    @staticmethod
    def _project(u2_label: Label) -> tuple[int, int]:
        """`((M, -M), (λ₁, λ₂)) ↦ fold(M, λ₁ - λ₂)` — det-projection."""
        mag, lam = u2_label
        assert mag[0] + mag[1] == 0, f"non-trace-zero magnetic {mag}"
        return su2_fold(mag[0], lam[0] - lam[1])

    def _project_element(self, u2_elem: Element) -> Element:
        """Push a U(2) `Element` through the det-projection, summing
        coefficients that collapse onto the same SU(2) label."""
        out: dict = {}
        for u2_label, coef in u2_elem.terms.items():
            lbl = self._project(u2_label)
            out[lbl] = out[lbl] + coef if lbl in out else coef
        return Element({k: v for k, v in out.items() if not v.is_zero()})

    # -- KAlgebra primitives ----------------------------------------------

    def coefficient_ring(self) -> ZPlusRing:
        return self._u2.coefficient_ring()

    def identity(self) -> Label:
        return (0, 0)

    def multiply(self, a: Label, b: Label) -> Element:
        prod = self._u2.multiply(self._lift(a), self._lift(b))
        return self._project_element(prod)

    def rho(self, label: Label) -> Label:
        img = self._project(self._u2.rho(self._lift(label)))
        return img

    def rho_inverse(self, label: Label) -> Label:
        return self._project(self._u2.rho_inverse(self._lift(label)))

    def trace(self, label: Label, K: int = 20):
        """Inherited **U(2)** Schur index of the lift (carries the decoupled
        U(1) photon factor relative to pure SU(2); see module docstring)."""
        return self._u2.trace(self._lift(label), K=K)

    def _label_section_decompose(self, label: Label):
        return label, self.coefficient_ring().one()

    # -- convenience ------------------------------------------------------

    def wilson(self, e: int) -> Label:
        """The Wilson character `χ_e` (spin `e/2`), `e ≥ 0`."""
        if e < 0:
            raise ValueError("Wilson label needs e >= 0 (Weyl: χ_e = χ_{-e})")
        return (0, e)

    def line(self, m: int, e: int) -> Label:
        """The 't Hooft–Wilson line `L_{m,e}`, folded to the Weyl chamber."""
        return su2_fold(m, e)
