"""
Abelianized quantum torus: the ring the UV monopole operators of 3d N=4 /
4d N=2 linear quivers live in, in the abelianized chart.

This module is the ambient ring D_rat for the canonical-surface
abelianized presentations.  It lives on the canonical surface so the
canonical-surface abelianized realisations can import it directly.

Scope
-----

Everything is over the scalar ring ``Z[q, q^{-1}]`` (= ``LaurentPoly``).
Habiro-style localization at ``(1 - q^{2n})`` is a future extension.

Flavour fugacities ``mu_r`` are first-class but live as **flavour
colors** in the v-grading: a ``DOp`` of ``n`` total colors and
``n_gauge`` gauge colors treats indices ``0..n_gauge-1`` as gauge (with
matching ``u_k`` shift operators) and indices ``n_gauge..n-1`` as
flavour (no matching ``u_k``).  ``mu_r`` is then
``v_{n_gauge + r}`` (0-indexed; helpers ``DOp.mu`` and ``VLaurent.mu``
are provided).  This keeps the algebra of the ring identical to the
pure-gauge case: ``u_k`` simply doesn't shift the flavour ``v``s, which
falls out for free since the corresponding entries of the shift vector
are zero.

Rings
-----

* ``VLaurent`` -- multivariate Laurent polynomial in ``(v_0, ..., v_{n-1})``
  with ``LaurentPoly`` (i.e.  ``Z[q^+/-1]``) coefficients.
  Stored as ``dict[tuple[int, ...], LaurentPoly]``: v-exponent tuple ->
  scalar coefficient, zeros dropped.

* ``VRational`` -- elements of ``VLaurent[Delta^{-1}]`` where ``Delta`` is
  the multiplicative monoid generated by the elementary root-like factors

        (v_i - q^m v_j)      for  0 <= i < j < n,   m in Z.

  These are the only allowed denominator factors.  The monoid is closed
  under the ``v_k -> q^{2 c_k} v_k`` substitution induced by ``u^c``:
  a factor ``(v_i - q^m v_j)`` becomes

        q^{2 c_i}  ( v_i - q^{m + 2(c_j - c_i)} v_j )

  -- same monoid, plus a ``q^{2 c_i}`` scalar that absorbs into the
  numerator.  This is the key property that lets ``DOp`` multiply without
  leaving the ring.

  Denominator stored as ``dict[(i, j, m): int]`` with ``i < j`` canonical.
  Equality is by cross-multiplication.

  By convention the ``(v_i - q^m v_j)`` denom factors only ever involve
  gauge colors in physical formulas, but the ring imposes no restriction.

* ``DOp`` -- normal-ordered difference operator

        F = sum_{a in Z^n}  f_a(v) * u^a,     f_a in VRational.

  Multiplication is governed by the abelianized q-Weyl relation

        u_k * v_l = q^{2 delta_{kl}} * v_l * u_k.

  Stored as ``dict[tuple[int, ...], VRational]``: u-exponent tuple ->
  rational-in-v coefficient.  When ``n_gauge < n``, slots
  ``[n_gauge, n)`` are flavour: ``u`` operators are not allowed there
  (``DOp.u(k)`` raises for ``k >= n_gauge``), and the corresponding
  entries of the u-exponent tuple are forced to zero.  Left-ordered
  form (coefficients multiply on the left).

Conventions
-----------

* Variables are indexed ``0..n-1``.  ``n`` is fixed per ``VLaurent`` /
  ``VRational`` / ``DOp`` instance; arithmetic checks matching ``n``.
  For ``DOp`` instances built with ``n_gauge < n``, the additional
  invariant is that u-exponent tuples are zero on the flavour slots.
* ``q`` lives in the scalar coefficient ring and is exactly the
  ``LaurentPoly`` ``q`` from ``laurent_poly``.
"""

from __future__ import annotations

from functools import lru_cache
from typing import Iterable, Mapping
from laurent_poly import LaurentPoly


# ============================================================================
# VLaurent: Z[q^+/-1][v_1^+/-1, ..., v_n^+/-1]
# ============================================================================


def _lp_is_zero(lp: LaurentPoly) -> bool:
    return lp.is_zero()


class VLaurent:
    """Multivariate Laurent polynomial in v_0, ..., v_{n-1} over Z[q^+/-1].

    Stored as ``dict[tuple[int, ...], LaurentPoly]``: the key is the
    v-exponent tuple, the value is the scalar coefficient (a ``LaurentPoly``
    in ``q``).  Zero coefficients are dropped at construction.
    """

    __slots__ = ("_terms", "_n")

    def __init__(self,
                 terms: Mapping[tuple[int, ...], LaurentPoly] | None = None,
                 n: int = 1):
        if n < 0:
            raise ValueError("VLaurent needs n >= 0")
        self._n = int(n)
        self._terms: dict[tuple[int, ...], LaurentPoly] = {}
        if terms:
            for e, c in terms.items():
                if len(e) != n:
                    raise ValueError(
                        f"v-exponent {e} has length {len(e)} != n {n}"
                    )
                if not isinstance(c, LaurentPoly):
                    raise TypeError(
                        f"coefficient for {e} is {type(c).__name__}, not LaurentPoly"
                    )
                if not c.is_zero():
                    self._terms[tuple(int(x) for x in e)] = c

    @classmethod
    def _from_clean_terms(cls, terms: dict, n: int) -> "VLaurent":
        """Fast-path constructor.  Caller MUST ensure:
          - terms is a dict[tuple[int, ...], LaurentPoly]
          - all exponent tuples have length n
          - no zero coefficients

        Skips iteration + validation in __init__.  Used in hot inner
        arithmetic loops (mul, add, q_shift) where invariants hold."""
        out = cls.__new__(cls)
        out._n = n
        out._terms = terms
        return out

    # --- constructors ---

    @staticmethod
    def zero(n: int) -> "VLaurent":
        return VLaurent(None, n=n)

    @staticmethod
    def one(n: int) -> "VLaurent":
        return VLaurent({tuple([0] * n): LaurentPoly.one()}, n=n)

    @staticmethod
    def from_scalar(s: "LaurentPoly | int", n: int) -> "VLaurent":
        if isinstance(s, int):
            s = LaurentPoly.from_int(s)
        if s.is_zero():
            return VLaurent.zero(n)
        return VLaurent({tuple([0] * n): s}, n=n)

    @staticmethod
    def v_pow(k: int, exp: int = 1, n: int | None = None) -> "VLaurent":
        """Return v_k^exp, where k is 0-based."""
        if n is None:
            n = k + 1
        if not (0 <= k < n):
            raise ValueError(f"v index {k} out of range for n {n}")
        e = [0] * n
        e[k] = int(exp)
        return VLaurent({tuple(e): LaurentPoly.one()}, n=n)

    @staticmethod
    def monomial(v_exps: Iterable[int],
                 coeff: "LaurentPoly | int" = 1,
                 n: int | None = None) -> "VLaurent":
        e = tuple(int(x) for x in v_exps)
        if n is None:
            n = len(e)
        if len(e) != n:
            raise ValueError("monomial: v_exps length != n")
        if isinstance(coeff, int):
            coeff = LaurentPoly.from_int(coeff)
        if coeff.is_zero():
            return VLaurent.zero(n)
        return VLaurent({e: coeff}, n=n)

    # --- accessors ---

    @property
    def n(self) -> int:
        return self._n

    def is_zero(self) -> bool:
        return not self._terms

    def items(self):
        return self._terms.items()

    def coeff(self, v_exp: Iterable[int]) -> LaurentPoly:
        key = tuple(int(x) for x in v_exp)
        return self._terms.get(key, LaurentPoly.zero())

    # --- arithmetic ---

    def _check_n(self, other: "VLaurent") -> None:
        if self._n != other._n:
            raise ValueError(f"VLaurent n mismatch: {self._n} vs {other._n}")

    def _coerce(self, other) -> "VLaurent | None":
        if isinstance(other, VLaurent):
            self._check_n(other)
            return other
        if isinstance(other, LaurentPoly):
            return VLaurent.from_scalar(other, n=self._n)
        if isinstance(other, int):
            return VLaurent.from_scalar(other, n=self._n)
        return None

    def __neg__(self) -> "VLaurent":
        return VLaurent._from_clean_terms(
            {e: -c for e, c in self._terms.items()}, self._n)

    def __add__(self, other) -> "VLaurent":
        o = self._coerce(other)
        if o is None:
            return NotImplemented
        out = dict(self._terms)
        for e, c in o._terms.items():
            nc = out.get(e, LaurentPoly.zero()) + c
            if nc.is_zero():
                out.pop(e, None)
            else:
                out[e] = nc
        return VLaurent._from_clean_terms(out, self._n)

    def __radd__(self, other):
        return self.__add__(other)

    def __sub__(self, other) -> "VLaurent":
        o = self._coerce(other)
        if o is None:
            return NotImplemented
        return self + (-o)

    def __rsub__(self, other):
        o = self._coerce(other)
        if o is None:
            return NotImplemented
        return o - self

    def __mul__(self, other) -> "VLaurent":
        o = self._coerce(other)
        if o is None:
            return NotImplemented
        if self.is_zero() or o.is_zero():
            return VLaurent.zero(self._n)
        a = self._terms
        b = o._terms
        n = self._n
        la = len(a)
        lb = len(b)
        # Fast-path: monomial * polynomial.
        if la == 1:
            e1, c1 = next(iter(a.items()))
            out = {}
            for e2, c2 in b.items():
                e = tuple(e1[i] + e2[i] for i in range(n))
                nc = c1 * c2
                if not nc.is_zero():
                    out[e] = nc
            return VLaurent._from_clean_terms(out, n)
        if lb == 1:
            e2, c2 = next(iter(b.items()))
            out = {}
            for e1, c1 in a.items():
                e = tuple(e1[i] + e2[i] for i in range(n))
                nc = c1 * c2
                if not nc.is_zero():
                    out[e] = nc
            return VLaurent._from_clean_terms(out, n)
        # General polynomial multiplication.  Accumulate the q-Laurent
        # coefficients into RAW {q-exp: coeff} dicts keyed by v-exponent,
        # convolving c1*c2 directly into the accumulator.  This skips the
        # per-product LaurentPoly object + the per-collision LaurentPoly
        # __add__ that dominated this path; one LaurentPoly is built per
        # output v-monomial at the end.
        out_raw: dict[tuple[int, ...], dict[int, int]] = {}
        for e1, c1 in a.items():
            a1 = c1._coeffs
            for e2, c2 in b.items():
                e = tuple(x + y for x, y in zip(e1, e2))
                d = out_raw.get(e)
                if d is None:
                    out_raw[e] = d = {}
                for q1, k1 in a1.items():
                    for q2, k2 in c2._coeffs.items():
                        qe = q1 + q2
                        nv = d.get(qe, 0) + k1 * k2
                        if nv:
                            d[qe] = nv
                        else:
                            d.pop(qe, None)
        out: dict[tuple[int, ...], LaurentPoly] = {}
        for e, d in out_raw.items():
            if d:
                out[e] = LaurentPoly._from_clean_dict(d)
        return VLaurent._from_clean_terms(out, n)

    __rmul__ = __mul__

    def __pow__(self, k: int) -> "VLaurent":
        if k < 0:
            raise ValueError("VLaurent: negative powers require inversion")
        if k == 0:
            return VLaurent.one(self._n)
        out = VLaurent.one(self._n)
        base = self
        while k > 0:
            if k & 1:
                out = out * base
            k >>= 1
            if k:
                base = base * base
        return out

    def q_shift(self, c: Iterable[int]) -> "VLaurent":
        """Substitute v_k -> q^{2 c_k} v_k.

        On a monomial ``lp(q) * prod v_k^{e_k}`` this produces
        ``lp(q) * q^{2 sum_k c_k e_k} * prod v_k^{e_k}``.
        """
        c = tuple(int(x) for x in c)
        if len(c) != self._n:
            raise ValueError(f"q_shift vector length {len(c)} != n {self._n}")
        out: dict[tuple[int, ...], LaurentPoly] = {}
        for e, lp in self._terms.items():
            shift = 2 * sum(ck * ek for ck, ek in zip(c, e))
            if shift == 0:
                out[e] = lp
            else:
                out[e] = LaurentPoly({k + shift: v for k, v in lp._coeffs.items()})
        return VLaurent(out, n=self._n)

    def __eq__(self, other) -> bool:
        if isinstance(other, (int, LaurentPoly)):
            return self == VLaurent._coerce_static(other, self._n)
        if not isinstance(other, VLaurent):
            return NotImplemented
        return self._n == other._n and self._terms == other._terms

    @staticmethod
    def _coerce_static(x, n: int) -> "VLaurent":
        if isinstance(x, VLaurent):
            if x._n != n:
                raise ValueError("VLaurent n mismatch")
            return x
        if isinstance(x, LaurentPoly):
            return VLaurent.from_scalar(x, n)
        if isinstance(x, int):
            return VLaurent.from_scalar(x, n)
        raise TypeError(f"cannot coerce {type(x).__name__} to VLaurent")

    def __hash__(self):
        return hash((self._n,
                     tuple(sorted((e, tuple(sorted(lp._coeffs.items())))
                                  for e, lp in self._terms.items()))))

    def __repr__(self) -> str:
        if not self._terms:
            return "0"
        parts = []
        for e in sorted(self._terms):
            lp = self._terms[e]
            vsym = _v_monomial_str(e)
            if vsym == "":
                parts.append(repr(lp))
            else:
                # stringify coefficient
                lp_str = repr(lp)
                if lp_str == "1":
                    parts.append(vsym)
                elif lp_str == "-1":
                    parts.append("-" + vsym)
                elif " + " in lp_str or " - " in lp_str:
                    parts.append(f"({lp_str})*{vsym}")
                else:
                    parts.append(f"{lp_str}*{vsym}")
        s = parts[0]
        for p in parts[1:]:
            if p.startswith("-"):
                s += " - " + p[1:]
            else:
                s += " + " + p
        return s


def _v_monomial_str(e: tuple[int, ...]) -> str:
    if all(x == 0 for x in e):
        return ""
    parts = []
    for k, x in enumerate(e):
        if x == 0:
            continue
        if x == 1:
            parts.append(f"v_{k}")
        else:
            parts.append(f"v_{k}^{x}")
    return "*".join(parts)


# ============================================================================
# VRational: VLaurent  /  product of (v_i - q^m v_j)
# ============================================================================


DenKey = tuple[int, int, int]   # (i, j, m) with i < j, meaning (v_i - q^m v_j)


@lru_cache(maxsize=None)
def _root_factor(i: int, j: int, m: int, n: int) -> VLaurent:
    """Return ``v_i - q^m v_j`` as a VLaurent.

    Memoized: a pure function of `(i, j, m, n)` returning an immutable
    `VLaurent` (a value object — never mutated in place).  Built thousands
    of times per L-build via `_den_product`; the cache removes that cost
    for every AbeKAlgebra."""
    if not (0 <= i < n and 0 <= j < n):
        raise ValueError(f"root factor indices ({i},{j}) out of range for n={n}")
    if i == j:
        raise ValueError("root factor requires i != j")
    e_i = [0] * n
    e_i[i] = 1
    e_j = [0] * n
    e_j[j] = 1
    return VLaurent({tuple(e_i): LaurentPoly.one(),
                     tuple(e_j): -LaurentPoly.q(m)}, n=n)


@lru_cache(maxsize=None)
def _sq_factor(i: int, m: int, n: int) -> VLaurent:
    """Return the single-variable square factor ``1 - q^m v_i^2`` as a VLaurent.
    Memoized (immutable value object; see `_root_factor`).

    These arise when a two-variable root factor ``(v_i - q^m v_j)`` is
    restricted to the SU(2) sublocus ``v_j = v_i^{-1}``:
    ``(v_i - q^m v_i^{-1}) = -q^m v_i^{-1} (1 - q^{-m} v_i^2)``.  In the
    rank-1 (``n = 1``) abelianized chart these are the *only* possible
    denominator factors (root factors require ``i != j``, hence ``n >= 2``).
    """
    if not (0 <= i < n):
        raise ValueError(f"sq factor index {i} out of range for n={n}")
    e0 = tuple([0] * n)
    e2 = [0] * n
    e2[i] = 2
    return VLaurent({e0: LaurentPoly.one(),
                     tuple(e2): -LaurentPoly.q(m)}, n=n)


def _vlaurent_sq_quotient(num: VLaurent, i: int, m: int):
    """Divide ``num`` by ``1 - q^m v_i^2`` (ascending in ``v_i``).

    Returns ``(quotient, remainder_is_zero)``.  Uses the recurrence from
    ``num = (1 - q^m v_i^2) * Q``: matching the coefficient of ``v_i^k``
    gives ``a_k = q_k - q^m q_{k-2}``, i.e. ``q_k = a_k + q^m q_{k-2}``
    solved ascending from ``k_min``.  Exact iff the top two would-be
    quotient coefficients vanish (the degree-<2 remainder).
    """
    if num.is_zero():
        return VLaurent.zero(num.n), True
    n_v = num.n
    # group num by v_i exponent: c_k is a VLaurent (v_i absent) in same ambient
    groups: dict[int, dict[tuple[int, ...], LaurentPoly]] = {}
    for e, c in num.items():
        k = e[i]
        e_no_i = tuple(0 if t == i else e[t] for t in range(n_v))
        groups.setdefault(k, {})
        d = groups[k]
        if e_no_i in d:
            d[e_no_i] = d[e_no_i] + c
            if d[e_no_i].is_zero():
                del d[e_no_i]
        else:
            d[e_no_i] = c
    a = {k: VLaurent(td, n=n_v) for k, td in groups.items() if td}
    if not a:
        return VLaurent.zero(n_v), True
    k_min, k_max = min(a), max(a)
    qm = LaurentPoly({m: 1})
    qfac = VLaurent.from_scalar(qm, n=n_v)
    q: dict[int, VLaurent] = {}
    for k in range(k_min, k_max + 1):
        term = a.get(k, VLaurent.zero(n_v))
        prev = q.get(k - 2)
        if prev is not None:
            term = term + qfac * prev
        if not term.is_zero():
            q[k] = term
    # remainder lives in the top two coefficients k_max, k_max-1
    rem_zero = (q.get(k_max) is None) and (q.get(k_max - 1) is None)
    quo_terms: dict[tuple[int, ...], LaurentPoly] = {}
    for k in range(k_min, k_max - 1):
        qk = q.get(k)
        if qk is None:
            continue
        for e_no_i, c in qk.items():
            ne = list(e_no_i)
            ne[i] = k
            quo_terms[tuple(ne)] = c
    return VLaurent(quo_terms, n=n_v), rem_zero


class VRational:
    """Rational function in v_0, ..., v_{n-1} over Z[q^+/-1].

    Numerator: ``VLaurent``.
    Denominator: multiset of elementary factors ``(v_i - q^m v_j)``, keyed
    by ``(i, j, m)`` with ``i < j`` canonical.  The multiplicity is the
    power of that factor in the denominator.

    Equality is tested by cross-multiplying numerators after normalizing
    the two denominators to a common refinement.  No Gruebner-style
    canonicalization of the numerator is done -- the numerator is kept as
    a bare ``VLaurent`` and reduced only by the denominator factors that
    divide it (on demand, via ``simplify`` -- not implemented yet).

    Closure under ``q_shift`` (the u-action):
      (v_i - q^m v_j)  ->  q^{2 c_i} (v_i - q^{m + 2(c_j - c_i)} v_j).
    The q-monomial ``q^{2 c_i}`` is factored into the numerator.
    """

    __slots__ = ("_num", "_den", "_sq", "_n", "_simplified_cache")

    def __init__(self,
                 num: VLaurent,
                 den: Mapping[DenKey, int] | None = None,
                 n: int | None = None,
                 sq: Mapping[tuple[int, int], int] | None = None):
        if n is None:
            n = num.n
        if num.n != n:
            raise ValueError(f"VRational num.n {num.n} != n {n}")
        self._n = int(n)
        self._num = num
        # Cache for self.simplify() result (lazy init to None).
        self._simplified_cache = None
        # single-variable square-factor denominators (1 - q^m v_i^2), keyed (i, m)
        self._sq: dict[tuple[int, int], int] = {}
        if sq:
            for k, mult in sq.items():
                ii, mm = int(k[0]), int(k[1])
                if not (0 <= ii < n):
                    raise ValueError(f"sq key {k} index out of range")
                self._sq[(ii, mm)] = self._sq.get((ii, mm), 0) + int(mult)
            self._sq = {k: v for k, v in self._sq.items() if v != 0}
        self._den: dict[DenKey, int] = {}
        if den:
            for k, mult in den.items():
                i, j, m = int(k[0]), int(k[1]), int(k[2])
                if not (0 <= i < n and 0 <= j < n):
                    raise ValueError(f"denom key {k} indices out of range")
                if i == j:
                    raise ValueError(f"denom key {k} has i == j")
                # canonicalize i < j:
                if i > j:
                    # Canonicalize (v_i - q^m v_j) with i > j.
                    # Identity:  (v_i - q^m v_j) = -q^m (v_j - q^{-m} v_i),
                    # so  1/(v_i - q^m v_j) = -q^{-m} / (v_j - q^{-m} v_i).
                    # Per multiplicity the numerator picks up (-q^{-m})^mult.
                    new_k = (j, i, -m)
                    factor = VLaurent.from_scalar(
                        LaurentPoly({-m: -1}), n=n) ** mult
                    self._num = self._num * factor
                    self._den[new_k] = self._den.get(new_k, 0) + int(mult)
                else:
                    self._den[(i, j, m)] = self._den.get((i, j, m), 0) + int(mult)
        # drop zero mult entries
        self._den = {k: v for k, v in self._den.items() if v != 0}

    # --- constructors ---

    @staticmethod
    def zero(n: int) -> "VRational":
        return VRational(VLaurent.zero(n), None, n=n)

    @staticmethod
    def one(n: int) -> "VRational":
        return VRational(VLaurent.one(n), None, n=n)

    @staticmethod
    def from_vlaurent(v: VLaurent) -> "VRational":
        return VRational(v, None, n=v.n)

    @staticmethod
    def from_scalar(s: "LaurentPoly | int", n: int) -> "VRational":
        return VRational(VLaurent.from_scalar(s, n), None, n=n)

    @staticmethod
    def root_inv(i: int, j: int, m: int, n: int) -> "VRational":
        """Return ``1 / (v_i - q^m v_j)``."""
        return VRational(VLaurent.one(n), {(i, j, m): 1}, n=n)

    @staticmethod
    def sq_inv(i: int, m: int, n: int) -> "VRational":
        """Return ``1 / (1 - q^m v_i^2)`` (single-variable square factor)."""
        return VRational(VLaurent.one(n), None, n=n, sq={(i, m): 1})

    # --- accessors ---

    @property
    def n(self) -> int:
        return self._n

    @property
    def num(self) -> VLaurent:
        return self._num

    @property
    def den(self) -> dict[DenKey, int]:
        return dict(self._den)

    def is_zero(self) -> bool:
        return self._num.is_zero()

    @property
    def sq(self) -> dict[tuple[int, int], int]:
        return dict(self._sq)

    def _den_as_vlaurent(self) -> VLaurent:
        out = VLaurent.one(self._n)
        for (i, j, m), mult in self._den.items():
            out = out * _root_factor_pow(i, j, m, self._n, mult)
        for (i, m), mult in self._sq.items():
            out = out * _sq_factor_pow(i, m, self._n, mult)
        return out

    def simplify(self) -> "VRational":
        """Strip common  ``(v_i - q^m v_j)``  factors between numerator
        and denominator.

        For each denom factor  (i, j, m)  with multiplicity  ``mult``,
        repeatedly test whether the numerator vanishes after substituting
        ``v_i -> q^m v_j``  (i.e., the factor divides the numerator).  If
        yes, perform the division and decrement the multiplicity.

        Returns a NEW  VRational  (does not mutate self).

        Cached per-instance: simplify is idempotent and called multiple
        times on the same VRational during decompose loops.  Hot path
        in profiling.
        """
        if self._simplified_cache is not None:
            return self._simplified_cache
        result = self._simplify_impl()
        # The simplified form is itself already simplified — point its
        # cache at itself to short-circuit repeated calls.
        result._simplified_cache = result
        self._simplified_cache = result
        return result

    def _simplify_impl(self) -> "VRational":
        num = self._num
        den = dict(self._den)
        sq = dict(self._sq)
        # Distinct denominator factors (v_i-q^m v_j) (i<j) are COPRIME — distinct
        # roots — so dividing one out never changes another's divisibility.  Hence
        # each factor can be cancelled to its full multiplicity in a SINGLE pass,
        # with no restart (the old `break`-and-restart re-tested every factor
        # O(#factors) times per division; this is O(#factors + #divisions)).
        for (i, j, m), mult in list(den.items()):
            while mult > 0 and _vlaurent_divisible_by_root(num, i, j, m):
                num = _vlaurent_divide_by_root(num, i, j, m)
                mult -= 1
            if mult <= 0:
                del den[(i, j, m)]
            elif mult != self._den[(i, j, m)]:
                den[(i, j, m)] = mult
        for (i, m), mult in list(sq.items()):
            while mult > 0:
                quo, rem_zero = _vlaurent_sq_quotient(num, i, m)
                if not rem_zero:
                    break
                num = quo
                mult -= 1
            if mult <= 0:
                del sq[(i, m)]
            elif mult != self._sq[(i, m)]:
                sq[(i, m)] = mult
        return VRational(num, den, n=self._n, sq=sq)

    # --- arithmetic ---

    def _coerce(self, other) -> "VRational | None":
        if isinstance(other, VRational):
            if other._n != self._n:
                raise ValueError("VRational n mismatch")
            return other
        if isinstance(other, VLaurent):
            if other.n != self._n:
                raise ValueError("VRational/VLaurent n mismatch")
            return VRational.from_vlaurent(other)
        if isinstance(other, LaurentPoly):
            return VRational.from_scalar(other, self._n)
        if isinstance(other, int):
            return VRational.from_scalar(other, self._n)
        return None

    def __neg__(self) -> "VRational":
        return VRational(-self._num, self._den, n=self._n, sq=self._sq)

    def __add__(self, other) -> "VRational":
        o = self._coerce(other)
        if o is None:
            return NotImplemented
        # common denominator = union of multisets (take max multiplicity)
        all_keys = set(self._den) | set(o._den)
        common: dict[DenKey, int] = {}
        a_extra: dict[DenKey, int] = {}
        b_extra: dict[DenKey, int] = {}
        for k in all_keys:
            sa = self._den.get(k, 0)
            sb = o._den.get(k, 0)
            m = max(sa, sb)
            common[k] = m
            if m - sa > 0:
                a_extra[k] = m - sa
            if m - sb > 0:
                b_extra[k] = m - sb
        # same common-denominator logic for the single-variable sq factors
        all_sq = set(self._sq) | set(o._sq)
        common_sq: dict[tuple[int, int], int] = {}
        a_sq_extra: dict[tuple[int, int], int] = {}
        b_sq_extra: dict[tuple[int, int], int] = {}
        for k in all_sq:
            sa = self._sq.get(k, 0)
            sb = o._sq.get(k, 0)
            mm = max(sa, sb)
            common_sq[k] = mm
            if mm - sa > 0:
                a_sq_extra[k] = mm - sa
            if mm - sb > 0:
                b_sq_extra[k] = mm - sb
        # multiply numerators by the extra factors (root + sq)
        new_a = (self._num * _den_product(a_extra, self._n)
                 * _sq_product(a_sq_extra, self._n))
        new_b = (o._num * _den_product(b_extra, self._n)
                 * _sq_product(b_sq_extra, self._n))
        return VRational(new_a + new_b, common, n=self._n, sq=common_sq)

    __radd__ = __add__

    def __sub__(self, other) -> "VRational":
        o = self._coerce(other)
        if o is None:
            return NotImplemented
        return self + (-o)

    def __rsub__(self, other) -> "VRational":
        o = self._coerce(other)
        if o is None:
            return NotImplemented
        return o - self

    def __mul__(self, other) -> "VRational":
        o = self._coerce(other)
        if o is None:
            return NotImplemented
        out_den: dict[DenKey, int] = {}
        for k, m in self._den.items():
            out_den[k] = out_den.get(k, 0) + m
        for k, m in o._den.items():
            out_den[k] = out_den.get(k, 0) + m
        out_sq: dict[tuple[int, int], int] = {}
        for k, m in self._sq.items():
            out_sq[k] = out_sq.get(k, 0) + m
        for k, m in o._sq.items():
            out_sq[k] = out_sq.get(k, 0) + m
        return VRational(self._num * o._num, out_den, n=self._n, sq=out_sq)

    __rmul__ = __mul__

    def __pow__(self, k: int) -> "VRational":
        if k < 0:
            raise ValueError("VRational: negative powers require inversion")
        if k == 0:
            return VRational.one(self._n)
        out = VRational.one(self._n)
        base = self
        while k > 0:
            if k & 1:
                out = out * base
            k >>= 1
            if k:
                base = base * base
        return out

    def invert_root_factor(self, i: int, j: int, m: int) -> "VRational":
        """Multiply self by ``1 / (v_i - q^m v_j)``."""
        return self * VRational.root_inv(i, j, m, self._n)

    def q_shift(self, c: Iterable[int]) -> "VRational":
        """Substitute v_k -> q^{2 c_k} v_k.

        A denom factor ``(v_i - q^m v_j)`` becomes
        ``q^{2 c_i} (v_i - q^{m + 2(c_j - c_i)} v_j)``.
        We divide the new numerator by the extracted ``q^{2 c_i}`` per each
        factor (i.e. for each denom factor times its multiplicity).
        """
        c = tuple(int(x) for x in c)
        if len(c) != self._n:
            raise ValueError(f"q_shift vector length != n ({len(c)} vs {self._n})")
        # shift numerator
        new_num = self._num.q_shift(c)
        # rebuild denominator with shifted m's and track extracted q-power
        new_den: dict[DenKey, int] = {}
        extracted_q_exp = 0  # total q-power pulled out of denom (into denom ->
                             # i.e. shows up as 1 / q^{2 c_i * mult}, which we
                             # must MULTIPLY new_num by the inverse = q^{-2 c_i * mult}).
        for (i, j, m), mult in self._den.items():
            new_m = m + 2 * (c[j] - c[i])
            # denom factor contributes q^{2 c_i} that lives in the denominator,
            # i.e. we must divide the numerator by q^{2 c_i}:
            extracted_q_exp -= 2 * c[i] * mult
            # canonicalize i < j (i is always < j by construction but new_m changed)
            new_den[(i, j, new_m)] = new_den.get((i, j, new_m), 0) + mult
        if extracted_q_exp != 0:
            new_num = new_num * VLaurent.from_scalar(
                LaurentPoly({extracted_q_exp: 1}), n=self._n)
        # sq factor (1 - q^m v_i^2) -> (1 - q^{m + 4 c_i} v_i^2); constant
        # term 1 is unchanged, so no q-power is extracted.
        new_sq: dict[tuple[int, int], int] = {}
        for (i, m), mult in self._sq.items():
            new_sq[(i, m + 4 * c[i])] = new_sq.get((i, m + 4 * c[i]), 0) + mult
        return VRational(new_num, new_den, n=self._n, sq=new_sq)

    def __eq__(self, other) -> bool:
        if isinstance(other, (int, LaurentPoly, VLaurent)):
            return self == self._coerce(other)
        if not isinstance(other, VRational):
            return NotImplemented
        if self._n != other._n:
            return False
        # cross-multiply: a.num * b.den == b.num * a.den
        return (self._num * other._den_as_vlaurent()
                == other._num * self._den_as_vlaurent())

    def __hash__(self):
        # Not canonical; hash is legal but not compatible with mathematical
        # equality.  Use with care.
        return hash((self._n, hash(self._num),
                     tuple(sorted(self._den.items())),
                     tuple(sorted(self._sq.items()))))

    def __repr__(self) -> str:
        if self.is_zero():
            return "0"
        num_str = repr(self._num)
        if not self._den and not self._sq:
            return num_str
        den_parts = []
        for (i, j, m), mult in sorted(self._den.items()):
            base = f"(v_{i} - q^{m}*v_{j})" if m != 0 else f"(v_{i} - v_{j})"
            if mult == 1:
                den_parts.append(base)
            else:
                den_parts.append(f"{base}^{mult}")
        for (i, m), mult in sorted(self._sq.items()):
            base = f"(1 - q^{m}*v_{i}^2)" if m != 0 else f"(1 - v_{i}^2)"
            den_parts.append(base if mult == 1 else f"{base}^{mult}")
        den_str = "*".join(den_parts)
        if " + " in num_str or " - " in num_str:
            num_str = f"({num_str})"
        return f"{num_str} / ({den_str})"


def _vlaurent_divisible_by_root(num: VLaurent, i: int, j: int, m: int) -> bool:
    """Test whether  ``(v_i - q^m v_j)``  divides ``num`` exactly.

    Substitution test:  set  v_i = q^m v_j  in  num ;  the factor divides
    iff the result is identically zero.

    For Laurent polynomials this is exact (substitute term-by-term and
    accumulate; check the resulting VLaurent is zero).
    """
    if num.is_zero():
        return True
    # Build the substituted num.  For each monomial  c · prod v_k^{e_k}  in
    # num, replace  v_i^{e_i}  with  (q^m v_j)^{e_i} = q^{m e_i} v_j^{e_i} .
    #
    # We only need to know whether the substituted polynomial vanishes, so we
    # accumulate into RAW q-coefficient dicts ({v-key -> {q-exp: coeff}}) and
    # skip LaurentPoly object creation / __add__ / __mul__ entirely -- this is
    # the single hottest path in the URQTorus multiply.  q^{m e_i} is a pure
    # exponent shift (s = m * e_i) on the q-keys.
    out: dict[tuple[int, ...], dict[int, int]] = {}
    for e, c in num.items():
        e_i = e[i]
        new_e = list(e)
        new_e[i] = 0
        new_e[j] = new_e[j] + e_i
        key = tuple(new_e)
        s = m * e_i
        d = out.get(key)
        if d is None:
            out[key] = {qe + s: qc for qe, qc in c._coeffs.items()}
        else:
            for qe, qc in c._coeffs.items():
                k2 = qe + s
                nv = d.get(k2, 0) + qc
                if nv:
                    d[k2] = nv
                else:
                    d.pop(k2, None)
    return all(not d for d in out.values())


def _vlaurent_divide_by_root(num: VLaurent, i: int, j: int, m: int) -> VLaurent:
    """Exact division  num / (v_i - q^m v_j) .

    Synthetic-division style:  treat  num  as a Laurent polynomial in  v_i ,
    write  num(v_i) = sum_k v_i^k · c_k(v_others)  (a finite sum since
    Laurent polynomials have finite support), and use the recurrence

        Q(v_i)  =  sum_{k}  v_i^k · q_k         with
        q_{n-1} = c_n,    q_{k-1} = c_k + (q^m v_j) · q_k    for k = n-1, ..., 1
        R       = c_0 + (q^m v_j) · q_0

    such that  num(v_i) = (v_i - q^m v_j) · Q(v_i) + R .  When the
    factor divides exactly,  R = 0 .
    """
    if num.is_zero():
        return num
    n_v = num.n
    # Group num by v_i exponent.  For each k, c_k is a VLaurent in (n_v - 1) v's
    # (with v_i absent) but expressed in the same n_v ambient.
    groups: dict[int, dict[tuple[int, ...], LaurentPoly]] = {}
    for e, c in num.items():
        k = e[i]
        e_no_i = tuple(0 if t == i else e[t] for t in range(n_v))
        if k not in groups:
            groups[k] = {}
        if e_no_i in groups[k]:
            groups[k][e_no_i] = groups[k][e_no_i] + c
            if groups[k][e_no_i].is_zero():
                del groups[k][e_no_i]
        else:
            groups[k][e_no_i] = c
    # Convert groups[k] (dict) to VLaurent objects.
    c_dict: dict[int, VLaurent] = {}
    for k, term_dict in groups.items():
        c_dict[k] = VLaurent(term_dict, n=n_v)

    if not c_dict:
        return VLaurent.zero(n_v)

    # Sort the v_i powers from high to low for the synthetic division.
    k_min = min(c_dict)
    k_max = max(c_dict)
    # alpha = q^m * v_j (a VLaurent monomial)
    e_alpha = [0] * n_v
    e_alpha[j] = 1
    alpha = VLaurent({tuple(e_alpha): LaurentPoly({m: 1})}, n=n_v)
    # Build Q = sum  v_i^k · q_k  for k = k_min, k_min+1, ..., k_max - 1.
    q_dict: dict[int, VLaurent] = {}
    # q_{k_max - 1} = c_{k_max}
    q_dict[k_max - 1] = c_dict.get(k_max, VLaurent.zero(n_v))
    # q_{k - 1} = c_k + alpha · q_k
    for k in range(k_max - 1, k_min, -1):
        q_dict[k - 1] = c_dict.get(k, VLaurent.zero(n_v)) + alpha * q_dict.get(k, VLaurent.zero(n_v))
    # Build the quotient as a VLaurent in all v's:
    out: dict[tuple[int, ...], LaurentPoly] = {}
    for k, q_k in q_dict.items():
        for e_no_i, c in q_k.items():
            new_e = list(e_no_i)
            new_e[i] = k
            key = tuple(new_e)
            if key in out:
                out[key] = out[key] + c
                if out[key].is_zero():
                    del out[key]
            else:
                out[key] = c
    return VLaurent(out, n=n_v)


@lru_cache(maxsize=None)
def _root_factor_pow(i: int, j: int, m: int, n: int, mult: int) -> VLaurent:
    """`(v_i - q^m v_j)^mult`, memoized (the repeated-squaring power is
    otherwise rebuilt on every `_den_product` call)."""
    return _root_factor(i, j, m, n) ** mult


@lru_cache(maxsize=None)
def _sq_factor_pow(i: int, m: int, n: int, mult: int) -> VLaurent:
    return _sq_factor(i, m, n) ** mult


@lru_cache(maxsize=8192)
def _den_product_keyed(den_items: tuple, n: int) -> VLaurent:
    out = VLaurent.one(n)
    for (i, j, m), mult in den_items:
        if mult > 0:
            out = out * _root_factor_pow(i, j, m, n, mult)
    return out


def _den_product(den: Mapping[DenKey, int], n: int) -> VLaurent:
    """Build the VLaurent ``prod (v_i - q^m v_j)^mult`` (memoized on the
    denominator multiset — saves the repeated factor multiplication that
    recurs across an L-build's atoms)."""
    return _den_product_keyed(
        tuple(sorted((k, v) for k, v in den.items() if v > 0)), n)


def _sq_product(sq: Mapping[tuple[int, int], int], n: int) -> VLaurent:
    """Build the VLaurent ``prod (1 - q^m v_i^2)^mult``."""
    out = VLaurent.one(n)
    for (i, m), mult in sq.items():
        if mult <= 0:
            continue
        out = out * _sq_factor_pow(i, m, n, mult)
    return out


# ============================================================================
# DOp: normal-ordered difference operators  sum_a f_a(v) u^a
# ============================================================================


UKey = tuple[int, ...]    # u-exponent tuple in Z^n


class DOp:
    """Normal-ordered difference operator over ``VRational``.

    A finite sum ``sum_a  f_a(v) * u^a`` stored as
    ``dict[tuple[int, ...], VRational]``: u-exponent tuple -> coefficient.

    The commutation relation ``u_k * v_l = q^{2 delta_{kl}} * v_l * u_k``
    drives multiplication: ``(f u^a)(g u^b) = f * g.q_shift(a) * u^{a+b}``.

    Flavour structure: ``n`` is the total v-dimension; ``n_gauge`` (default
    ``n``) is the number of gauge colors.  Slots ``[n_gauge, n)`` are
    flavour: no ``u_k`` operators allowed there.  ``DOp.u(k)`` raises if
    ``k >= n_gauge``.  Internally u-exponent tuples remain length ``n``,
    but with zeros in the flavour slots; the ``n_gauge`` invariant is
    enforced at construction.

    Convenience constructor ``DOp.mu(r)`` returns ``v_{n_gauge + r}`` --
    the r-th flavour fugacity (0-indexed).

    Left-ordered by convention: coefficient times ``u^a``.
    """

    __slots__ = ("_terms", "_n", "_n_gauge")

    def __init__(self,
                 terms: Mapping[UKey, VRational] | None = None,
                 n: int = 1,
                 n_gauge: int | None = None):
        if n < 0:
            raise ValueError("DOp needs n >= 0")
        if n_gauge is None:
            n_gauge = n
        if not (0 <= n_gauge <= n):
            raise ValueError(f"DOp needs 0 <= n_gauge <= n, got {n_gauge}/{n}")
        self._n = int(n)
        self._n_gauge = int(n_gauge)
        self._terms: dict[UKey, VRational] = {}
        if terms:
            for a, coef in terms.items():
                if len(a) != n:
                    raise ValueError(
                        f"u-exponent {a} length {len(a)} != n {n}"
                    )
                if not isinstance(coef, VRational):
                    raise TypeError(
                        f"DOp coeff at {a} must be VRational, got {type(coef).__name__}"
                    )
                if coef.n != n:
                    raise ValueError(
                        f"DOp coeff at {a} has n {coef.n} != {n}"
                    )
                a_tup = tuple(int(x) for x in a)
                # enforce: zero in flavour slots
                for k in range(self._n_gauge, self._n):
                    if a_tup[k] != 0:
                        raise ValueError(
                            f"DOp u-exponent {a_tup} has nonzero flavour slot {k}"
                            f" (n_gauge={self._n_gauge}, n={self._n})"
                        )
                # enforce: no flavour indices in any coefficient's denominator
                for (i, j, _m) in coef.den:
                    if i >= self._n_gauge or j >= self._n_gauge:
                        raise ValueError(
                            f"DOp coeff at u-exp {a_tup} has flavour index in"
                            f" denom factor (v_{i} - q^.. v_{j});"
                            f" n_gauge = {self._n_gauge}"
                        )
                if not coef.is_zero():
                    self._terms[a_tup] = coef

    # --- constructors ---

    @staticmethod
    def zero(n: int, n_gauge: int | None = None) -> "DOp":
        return DOp(None, n=n, n_gauge=n_gauge)

    @staticmethod
    def one(n: int, n_gauge: int | None = None) -> "DOp":
        return DOp({tuple([0] * n): VRational.one(n)}, n=n, n_gauge=n_gauge)

    @staticmethod
    def from_scalar(s: "VRational | VLaurent | LaurentPoly | int",
                    n: int, n_gauge: int | None = None) -> "DOp":
        if isinstance(s, VRational):
            if s.n != n:
                raise ValueError("DOp.from_scalar n mismatch")
            if s.is_zero():
                return DOp.zero(n, n_gauge=n_gauge)
            return DOp({tuple([0] * n): s}, n=n, n_gauge=n_gauge)
        if isinstance(s, VLaurent):
            if s.n != n:
                raise ValueError("DOp.from_scalar n mismatch")
            return DOp.from_scalar(VRational.from_vlaurent(s),
                                   n=n, n_gauge=n_gauge)
        if isinstance(s, LaurentPoly):
            return DOp.from_scalar(VRational.from_scalar(s, n),
                                   n=n, n_gauge=n_gauge)
        if isinstance(s, int):
            return DOp.from_scalar(VRational.from_scalar(s, n),
                                   n=n, n_gauge=n_gauge)
        raise TypeError(f"cannot coerce {type(s).__name__} to DOp")

    @staticmethod
    def u(k: int, exp: int = 1, n: int | None = None,
          n_gauge: int | None = None) -> "DOp":
        """Return ``u_k^exp`` as a DOp.  ``k`` must be a gauge color."""
        if n is None:
            n = k + 1
        if n_gauge is None:
            n_gauge = n
        if not (0 <= k < n_gauge):
            raise ValueError(
                f"u index {k} out of range for n_gauge {n_gauge} (n={n})"
            )
        a = [0] * n
        a[k] = int(exp)
        return DOp({tuple(a): VRational.one(n)}, n=n, n_gauge=n_gauge)

    @staticmethod
    def v(k: int, exp: int = 1, n: int | None = None,
          n_gauge: int | None = None) -> "DOp":
        """Return ``v_k^exp`` as a DOp.  ``k`` may be gauge or flavour."""
        if n is None:
            n = k + 1
        return DOp.from_scalar(
            VRational.from_vlaurent(VLaurent.v_pow(k, exp=exp, n=n)),
            n=n, n_gauge=n_gauge,
        )

    @staticmethod
    def mu(r: int, exp: int = 1, n: int | None = None,
           n_gauge: int | None = None) -> "DOp":
        """Return ``mu_r^exp`` (= v_{n_gauge + r}) as a DOp.  r is 0-indexed.

        Either both ``n`` and ``n_gauge`` must be given, or only ``n_gauge``
        in which case ``n`` defaults to ``n_gauge + r + 1``.
        """
        if n_gauge is None:
            raise ValueError("DOp.mu: must specify n_gauge")
        if n is None:
            n = n_gauge + r + 1
        if not (0 <= r < n - n_gauge):
            raise ValueError(
                f"mu index {r} out of range; n_flavour = n - n_gauge = {n - n_gauge}"
            )
        return DOp.v(n_gauge + r, exp=exp, n=n, n_gauge=n_gauge)

    # --- accessors ---

    @property
    def n(self) -> int:
        return self._n

    @property
    def n_gauge(self) -> int:
        return self._n_gauge

    @property
    def n_flavour(self) -> int:
        return self._n - self._n_gauge

    def is_zero(self) -> bool:
        return not self._terms

    def items(self):
        return self._terms.items()

    def coeff(self, u_exp: Iterable[int]) -> VRational:
        key = tuple(int(x) for x in u_exp)
        return self._terms.get(key, VRational.zero(self._n))

    # --- arithmetic ---

    def _coerce(self, other) -> "DOp | None":
        if isinstance(other, DOp):
            if other._n != self._n:
                raise ValueError(f"DOp n mismatch ({other._n} vs {self._n})")
            if other._n_gauge != self._n_gauge:
                raise ValueError(
                    f"DOp n_gauge mismatch ({other._n_gauge} vs {self._n_gauge})"
                )
            return other
        if isinstance(other, (VRational, VLaurent, LaurentPoly, int)):
            return DOp.from_scalar(other, n=self._n, n_gauge=self._n_gauge)
        return None

    def __neg__(self) -> "DOp":
        return DOp({a: -c for a, c in self._terms.items()},
                   n=self._n, n_gauge=self._n_gauge)

    def __add__(self, other) -> "DOp":
        o = self._coerce(other)
        if o is None:
            return NotImplemented
        out = dict(self._terms)
        for a, c in o._terms.items():
            nc = out.get(a, VRational.zero(self._n)) + c
            if nc.is_zero():
                out.pop(a, None)
            else:
                out[a] = nc
        return DOp(out, n=self._n, n_gauge=self._n_gauge)

    __radd__ = __add__

    def __sub__(self, other) -> "DOp":
        o = self._coerce(other)
        if o is None:
            return NotImplemented
        return self + (-o)

    def __rsub__(self, other):
        o = self._coerce(other)
        if o is None:
            return NotImplemented
        return o - self

    def __mul__(self, other) -> "DOp":
        o = self._coerce(other)
        if o is None:
            return NotImplemented
        out: dict[UKey, VRational] = {}
        for a, fa in self._terms.items():
            for b, gb in o._terms.items():
                # (fa u^a)(gb u^b) = fa * gb.q_shift(a) * u^{a+b}
                ab = tuple(a[k] + b[k] for k in range(self._n))
                coef = fa * gb.q_shift(a)
                nc = out.get(ab, VRational.zero(self._n)) + coef
                if nc.is_zero():
                    out.pop(ab, None)
                else:
                    out[ab] = nc
        return DOp(out, n=self._n, n_gauge=self._n_gauge)

    __rmul__ = __mul__

    def mul_dom_only(self, other) -> "DOp":
        """Like `__mul__`, but the result only keeps **dominant-chamber**
        u-keys (sorted descending).  Used for Weyl-symmetric inputs
        where the consumer only needs the dom slice — saves the
        VRational sums and storage for non-dom output keys (factor
        |W| = N!)."""
        o = self._coerce(other)
        if o is None:
            return NotImplemented
        out: dict[UKey, VRational] = {}
        n = self._n
        for a, fa in self._terms.items():
            for b, gb in o._terms.items():
                ab = tuple(a[k] + b[k] for k in range(n))
                # Skip non-dom output keys early.
                is_dom = True
                for k in range(n - 1):
                    if ab[k] < ab[k + 1]:
                        is_dom = False
                        break
                if not is_dom:
                    continue
                coef = fa * gb.q_shift(a)
                nc = out.get(ab, VRational.zero(n)) + coef
                if nc.is_zero():
                    out.pop(ab, None)
                else:
                    out[ab] = nc
        return DOp(out, n=n, n_gauge=self._n_gauge)

    def __pow__(self, k: int) -> "DOp":
        if k < 0:
            raise ValueError("DOp: negative powers not supported")
        if k == 0:
            return DOp.one(self._n, n_gauge=self._n_gauge)
        out = DOp.one(self._n, n_gauge=self._n_gauge)
        base = self
        while k > 0:
            if k & 1:
                out = out * base
            k >>= 1
            if k:
                base = base * base
        return out

    def weyl_permute(self, perm: Iterable[int]) -> "DOp":
        """Apply a permutation of the colors 0..n-1 to u and v simultaneously.

        ``perm`` is a tuple p of length n with {p_0, ..., p_{n-1}} = {0, ..., n-1}.
        The result replaces variable k by variable perm[k] (i.e. sends v_k to
        v_{perm[k]} and u_k to u_{perm[k]}).

        For mixed gauge/flavour DOps (n_gauge < n) the permutation must
        preserve the gauge/flavour partition: gauge slots map to gauge slots,
        flavour slots map to flavour slots.  Otherwise raises ValueError.
        """
        p = tuple(int(x) for x in perm)
        if sorted(p) != list(range(self._n)):
            raise ValueError(f"not a permutation of 0..{self._n - 1}: {p}")
        if self._n_gauge < self._n:
            for k in range(self._n_gauge):
                if p[k] >= self._n_gauge:
                    raise ValueError(
                        f"weyl_permute: gauge slot {k} maps to flavour slot "
                        f"{p[k]}; permutation must preserve "
                        f"gauge/flavour partition (n_gauge={self._n_gauge})"
                    )
            for k in range(self._n_gauge, self._n):
                if p[k] < self._n_gauge:
                    raise ValueError(
                        f"weyl_permute: flavour slot {k} maps to gauge slot "
                        f"{p[k]}; permutation must preserve "
                        f"gauge/flavour partition (n_gauge={self._n_gauge})"
                    )
        out: dict[UKey, VRational] = {}
        for a, coef in self._terms.items():
            new_a = [0] * self._n
            for k in range(self._n):
                new_a[p[k]] = a[k]
            new_coef = _vrat_permute(coef, p)
            key = tuple(new_a)
            nc = out.get(key, VRational.zero(self._n)) + new_coef
            if nc.is_zero():
                out.pop(key, None)
            else:
                out[key] = nc
        return DOp(out, n=self._n, n_gauge=self._n_gauge)

    def __eq__(self, other) -> bool:
        if isinstance(other, (int, LaurentPoly, VLaurent, VRational)):
            return self == self._coerce(other)
        if not isinstance(other, DOp):
            return NotImplemented
        if self._n != other._n or self._n_gauge != other._n_gauge:
            return False
        keys = set(self._terms) | set(other._terms)
        for a in keys:
            if self._terms.get(a, VRational.zero(self._n)) \
               != other._terms.get(a, VRational.zero(self._n)):
                return False
        return True

    def __hash__(self):
        return hash((self._n, self._n_gauge,
                     tuple(sorted((a, hash(c)) for a, c in self._terms.items()))))

    def __repr__(self) -> str:
        if not self._terms:
            return "0"
        parts = []
        for a in sorted(self._terms):
            coef = self._terms[a]
            u_sym = _u_monomial_str(a)
            coef_str = repr(coef)
            if u_sym == "":
                parts.append(coef_str)
            elif coef_str == "1":
                parts.append(u_sym)
            elif coef_str == "-1":
                parts.append("-" + u_sym)
            else:
                if " + " in coef_str or " - " in coef_str:
                    coef_str = f"({coef_str})"
                parts.append(f"{coef_str}*{u_sym}")
        return " + ".join(parts)


def _u_monomial_str(a: tuple[int, ...]) -> str:
    if all(x == 0 for x in a):
        return ""
    parts = []
    for k, x in enumerate(a):
        if x == 0:
            continue
        if x == 1:
            parts.append(f"u_{k}")
        elif x == -1:
            parts.append(f"u_{k}^{-1}")
        else:
            parts.append(f"u_{k}^{x}")
    return "*".join(parts)


def _vlaurent_permute(v: VLaurent, perm: tuple[int, ...]) -> VLaurent:
    """Apply permutation of color indices to a VLaurent."""
    out: dict[tuple[int, ...], LaurentPoly] = {}
    for e, c in v.items():
        new_e = [0] * v.n
        for k in range(v.n):
            new_e[perm[k]] = e[k]
        out[tuple(new_e)] = c
    return VLaurent(out, n=v.n)


def _vrat_permute(r: VRational, perm: tuple[int, ...]) -> VRational:
    """Apply permutation of color indices to a VRational."""
    new_num = _vlaurent_permute(r.num, perm)
    new_den: dict[DenKey, int] = {}
    for (i, j, m), mult in r.den.items():
        ni, nj = perm[i], perm[j]
        if ni < nj:
            key = (ni, nj, m)
            new_den[key] = new_den.get(key, 0) + mult
        elif ni > nj:
            # (v_{ni} - q^m v_{nj}) = -q^m (v_{nj} - q^{-m} v_{ni}),
            # so 1/(v_{ni} - q^m v_{nj}) = -q^{-m} / (v_{nj} - q^{-m} v_{ni}).
            # The numerator picks up (-q^{-m})^mult per permuted factor.
            key = (nj, ni, -m)
            new_den[key] = new_den.get(key, 0) + mult
            factor = VLaurent.from_scalar(LaurentPoly({-m: -1}), n=r.n) ** mult
            new_num = new_num * factor
        else:
            raise AssertionError("permutation sent distinct indices to same")
    return VRational(new_num, new_den, n=r.n)



def u_order(w: tuple):
    """Total order on chart u-exponent tuples; `min` picks the most-anti-
    dominant Weyl-orbit representative, `max` the most-dominant
    (lexicographic on the raw tuple — the convention the pure-U(N)
    engine is certified with).  Relocated from the AbeKAlgebra tier
    (Plan 30 T2 / D4: no DOp-frame utilities on the contract)."""
    return tuple(w)


def simplify_dop(F: "DOp") -> "DOp":
    """Simplify each `VRational` coefficient in `F` (cancel root / sq
    factors that divide the numerator).  Relocated from the AbeKAlgebra
    tier (Plan 30 T2 / D4)."""
    return DOp({u: c.simplify() for u, c in F._terms.items()},
               n=F._n, n_gauge=F._n_gauge)
