"""Generator script: build the cluster cone graph for E_6, dump the
resulting FiniteConeData ingredients (mult_gens, cones, cocycle,
cross_product) as Python literals into a standalone
``finite_e6_kalg.py`` -- no dependency on FiniteBPSKAlgebra at runtime.

Run once:  PYTHONPATH=. python generate_finite_e6_kalg.py
"""
from __future__ import annotations
import sys
sys.path.insert(0, ".")

from cluster_cone_builder import FiniteBPSKAlgebra
from finite_e6_kalg import E6_BPS_PAIRING, E6_BPS_NODE_CHARGES


def _laurent_repr(coeff) -> str:
    """LaurentPoly → Python literal."""
    return f"LaurentPoly({dict(coeff._coeffs)!r})"


def main(out_path: str = "finite_e6_kalg.py"):
    print("Building E_6 cluster cone graph...")
    A = FiniteBPSKAlgebra(
        pairing=E6_BPS_PAIRING, node_charges=E6_BPS_NODE_CHARGES,
        verify="off",
    )
    A.populate_specs()
    X = A.to_cone_kalgebra()
    cd = X.cone_data()

    mult_gens_lattice = tuple(X._ray_idx_to_gamma)
    cones = tuple(tuple(sorted(c)) for c in cd.cones())
    # Cocycle table by iterating cones and pairs
    cocycle_table: dict = {}
    for cone in cd.cones():
        cone_ids = sorted(cone)
        for i in cone_ids:
            for j in cone_ids:
                if i != j:
                    cocycle_table[(i, j)] = cd.cocycle(i, j)
    # cross-product table: keys (i, j), values list of (LaurentPoly, word)
    n = len(mult_gens_lattice)
    cross_table: dict = {}
    for i in range(n):
        for j in range(n):
            xp = cd.cross_product(i, j)
            cross_table[(i, j)] = [
                (dict(c._coeffs), tuple(w)) for c, w in xp
            ]

    # ρ-permutation on mult-gens (for ρ-orbit-organised trace dispatch).
    rho_perm = dict(X._rho_perm)

    # Per-ρ²-orbit-rep trace data (6 reps for E_6).  Stored as
    # {ray_idx: (spec_tuple, label_at_home)} so trace can be computed
    # via s_gamma_habiro at runtime.
    ray_trace_info: dict = {}
    # ρ²-orbits on rays
    rho2_perm = {i: rho_perm.get(rho_perm.get(i, i), i) for i in range(n)}
    seen: set = set()
    rho2_orbits = []
    for i in range(n):
        if i in seen:
            continue
        orb = []
        j = i
        for _ in range(n + 1):
            if j in seen:
                break
            orb.append(j)
            seen.add(j)
            j = rho2_perm.get(j, j)
        rho2_orbits.append(orb)
    # For each orbit, store data for the minimum-index rep
    for orb in rho2_orbits:
        rep = min(orb)
        from cluster_cone_builder import find_cone, _mu_g_step
        ray = mult_gens_lattice[rep]
        cid = find_cone(
            A._fbk_clusters, A._fbk_edges, tuple(ray),
            sec_basis=A._fbk_sec_basis, L_basis=A._fbk_L_basis,
        )
        cluster = A._fbk_clusters[cid]
        if cluster.spec is None:
            # No spec for this cluster -- skip; trace_residual falls back
            continue
        spec = [tuple(s) for s in cluster.spec]
        label_at_home = tuple(ray)
        for g in cluster.path_from_root:
            label_at_home = _mu_g_step(
                label_at_home, g, A._fbk_pairing,
            )
        ray_trace_info[rep] = {
            "orbit": orb,
            "spec": spec,
            "label_at_home": label_at_home,
        }

    # Pairing (for kmat computation in trace)
    pairing = [list(row) for row in E6_BPS_PAIRING]

    print(f"  mult_gens: {n}")
    print(f"  cones:     {len(cones)}")
    print(f"  cocycles:  {len(cocycle_table)}")
    print(f"  cross:     {len(cross_table)} entries")
    print(f"  ρ²-orbits: {len(rho2_orbits)} (sizes {sorted(len(o) for o in rho2_orbits)})")

    # Emit Python literal data file
    print(f"Writing {out_path} ...")
    with open(out_path, "w") as f:
        f.write('"""``FiniteE6KAlgebra`` -- standalone E_6 K-algebra.\n\n')
        f.write("Data inlined from the cluster cone graph of the E_6 BPS quiver\n")
        f.write("(generated by ``generate_finite_e6_kalg.py``).  No runtime\n")
        f.write("dependency on ``FiniteBPSKAlgebra``.\n")
        f.write('"""\n')
        f.write("from __future__ import annotations\n\n")
        f.write("from cone_data import FiniteConeData, CrossProductTerm\n")
        f.write("from cone_kalgebra import ConeKAlgebra\n")
        f.write("from laurent_poly import LaurentPoly\n")
        f.write("from zplus_ring import TrivialZPlusRing\n\n")
        f.write(f"E6_BPS_PAIRING = {pairing!r}\n")
        f.write(f"E6_BPS_NODE_CHARGES = {list(E6_BPS_NODE_CHARGES)!r}\n\n")
        f.write(f"# Mult-gens (cluster variables) as lattice rays.\n")
        f.write(f"E6_MULT_GENS_LATTICE = {mult_gens_lattice!r}\n\n")
        f.write(f"# Cones: tuples of mult-gen indices (sorted).\n")
        f.write(f"E6_CONES = {cones!r}\n\n")
        f.write(f"# Cocycle table: (i, j) -> integer q-power.\n")
        f.write(f"E6_COCYCLE_TABLE = {cocycle_table!r}\n\n")
        f.write(f"# ρ-permutation on mult-gens.\n")
        f.write(f"E6_RHO_PERM = {rho_perm!r}\n\n")
        # cross-product dump
        f.write(f"# Cross-product table: (i, j) -> list of (q-coeff-dict, word).\n")
        f.write("E6_CROSS_TABLE = {\n")
        for (i, j), terms in cross_table.items():
            f.write(f"    ({i}, {j}): {terms!r},\n")
        f.write("}\n\n")
        # Trace data
        f.write(f"# Per-ρ²-orbit trace data for the 6 elementary traces.\n")
        f.write(f"E6_RAY_TRACE_INFO = {ray_trace_info!r}\n\n")

        # Class definition
        f.write('class FiniteE6KAlgebra(ConeKAlgebra):\n')
        f.write('    """E_6 K-algebra ``A_𝖖(E_6)``, with all data inlined."""\n\n')
        f.write('    _R = TrivialZPlusRing()\n\n')
        f.write('    def __init__(self):\n')
        f.write('        # Build FiniteConeData from inlined literals.\n')
        f.write('        self._cone_data = _ExportedE6ConeData()\n\n')
        f.write('    def coefficient_ring(self):\n')
        f.write('        return self._R\n\n')
        f.write('    def identity(self):\n')
        f.write('        return ()\n\n')
        f.write('    def cone_data(self):\n')
        f.write('        return self._cone_data\n\n')
        f.write('    def rho(self, label):\n')
        f.write('        return tuple(sorted(\n')
        f.write('            (E6_RHO_PERM.get(i, i), p) for (i, p) in label\n')
        f.write('        ))\n\n')
        f.write('    def rho_inverse(self, label):\n')
        f.write('        rho_inv = {v: k for k, v in E6_RHO_PERM.items()}\n')
        f.write('        return tuple(sorted(\n')
        f.write('            (rho_inv.get(i, i), p) for (i, p) in label\n')
        f.write('        ))\n\n')
        f.write('    def _label_section_decompose(self, label):\n')
        f.write('        return label, self.coefficient_ring().one()\n\n')
        f.write('    def _trace_residual(self, seed_label, K):\n')
        f.write('        from nahm_local import s_gamma_habiro\n')
        f.write('        from bps_kalgebra import BPSKAlgebra\n')
        f.write('        if not seed_label:\n')
        f.write('            # Tr(1): build temp BPSKAlgebra at root\n')
        f.write('            A = BPSKAlgebra(\n')
        f.write('                pairing=E6_BPS_PAIRING,\n')
        f.write('                node_charges=E6_BPS_NODE_CHARGES,\n')
        f.write('                verify="off",\n')
        f.write('            )\n')
        f.write('            return A.trace(A.identity(), K=K)\n')
        f.write('        ray_idx = seed_label[0][0]\n')
        f.write('        # Look up ρ²-orbit canonical rep\n')
        f.write('        for rep_idx, info in E6_RAY_TRACE_INFO.items():\n')
        f.write('            if ray_idx in info["orbit"]:\n')
        f.write('                # Build temp BPSKAlgebra with home spec\n')
        f.write('                A = BPSKAlgebra(\n')
        f.write('                    pairing=E6_BPS_PAIRING,\n')
        f.write('                    node_charges=list(E6_MULT_GENS_LATTICE[:6]),  # not great\n')
        f.write('                    spec=info["spec"],\n')
        f.write('                    verify="off",\n')
        f.write('                )\n')
        f.write('                return A.trace(info["label_at_home"], K=K)\n')
        f.write('        raise ValueError(\n')
        f.write('            f"_trace_residual: unknown seed {seed_label!r}"\n')
        f.write('        )\n\n')
        # FiniteConeData class
        f.write('class _ExportedE6ConeData(FiniteConeData):\n')
        f.write('    def mult_gens(self):\n')
        f.write('        return tuple(range(len(E6_MULT_GENS_LATTICE)))\n\n')
        f.write('    def cones(self):\n')
        f.write('        return tuple(frozenset(c) for c in E6_CONES)\n\n')
        f.write('    def q_commute(self, g, h):\n')
        f.write('        return g == h or (g, h) in E6_COCYCLE_TABLE\n\n')
        f.write('    def cocycle(self, g, h):\n')
        f.write('        if g == h: return 0\n')
        f.write('        return E6_COCYCLE_TABLE[(g, h)]\n\n')
        f.write('    def cross_product(self, g, h):\n')
        f.write('        terms = E6_CROSS_TABLE.get((g, h), [])\n')
        f.write('        return tuple((LaurentPoly(c), w) for c, w in terms)\n\n')
        f.write('    def to_cone_label(self, native_label):\n')
        f.write('        gens = frozenset(i for i, p in native_label if p != 0)\n')
        f.write('        powers = {i: p for i, p in native_label if p != 0}\n')
        f.write('        return (gens, powers)\n\n')
        f.write('    def from_cone_label(self, gens, powers):\n')
        f.write('        return tuple(sorted((i, powers[i]) for i in gens))\n\n')
        f.write('    def cycle_period_bound(self):\n')
        f.write('        return len(E6_MULT_GENS_LATTICE)\n\n')

    print(f"  written.")


if __name__ == "__main__":
    main(out_path="finite_e6_kalg_standalone.py")
