"""Pure SU(2) BPS K-algebra with abstract (m, e) labelling.

`pSU2KAlgebra` exposes the canonical basis of the pure SU(2) BPS K-algebra
(simply-connected gauge group, NOT SO(3)) indexed by abstract labels:

  * m ∈ ℤ_{≥0}   — dominant cocharacter in P^∨ ≅ ℤ
  * e ∈ ℤ        — electric weight in P ≅ ℤ
  * Wilson floor: m = 0, e ≥ 0 dominant.

Boundary cases:

    T_m   =  D(m, 0)              ('t Hooft tower at pure magnetic charge m)
    W_e   =  D(0, e),   e ≥ 0     (Wilson tower at electric weight e)

The fundamental Wilson is `W_1 = D(0, 1)` (= the χ_{1/2} character of
the SU(2) fundamental rep; tropical chord charge γ = (0, −1)).

The H tower
-----------
The full line-operator algebra is generated by the W_e Wilson tower
and the **H tower** of 't Hooft-like operators:

    H_n := D(1, n)     for all n ∈ ℤ

with H_0 = T_1 and H_n_tropical = γ_SU2(1, n) realising a 3-piecewise
path in tropical chord-charge space:

    n ≤ 0:  H_n_tropical = (1, n)        (magnetic-positive branch)
    n = 1:  H_1_tropical = (0, 1)        (unique m=0 element)
    n ≥ 2:  H_n_tropical = (-1, 4-n)     (magnetic-negative branch)

ρ action: ρ(H_n) = H_{n - 4}, i.e. the standard e-shift ρ(D(m, e)) =
D(m, e − 4m) restricted to H_n shifts n by −4.

Fundamental Wilson recursion:

    W_1 · H_n  =  q · H_{n-1} + q^{-1} · H_{n+1} + ε_n
    H_n · W_1  =  q^{-1} · H_{n-1} + q · H_{n+1} + ε_n

with ε_n = 𝟙 (vacuum correction) at n = ±1 and zero otherwise.

This is a thin wrapper over ``pure_ade_lattice.pure_ade_kalgebra([("A", 1)])``,
which serves as the computational engine.  The (m, e) ↔ chart γ bijection
is the closed-form 3-piece piecewise-linear map ``gamma_SU2`` /
``label_SU2`` from ``abstract_label.py``.

Verified empirically:

  * ``ρ(D_{m, e}) = D_{m, e − 4m}``         (chart-aut tested in tests)
  * ``T_{m'} · D_{m, e} = q^{m' e} D_{m+m', e} + (lower filtration)``
  * ``W_w · D_{m, e} = Σ_ε q^{−m ε} D_{m, e+ε} + …`` over weights ε of V_w

⚠ Lattice convention note: an earlier version of this docstring said
"m ∈ P^∨ = Q (root lattice)".  That equates coweight with root, which is
the SO(3) = PSU(2) = SU(2)/ℤ_2 normalisation, not SU(2).  The algebra
implemented here IS pure SU(2): it admits the fundamental Wilson W_1 at
weight e=1 and odd-e 't Hoofts H_n at e=1, 3, 5, ... — neither of which
exist in pure SO(3).  See ``bps_kalgebra.BPSKAlgebra(pairing=[[0,1],
[-1,0]], node_charges=[(1,0), (-1,2)])`` for the corresponding
BPSKAlgebra realisation in tropical chord-charge coordinates.

Open questions (left as TODOs):

  * The single-node mutation algebra automorphism: empirically the lattice
    action alone does not give a clean (m, e) → (m, e − 2m) shift; the
    full automorphism additionally pulls back F-elements through the new
    chart.  A working ``mu0_label`` is left for future work.
  * The general ADE generalization of `gamma_SU2`: the SU(2) case has 3
    chambers (south / diagonal / west) with one fold; for higher rank the
    chamber count is at least |W| (Weyl group order) and the fold
    structure is multi-dimensional.
"""

from __future__ import annotations

import os, sys

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from kalgebra import KAlgebra, Element
from zplus_ring import TrivialZPlusRing
from abstract_label import gamma_SU2, label_SU2
from pure_ade_lattice import pure_ade_kalgebra


# Type aliases for clarity
MELabel = tuple   # (m, e) with m ∈ ℤ_{≥0}, e ∈ ℤ
ChartGamma = tuple  # (v, e_chart) ∈ ℤ²


class pSU2KAlgebra(KAlgebra):
    """Pure SU(2) BPS K-algebra with canonical basis indexed by (m, e).

    Construction:
        A = pSU2KAlgebra()
        A.D(1, 0)               # T_1 label
        A.W(2)                  # Wilson at weight 2
        A.multiply(A.T(2), A.W(1))   # structure constants

    The label space is `{(m, e) : m ∈ Z_{>=0}, e ∈ Z}` minus the Wilson
    anti-dominant tail (m=0, e<0), which doesn't carry an independent
    canonical element.  ``label_SU2`` performs the inverse map γ → (m, e).
    """

    def __init__(self):
        # Computational engine: BPSKAlgebra in chart coords.
        self._chart = pure_ade_kalgebra([("A", 1)])
        # Reuse the chart algebra's ring instance so coefficients propagate
        # without rebuild.
        self._R = self._chart.coefficient_ring()
        # Pre-cache identity as the Wilson at weight 0.
        self._identity = (0, 0)

    # --- chart ↔ abstract translation ---

    def gamma(self, label: MELabel) -> ChartGamma:
        """Forward map: abstract (m, e) → chart γ = (v, e_chart)."""
        return gamma_SU2(label[0], label[1])

    def label(self, gamma: ChartGamma) -> MELabel:
        """Inverse map: chart γ → abstract (m, e)."""
        return label_SU2(gamma)

    # --- KAlgebra primitives ---

    def coefficient_ring(self):
        """Pure SU(2) is unflavoured; trivial Z+-ring (shared with chart)."""
        return self._R

    def identity(self) -> MELabel:
        return self._identity

    def multiply(self, a: MELabel, b: MELabel) -> Element:
        """Structure constants in (m, e) labels.

        Translates the inputs to chart γ, multiplies in the chart algebra,
        and re-labels each output γ to (m, e).  Output γ's that are not
        reachable as canonical D_{m, e} (should not occur for valid inputs)
        are dropped with a warning.
        """
        ga = self.gamma(a)
        gb = self.gamma(b)
        chart_prod = self._chart.multiply(ga, gb)
        out: dict[MELabel, "RLaurent"] = {}
        for g, c in chart_prod.terms.items():
            try:
                lab = self.label(g)
            except ValueError:
                # Outside canonical chambers — should not happen for
                # canonical-basis multiplication; report and drop.
                continue
            if lab in out:
                out[lab] = out[lab] + c
            else:
                out[lab] = c
        return Element({l: c for l, c in out.items() if not c.is_zero()})

    def rho(self, a: MELabel) -> MELabel:
        """ρ(D_{m, e}) = D_{m, e − 4m}.  Verified empirically."""
        m, e = a
        return (m, e - 4 * m)

    def rho_inverse(self, a: MELabel) -> MELabel:
        m, e = a
        return (m, e + 4 * m)

    # Unflavoured (Trivial coefficient ring): the flavour-lift coordinate and
    # _label_section_decompose are inherited from the KAlgebra universal
    # trivial-flavour treatment — section = label, irrep = χ₀ (the author's ruling
    # 2026-06-19: trivial own-label section, not the old chart-coordinate one).

    def trace(self, a: MELabel, K: int = 20):
        """Delegate to the chart algebra's trace."""
        return self._chart.trace(self.gamma(a), K=K)

    # --- convenience constructors ---

    def T(self, m: int) -> MELabel:
        """Pure t'Hooft label at cocharacter m.  T_m = D(m, 0)."""
        if not isinstance(m, int) or m < 0:
            raise ValueError(f"T_m requires m ∈ Z_{{≥0}}, got {m}")
        return (m, 0)

    def W(self, e: int) -> MELabel:
        """Pure Wilson label at dominant weight e.  W_e = D(0, e)."""
        if not isinstance(e, int) or e < 0:
            raise ValueError(f"W_e requires e ∈ Z_{{≥0}} (dominant), got {e}")
        return (0, e)

    def D(self, m: int, e: int) -> MELabel:
        """General canonical-basis label D_{m, e}."""
        # Validate via gamma_SU2 (raises if out of domain).
        gamma_SU2(m, e)
        return (m, e)

