"""`PureGAbeKAlgebra` — pure gauge theory at a **general** `G` as an `AbeKAlgebra`
on the group-general `WRQTorus`.

One class over a `RootDatum` (user ruling, 2026-07-27), covering the groups the
type-A machinery cannot reach.  The pure-U(N) keystone leans on a luxury most
groups lack: every fundamental coweight is **minuscule**, so dressed minuscule
monopoles are closed-form bar-invariant generators and every canonical is a
polynomial in them.  Outside type A that fails — `Spin(5)`/`B₂` has **no
minuscule cocharacter at all** (`wrq_torus.is_minuscule` agrees), so *every*
monopole bubbles and product-and-peel has nothing to start from.

How a chart is built — constructive first, licensed solve last
--------------------------------------------------------------
`chart(m, e)` dispatches through routes in order of decreasing preference, and
records which one fired in `route(label)`:

| route | build | discipline |
|---|---|---|
| `wilson` | `m = 0`: the full-group character `χ_e` | constructive |
| `minuscule` | `m` minuscule ⇒ the leading orbit **is** the canonical | constructive |
| `cone` | `wrq_torus.build_canonical` (cone / dressed-cone monomial) | constructive |
| `peel` | product-and-peel from a lower-canonical seed + `kl_bar_correct` | constructive |
| `star` | `star_bubbling.solve_canonical` — (★) + bar + `O(𝖖)` | **licensed solve** |

Routes 1–4 are the constructive-build rule as it applies wherever it reaches;
route 5 is the licensed exception.  **The `AbeKAlgebra` tier itself still exposes
no solve entry point** — the license lives in `star_bubbling`, which applies the
whole guard before returning anything, and this class additionally asserts the
W2 half of the KL acceptance via `certify_canonical`.

Why the solve is legitimate here (user ruling, 2026-07-27)
---------------------------------------------------------
Not because a solve is harmless, but because (★) supplies the post-hoc guard
whose absence motivates the ban.  The axiom, in the user's words: **Neumann
lines are generated by `L_{0,e'}|N]`, so the difference operator associated to
`L_{m,e}` must act on the space of symmetric functions.**  Since
`L_{0,e}|N] = χ_e` exactly (measured 27/27 across SU(2)/SU(3)/PSU(3)/Spin(5)/G₂),
`span{L_{0,e'}|N]} = Λ = R(G)` — where `R(G)` is the rep ring of **this form**:
for `G = G̃/H` only the centre-neutral `e` are admitted, so
`Λ_H = R(G̃)^H = R(G̃/H)`, a proper submodule of the cover's (at PSU(3), 4 of 10
dominant weights).  Using the cover's `R(G̃)` there is the D24 bug.  So

    (★)  ⟺  `L` preserves the Neumann module `A·|N] = R(G)`.

That is a membership condition on the presentation, *not* a pairing within the
span — which is exactly why orthonormality and the M-test cannot substitute for
it (they pass on off-span garbage; (★) rejects the
the design notes failure mode 23/23).  Full statement and the
measured evidence: `star_bubbling`'s module docstring and
the design notes §2/§5.

Labels and conventions
----------------------
`(m, e)` with `m` a **cochar-dominant** cocharacter and `e` a **Levi-dominant**
weight — the lower-Kapustin `(m, λ)` convention in the `WRQTorus` frame, matching
`wrq_torus.leading_orbit`.  `fold(m, e)` transports an arbitrary label there
(Weyl-transport `m` to the dominant chamber carrying `e` along, then take the
`W_m`-orbit's Levi-dominant representative).  Pure gauge ⇒ unflavoured,
`R = TrivialZPlusRing`.

Honest scope, stated rather than papered over
---------------------------------------------
* **rank is not capped** — the old dim-3 facet-normal ceiling is gone
  (`tropical_support` now decides membership by the dominance order), and the
  rank-4 SU(5) solve is certified against the `PureSUNKAlgebra(5)` oracle.  What
  bounds the reach is **cost**, not correctness.
* **odd `⟨Σ⁺, m⟩` IS carried, since ruling D31 (2026-07-29)** — the earlier
  "theorem" that it is not is retracted.  The atom phase `S(m) = −⟨ρ,m⟩` is a
  half-integer exactly there, so the *materialised* monomial
  `M(m) ∝ (−𝖖)^{⟨ρ,m⟩}` — the square root of the measure — cannot be written; but
  the algebra needs only the **coboundary** `δS̃`, and that is an integer even then
  (`π = ⟨Σ⁺,·⟩ mod 2` is Weyl-invariant *and* additive, so the halves cancel).
  `wrq_torus.cocycle_R` restores the honest phase through
  `(−𝖖)^{δ(S_honest − S_used)}`, and `RootDatum.rho_sign_exp` is the derived
  `atom_phase_doubled(k) + ⟨Σ⁺,k⟩` — identically `0` on the honest phase.  No
  `𝖖^{1/2}` and no `i` anywhere, so the standing no-`Z[𝖖^{±1/2}]`-chart ruling
  (the design notes C3) is untouched and was never what blocked this.
  Certified at SO(3) against the `PureSO3KAlgebra` BPS oracle — `H_0`
  bar-invariant, `H_0² = L_{(2,0)}` exactly, `I(H_0,H_0) = 1 − 𝖖² + 𝖖⁴ + 𝖖⁶ − 𝖖⁸`,
  `I(H_0, L_{(2,0)}) = 0` — and measured orthonormal at the non-simply-laced
  SO(5) (`m=(1,0)`, `⟨Σ⁺,m⟩=3`; `m=(2,1)`, `=7`) and SO(7).  The whole even sector
  is bit-identical.  Battery: a probe in the source repository.
  `abe_representable` now answers `True` everywhere; `π` keeps its meaning as
  *"is `ρ` a character of this form"*, a statement about the private `ψ`.
  `src/gn/pure_so3.py`'s standard-`Z²` BPS chart remains a correct
  independent presentation — it is the oracle that certified the fix — and is
  **not** a rescaling of this tier (ruling D22).
  The two `−𝖖^{−1}`-flavoured claims that used to sit here are withdrawn: the
  `ε`-corrected and honest phases do **not** give termwise-identical `I` in
  general (that coincidence was the `sgn % 2` half-integer branch silently
  returning `+1`), and `I` is bilinear, so a rescale moves it by `c²`, not
  `c·bar(c)`.
* the **ρ-twist sign** at a general datum is **derived**, not fitted
: `root_datum.weyl_vector_rho_sign` = `⟨Σ⁺, k⟩`, a **character of
  `π₁(G)`**.  It is trivial on any coroot-lattice datum — which is why the
  earlier constant `+1` worked there and why that "fit" was really a theorem —
  and nontrivial on `so_n(5)`/`so_n(7)`, i.e. exactly the sectors this tier
  honest-fails on anyway.
* **`rho(a)` is cheap, but building `chart(ρ(a))` need not be.**  The label map
  is read off the chart (`chart(a).rho().well_formed()`) with no rebuild, but the
  image label can be much more expensive to *construct* than the original —
  measured at G₂, `ρ(L_{(2,3),(−1,1)}) = L_{(2,3),(−13,1)}`, whose Wilson anchor
  is far larger.  Check ρ round-trips at the **element** level
  (`chart(a).rho().rho_inverse() == chart(a)`) rather than by rebuilding the
  image chart.

Global form — the 4d notion
---------------------------
The global form is **a sublattice of the Kapustin `(m, e)` labels** (user,
2026-07-27), not a choice of cocharacter lattice; the latter reading is the one
appropriate to 3d.  It is carried by `lines` (a `global_form.LineLattice`), and
`chart` honest-fails on a label outside it.  The default is the simply connected
form, which is what the repo's coordinates realise.  A form's charge data is **a
lattice and its dual** (user, 2026-07-29;
`global_form.LineLattice.verify_lattices_are_dual`):
`SU(2) = (Q^∨, P)` = (dual to weights, weights), `SO(3) = (P^∨, Q)` = (dual to
roots, roots).  Written in SU(2)'s coordinates that index-2 inclusion `Q ⊂ P` reads
"magnetic doubled, electric halved", which is why SU(2)'s fundamental Wilson is
**not** an SO(3) line — a description of the two lattices, not a rescaling.  Mutual
locality is integrality of the Dirac pairing `⟨m,e'⟩ − ⟨m',e⟩`.  G₂ has trivial
centre, hence exactly one global form.

Every label of a non-simply-connected form is therefore an ordinary integral point
of its own lattice; what varies is which presentation carries it.  Since ruling D31 this
one carries **all** of them, odd `⟨Σ⁺,m⟩` included; `abe_representable` answers
`True` everywhere and `lines.legal_lines(labels)` no longer removes anything on
that ground.

At `su_2()` this class reproduces `PureSU2KAlgebra` and at `su_n(3)`
`PureSUNKAlgebra`, label by label — those stay as the certified anchors (they are
fully native/constructive there, which is *stronger* than a solve, so where they
reach they remain the reference).
"""
from __future__ import annotations

import itertools
import math
import os
import sys
from fractions import Fraction

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)
_ROOT = os.path.dirname(_HERE)
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from abe_kalgebra import AbeKAlgebra, TorusShape
from kalgebra import Element, Label
from laurent_poly import LaurentPoly
from zplus_ring import ZPlusRing, TrivialZPlusRing, RPowerSeries
import star_bubbling as SB
from wrq_torus import (WRQTorus, wilson, minuscule, build_canonical,
                       decompose as _wrq_decompose, is_minuscule,
                       peel_to_canonical, kl_bar_correct, _levi_data,
                       _cochar_height)


__all__ = ["PureGAbeKAlgebra", "cone_generators", "NonPointedMonoid"]


class NonPointedMonoid(Exception):
    """The dominant cocharacter monoid contains a line, so it has no finite
    generating set as a monoid.

    Raised by `cone_generators` when `G` has a **central torus**: the central
    direction is a *group* (`det^{±1}` and its cousins), not a monoid, and
    belongs with the invertible generators — which is exactly how
    `PureUNKAlgebra` already carries `det`.  The exception reports the
    lineality space so a caller can split
    `M(G) = (pointed part) ⊕ (central lattice)` (the design notes F1)."""

    def __init__(self, datum, lineality):
        self.lineality = tuple(tuple(v) for v in lineality)
        super().__init__(
            f"{datum.name}: the dominant cocharacter monoid is not pointed — "
            f"it contains the {len(self.lineality)}-dimensional central "
            f"direction {self.lineality}.  A central torus needs INVERTIBLE "
            f"generators (det^{{±1}}), not cone generators; see "
            f"the design notes F1.")


# --------------------------------------------------------------------------
#  Cone generators — the Hilbert basis of the dominant cocharacter monoid
# --------------------------------------------------------------------------
def _rref_inverse(rows):
    """Exact inverse of a square rational matrix (Gauss–Jordan over
    `Fraction`).  Pure Python — the repo takes no external dependencies, and
    exactness matters: the ray directions are read off this and then scaled to
    primitive lattice vectors, so a float would corrupt the primitivity."""
    n = len(rows)
    A = [[Fraction(x) for x in row] + [Fraction(int(i == j)) for j in range(n)]
         for i, row in enumerate(rows)]
    for c in range(n):
        piv = next((r for r in range(c, n) if A[r][c] != 0), None)
        if piv is None:
            return None                        # singular ⇒ non-pointed cone
        A[c], A[piv] = A[piv], A[c]
        inv = Fraction(1) / A[c][c]
        A[c] = [x * inv for x in A[c]]
        for r in range(n):
            if r != c and A[r][c] != 0:
                f = A[r][c]
                A[r] = [x - f * y for x, y in zip(A[r], A[c])]
    return [row[n:] for row in A]


def _primitive(vec):
    """Scale a rational vector to the shortest integer vector on the same ray."""
    den = 1
    for x in vec:
        den = den * x.denominator // math.gcd(den, x.denominator)
    ints = [int(x * den) for x in vec]
    g = 0
    for x in ints:
        g = math.gcd(g, abs(x))
    return tuple(x // g for x in ints) if g else tuple(ints)


def _kernel_basis(rows, d):
    """A basis of `{x : rows · x = 0}` over `Q`, returned as integer vectors."""
    A = [[Fraction(x) for x in row] for row in rows]
    piv_cols, r = [], 0
    for c in range(d):
        piv = next((i for i in range(r, len(A)) if A[i][c] != 0), None)
        if piv is None:
            continue
        A[r], A[piv] = A[piv], A[r]
        inv = Fraction(1) / A[r][c]
        A[r] = [x * inv for x in A[r]]
        for i in range(len(A)):
            if i != r and A[i][c] != 0:
                f = A[i][c]
                A[i] = [x - f * y for x, y in zip(A[i], A[r])]
        piv_cols.append(c)
        r += 1
    out = []
    for free in [c for c in range(d) if c not in piv_cols]:
        v = [Fraction(0)] * d
        v[free] = Fraction(1)
        for i, c in enumerate(piv_cols):
            v[c] = -A[i][free]
        out.append(_primitive(v))
    return out


def cone_generators(datum):
    """The **cone generators** of `datum`: the Hilbert basis of the monoid
    `M(G) = X_*(T) ∩ 𝔠⁺` of dominant cocharacters — its unique minimal
    generating set (the design notes §0).

    This is the general-`G` replacement for type A's dressed minuscules.  It is
    neither the minuscule cocharacters (most groups have none) nor the
    fundamental coweights `ω_i^∨` (which are the *rational* ray generators and
    for a simply connected `G` generally lie outside `Q^∨` — `SU(3)` needs
    three generators where it has two rays).

    **The search is complete, not a height cut.**  Every element of the Hilbert
    basis of a pointed rational cone is either a primitive ray generator or
    lies in the half-open fundamental parallelepiped `{Σ tᵢ rᵢ : 0 ≤ tᵢ < 1}`
    of the extreme rays, so `⟨Σ⁺, ·⟩ ≤ Σᵢ ⟨Σ⁺, rᵢ⟩` is a **proof** bound and
    searching to it misses nothing.  (This closes the one non-rigorous step of
    the design notes §1a, where the tables were "indecomposable up to a
    height cut".)

    Raises `NonPointedMonoid` when `G` has a central torus — see that class.

    Measured (this session): `SU(2)` 1, `SU(3)` 3, `SU(4)` 6, `Spin(5)` 2,
    `Spin(7)` 2, `Sp(2)` 2, `Sp(3)` 3, `G₂` 2 — and the (★) solves the class
    actually pays are exactly `{L_{h,0} : h a cone generator}` at `SU(2)`,
    `SU(3)`, `Spin(5)` and `G₂`."""
    d = datum.dim
    rows = [tuple(a) for a in datum.simple_roots]
    if len(rows) != d:                  # fewer roots than dim ⇒ a central torus
        raise NonPointedMonoid(datum, _kernel_basis(rows, d))
    inv = _rref_inverse(rows)
    if inv is None:
        raise NonPointedMonoid(datum, _kernel_basis(rows, d))
    # Extreme rays of `{x : Rx ≥ 0}` are the COLUMNS of `R⁻¹`, made primitive.
    rays = [_primitive([inv[i][j] for i in range(d)]) for j in range(d)]
    heights = [_cochar_height(datum, r) for r in rays]
    H = sum(heights)
    # Bounding box of `{x ∈ cone : ⟨Σ⁺,x⟩ ≤ H}` — a simplex with vertices `0`
    # and `(H/hᵢ)·rᵢ`, so coordinate-wise min/max over those vertices bound it.
    verts = [(0,) * d] + [tuple(Fraction(H, h) * c for c in r)
                          for r, h in zip(rays, heights)]
    lo = [int(math.floor(min(v[i] for v in verts))) for i in range(d)]
    hi = [int(math.ceil(max(v[i] for v in verts))) for i in range(d)]
    pts = []
    for x in itertools.product(*[range(lo[i], hi[i] + 1) for i in range(d)]):
        if not any(x) or not datum.is_dominant_cochar(x):
            continue
        h = _cochar_height(datum, x)
        if 0 < h <= H:
            pts.append((h, tuple(x)))
    pts.sort()
    seen = {p for _h, p in pts}
    gens = []
    for h, m in pts:
        decomposable = False
        for ha, a in pts:
            if ha >= h:                 # `pts` is height-sorted: nothing lower left
                break
            b = tuple(m[i] - a[i] for i in range(d))
            if any(b) and b in seen:
                decomposable = True
                break
        if not decomposable:
            gens.append(m)
    return tuple(gens)


class PureGAbeKAlgebra(AbeKAlgebra):
    """Pure gauge theory at any `RootDatum` on `WRQTorus` — labels `(m, e)` with
    `m` cochar-dominant and `e` Levi-dominant, unflavoured (`R = Z`).

    `PureGAbeKAlgebra(root_datum.b_n_simply_connected(2))` is `Spin(5)`,
    `PureGAbeKAlgebra(root_datum.g_2())` is `G₂`, `PureGAbeKAlgebra(root_datum.su_2())`
    reproduces `PureSU2KAlgebra`.  Set `allow_solve=False` to get a
    constructive-only instance that honest-fails wherever the (★) solve would
    have been needed (useful for isolating what the constructive routes reach)."""

    _MAX_PEEL = 400

    def __init__(self, datum, allow_solve: bool = True,
                 certify_box: bool = False, verbose: bool = False,
                 lines=None, strict_guard: bool = False) -> None:
        self.datum = datum
        # `strict_guard=True` re-applies (★) to EVERY route, including the ones
        # canonical by construction.  Off by default (it was 86% of build time
        # at SU(2) m=8); on for certification runs.
        self.strict_guard = bool(strict_guard)
        # The 4d global form: a SUBLATTICE of the Kapustin `(m, e)` labels, not
        # a choice of cocharacter lattice (that reading is the 3d one — user,
        # 2026-07-27).  Default = the simply connected form, which is what the
        # repo's coordinates realise (cocharacters in the coroot basis `Q^∨`,
        # weights in the fundamental-weight basis `P`; `⟨Q^∨, P⟩ ⊆ Z`, so the
        # Dirac pairing is integral and the lines are mutually local).  Pass
        # `global_form.adjoint_lines(datum)` to restrict to the adjoint form's
        # lines — admitted as a predicate, presented only by the non-atombled
        # frame (the design notes).
        if lines is None:
            from global_form import simply_connected_lines
            lines = simply_connected_lines(datum)
        self.lines = lines
        self.allow_solve = bool(allow_solve)
        self.certify_box = bool(certify_box)
        self.verbose = bool(verbose)
        self._R = TrivialZPlusRing()
        self._cache: dict = {}
        self._route: dict = {}
        self._building: set = set()
        self._cone_gens = None

    def __repr__(self) -> str:
        return f"PureGAbeKAlgebra({self.datum.name})"

    # ----- contract: ring / identity / shape --------------------------------
    def coefficient_ring(self) -> ZPlusRing:
        return self._R

    def identity(self) -> Label:
        z = (0,) * self.datum.dim
        return (z, z)

    def torus_shape(self) -> TorusShape:
        """One gauge node, no fundamentals — the honest root-datum shape."""
        return TorusShape.from_root_data((self.datum,))

    def _label_section_decompose(self, label: Label):
        return (label, self.coefficient_ring().one())

    # ----- the declared generating set --------------------------------------
    def cone_generators(self):
        """The cone generators of this datum — the finitely many undressed
        monopoles `L_{h,0}` from which the magnetic direction is built by
        products (the design notes F1).  MEASURED to be exactly where the
        licensed (★) solve fires at `SU(2)`/`SU(3)`/`Spin(5)`/`G₂`.

        Raises `NonPointedMonoid` at a datum with a central torus, where the
        central direction needs invertible generators instead."""
        if getattr(self, "_cone_gens", None) is None:
            self._cone_gens = cone_generators(self.datum)
        return self._cone_gens

    # ----- the label frame --------------------------------------------------
    def fold(self, m, e) -> Label:
        """Transport `(m, e)` to the canonical frame: `m` cochar-dominant (the
        Weyl element carrying `m` there is applied to `e` as well, since the
        Weyl group acts diagonally on `(m, e)`), then `e` replaced by the
        Levi-dominant representative of its `W_m`-orbit."""
        dat = self.datum
        m, e = tuple(m), tuple(e)
        for w in dat.weyl_elements():
            mw = tuple(dat.act_cochar(w, m))
            if dat.is_dominant_cochar(mw):
                m, e = mw, tuple(dat.act(w, e))
                break
        else:                                   # pragma: no cover
            raise ValueError(f"no dominant cocharacter for {m} in {dat.name}")
        Wm, Phim = _levi_data(dat, m)
        # Dominance of a WEIGHT is `⟨x, α^∨⟩ ≥ 0` — pair against the **coroot**.
        # `shift_pairing` takes `(cocharacter, weight)`, so the coroot goes first.
        # This used to read `shift_pairing(x, a)`, i.e. it fed the electric charge
        # in the cocharacter slot and the root in the weight slot; the test then
        # never fired and `fold` fell through the silent fallback below, returning
        # a NON-canonical label.  Measured at SU(3): `fold((0,0), (−1,0))` returned
        # `(−1,0)` unchanged although the dominant representative of `−ω₁` is `ω₂`
        # — and the unfolded label's `ρ` decomposes to **0 terms**.  (It folded
        # `(−1,−1) → (1,1)` correctly, which is what made the gap look sporadic.)
        cor = [SB.coroot_of(dat, a) for a in Phim]
        for w in Wm:
            x = tuple(dat.act(w, e))
            if all(c is not None and dat.shift_pairing(tuple(c), x) >= 0
                   for c in cor):
                return (m, x)
        raise NotImplementedError(
            f"{dat.name}.fold: no Levi-dominant representative of e={e} in its "
            f"W_m orbit at m={m}.  A dominant representative always exists, so "
            f"this means the Levi data or the dominance test is inconsistent — "
            f"returning the unfolded label instead (as this did before "
            f"2026-07-28) yields a non-canonical label whose ρ silently "
            f"decomposes to 0 terms.")

    def m_bar(self, m):
        """`m̄` — the cocharacter's Weyl-equivariant image in the weight lattice
        (`star_bubbling.cochar_to_weight`).  The `e ↦ e + k·m̄` symmetry shifts
        the dressing by multiples of this, NOT of `m`'s raw coordinates: at
        `SU(2)` the coroot `(1)` maps to the root `(2)`, and at a non-simply-
        laced datum the root-length multipliers enter (`Spin(5)` `[1,2]`,
        `Sp(2)` `[2,1]`, `G₂` `[3,1]`)."""
        return SB.cochar_to_weight(self.datum, tuple(m))

    def _monoid_split(self, m):
        """A splitting `m = h + m'` with `h` a cone generator and `m'` dominant,
        or `None` if `m` is itself a generator (or has none below it).

        Exists for every non-generator dominant `m` by definition of the Hilbert
        basis, so the recursion terminates at the generators."""
        d = self.datum.dim
        m = tuple(m)
        try:
            gens = self.cone_generators()
        except NonPointedMonoid:
            return None
        if m in gens:
            return None
        for h in sorted(gens, key=lambda g: -_cochar_height(self.datum, g)):
            rest = tuple(m[i] - h[i] for i in range(d))
            if any(rest) and self.datum.is_dominant_cochar(rest):
                return (tuple(h), rest)
        return None

    def _monoid(self, m, h, rest):
        """`L_{m,0} = L_{h,0}·L_{rest,0}` — EXACT, no peel (see `_routes`)."""
        z = (0,) * self.datum.dim
        out = self._build(self.fold(h, z)) * self._build(self.fold(rest, z))
        if out.well_formed() != (tuple(m), z):
            raise NotImplementedError(
                f"monoid law failed at L_{(tuple(m), z)}: product is "
                f"{out.well_formed()}")
        return out

    def twist_level(self, m, e):
        """Public face of `_twist_level`: `k` when `e = k·m̄` (`k ≠ 0`), else
        `None`.

        Exposed because the matter tier needs the same rule to dispatch its own
        `twist[k]` route and must not reach into a private helper
        (`GNAbeKAlgebra`; the θ-twist survives matter — `matter_star_bubbling.
        matter_theta_twist`)."""
        return self._twist_level(m, e)

    def _twist_level(self, m, e):
        """`k` when `e = k·m̄` with `k ≠ 0`, else `None` — i.e. when this label
        is a `T^k`-image of the undressed `L_{m,0}` and needs no solve."""
        if not any(e):
            return None
        try:
            mb = self.m_bar(m)
        except NotImplementedError:
            return None
        if not any(mb):
            return None
        k = None
        for a, b in zip(e, mb):
            if b == 0:
                if a:
                    return None
                continue
            if a % b:
                return None
            kk = a // b
            if k is None:
                k = kk
            elif k != kk:
                return None
        return k or None

    # ----- the constructive seed for the peel route -------------------------
    def _peel_seeds(self, m, e):
        """Candidate `(label_a, label_b)` splittings whose product can seed the
        peel: `m = m_a + m_b` with `e = e_a + e_b` and **both parts strictly
        lower in cocharacter height** than the target, so the recursion is
        well-founded.  Cheapest first — the general-G analogue of
        `PureSU2KAlgebra`'s `H·L_{m−1,e}`.

        Returns `[]` when nothing descends, which is the honest answer for the
        minimal bubbling monopoles of a group with no minuscule cocharacter
        (`Spin(5)` at `m = (1,1)` has no lower dominant factorization at all —
        precisely why the (★) route exists)."""
        dat = self.datum
        d = dat.dim
        z = (0,) * d
        target = (tuple(m), tuple(e))
        h = _cochar_height(dat, m)
        cands = []
        # --- monopole × Wilson, FIRST (user, 2026-07-27) ---------------------
        # `L_{m,0}·L_{0,e}` and its reverse.  This is the U(N) dressed-minuscule
        # pattern transplanted: dress an UNDRESSED monopole with a Wilson line
        # instead of solving the dressed label outright.  MEASURED to lead at
        # the target at SU(2) (e = 1,2,3), SU(3) ((1,0),(0,1),(1,1)) and
        # Spin(5) ((1,0),(0,1)) — in both orders.
        #
        # The magnetic charge does NOT descend here; the *dressing* does, from
        # `e` to `0`, which is what makes the recursion well-founded (one step,
        # and `L_{m,0}` cannot re-enter this branch).  So the height guard below
        # must not be applied to these two seeds — the ordering is lexicographic
        # in (height, dressing), not height alone.
        #
        # Why it matters: without it every dressed label falls through to the
        # `star` solve, so one solve is paid per `(m, e)`.  With it, one solve is
        # paid per *magnetic charge* and the whole dressed fibre comes from
        # products with the free Wilson lines — the point of
        # `L_{adj,0}·L_{0,e}` carrying the information (user).
        if any(e):
            und = self.fold(m, z)
            wil = self.fold(z, e)
            if und != target and wil != target:
                out_first = [(und, wil), (wil, und)]
            else:                                   # pragma: no cover
                out_first = []
        else:
            out_first = []
        # --- factors: the UNDRESSED small monopoles `L_{m_a,0}` ---------------
        # (user, 2026-07-27: "Using L_{m,0} for other small m's may be
        # helpful".)  The general-`G` analogue of U(N)'s dressed-minuscule
        # generating set: undressed monopoles generate the magnetic direction,
        # Wilson lines supply the dressing (the seed above), and everything else
        # is a peeled product.
        #
        # The candidate factors are the dominant cocharacters strictly BELOW `m`
        # in the dominance order — which is exactly `tropical_support(m)` folded
        # to dominant representatives, machinery the solver already has.  The
        # previous version offered only `m ± (one simple coroot)`, which is why
        # peeling `m = (2,2)` at SU(3) dragged 30 of 48 charts down to a solve:
        # when that single step's seed failed to lead at the target, the label
        # fell through to `star`.
        steps = [tuple(c) for c in dat.simple_coroots]
        try:
            for p in SB.tropical_support(dat, m):
                dom = tuple(dat.dominant_cochar_rep(p))
                if any(dom) and dom not in steps:
                    steps.append(dom)
        except Exception:                       # honest-fail → simple coroots
            pass
        for cor in steps:
            for sgn in (1, -1):
                step = tuple(sgn * x for x in cor)
                mb = tuple(m[i] - step[i] for i in range(d))
                ma = tuple(step)
                if not any(ma) or not any(mb):
                    continue
                for ee in (z, tuple(e)):
                    lab_a = self.fold(ma, ee)
                    lab_b = self.fold(mb, tuple(e[i] - ee[i] for i in range(d)))
                    ha = _cochar_height(dat, lab_a[0])
                    hb = _cochar_height(dat, lab_b[0])
                    if lab_a == target or lab_b == target:
                        continue
                    if not (0 <= ha < h and 0 <= hb < h):
                        continue                # must strictly descend
                    cands.append((ha + hb, lab_a, lab_b))
        cands.sort(key=lambda t: t[0])
        out, seen = list(out_first), set(out_first)
        for _k, a, b in cands:
            if (a, b) in seen:
                continue
            seen.add((a, b))
            out.append((a, b))
        return out

    # ----- the build --------------------------------------------------------
    def _lower_chart(self, mt, et) -> WRQTorus:
        return self._build(self.fold(mt, et))

    def _build(self, label: Label) -> WRQTorus:
        m, e = label
        if label in self._cache:
            return self._cache[label]
        if label in self._building:
            raise NotImplementedError(
                f"{self!r}._build: cyclic dependency at L_{label}")
        self._building.add(label)
        try:
            result, route = self._guarded_dispatch(m, e)
        finally:
            self._building.discard(label)
        self._cache[label] = result
        self._route[label] = route
        return result

    # Routes whose output is canonical by construction, so (★) is not needed to
    # ACCEPT them.  `wilson` is `χ_e` at magnetic 0 (q-free ⇒ bar-invariant);
    # `minuscule` is the leading orbit, which IS the canonical at minuscule `m`
    # (`wrq_torus.is_minuscule`); `peel` is a constructive product of
    # already-guarded canonicals that additionally ends by checking
    # `well_formed() == target`.  `cone` is NOT here — it returns the
    # bubbling-free cone monomial at non-minuscule `m`, which W1+W2 *accepts*
    # and only (★) rejects — and `star` runs (★) inside `solve_canonical`.
    #
    # Why this matters: (★)'s cost grows with the support, and MEASURED on the
    # SU(2) ladder it was 62% / 75% / 86% of total build time at m = 4 / 6 / 8 —
    # the whole of the divergence against the native class.  Running it on every
    # constructive route was redundant belt-and-braces.  `strict_guard=True`
    # restores (★) everywhere for certification runs.
    # `monoid` joins the exempt list on the same footing as `peel`: it is an
    # exact product of two already-guarded canonicals and it ends by demanding
    # `well_formed() == target` (W1+W2).  `twist` is NOT exempt — the twist law
    # is measured, not proved, so (★) stays on it.
    _STAR_EXEMPT = ("wilson", "minuscule", "peel", "monoid")

    def _guard(self, x, route=None):
        """W1 (bar) + (★) (the element acts on `R(G)`) — the acceptance every
        route must clear.  Returns `None` on success, else a reason string.

        This is applied to each route's candidate and a failure makes the build
        **fall through to the next route**, not abort.  That matters: at `e = 0`
        the `cone` route returns `wrq_torus`'s bubbling-free cone monomial, which
        for a group with no minuscule cocharacter is *not* the canonical, and
        (★) rejects it — the documented R7 behaviour ("that rejection is a
        feature", the design notes), measured here on SU(2),
        SU(3) and Spin(5) at `e = 0`.  Using a guard to *choose* the route is the
        whole point of having one; the W2 half arrives with
        `certify_canonical`."""
        if x is None:
            return "builder returned None"
        if not x.well_formed_w1():
            return "not bar-invariant (W1)"
        base = (route or "").split("[")[0]
        if not self.strict_guard and base in self._STAR_EXEMPT:
            return None
        ok, report = SB.criterion(x)
        if not ok:
            return f"fails (★) — does not preserve R(G): {report[:2]}"
        return None

    def _guarded_dispatch(self, m, e):
        """Try the routes in order of preference, guard each candidate, and
        return the first that clears.  Honest-fails with every route's reason if
        none does."""
        rejected = []
        for route, make in self._routes(m, e):
            try:
                cand = make()
            except (NotImplementedError, RuntimeError) as ex:
                rejected.append(f"{route}: {type(ex).__name__} {str(ex)[:80]}")
                continue
            except SB.StarGuardFailure as ex:
                rejected.append(f"{route}: {str(ex)[:110]}")
                continue
            why = self._guard(cand, route)
            if why is None:
                return cand, route
            rejected.append(f"{route}: {why}")
        raise NotImplementedError(
            f"{self!r}: no guarded route reaches L_{(tuple(m), tuple(e))} — "
            + "; ".join(rejected))

    def _routes(self, m, e):
        """`[(route_name, thunk)]` in order of preference: constructive first,
        the licensed (★) solve last."""
        dat = self.datum
        out = []
        if not any(m):
            out.append(("wilson", lambda: wilson(dat, e)))
        if any(m) and is_minuscule(dat, m):
            out.append(("minuscule", lambda: minuscule(dat, m, e)))
        if any(m):
            # --- the `e ↦ e + k·m̄` symmetry (user, 2026-07-27) ---------------
            # `T^k : f_p ↦ v^{k·p̄}` carries the canonical `L_{m,e}` to the
            # canonical `L_{m, e + k·m̄}` (MEASURED 30/30 — `SU(2)`, `SU(3)`
            # regular and singular `m`, `Spin(5)`, `Sp(2)`, `G₂`; `k = ±1, 2`;
            # W1 + (★) + `well_formed` at the predicted label every time).
            #
            # So a whole cone of dressed lines is the twisted image of the
            # UNDRESSED cone and costs **no solve at all**: ahead of `cone`,
            # because it is both cheaper and canonical by construction.
            # --- the MONOID LAW (2026-07-27) --------------------------------
            # `L_{m,0}·L_{m',0} = L_{m+m',0}` **exactly** — measured at SU(2),
            # SU(3), Spin(5), Sp(2) and G₂ on every pair of cone generators and
            # on cubes.  So `m ↦ L_{m,0}` is a monoid homomorphism and every
            # undressed monopole is an exact monomial in the cone-generator
            # monopoles: no peel, no leading-term subtraction, no bar
            # correction.  Why it must be so, given the spectral law: the family
            # is commutative with `L_{m,0} = (−1)^{⟨ρ,m⟩}𝖖^{⟨ρ,m⟩}·Λ_m` and
            # `Λ_m : P_μ ↦ 𝖖^{2⟨μ,m⟩}P_μ` on a COMMON eigenbasis, so eigenvalues
            # multiply and — because `⟨ρ,·⟩` is linear — the normalizations
            # cancel exactly.  Ahead of `cone` and `peel`: it is both exact and
            # far cheaper (the design notes §7e).
            if not any(e):
                split = self._monoid_split(m)
                if split is not None:
                    h, rest = split
                    out.append((f"monoid[{h}+{rest}]",
                                lambda hh=h, rr=rest: self._monoid(m, hh, rr)))
                # --- the CLOSED FORM (2026-07-27) ------------------------
                # No solve and no peel: top orbit `f=1`, the bubbling cells by
                # `one_step_residual` / `two_root_residual` transported by Weyl
                # covariance, and the origin from the SCALAR Neumann row
                # `L_{m,0}|N] = (−1)^{⟨ρ,m⟩}𝖖^{⟨ρ,m⟩}`.  Honest-fails where a
                # cell is not yet covered, and then `star` picks it up.
                out.append(("closed_form",
                            lambda: SB.closed_form_undressed(dat, m)))
            k = self._twist_level(m, e)
            if k:
                out.append((f"twist[k={k}]",
                            lambda kk=k: SB.theta_twist(
                                self._build(self.fold(m, (0,) * dat.dim)), kk)))
            out.append(("cone", lambda: build_canonical(dat, m, e)))
            for lab_a, lab_b in self._peel_seeds(m, e):
                out.append((f"peel[{lab_a}·{lab_b}]",
                            lambda a=lab_a, b=lab_b: self._peel(m, e, a, b)))
            if self.allow_solve:
                out.append(("star", lambda: SB.solve_canonical(
                    dat, m, e, certify_box=self.certify_box,
                    verbose=self.verbose)))
        return out

    def _peel(self, m, e, lab_a, lab_b):
        """Product-and-peel from one lower-canonical splitting."""
        dat = self.datum
        seed = self._build(lab_a) * self._build(lab_b)
        if (tuple(m), tuple(e)) not in seed.recognize_leading():
            raise NotImplementedError("seed does not lead at the target")
        L = peel_to_canonical(dat, (m, e), seed, self._lower_chart,
                              self._MAX_PEEL)
        L = kl_bar_correct(dat, L, (m, e), self._lower_chart, self._MAX_PEEL)
        if L.well_formed() != (tuple(m), tuple(e)):
            raise NotImplementedError("peel result is not well-formed at target")
        return L

    def route(self, label: Label) -> str:
        """Which route built `L_label` ('wilson' / 'minuscule' / 'cone' /
        'peel' / 'star') — builds it if necessary."""
        lab = self.fold(*label)
        self._build(lab)
        return self._route[lab]

    # ----- contract triple --------------------------------------------------
    def chart(self, label: Label):
        lab = self.fold(*label)
        if not self.lines.admits(*lab):
            raise NotImplementedError(
                f"{self!r}: L_{lab} is not a line of {self.lines.name} — the "
                f"global form's Kapustin (m, e) sublattice excludes it")
        if not self.lines.abe_representable(lab[0]):
            # This is about the FRAME, never about the line: L_lab is a genuine line
            # of the form (`admits` passed just above) and it has a presentation —
            # the doubled one.  Say which, and say whether the whole form is out of
            # reach here or only this charge, since the parity character answers that
            # from the centre alone (ruling D19/D20).
            # `abe_representable_lattice` can itself refuse (non-cyclic centre), and
            # this is an error path — never let the diagnostic mask the diagnosis.
            try:
                whole = self.lines.abe_representable_lattice()
            except NotImplementedError:
                whole = None
            if whole is None:
                extra = ""
            elif whole:
                # Unreachable if both predicates are right: π is well defined on
                # classes, so `admits` (⇒ [m] ∈ H) together with π|_H ≡ 0 forces
                # ⟨Σ⁺,m⟩ even.  Reaching it means the two disagree.
                extra = (f"  INCONSISTENT: {self.lines.name} reports π|_H ≡ 0, "
                         f"which together with admits(m,e) should force EVEN "
                         f"⟨Σ⁺,m⟩ — the two predicates disagree, so one is wrong.")
            else:
                extra = (f"  {self.lines.name} is not carried whole by this frame "
                         f"(π|_H ≠ 0), so its out-of-frame charges all belong "
                         f"there.")
            raise NotImplementedError(
                f"{self!r}: L_{lab} was refused by abe_representable.  Since ruling "
                f"D31 that predicate is True for every charge of every datum on "
                f"the default phase — odd ⟨Σ⁺,m⟩ included — so reaching this path "
                f"means the datum carries an explicit phase_is_canonical= override "
                f"that refuses it.  It is NOT a claim that the line cannot be built "
                f"(see global_form.LineLattice.abe_representable and "
                f"a probe in the source repository)." + extra)
        return self._build(lab)

    def decompose(self, x) -> Element:
        out = _wrq_decompose(self.datum, x,
                             build=lambda dat, mv, ev: self._build(
                                 self.fold(mv, ev)))
        folded: dict = {}
        for (mv, ev), C in out.items():
            lab = self.fold(mv, ev)
            folded[lab] = folded.get(lab, LaurentPoly.zero()) + C
        return Element({lab: C for lab, C in folded.items() if not C.is_zero()})

    # ----- ρ: read the image label via well_formed --------------------------
    def _wf_label(self, img, what: str) -> Label:
        wf = img.well_formed()
        if wf is False:
            raise NotImplementedError(
                f"{self!r}.{what}: image is not well-formed")
        return self.fold(*wf)

    def rho(self, a: Label) -> Label:
        return self._wf_label(self.chart(a).rho(), "rho")

    def rho_inverse(self, a: Label) -> Label:
        return self._wf_label(self.chart(a).rho_inverse(), "rho_inverse")

    # ----- trace / pairing: native WRQ (pure gauge, unflavoured) ------------
    def trace(self, a: Label, K: int = 20) -> RPowerSeries:
        """`Tr(L_a)` — the native Schur-measure residue of the chart."""
        lp = self.chart(a).trace(K)
        return RPowerSeries(self._R,
                            {e: c for e, c in lp._coeffs.items() if 0 <= e <= K},
                            K)

    def inner_product(self, a: Label, b: Label, K: int = 20) -> RPowerSeries:
        """`I_{a,b} = Tr(ρ(L_a)·L_b)` — the §6b chart pairing.  The tier's
        multiply-then-trace default is the cross-check
        (`verify_inner_product_consistent`)."""
        lp = self.chart(a).inner(self.chart(b), K)
        return RPowerSeries(self._R,
                            {e: c for e, c in lp._coeffs.items() if 0 <= e <= K},
                            K)


if __name__ == "__main__":
    from root_datum import b_n_simply_connected, g_2, su_2

    for dat in (su_2(), b_n_simply_connected(2), g_2()):
        A = PureGAbeKAlgebra(dat)
        z = (0,) * dat.dim
        one = (z, z)
        first = tuple(1 if i == 0 else 0 for i in range(dat.dim))
        lab = A.fold(first, first)
        print(f"{dat.name}: 1 = {one}, Tr(1, K=6) = "
              f"{dict(A.trace(one, 6).coeffs)}")
        print(f"   L_{lab} route = {A.route(lab)},  "
              f"certify_canonical = {A.certify_canonical(lab)},  "
              f"I = {A.inner_product(lab, lab, 4)}")
