"""Root data for compact connected gauge groups, on the flux lattice.

A 3d gauge theory's monopole fluxes live in the cocharacter lattice
`X_*(T)` of (a maximal torus of) the gauge group `G`; matter charges
and roots act on fluxes as integral functionals (elements of `X^*(T)`).
`GaugeDatum` presents `G` exactly by this data — a root datum in a
chosen basis of `X_*(T) ≅ Z^rank`:

- ``roots``   — tuples `a` with `a(m) = sum_i a[i] m[i]` (functionals);
- ``coroots`` — tuples in flux coordinates, parallel to ``roots``,
  with the root-datum pairing `a(a_vee) = 2`;
- ``simple``  — indices of the simple positive roots.

Because the *lattice* is part of the data, global structure is native:
`SU(2)` (cocharacter lattice = coroot lattice) and `SO(3)` (full
coweight lattice) are different `GaugeDatum`s with the same root
system, and their different monopole-flux quantizations follow.

Weyl machinery provided: reflections, the full Weyl group (bounded
generation), dominance and dominant representatives, orbits, and
stabilizer orders `|W_m|` (for a dominant `m`, the stabilizer is the
parabolic subgroup generated by the simple reflections fixing it —
Bourbaki/Steinberg), which is exactly the `1/|W_m|` symmetry factor of
monopole-flux sums.

Standard library only (package independence discipline).
"""

from fractions import Fraction


def _dot(a, m):
    return sum(x * y for x, y in zip(a, m))


class GaugeDatum:
    """A compact connected gauge group as a root datum on Z^rank."""

    def __init__(self, rank, roots, coroots, simple, name=""):
        self.rank = rank
        self.roots = [tuple(r) for r in roots]
        self.coroots = [tuple(c) for c in coroots]
        self.simple = list(simple)
        self.name = name or "GaugeDatum(rank=%d)" % rank
        self._weyl = None          # cached list of Weyl matrices
        self._positive = None      # cached positive-root indices
        self._validate()

    # -- validation ----------------------------------------------------

    def _validate(self):
        if len(self.roots) != len(self.coroots):
            raise ValueError("roots/coroots length mismatch")
        for r, c in zip(self.roots, self.coroots):
            if len(r) != self.rank or len(c) != self.rank:
                raise ValueError("root/coroot of wrong rank")
            if _dot(r, c) != 2:
                raise ValueError("root-datum pairing violated: a(a_vee)="
                                 "%d != 2 for %s, %s" % (_dot(r, c), r, c))
        pair_set = set(zip(self.roots, self.coroots))
        if len(pair_set) != len(self.roots):
            raise ValueError("duplicate (root, coroot) pair")
        for i in self.simple:
            if not 0 <= i < len(self.roots):
                raise ValueError("simple index out of range")
        # closure: each simple reflection permutes the (root, coroot) set
        for i in self.simple:
            a, av = self.roots[i], self.coroots[i]
            for r, c in pair_set:
                r2 = tuple(r[k] - _dot(r, av) * a[k] for k in range(self.rank))
                c2 = tuple(c[k] - _dot(a, c) * av[k] for k in range(self.rank))
                if (r2, c2) not in pair_set:
                    raise ValueError(
                        "reflection closure fails: s_%d maps (%s, %s) to "
                        "(%s, %s), not a listed pair" % (i, r, c, r2, c2))

    # -- reflections and the Weyl group --------------------------------

    def _reflection_matrix(self, i):
        """Matrix of s_i on flux vectors: m -> m - a_i(m) * a_i_vee."""
        a, av = self.roots[i], self.coroots[i]
        n = self.rank
        return tuple(tuple((1 if r == c else 0) - av[r] * a[c]
                           for c in range(n)) for r in range(n))

    @staticmethod
    def _mat_apply(M, m):
        return tuple(sum(M[r][c] * m[c] for c in range(len(m)))
                     for r in range(len(m)))

    @staticmethod
    def _mat_mul(A, B):
        n = len(A)
        return tuple(tuple(sum(A[r][k] * B[k][c] for k in range(n))
                           for c in range(n)) for r in range(n))

    @staticmethod
    def _generate(generators, rank, max_size):
        ident = tuple(tuple(1 if r == c else 0 for c in range(rank))
                      for r in range(rank))
        seen = {ident}
        frontier = [ident]
        while frontier:
            new = []
            for M in frontier:
                for g in generators:
                    P = GaugeDatum._mat_mul(g, M)
                    if P not in seen:
                        seen.add(P)
                        new.append(P)
                        if max_size is not None and len(seen) > max_size:
                            raise RuntimeError(
                                "Weyl generation exceeded max_size=%d"
                                % max_size)
            frontier = new
        return seen

    def weyl_matrices(self, max_size=10 ** 6):
        """The full Weyl group as matrices on the flux lattice
        (bounded generation; cached)."""
        if self._weyl is None:
            gens = [self._reflection_matrix(i) for i in self.simple]
            self._weyl = GaugeDatum._generate(gens, self.rank, max_size)
        return self._weyl

    def weyl_order(self, max_size=10 ** 6):
        return len(self.weyl_matrices(max_size))

    # -- dominance, orbits, stabilizers ---------------------------------

    def is_dominant(self, m):
        return all(_dot(self.roots[i], m) >= 0 for i in self.simple)

    def dominant_rep(self, m):
        """The dominant Weyl-chamber representative of a flux vector."""
        m = tuple(m)
        for _ in range(10 ** 6):
            for i in self.simple:
                v = _dot(self.roots[i], m)
                if v < 0:
                    av = self.coroots[i]
                    m = tuple(m[k] - v * av[k] for k in range(self.rank))
                    break
            else:
                return m
        raise RuntimeError("dominant_rep failed to terminate")

    def weyl_orbit(self, m, max_size=10 ** 6):
        """The Weyl orbit of a flux vector (set of tuples)."""
        m = tuple(m)
        seen = {m}
        frontier = [m]
        refl = [self._reflection_matrix(i) for i in self.simple]
        while frontier:
            new = []
            for x in frontier:
                for M in refl:
                    y = GaugeDatum._mat_apply(M, x)
                    if y not in seen:
                        seen.add(y)
                        new.append(y)
                        if len(seen) > max_size:
                            raise RuntimeError("weyl_orbit exceeded max_size")
            frontier = new
        return seen

    def stabilizer_order(self, m, max_size=10 ** 6):
        """|W_m| — the order of the Weyl stabilizer of the flux `m`
        (the 1/|W_m| factor of monopole sums).  Computed on the dominant
        representative, whose stabilizer is the parabolic generated by
        the simple reflections fixing it."""
        md = self.dominant_rep(m)
        fixing = [i for i in self.simple
                  if _dot(self.roots[i], md) == 0]
        if not fixing:
            return 1
        gens = [self._reflection_matrix(i) for i in fixing]
        return len(GaugeDatum._generate(gens, self.rank, max_size))

    # -- positive roots --------------------------------------------------

    def _regular_vector(self):
        """A flux-space vector (rational, in coroot coordinates) that is
        strictly positive on every simple root — used only to split the
        root set into positive/negative halves."""
        k = len(self.simple)
        if k == 0:
            return None
        A = [[Fraction(_dot(self.roots[i], self.coroots[j]))
              for j in self.simple] for i in self.simple]
        rhs = [Fraction(1)] * k
        # Gaussian elimination (A is the Cartan matrix of the simples —
        # invertible for a valid finite root datum).
        M = [row[:] + [rhs[r]] for r, row in enumerate(A)]
        for c in range(k):
            p = next((r for r in range(c, k) if M[r][c] != 0), None)
            if p is None:
                raise ValueError("simple roots are not independent")
            M[c], M[p] = M[p], M[c]
            piv = M[c][c]
            M[c] = [x / piv for x in M[c]]
            for r in range(k):
                if r != c and M[r][c] != 0:
                    f = M[r][c]
                    M[r] = [M[r][t] - f * M[c][t] for t in range(k + 1)]
        x = [M[r][k] for r in range(k)]
        v = [Fraction(0)] * self.rank
        for xi, j in zip(x, self.simple):
            for t in range(self.rank):
                v[t] += xi * self.coroots[j][t]
        return v

    def positive_root_indices(self):
        """Indices of the positive roots (those positive on the regular
        vector); exactly half the roots, else the datum is rejected."""
        if self._positive is None:
            v = self._regular_vector()
            pos = []
            for idx, r in enumerate(self.roots):
                s = sum(Fraction(ri) * vi for ri, vi in zip(r, v)) \
                    if v is not None else 0
                if s == 0:
                    raise ValueError("root %s vanishes on the regular "
                                     "vector — not in the span of the "
                                     "simples" % (r,))
                if s > 0:
                    pos.append(idx)
            if 2 * len(pos) != len(self.roots):
                raise ValueError("positive roots are not half the roots")
            self._positive = pos
        return self._positive

    def positive_roots(self):
        return [self.roots[i] for i in self.positive_root_indices()]

    # -- constructors ----------------------------------------------------

    @classmethod
    def torus(cls, r):
        return cls(r, [], [], [], name="U(1)^%d" % r)

    @classmethod
    def u(cls, N):
        """U(N): flux lattice Z^N, roots e_i - e_j."""
        roots, coroots = [], []
        for i in range(N):
            for j in range(N):
                if i == j:
                    continue
                v = tuple(1 if k == i else (-1 if k == j else 0)
                          for k in range(N))
                roots.append(v)
                coroots.append(v)
        simple = [roots.index(tuple(1 if k == i else (-1 if k == i + 1 else 0)
                                    for k in range(N)))
                  for i in range(N - 1)]
        return cls(N, roots, coroots, simple, name="U(%d)" % N)

    @classmethod
    def su(cls, N):
        """SU(N) (simply connected): flux lattice = coroot lattice,
        coordinates in the basis of simple coroots a_k_vee = e_k - e_{k+1}."""
        rank = N - 1

        def pair_with_simple_coroots(i, j):
            # functional (e_i - e_j) evaluated on a_k_vee = e_k - e_{k+1}
            return tuple((1 if k == i else 0) - (1 if k + 1 == i else 0)
                         - (1 if k == j else 0) + (1 if k + 1 == j else 0)
                         for k in range(rank))

        def coroot_coords(i, j):
            # e_i - e_j = sum_{k in [min,max)} sign * a_k_vee
            lo, hi, s = (i, j, 1) if i < j else (j, i, -1)
            return tuple(s if lo <= k < hi else 0 for k in range(rank))

        roots, coroots, simple = [], [], []
        for i in range(N):
            for j in range(N):
                if i == j:
                    continue
                roots.append(pair_with_simple_coroots(i, j))
                coroots.append(coroot_coords(i, j))
                if j == i + 1:
                    simple.append(len(roots) - 1)
        return cls(rank, roots, coroots, simple, name="SU(%d)" % N)

    @classmethod
    def so(cls, N):
        """SO(N) (the SO form: flux lattice Z^n for T = SO(2)^n)."""
        n = N // 2
        if N == 2:
            return cls(1, [], [], [], name="SO(2)")
        roots, coroots = [], []

        def e(i, s=1):
            return tuple(s if k == i else 0 for k in range(n))

        def pm(i, j, si, sj):
            return tuple((si if k == i else 0) + (sj if k == j else 0)
                         for k in range(n))

        for i in range(n):
            for j in range(i + 1, n):
                for si in (1, -1):
                    for sj in (1, -1):
                        v = pm(i, j, si, sj)
                        roots.append(v)
                        coroots.append(v)
        if N % 2:  # B_n: short roots +-e_i, coroot +-2e_i
            for i in range(n):
                for s in (1, -1):
                    roots.append(e(i, s))
                    coroots.append(e(i, 2 * s))
        if N % 2:
            simple_roots = [pm(i, i + 1, 1, -1) for i in range(n - 1)] \
                + [e(n - 1)]
        else:
            simple_roots = [pm(i, i + 1, 1, -1) for i in range(n - 1)] \
                + [pm(n - 2, n - 1, 1, 1)]
        simple = [roots.index(r) for r in simple_roots]
        return cls(n, roots, coroots, simple, name="SO(%d)" % N)

    @classmethod
    def sp(cls, n):
        """Compact Sp(n) = USp(2n) (simply connected; flux lattice Z^n =
        the C_n coroot lattice)."""
        roots, coroots = [], []

        def e(i, s=1):
            return tuple(s if k == i else 0 for k in range(n))

        def pm(i, j, si, sj):
            return tuple((si if k == i else 0) + (sj if k == j else 0)
                         for k in range(n))

        for i in range(n):
            for j in range(i + 1, n):
                for si in (1, -1):
                    for sj in (1, -1):
                        v = pm(i, j, si, sj)
                        roots.append(v)
                        coroots.append(v)
        for i in range(n):
            for s in (1, -1):
                roots.append(e(i, 2 * s))     # long roots +-2e_i
                coroots.append(e(i, s))
        simple_roots = [pm(i, i + 1, 1, -1) for i in range(n - 1)] \
            + [e(n - 1, 2)]
        simple = [roots.index(r) for r in simple_roots]
        return cls(n, roots, coroots, simple, name="Sp(%d)" % n)

    def product(self, other):
        """Direct product: flux lattices concatenate, roots pad with 0."""
        r1, r2 = self.rank, other.rank
        z1, z2 = (0,) * r1, (0,) * r2
        roots = [r + z2 for r in self.roots] + [z1 + r for r in other.roots]
        coroots = [c + z2 for c in self.coroots] \
            + [z1 + c for c in other.coroots]
        simple = list(self.simple) \
            + [len(self.roots) + i for i in other.simple]
        return GaugeDatum(r1 + r2, roots, coroots, simple,
                          name="%s x %s" % (self.name, other.name))

    def __repr__(self):
        return ("GaugeDatum(%s: rank %d, %d roots)"
                % (self.name, self.rank, len(self.roots)))
