"""Abstract canonical-basis labelling D_{m, e} for pure ADE BPS K_𝖖-algebras.

A utility for exposing the canonical basis via intrinsic (m, e) labels on
top of a chart-coordinate BPS realisation; it implements the (m, e) ↔ γ
mapping.  The pure-ADE chart builders it consumes (``pure_ade_kalgebra``,
``pure_ade_lattice``) are derivations not included in this repository.

Mathematical setup (SU(2), simply-connected)
--------------------------------------------
For the pure SU(2) gauge theory (G̃ = SU(2)), every canonical basis
element of the BPS K-algebra is intrinsically labelled by

    D_{m, e}    with    m ∈ ℤ_{≥0}    (dominant cocharacter in P^∨ ≅ ℤ)
                       e ∈ ℤ          (electric weight in P ≅ ℤ)

with the boundary cases

    T_m  =  D_{m, 0}      (pure 't Hooft at cocharacter m)
    W_e  =  D_{0, e}      (pure Wilson at weight e ≥ 0)

The fundamental Wilson is W_1 = D_{0, 1} (= the χ_{1/2} character of
the SU(2) fundamental rep; tropical chord charge γ = (0, −1)).

The H tower of line operators
-----------------------------
The full line-operator algebra is generated by the W_e Wilson tower
and the **H tower** of 't Hooft-like operators:

    H_n := D_{1, n}    for all n ∈ ℤ

In tropical chord-charge γ:

    n ≤ 0:  H_n = γ(1, n)   = (1, n)        — magnetic-positive branch
    n = 1:  H_1 = γ(1, 1)   = (0, 1)        — unique m=0 element (= "anti-W_1")
    n ≥ 2:  H_n = γ(1, n)   = (-1, 4-n)     — magnetic-negative branch

(So the H tower projects onto a three-piecewise-linear path in tropical
γ space, in agreement with `gamma_SU2`'s south/diagonal/west chambers.)

The H tower satisfies the **fundamental Wilson-step recursion**:

    W_1 · H_n  =  q · H_{n-1}  +  q^{-1} · H_{n+1}  +  ε_n

where ε_n is a vacuum correction ε_n = 1·𝟙 at n = ±1 and zero otherwise.
The reverse-order product is similar with q ↔ q^{-1} on the H_{n±1}
prefactors:

    H_n · W_1  =  q^{-1} · H_{n-1}  +  q · H_{n+1}  +  ε_n

This recursion DEFINES the H tower indexing (up to a choice of origin
H_0 = T_1, with H_1 = W_1's complex conjugate, etc.).

ρ-action on the H tower
-----------------------
The chart automorphism ρ acts on (m, e) labels as

    ρ(D_{m, e}) = D_{m, e − 4m}

so on H_n = D_{1, n}:

    ρ(H_n) = H_{n - 4}

ρ shifts the H tower index n by −4 (uniformly, with no chamber
exception).  The ρ²-twisted trace cyclicity Tr(a · b) = Tr(ρ²(b) · a)
therefore gives the m=1 trace collapse Tr(H_n) = Tr(H_{n - 8}), and
empirically all Tr(H_n) for n in the (m=1) ρ²-fundamental domain are
equal as q-series.

Wilson fusion
-------------
The framework predicts (and we verify empirically below) that the
fusion of a Wilson with any canonical basis element factors over the
weights of the corresponding SU(2)-irrep V_w:

    W_w · D_{m, e}  =  Σ_{ε ∈ wts(V_w)} 𝖖^{−⟨m, ε⟩} D_{m, e+ε}
                       +  (lower-filtration corrections)

The 𝖖-power identifies abstract weights cleanly: the term at filtration
level (m + m') in T_{m'} · D_{m, e} carries 𝖖^{⟨m', e⟩}, with sign
flipped in the reverse direction.

⚠ Note on lattice convention: an earlier version of this docstring stated
"m ∈ P^∨ = Q (root-lattice cocharacter)".  That is the SO(3) (i.e., the
PSU(2) = SU(2)/ℤ_2) lattice, not the SU(2) one.  The algebra
implemented here IS pure SU(2) (it includes the fundamental Wilson W_1
at e=1 and odd-e 't Hoofts in the H tower, neither of which exist in
pure SO(3)).  See `bps_kalgebra.BPSKAlgebra(pairing=[[0,1],[-1,0]],
node_charges=[(1, 0), (-1, 2)])` for the BPSKAlgebra realisation in
tropical chord-charge coordinates.

Chart conventions
-----------------
For a pure ADE algebra in the doubled-Dynkin chart of
``pure_ade_lattice``:

* T_m ↔ γ = (m_1, 0, m_2, 0, …)        — chart-magnetic = m, chart-electric = 0
* W_w ↔ γ = (0, −w_1, 0, −w_2, …)      — chart-electric = −w  (sign flip!)
* D_{m, e} for m > 0 ↔ chart-electric = +e (no sign flip on the dyon side)

So the chart γ ↔ (m, e_abs) bijection is non-trivial; this module
extracts e_abs by 𝖖-probing.
"""

from __future__ import annotations
from fractions import Fraction


def _single_qpow(c):
    """Return the unique 𝖖-power if c = 𝖖^k (unit coefficient), else None.

    Accepts either an `RLaurent`-style object (`.coeffs` exposes
    `dict[int, RElement]`) or a `LaurentPoly` (`._coeffs` exposes
    `dict[int, int]`).
    """
    coeffs = getattr(c, "coeffs", None)
    if coeffs is None:
        coeffs = getattr(c, "_coeffs", None)
    if coeffs is None:
        return None
    nonzero = [(k, v) for k, v in coeffs.items() if v != 0]
    if len(nonzero) == 1 and nonzero[0][1] == 1:
        return nonzero[0][0]
    return None


def extract_abstract_e(alg, fi, gamma, m=None, level_fn=None, mp_list=None):
    """Identify the abstract dominant-Levi weight e ∈ P of the canonical
    basis element F_γ in a pure ADE BPS K-algebra.

    Returns (e_omega, info) where e_omega is a tuple of Fraction (e in
    the fundamental-weight ω basis), or (None, error_string) on failure.

    Parameters
    ----------
    alg       : BPSKAlgebra built by ``pure_ade_kalgebra``
    fi        : factor_info from ``pure_ade_lattice_data``
    gamma     : tuple — the chart coordinates of the canonical basis element
    m         : optional dominant cocharacter; if None, use level_fn(γ).
    level_fn  : optional callable γ → m; defaults to
                ``filtration_level_ADE_closed_form(γ, fi)``.
    mp_list   : optional list of T-atom probe cocharacters; default uses
                a basis of (rank+1) probes at small dominant cocharacters.

    Method: probes 𝖖-powers in T_{m'} · F_γ for several m' values.  Each
    probe contributes a linear constraint ⟨m', e⟩ = q-power.  We solve
    the resulting integer linear system over ω-basis coordinates.
    """
    if level_fn is None:
        from pure_ade_lattice import filtration_level_ADE_closed_form
        level_fn = lambda g: filtration_level_ADE_closed_form(g, fi)

    if m is None:
        m = level_fn(gamma)
    r = len(m)

    if mp_list is None:
        # Default probes: r linearly independent dominant cocharacters near origin.
        # For A_n this gives a non-degenerate Gram matrix.
        if r == 1:
            mp_list = [(1,), (2,)]
        elif r == 2:
            mp_list = [(1, 1), (2, 1), (1, 2), (2, 2)]
        else:
            mp_list = [tuple(2 if j == i else 1 for j in range(r)) for i in range(r)]
            mp_list.append(tuple([1] * r))

    eqs = []
    for mT in mp_list:
        # Build T_{mT} chart-charge: interleaved (m_1, 0, m_2, 0, …)
        gT = tuple(x for vi in mT for x in (vi, 0))
        prod = alg.multiply(gT, gamma)
        target_lvl = tuple(a + b for a, b in zip(mT, m))
        hits = [(g, c) for g, c in prod.terms.items()
                if level_fn(g) == target_lvl]
        if len(hits) != 1:
            return None, f"non-unique level-{target_lvl} hits ({len(hits)}) for T_{mT}"
        _, c = hits[0]
        k = _single_qpow(c)
        if k is None:
            return None, f"non-unit-monomial coef {c} for T_{mT}"
        eqs.append((mT, k))

    # Solve ⟨m'_i, e⟩ = k_i for e (in ω-basis) using the first r probes.
    if len(eqs) < r:
        return None, f"need at least {r} probes, got {len(eqs)}"

    # Build r-x-r system from first r eqs
    M = [list(eqs[i][0]) for i in range(r)]
    b = [eqs[i][1] for i in range(r)]
    e = _gauss_jordan_solve(M, b)
    if e is None:
        return None, f"first {r} probes are linearly degenerate"

    # Verify on remaining probes
    for mT, k in eqs[r:]:
        pred = sum(mT[i] * e[i] for i in range(r))
        if pred != k:
            return None, f"inconsistent: T_{mT} predicts {pred}, got {k}"

    return tuple(e), None


def gamma_SU2(m, e):
    """Closed-form tropical map γ(m, e) ∈ ℤ² for SU(2) = A_1.

    Returns the chart-coordinate γ of the canonical basis element D_{m, e}
    in the pure SU(2) BPS K-algebra (doubled-Dynkin chart).  Piecewise
    linear with three chambers meeting at corners (m, 0) and (-m, 2m):

        south ray  (e ≤ 0):                  γ = (m, e)
        diagonal   (0 ≤ e ≤ 2m):             γ = (m − e, e)
        west ray   (e ≥ 2m):                 γ = (−m, 4m − e)

    For m = 0 only dominant e ≥ 0 is meaningful (Wilson lines, anti-
    dominant chart-electric).  All three chambers agree on m=0 and give
    γ = (0, −e).

    Verified empirically on the (m, e) grid m ∈ {0..4}, e ∈ {-4..7}; see
    test_gamma_SU2_closed_form.
    """
    if not isinstance(m, int) or m < 0:
        raise ValueError(f"m must be a non-negative integer, got {m}")
    if not isinstance(e, int):
        raise ValueError(f"e must be an integer, got {e}")
    if m == 0 and e < 0:
        raise ValueError(f"Wilson at m=0 requires dominant e >= 0, got e={e}")
    if e <= 0:
        return (m, e)
    if e <= 2 * m:
        return (m - e, e)
    return (-m, 4 * m - e)


def label_SU3(gamma, alg, fi, level_fn=None):
    """Inverse map γ → (m, e) for SU(3) canonical basis elements.

    Uses ``filtration_level_ADE_closed_form`` for m and ``extract_abstract_e``
    for e, with shortcuts for Wilson lines (m = 0) and T-atoms (e = 0).
    Returns ((m_1, m_2), (e_1, e_2)) with m_i ≥ 0 dominant.

    The Wilson floor m = 0 sits at the closure of multiple chambers and the
    direct q-probe at level (1, 1) is rank-deficient; for that case we read
    e directly off the chart (γ = (0, −e_1, 0, −e_2)).

    Parameters
    ----------
    gamma : tuple[int, ...]
        Chart γ = (v_1, e_1^chart, v_2, e_2^chart) in the SC interleaved basis.
    alg : BPSKAlgebra
        Chart engine (for the q-probe in extract_abstract_e).
    fi : list[dict]
        ``factor_info`` from ``pure_ade_lattice_data([("A", 2)])``.
    level_fn : callable, optional
        γ → m level function; defaults to ``filtration_level_ADE_closed_form``.
    """
    if len(gamma) != 4:
        raise ValueError(f"SU(3) chart γ must have 4 components, got {len(gamma)}")
    v1, ec1, v2, ec2 = gamma

    # Wilson special case: γ = (0, −e_1, 0, −e_2) with e_i ≥ 0 dominant.
    if v1 == 0 and v2 == 0 and ec1 <= 0 and ec2 <= 0:
        return ((0, 0), (-ec1, -ec2))

    if level_fn is None:
        from pure_ade_lattice import filtration_level_ADE_closed_form
        level_fn = lambda g: filtration_level_ADE_closed_form(g, fi)
    m = level_fn(gamma)

    # T-atom shortcut: γ = (m_1, 0, m_2, 0) with m_i ≥ 0.
    if ec1 == 0 and ec2 == 0 and v1 >= 0 and v2 >= 0:
        return ((v1, v2), (0, 0))

    # General: q-probe to extract e.
    e_om, err = extract_abstract_e(alg, fi, gamma, m=m, level_fn=level_fn)
    if e_om is None:
        raise ValueError(f"label_SU3: cannot extract e for γ={gamma}: {err}")
    e_int = tuple(int(x) if x.denominator == 1 else x for x in e_om)
    return (m, e_int)


def build_SU3_table(alg, fi, gammas, level_fn=None):
    """Build a (m, e) → γ table by inverting label_SU3 over a γ collection.

    Parameters
    ----------
    alg : BPSKAlgebra
        Chart engine for SU(3).
    fi : list[dict]
        factor_info for SU(3).
    gammas : iterable of tuple
        γ's to iterate over (e.g. from the precomputed Wilson-product
        dataset).
    level_fn : callable, optional
        γ → m level function; defaults to filtration_level_ADE_closed_form.

    Returns
    -------
    dict[tuple, tuple]
        Map ((m_1, m_2), (e_1, e_2)) → γ.  Multiple γ's can collide on
        the same (m, e); the first one wins.
    """
    if level_fn is None:
        from pure_ade_lattice import filtration_level_ADE_closed_form
        level_fn = lambda g: filtration_level_ADE_closed_form(g, fi)
    table = {}
    for g in gammas:
        try:
            lvl = level_fn(g)
        except Exception:
            continue
        # Wilson floor: read off directly.
        v1, ec1, v2, ec2 = g
        if lvl == (0, 0):
            if v1 == 0 and v2 == 0 and ec1 <= 0 and ec2 <= 0:
                table.setdefault(((0, 0), (-ec1, -ec2)), g)
            continue
        # T-atom: e=(0,0).
        if ec1 == 0 and ec2 == 0:
            table.setdefault((lvl, (0, 0)), g)
            continue
        ee, err = extract_abstract_e(alg, fi, g, m=lvl, level_fn=level_fn)
        if ee is None:
            continue
        ee_int = tuple(int(x) if x.denominator == 1 else x for x in ee)
        table.setdefault((lvl, ee_int), g)
    return table


def _gamma_SU3_closed_form_chamber(m, e):
    """Return γ from a closed-form chamber, or None if (m, e) is not in
    one of the safe chambers below.

    Safe chambers (verified against the V_MAX=8 M_W=3 Wilson-product
    dataset — 208 hits, 0 misses):

    * Wilson:                m = (0, 0), e_i ≥ 0
    * T-atom:                e = (0, 0)
    * South:                 e_1 ≤ 0 and e_2 ≤ 0          (m > 0)
    * Symmetric diagonal:    m_1 = m_2 and 0 ≤ e_i ≤ m_i
    * Symmetric mixed N1:    m_1 = m_2 and e_1 ≤ 0 ≤ e_2 ≤ m_2
    * Symmetric mixed N2:    m_1 = m_2 and e_2 ≤ 0 ≤ e_1 ≤ m_1

    For *asymmetric* m (m_1 ≠ m_2) with e in the dominant cone the
    Cartan coupling between the two nodes introduces non-trivial
    structure that has no clean closed form yet — ``gamma_SU3`` falls
    back to the precomputed table there.
    """
    m1, m2 = m
    e1, e2 = e
    if m == (0, 0):
        if e1 >= 0 and e2 >= 0:
            return (0, -e1, 0, -e2)
        return None
    if e1 == 0 and e2 == 0:
        return (m1, 0, m2, 0)
    if e1 <= 0 and e2 <= 0:
        return (m1, e1, m2, e2)
    if m1 == m2:
        if 0 <= e1 <= m1 and 0 <= e2 <= m2:
            return (m1 - e1, e1, m2 - e2, e2)
        if e1 <= 0 and 0 <= e2 <= m2:
            return (m1, e1, m2 - e2, e2)
        if e2 <= 0 and 0 <= e1 <= m1:
            return (m1 - e1, e1, m2, e2)
    return None


def gamma_SU3(m, e, table=None):
    """Forward map (m, e) → γ for SU(3) canonical basis elements.

    Closed-form for ~83 % of the labels via four chambers (Wilson,
    T-atom, south, diagonal-interior, two mixed-interior); the
    remaining ones fall back to a precomputed *table* built by
    ``build_SU3_table``.

    The fully-general piecewise-linear formula (analogue of the
    3-chamber ``gamma_SU2``) is open work — the Cartan coupling
    between nodes 1 and 2 introduces chamber boundaries beyond
    e_i = m_i where no clean per-node decomposition exists.

    Parameters
    ----------
    m : tuple[int, int]
        Dominant cocharacter (m_1, m_2) with m_i ≥ 0.
    e : tuple[int, int]
        Weight (e_1, e_2).  For m = (0, 0) (Wilson floor) e_i must be ≥ 0
        dominant; otherwise integer.
    table : dict, optional
        Precomputed (m, e) → γ map (see ``build_SU3_table``).  Used
        as fallback for chambers without closed forms.  May be None
        if (m, e) lies in one of the closed-form chambers.

    Raises
    ------
    ValueError
        If m is non-dominant, e is non-dominant for a Wilson, or the
        general dyon (m, e) is neither in a closed-form chamber nor
        in the table.
    """
    if not (isinstance(m, tuple) and len(m) == 2):
        raise ValueError(f"m must be a 2-tuple, got {m}")
    if not (isinstance(e, tuple) and len(e) == 2):
        raise ValueError(f"e must be a 2-tuple, got {e}")
    m1, m2 = m
    e1, e2 = e
    if m1 < 0 or m2 < 0:
        raise ValueError(f"m must be dominant (m_i ≥ 0), got {m}")
    if m == (0, 0) and (e1 < 0 or e2 < 0):
        raise ValueError(
            f"Wilson at m=(0,0) requires dominant e (e_i ≥ 0), got {e}")

    # 1. Closed-form fast path
    cf = _gamma_SU3_closed_form_chamber(m, e)
    if cf is not None:
        return cf

    # 2. Table fallback
    if table is not None and (m, e) in table:
        return table[(m, e)]

    raise ValueError(
        f"gamma_SU3({m}, {e}): not in a closed-form chamber and not in "
        f"table; extend the table by passing more γ's to build_SU3_table.")


def label_SU2(gamma):
    """Inverse of gamma_SU2: chart γ → (m, e) for SU(2) canonical basis elements
    that are reachable as D_{m, e}.  Disambiguates the three chambers from γ.

    Returns (m, e) with m ≥ 0; raises ValueError if γ is not a canonical
    chart-realization of any D_{m, e}.
    """
    v, ec = gamma
    # Wilson special case (m=0): chart γ=(0, -e) with e ≥ 0 dominant.
    if v == 0 and ec <= 0:
        return (0, -ec)
    # South ray (m ≥ 1, e ≤ 0): v = m ≥ 1, ec = e ≤ 0
    if ec <= 0 and v >= 1:
        return (v, ec)
    # West ray (m ≥ 1, e ≥ 2m): v = -m < 0, ec = 4m − e ≤ 2m
    if v < 0 and ec <= -2 * v:
        return (-v, -4 * v - ec)
    # Diagonal (m ≥ 1, 0 ≤ e ≤ 2m): v = m − e, ec = e
    if ec >= 0 and v + ec >= 0 and ec <= 2 * (v + ec):
        return (v + ec, ec)
    raise ValueError(f"γ={gamma} is not in the SU(2) canonical D_{{m, e}} chart")


def _gauss_jordan_solve(M, b):
    """Solve M·x = b with M ∈ Z^{r×r}, b ∈ Z^r.  Returns x as
    tuple of Fractions, or None if singular."""
    r = len(M)
    A = [[Fraction(M[i][j]) for j in range(r)] + [Fraction(b[i])] for i in range(r)]
    for col in range(r):
        piv = None
        for row in range(col, r):
            if A[row][col] != 0:
                piv = row
                break
        if piv is None:
            return None
        A[col], A[piv] = A[piv], A[col]
        f = A[col][col]
        A[col] = [x / f for x in A[col]]
        for row in range(r):
            if row != col and A[row][col] != 0:
                g = A[row][col]
                A[row] = [A[row][j] - g * A[col][j] for j in range(r + 1)]
    return [A[i][r] for i in range(r)]


# ============================================================================
# A natural extension (not implemented) is a wrapper class exposing the
# canonical basis directly through (m, e) — .D(m, e), .T(m), .W(e), a cached
# (m, e) ↔ γ bijection, and multiplication in (m, e) coordinates — built on
# the primitives above.  Note that the "Weyl orbit" elements (m, e) at
# non-dominant chart-magnetic v are empirically distinct elements with
# different e_abs, so such a wrapper must expose them as separate D_{m, e}
# entries.
# ============================================================================
