"""``FiniteA1D3KAlgebra`` -- standalone su2-flavored ConeKAlgebra.

Generated by ``generate_finite_kalg.py`` (generator not included in
this repository) from a finite BPS quiver.  All data (mult_gens,
cones, cocycle, ρ-permutation, cross_product) inlined as Python
literals.  No runtime dependency on the BPS realisation layer.
"""
from __future__ import annotations

from cone_data import FiniteConeData
from cone_kalgebra import ConeKAlgebra
from laurent_poly import LaurentPoly
from zplus_ring import SU2ZPlusRing, RElement, RLaurent
_R = SU2ZPlusRing()

A1D3_BPS_PAIRING = [[0, 1, 0], [-1, 0, 0], [0, 0, 0]]
A1D3_BPS_NODE_CHARGES = [(1, 0, 0), (0, 1, 1), (0, 1, -1)]

A1D3_MULT_GENS_LATTICE = ((-1, -2, 0), (-1, -1, 0), (-1, 0, 0), (0, -1, 0), (0, 1, 0), (1, 0, 0))

A1D3_CONES = ((3, 5), (4, 5), (3,), (4,), (0, 3), (2, 4), (1,), (0, 1), (1, 2))

A1D3_COCYCLE_TABLE = {(3, 5): 1, (5, 3): -1, (4, 5): -1, (5, 4): 1, (0, 3): 1, (3, 0): -1, (2, 4): -1, (4, 2): 1, (0, 1): -1, (1, 0): 1, (1, 2): -1, (2, 1): 1}

A1D3_RHO_PERM = {0: 2, 1: 4, 2: 5, 3: 1, 4: 3, 5: 0}

A1D3_RHO_DELTA = {}

A1D3_CONE_CANON = {}

A1D3_CROSS_TABLE = {
    (0, 0): [('RL', {0: {0: 1}}, (0, 0))],
    (0, 1): [('RL', {-2: {0: 1}}, (1, 0))],
    (0, 2): [('RL', {-2: {0: 1}}, (1, 1)), ('RL', {-1: {1: 1}}, (1,)), ('RL', {0: {0: 1}}, ())],
    (0, 3): [('RL', {2: {0: 1}}, (3, 0))],
    (0, 4): [('RL', {-1: {0: 1}}, (1,)), ('RL', {0: {1: 1}}, ()), ('RL', {1: {0: 1}}, (3,))],
    (0, 5): [('RL', {0: {0: 1}}, ()), ('RL', {1: {1: 1}}, (3,)), ('RL', {2: {0: 1}}, (3, 3))],
    (1, 0): [('RL', {2: {0: 1}}, (0, 1))],
    (1, 1): [('RL', {0: {0: 1}}, (1, 1))],
    (1, 2): [('RL', {0: {0: 1}}, (1, 2))],
    (1, 3): [('RL', {1: {0: 1}}, (0,)), ('RL', {0: {0: 1}}, ())],
    (1, 4): [('RL', {0: {0: 1}}, ()), ('RL', {-1: {0: 1}}, (2,))],
    (1, 5): [('RL', {1: {0: 1}}, (3,)), ('RL', {0: {1: 1}}, ()), ('RL', {-1: {0: 1}}, (4,))],
    (2, 0): [('RL', {0: {0: 1}}, ()), ('RL', {1: {1: 1}}, (1,)), ('RL', {2: {0: 1}}, (1, 1))],
    (2, 1): [('RL', {2: {0: 1}}, (1, 2))],
    (2, 2): [('RL', {0: {0: 1}}, (2, 2))],
    (2, 3): [('RL', {-1: {0: 1}}, (4,)), ('RL', {0: {1: 1}}, ()), ('RL', {1: {0: 1}}, (1,))],
    (2, 4): [('RL', {-2: {0: 1}}, (4, 2))],
    (2, 5): [('RL', {-2: {0: 1}}, (4, 4)), ('RL', {-1: {1: 1}}, (4,)), ('RL', {0: {0: 1}}, ())],
    (3, 0): [('RL', {0: {0: 1}}, (3, 0))],
    (3, 1): [('RL', {0: {0: 1}}, ()), ('RL', {-1: {0: 1}}, (0,))],
    (3, 2): [('RL', {-1: {0: 1}}, (1,)), ('RL', {0: {1: 1}}, ()), ('RL', {1: {0: 1}}, (4,))],
    (3, 3): [('RL', {0: {0: 1}}, (3, 3))],
    (3, 4): [('RL', {1: {0: 1}}, (5,)), ('RL', {0: {0: 1}}, ())],
    (3, 5): [('RL', {2: {0: 1}}, (5, 3))],
    (4, 0): [('RL', {1: {0: 1}}, (1,)), ('RL', {-1: {0: 1}}, (3,)), ('RL', {0: {1: 1}}, ())],
    (4, 1): [('RL', {1: {0: 1}}, (2,)), ('RL', {0: {0: 1}}, ())],
    (4, 2): [('RL', {2: {0: 1}}, (2, 4))],
    (4, 3): [('RL', {0: {0: 1}}, ()), ('RL', {-1: {0: 1}}, (5,))],
    (4, 4): [('RL', {0: {0: 1}}, (4, 4))],
    (4, 5): [('RL', {0: {0: 1}}, (4, 5))],
    (5, 0): [('RL', {-2: {0: 1}}, (3, 3)), ('RL', {-1: {1: 1}}, (3,)), ('RL', {0: {0: 1}}, ())],
    (5, 1): [('RL', {-1: {0: 1}}, (3,)), ('RL', {0: {1: 1}}, ()), ('RL', {1: {0: 1}}, (4,))],
    (5, 2): [('RL', {0: {0: 1}}, ()), ('RL', {1: {1: 1}}, (4,)), ('RL', {2: {0: 1}}, (4, 4))],
    (5, 3): [('RL', {-2: {0: 1}}, (3, 5))],
    (5, 4): [('RL', {2: {0: 1}}, (4, 5))],
    (5, 5): [('RL', {0: {0: 1}}, (5, 5))],
}

def _make_coeff(kind, data):
    if kind == 'LP':
        return LaurentPoly(data)
    if kind == 'RL':
        d = {q: RElement(_R, terms) for q, terms in data.items()}
        return RLaurent(_R, d)
    raise ValueError(f'Unknown coeff kind: {kind!r}')

class _ExportedFiniteA1D3KAlgebraConeData(FiniteConeData):
    def coefficient_ring(self):
        return _R

    def mult_gens(self):
        return tuple(range(len(A1D3_MULT_GENS_LATTICE)))

    def cones(self):
        return tuple(frozenset(c) for c in A1D3_CONES)

    def q_commute(self, g, h):
        return g == h or (g, h) in A1D3_COCYCLE_TABLE

    def cocycle(self, g, h):
        if g == h: return 0
        return A1D3_COCYCLE_TABLE[(g, h)]

    def cross_product(self, g, h):
        terms = A1D3_CROSS_TABLE.get((g, h), [])
        return tuple((_make_coeff(kind, data), word) for kind, data, word in terms)

    def to_cone_label(self, native_label):
        gens = frozenset(i for i, p in native_label if p != 0)
        powers = {i: p for i, p in native_label if p != 0}
        return (gens, powers)

    def from_cone_label(self, gens, powers):
        return tuple(sorted((i, powers[i]) for i in gens))

    def canonicalize_cone_label(self, cone, gens, powers):
        # Apply subword substitutions; q-phase = full cone_label_phase
        # difference between before/after each step (principled — uses
        # the same formula as cone_label_phase, so signs are consistent).
        from itertools import combinations as _C
        def _full_phase(d):
            # cone_label_phase = -Σ_{i<j in sorted flat word} cocycle(i, j).
            ks = sorted(g for g, p in d.items() if p > 0)
            total = 0
            for ii in range(len(ks)):
                gi, pi = ks[ii], d[ks[ii]]
                # pairs (gi, gi) — same gen, count C(pi, 2) pairs
                # cocycle(gi, gi) is 0 so skip.
                for jj in range(ii + 1, len(ks)):
                    gj, pj = ks[jj], d[ks[jj]]
                    total += A1D3_COCYCLE_TABLE.get((gi, gj), 0) * pi * pj
            return -total
        cur = {g: p for g, p in powers.items() if p != 0}
        accum_phase = 0
        changed = True
        while changed:
            changed = False
            in_cone = sorted(cur.keys())
            # Try pair subs, then triple subs.
            for size in (2, 3):
                if changed: break
                for combo in _C(in_cone, size):
                    if any(cur.get(g, 0) <= 0 for g in combo): continue
                    key = tuple((g, 1) for g in combo)
                    entry = A1D3_CONE_CANON.get(key)
                    if entry is None: continue
                    canon, _stored_phase = entry  # recompute properly
                    new_cur = dict(cur)
                    for g in combo: new_cur[g] -= 1
                    for g, p in canon: new_cur[g] = new_cur.get(g, 0) + p
                    new_cur = {g: p for g, p in new_cur.items() if p > 0}
                    accum_phase += _full_phase(new_cur) - _full_phase(cur)
                    cur = new_cur
                    changed = True
                    break
        new_powers = dict(cur)
        new_gens = frozenset(new_powers)
        return new_gens, new_powers, accum_phase

    def cycle_period_bound(self):
        return len(A1D3_MULT_GENS_LATTICE)

class FiniteA1D3KAlgebra(ConeKAlgebra):
    """Self-contained su2-flavored ConeKAlgebra.

    Generated by ``generate_finite_kalg.generate`` from
    a finite ADE BPS quiver.
    """

    _R = _R
    _rho_perm = A1D3_RHO_PERM
    _rho_inv_perm = {v: k for k, v in A1D3_RHO_PERM.items()}
    _ray_idx_to_gamma = A1D3_MULT_GENS_LATTICE

    def __init__(self):
        self._cone_data = _ExportedFiniteA1D3KAlgebraConeData()

    def coefficient_ring(self): return self._R
    def identity(self): return ()
    def cone_data(self): return self._cone_data

    def rho(self, label):
        return tuple(sorted(
            (self._rho_perm.get(i, i), p) for (i, p) in label
        ))

    def rho_inverse(self, label):
        return tuple(sorted(
            (self._rho_inv_perm.get(i, i), p) for (i, p) in label
        ))

    def rho_R_element(self, elem):
        return self.rho_element(elem)

    def _trace_residual(self, seed_label, K):
        from elem_traces import trace_residual
        return trace_residual('a1d3', self, seed_label, K)
