"""
u1a1deven_cone_kalgebra.py
==========================

`U1A1DevenConeKAlgebra(k)` — the **U(1)-gauged** `[A_1, D_{2k+2}]` as a
**self-contained** (BPS-free) ray-keyed **QT-cone** `ConeKAlgebra` over
`SU2ZPlusRing`.  The D-even analogue of the gauged-A `U1A1AoddKAlg`.

Self-contained `multiply` (no oracle fallback)
----------------------------------------------
Built from the *complete* cone tables of `u1a1deven_cone_build.DevenConeTables`,
which extract — once, from the fast BPS-free RG oracle `U1A1DevenRGKAlgebra`
(auxiliary `A1A2k(k) ⊗ QT(Z²) ⊗ SU(2)`) — the full ray set via the
construction (user, 2026-06-21):

    rays = monomial-RG canonical elements (seeds);
    cones = q-commuting cliques of rays;
    **ρ-images of the seed cones are new cones**;
    mult-gens = the union of all cones' rays.

This *replaces* the earlier under-counting `atomic_gens` heuristic (which left
`multiply` falling back to the oracle on ρ-image labels) and the A1A2k-letter
`to_cone_label` (its self-described "blind alley").  Native labels are now
**ray-keyed** like `U1A1AoddKAlg`: `(factors, e_X01)` with `factors` a sorted
tuple of `(ray_id, exp)` and `e_X01 ∈ Z` the `X_{0,1}` torus power — so
`to_cone_label`/`from_cone_label` are trivial bijections, the factoring is done
once at construction (the decode lookup), and `multiply` runs the generic
cone-monomial reducer with **no per-multiply oracle call**.

  * **torus** `X_{0,1}^{±1}` — the clean Laurent matter direction;
  * the magnetic `X_{1,0}` is a *one-directional conventional* ray (its inverse
    threads the matter), with its negative-magnetic tower generated by the
    ρ-image rays in the closed set;
  * **ρ** is the closed-form per-ray permutation (`DevenConeTables.rho_native`);
  * SU(2) χ-content rides in the `SU2ZPlusRing` coefficient (the cross_product
    coefficients are `RLaurent[SU(2)]`).

Validated k=1 (D₄): 16 rays + `X_{0,1}^±`, 20 cones; `multiply` reproduces the
oracle on every ray pair with **0 fallback** (construction ~1.5 s).

Trace — exact closed-form gauge sector (oracle-free, arbitrary 𝖖)
----------------------------------------------------------------
`c₁` (the `X_{1,0}` 't Hooft magnetic charge) is a ρ²-invariant the
quantum-torus trace annihilates exactly (`c₁ ≠ 0 ⇒ Tr = 0`).  The surviving
`c₁ = 0` **gauge sector** — `Tr(1)` and the whole v-tower `Tr(X_{0,1}ⁿ)` — is
the **exact closed-form character** `exact_characters.deven_gauged_xn_qn` (the
`xⁿ` slice of Creutzig's `(A_1, D_{2p})` index, `p = k+1`; arbitrary 𝖖, no
oracle, no freeze cap).  Cross-verified against the repo's INDEPENDENT
`sl(3)₋₃/₂` Kac–Wakimoto vacuum character (theta sums, no cone/BPS) for the
slices `n = 0…4` to `q_d²⁸` — which exposed and replaced the cone oracle's
fixed-cutoff matter-tower truncation from `q_d²⁴` on.  (That cross-check is
`k=1`; for **even k** the odd
v-powers carry genuine **odd-q_d** terms — the `√Q = -q_d` branch — which the
closed form now emits with sign `(-1)^{sh}`, verified for `k=2`/D6 against the
oracle's `Tr(X01ⁿ)`, `n=0…3`.)  The matter-ray seeds serve from the frozen table
(both `X01` signs — `Tr(X01⁻ᵐ) ≠ Tr(X01⁺ᵐ)` in general, only self-conjugate rays
are symmetric).  For **k=1** the spine-free SU(2) bootstrap (`matter_seed_trace`)
extends the freeze; for **k≥2** that bootstrap is intractable (the ~3× cone's
30-ray deep-label reductions don't scale, finding A15), so it is guarded off
(`_matter_bootstrap_tractable()`) and matter serves from the shipped freeze
(`_seed_trace` honest-fails only for seeds *outside* the shipped box).  For
**D6 (k=2) the freeze is COMPLETE: 221/221 seeds** (10 ρ²-canon rays × the
`|m|≤10` box + v-tower), and now **fully derived from the reliable A1Dodd×QT
oracle** `U1A1DevenViaDoddRG` (#632) — legacy-free (the whole freeze is
oracle-read, not just the hard rays; the 8 non-deep rays were independently
re-verified to agree with the new oracle through q⁸, then extended to q¹⁰).
The two deepest **composite** rays 20/24 (3-chord / multiplicity-2 sections,
vs the lights' 1–2 chord) are mag-0 matter, so their trace is **nonzero** (the
magnetic-charge selection rule's converse — `Tr(E⁻¹L_aE) = 𝖖^{c₁}Tr(L_a)` forces
`Tr=0` *only* for `c₁≠0`; user 2026-06-24).  They are the cone image of the
oracle's **`(1,0,·)` odd-`𝖖` matter family** — the *unique* family whose trace
carries odd powers of `𝖖` (orbit "E"; `c1 = m`, support `m ∈ {−1,0,1}`):
`Tr(ray20@0)=Tr(ray24@0)= −q+(2−χ₂)q³+(−1+χ₂−χ₄)q⁵+(χ₄−χ₆)q⁷
+(−χ₂−χ₄+χ₆−χ₈)q⁹+…` (onset q¹) and `Tr(ray·@±1)= χ₁q⁶+(−χ₁+χ₃)q⁸+χ₅q¹⁰+…`
(onset q⁶); `|m|≥2` vanish (QT support bound).  The values are read by matching
each cone ρ-orbit to its oracle matter family by trace tower (`c1 = ±m + β`,
validated against the 8 non-deep rays) — **NOT** the earlier ρ-transport
derivation (`ray14·ray18=q·ray24+𝟙`), which gave the wrong deep coefficients and
is retracted (finding A16).  The oracle trace is exact-converged (K=12≡K=16
on `q≤10`), so the deep high-spin terms (e.g. χ₈ at q⁹) are real physics, not
windowing noise.  **The legacy A1A2k⊗QT⊗SU(2) oracle wrongly zeroed rays 20/24
entirely.**  Cross-validated by canonical orthonormality (`I_{20,20}=I_{24,24}
=1+O(𝖖)`, off-diagonals `O(𝖖)`).  `_seed_trace` is oracle-free at runtime (the
oracle is only a build-time table learner; verified with it blocked).

D8 (k=3) — built on the **reliable A1Dodd×QT oracle**, legacy-free (user, 2026-06-25)
------------------------------------------------------------------------------------
For **D8 (k=3)** the cone tables AND the trace freeze are built on the fast,
correct `U1A1DevenViaDoddRG` (A1Dodd(k-1)⊗QT) oracle via `DevenDoddConeTables`
(`u1a1deven_dodd_build.py`) — *not* the legacy `A1A2k⊗QT⊗SU(2)` oracle.  This
makes k=3 **fully oracle-consistent**: `multiply`/`ρ` AND the matter freeze come
from the *same* (correct) oracle, so the cross-oracle matching that k=2 needed is
**not required** — the freeze is read directly off the build oracle (the section
`(dodd_word,(c0_mag,c1_x01))` IS an oracle label; the trace is its A1Dodd×QT Schur
index).  The build extracts 120 rays / 3432 cones / 88 mag-0 matter rays via the
oracle's public API (`r_label_decompose`, `RG`, `multiply`, `ρ`); the freeze is
read with a ρ-canonical cache (the trace is ρ-invariant).  Validated by canonical
orthonormality (`I_{a,a}=1+O(𝖖)`, off-diagonals `O(𝖖)`) on every mag-0 orbit rep.
Runtime is spine-free (frozen tables + freeze; no oracle).
"""
from __future__ import annotations

import sys, os
_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from kalgebra import Element
from laurent_poly import LaurentPoly
from zplus_ring import ZPlusRing, SU2ZPlusRing, RLaurent, RPowerSeries
from cone_data import FiniteConeData, Cone
from cone_kalgebra import ConeKAlgebra
from u1a1deven_cone_build import (
    DevenConeTables, build_tables, E_GEN, E_INV, _gen_sort_key)
# NOTE: `u1a1deven_rgkalgebra` (the RG oracle) is imported LAZILY in the
# `_oracle` property only — the frozen runtime path never builds it, so the
# module drops cleanly into a strict-isolation release (the u1e7 pattern).


class U1A1DevenConeData(FiniteConeData):
    """Ray-keyed QT-cone data wrapping the self-contained `DevenConeTables`.

    Native label = `(factors, e_X01)`: `factors` a sorted tuple of
    `(ray_id, exp)`, `e_X01` the `X_{0,1}` torus power.  `X_{0,1}^±` are the
    torus letters `E_GEN`/`E_INV`; conventional rays are integer ids."""

    def __init__(self, tables: DevenConeTables) -> None:
        self._tb = tables
        self._R = tables.R
        # cones include the X_01 torus gens (q-commute with everything).
        self._cones = tuple(frozenset(set(c) | {E_GEN, E_INV})
                            for c in tables.cones)

    # -- ConeData primitives ---------------------------------------------
    def coefficient_ring(self) -> ZPlusRing:
        return self._R

    def mult_gens(self):
        return self._tb.mult_gens

    def cones(self):
        return self._cones

    def q_commute(self, g, h) -> bool:
        return self._tb.q_commute_gen(g, h)

    def cocycle(self, g, h) -> int:
        return self._tb.cocycle_gen(g, h)

    def cross_product(self, g, h):
        return self._tb.cross_gen(g, h)

    def canonical_cone_order(self, gens):
        # ray ids (ints) before torus sentinels (tuples).
        return tuple(sorted(gens, key=_gen_sort_key))

    # -- ray-keyed label bijection (trivial) -----------------------------
    def to_cone_label(self, native):
        factors, e_X01 = native
        gens, powers = set(), {}
        for (rid, exp) in factors:
            if exp > 0:
                gens.add(rid); powers[rid] = powers.get(rid, 0) + exp
        if e_X01 > 0:
            gens.add(E_GEN); powers[E_GEN] = e_X01
        elif e_X01 < 0:
            gens.add(E_INV); powers[E_INV] = -e_X01
        return frozenset(gens), powers

    def from_cone_label(self, gens, powers):
        fac = sorted((g, powers[g]) for g in gens
                     if g not in (E_GEN, E_INV) and powers.get(g, 0) != 0)
        factors = tuple((g, e) for (g, e) in fac)
        e_X01 = powers.get(E_GEN, 0) - powers.get(E_INV, 0)
        return (factors, e_X01)

    def canonicalize_cone_label(self, cone, gens, powers):
        """Identify cone labels that are the same algebra element (the ray set
        is non-simplicial: a ray can equal a product of others × torus, e.g.
        `L_11 = L_10·L_13·X_01^{-3}`).  Canonical rep = the decode's word for
        the element's oracle section; both are the canonical basis element with
        that section, so the q-phase is 0."""
        native = self.from_cone_label(gens, powers)
        S = self._tb.oracle_section_of_native(native)
        if S is None:
            return gens, powers, 0
        canon = self._tb.native_of_oracle_section(S)
        cg, cp = self.to_cone_label(canon)
        if (cg, cp) == (gens, powers):
            return gens, powers, 0           # no redundancy — unchanged
        # L_orig == L_canon (same canonical element / oracle section), so
        #   L_{(gens,powers)} = q^{phase(canon) - phase(orig)} · L_{(cg,cp)}.
        q_phase = self.cone_label_phase(cg, cp) - self.cone_label_phase(gens, powers)
        return cg, cp, q_phase

    # -- QTCone wiring (torus on X_{0,1}) --------------------------------
    def _torus_inverse_letter(self, g):
        if g == E_GEN:
            return E_INV
        if g == E_INV:
            return E_GEN
        return None

    def iter_cones(self):
        for cone in self._cones:
            yield Cone(self, cone, torus_gens=frozenset({E_GEN, E_INV}) & cone)

    def cycle_period_bound(self) -> int:
        return 2 * (2 * (self._tb.k or 1) + 4)


class U1A1DevenConeKAlgebra(ConeKAlgebra):
    """U(1)-gauged `[A_1, D_{2k+2}]` — self-contained ray-keyed QT-cone over
    `R(SU(2))`.  `multiply`/`ρ` are oracle-free closed forms; the `c₁ = 0` trace
    seeds are **bootstrapped from `Tr(1)` alone** (`bootstrap_all_seeds`,
    spine-free) — the live `trace` runs without the oracle."""

    def __init__(self, k: int):
        if k < 1:
            raise ValueError(f"k must be >= 1, got {k}")
        self.k = k
        self._R = SU2ZPlusRing()
        # Cone tables: loaded **spine-free** from the shipped freeze
        # (`u1a1deven_tables_k{k}.pkl`) when present — construction then needs no
        # oracle (the strict-isolation release path) — else *learned* (ρ-folded,
        # closed-form q-powers) from the fast RG oracle and memoised per process.
        # Either way multiply/ρ are oracle-free closed forms (no mult-table
        # freeze: the q-powers are derived, unlike the u1a1aodd sibling).
        self._tb = build_tables(k, allow_frozen=True)
        self._oracle_ = None
        self._cone_data = U1A1DevenConeData(self._tb)
        self._seed_cache: dict = {}
        self._frozen_seeds = self._load_frozen_seeds()   # ρ²-canon → RPowerSeries

    @property
    def _oracle(self):
        """The RG oracle — reused from the cone tables (which built it to learn
        the mult table), so the trace seeding needs no second build."""
        if self._oracle_ is None:
            self._oracle_ = self._tb.oracle
        return self._oracle_

    def coefficient_ring(self) -> ZPlusRing:
        return self._R

    def identity(self):
        return ((), 0)

    def cone_data(self):
        return self._cone_data

    def multiply(self, a, b):
        """Self-contained cone multiply — no oracle fallback."""
        return self._multiply_via_cone_data(a, b)

    def rho(self, a):
        return self._tb.rho_native(a)

    def rho_inverse(self, a):
        return self._tb.rho_inv_native(a)

    def _canonical_rho2_orbit_rep(self, label):
        """Closed-form drift-quotient ρ²-orbit rep (ρ² shears the X_{0,1} torus
        → infinite orbits).  Required by the generic cone Layer-1 trace
        reduction / the smart trace bootstrap."""
        return self._tb.rho2_canon(label)

    # -- trace: magnetic-charge vanishing + cached oracle seeds (c₁ = 0) --
    def _oracle_section(self, native):
        sec = self._tb.oracle_section_of_native(native)
        if sec is None:
            raise ValueError(f"trace: {native!r} is not a cone monomial")
        return sec

    @staticmethod
    def _mag_charge(section):
        (_chord, (c1, _c2)), _ = section
        return c1

    def trace(self, a, K: int = 20):
        """μ-refined SU(2) Schur index, **bootstrapped**: Layer-1 reduces
        `Tr(a)` to *fundamental* seeds (v-tower `X01^m` + single matter rays)
        by the generic cone ρ²-twisted cyclicity (over the closed-form
        multiply), then each fundamental seed value is read off `_seed_trace`.
        `c₁ ≠ 0 ⇒ Tr = 0` (exact, per seed).  Cyclicity collapses the deep-power
        / multi-ray monomials that would otherwise need their own seed value."""
        simplified = self.cone_data().simplify_trace_via_cone_data(self, a)
        result = RPowerSeries.zero(self._R, K)
        for lab, coeff in simplified.terms.items():
            if hasattr(coeff, "is_zero") and coeff.is_zero():
                continue
            if self._mag_charge(self._oracle_section(lab)) != 0:
                continue                              # c₁ ≠ 0 ⇒ Tr = 0
            seed = self._tb.rho2_canon(lab)           # fundamental ρ²-orbit rep
            if isinstance(coeff, LaurentPoly):
                coeff = RLaurent(self._R, dict(coeff._coeffs))
            emin = min(coeff.coeffs) if coeff.coeffs else 0
            wide = K - emin if emin < 0 else K
            result = result + self._seed_trace(seed, wide) * coeff
        return RPowerSeries(self._R, dict(result.coeffs), K)

    def _closed_form_gauge_trace(self, e, K):
        """`Tr(X_{0,1}^e)` — the whole **gauge sector** (vacuum `e=0` + v-tower)
        as an **exact closed-form character** (arbitrary 𝖖, no oracle): the `xᵉ`
        slice of Creutzig's `(A_1, D_{2p})` index, `p = k+1`
        (`exact_characters.deven_gauged_xn_qn`).  Cross-verified against the
        repo's INDEPENDENT `sl(3)₋₃/₂` Kac–Wakimoto vacuum character (theta sums)
        for `e = 0…4` to `q_d²⁸`; this is what exposed the cone-oracle's
        fixed-cutoff matter-tower truncation from `q_d²⁴` on."""
        from exact_characters import deven_gauged_xn_qn
        return self._qn_to_rps(deven_gauged_xn_qn(self.k, e, K), K)

    def _seed_trace(self, seed, K):
        factors, e = seed
        # GAUGE SECTOR (Tr(1) + v-tower X_{0,1}^e): exact closed-form character,
        # arbitrary 𝖖, oracle-free.  Authoritative — bypasses the frozen deep
        # tail (which cached the now-superseded oracle past q_d²²) and the
        # unsound matter bootstrap; never recurses.
        if not factors:
            cached = self._seed_cache.get(seed)
            if cached is not None and cached[0] >= K:
                return RPowerSeries(self._R, dict(cached[1].coeffs), K)
            series = self._closed_form_gauge_trace(e, K)
            self._seed_cache[seed] = (K, series)
            return series
        # MATTER SEED: the stand-alone SU(2) bootstrap (`matter_seed_trace`,
        # oracle-free), fed the exact closed-form gauge tower as known input.
        # Correct at arbitrary 𝖖 but HEAVY beyond the frozen depth (the per-ray
        # deep-label cone reductions dominate); the frozen table serves its
        # depth instantly and the bootstrap extends it.  The standing speed item
        # is to feed exact matter seeds (per-ray module characters) so the
        # solver need not generate those rows.  Honest-fail only if the seed
        # lies outside the bootstrap's solved X01-tower range.
        fr = self._frozen_seeds.get(seed)
        if fr is not None and fr.K >= K:
            return RPowerSeries(self._R, dict(fr.coeffs), K)
        cached = self._seed_cache.get(seed)
        if cached is not None and cached[0] >= K:
            return RPowerSeries(self._R, dict(cached[1].coeffs), K)
        # The SU(2) matter bootstrap is tractable only on the small D4 (k=1) cone;
        # for k>=2 (D6+, ~3x the rays) its 30-ray deep-label reductions don't
        # scale (finding A15), so honest-fail FAST rather than hang — the
        # shipped freeze is the matter source there.
        if self._matter_bootstrap_tractable():
            qn = self.matter_seed_trace(K).get(seed)
            if qn is not None:
                series = self._qn_to_rps(qn, K)
                self._seed_cache[seed] = (K, series)
                return series
            reason = "outside the bootstrap's solved X01-tower range"
        else:
            reason = "the bootstrap is intractable for this cone size (A15); the " \
                     "shipped freeze is COMPLETE on the |m|<=10 seed box (k=2: " \
                     "221/221) but this seed lies outside it, and the W_p " \
                     "module closed forms are the open arbitrary-q item"
        raise ValueError(
            f"deven matter seed {seed!r} at 𝖖^{K} is beyond the shipped freeze "
            f"(k={self.k}); {reason}")

    def _matter_bootstrap_tractable(self) -> bool:
        """Whether the spine-free SU(2) matter bootstrap is feasible.  Only on
        the small D4 (k=1) cone: k>=2's 30-ray deep-label cone reductions don't
        scale (finding A15)."""
        return self.k <= 1

    def _qn_to_rps(self, qn, K):
        """`{𝖖: {irrep: int}}` (the bootstrap's output) → `RPowerSeries` over
        `R(SU(2))`."""
        coeffs = {}
        for q, d in qn.items():
            if q > K:
                continue
            re = None
            for n, c in d.items():
                term = c * self._R.basis_element(n)
                re = term if re is None else re + term
            if re is not None:
                coeffs[q] = re
        return RPowerSeries(self._R, coeffs, K)

    # -- frozen seed table (self-contained, oracle-free trace) -----------
    @staticmethod
    def _frozen_path(k):
        import os
        return os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            f"u1a1deven_traces_k{k}.pkl")

    def _load_frozen_seeds(self):
        import os, pickle
        p = self._frozen_path(self.k)
        if not os.path.exists(p):
            return {}
        with open(p, "rb") as f:
            return pickle.load(f)

    def freeze_traces(self, K=16, max_chord_len=2, n_max=None):
        """Compute the ρ²-canon mag-0 seed traces to order `K` (from the
        oracle) and pickle them, so later constructions read an oracle-free
        trace.  Enumerates the v-tower X_{0,1}^n and the matter rays × X_{0,1}^m
        up to `n_max` / `max_chord_len`.  The v-tower is the closed recursion;
        the matter families are the hard-coded ('RG answer') part."""
        import pickle
        if n_max is None:
            n_max = K + 2
        tb = self._tb
        mag0 = [i for i in range(len(tb.rays)) if tb.ray_section[i][0][1][0] == 0]
        seeds = set()
        for n in range(0, n_max + 1):
            seeds.add(((), n))                                # v-tower
        for i in mag0:
            for m in range(0, n_max + 1):
                seeds.add(tb.rho2_canon(((((i, 1),), m))))    # matter towers
        frozen = {}
        for s in seeds:
            frozen[s] = self._oracle.trace(self._oracle_section(s), K)
        with open(self._frozen_path(self.k), "wb") as f:
            pickle.dump(frozen, f)
        self._frozen_seeds = frozen
        return self._frozen_path(self.k)

    def matter_seed_trace(self, K):
        """All matter-ray seed traces via the **stand-alone SU(2) bootstrap**
        (`u1a1deven_matter_bootstrap.solve_matter`), memoised — oracle-free.

        The sole known input is the **exact closed-form gauge tower**
        (`deven_gauged_xn_qn`, fed directly via `_closed_form_gauge_trace` — no
        recursion into the matter solver, the spine-free upgrade over the old
        seed-table read); the matter rays are solved and certified per output
        irrep (Clebsch–Gordan orthonormality + ρ²-twisted cyclicity).  `nmax`
        (the self-norm window anchoring the sweep) starts at 3 and is grown on
        demand (two-cutoff style) until the solve certifies.  Returns
        `{matter ρ²-seed: {𝖖: {irrep: int}}}`, both X01 signs.

        COST: the per-ray deep-label reductions `ray^p` (needed to deep order)
        are the bottleneck (`simplify_trace_via_cone_data` grows steeply in p),
        so this is correct but heavy beyond the frozen depth — the standing
        speed item is to *feed* exact matter seeds (the per-ray module
        characters, ÷P recipe) so the solver need not generate those rows.
        Do NOT drop rays or cap the power to go faster: the ρ²-image rays are
        independent rows (same trace *value*, different tower-seed
        decomposition) and the high-p rows carry the deep reach — omitting
        either silently converges to WRONG values (learned the hard way)."""
        cache = self.__dict__.setdefault("_matter_boot", {})
        if K in cache:
            return cache[K]
        from u1a1deven_matter_bootstrap import solve_matter, rps_to_qn

        def known_qn(seed):
            # gauge sector → exact closed-form character (no oracle, no
            # recursion); matter → unknown (solved by the sweep).
            if self._mag_charge(self._oracle_section(seed)) != 0:
                return {}
            if len(seed[0]) == 0:
                return rps_to_qn(self._closed_form_gauge_trace(abs(seed[1]),
                                                               K + 10))
            return {}

        nmax = 3
        while True:
            try:
                result = solve_matter(self, known_qn, K, nmax=nmax)
                break
            except RuntimeError:                       # under-anchored: widen
                nmax += 4
                if nmax > K + 8:
                    raise
        cache[K] = result
        return result

    def bootstrap_all_seeds(self, K):
        """Every trace seed (v-tower + matter) bootstrapped from **Tr(1) alone**,
        spine-free: the SU(2) per-irrep orthonormality sweep + the all-orders
        monopole cyclicity (`u1a1deven_matter_bootstrap.solve_matter` with
        `full=True`).  `Tr(1)` (the gauged vacuum index) is the sole input; the
        v-tower and matter are solved and certified.  Memoised.  Validated at
        k=1: 100% vs the oracle through K=6 (v-tower + matter).  Returns
        `{ρ²-seed: {𝖖: {irrep: int}}}`."""
        cache = self.__dict__.setdefault("_boot_all", {})
        if K in cache:
            return cache[K]
        from u1a1deven_matter_bootstrap import solve_matter, rps_to_qn

        def known_qn(seed):
            if self._mag_charge(self._oracle_section(seed)) != 0:
                return {}
            f, e = seed
            if len(f) == 0 and e == 0:                 # Tr(1): the sole input
                return rps_to_qn(self._seed_trace(((), 0), K + 12))
            return {}

        cache[K] = solve_matter(self, known_qn, K, full=True)
        return cache[K]

    def _trace_residual(self, seed_label, K):
        """Contract hook; the fast entry point is `trace`."""
        return self.trace(seed_label, K)

    def trace_element(self, x, K: int = 20):
        """R-form linear extension of `trace` (R-side coefficients), each seed
        widened to absorb negative-q tails before truncating to K."""
        result = RPowerSeries.zero(self._R, K)
        for label, c in x.terms.items():
            if c.is_zero():
                continue
            if isinstance(c, LaurentPoly):
                c = RLaurent(self._R, dict(c._coeffs))
            emin = min(c.coeffs.keys())
            wide_K = K - emin if emin < 0 else K
            result = result + self.trace(label, wide_K) * c
        return RPowerSeries(self._R, dict(result.coeffs), K)

    # -- bridge to the oracle (iso / cross-validation) -------------------
    def oracle_section_of(self, native):
        """The oracle κ=0 section of a native ray-keyed label."""
        return self._tb.oracle_section_of_native(native)

    def native_of_oracle_section(self, section):
        """The native ray-keyed label of an oracle κ=0 section."""
        return self._tb.native_of_oracle_section(section)


if __name__ == "__main__":
    import time
    t0 = time.time()
    A = U1A1DevenConeKAlgebra(1)
    cd = A.cone_data()
    nray = len(cd._tb.rays)
    print(f"U1A1DevenConeKAlgebra(k=1): {nray} rays + X_0,1^± , "
          f"{len(cd.cones())} cones, R = {A.coefficient_ring()}  "
          f"[built in {time.time()-t0:.1f}s]")
