"""
u1a1deven_cone_build.py
=======================

Complete, **self-contained** cone tables for the U(1)-gauged `[A_1, D_{2k+2}]`
(`U1A1DevenRGKAlgebra`), built from the *fast, BPS-free* RG-flow oracle
(auxiliary = `A1A2k(k) ⊗ QT(Z²) ⊗ SU(2)`).

This replaces the under-counting `atomic_gens` heuristic of
`u1a1deven_cone_derivation.py` (its self-described "blind alley": deriving
chords from A1A2k single-letter coordinates).  It instead follows the
**construction the U(1)-gauged A-type uses** (`u1a1aodd_kalg.select_chords`),
adapted to D-type per the user's recipe (2026-06-21):

    rays = the monomial-RG canonical elements (seeds);
    cones = q-commuting cliques of those rays;
    **ρ-images of the seed cones are new cones** (ρ transports whole cones);
    the full mult-gen set = the union of all cones' rays.

The D-type subtlety this resolves: ρ_UV does **not** keep a ray monomial-RG
(unlike A-type) — ρ of a single-chord ray lands on product-cone labels.  So the
ρ-equivariant object is the *cone*, not a single ray's orbit; the monomial-RG
elements only *seed* the rays and ρ fills out the rest (validated k=1: 11 seed
rays → 17 ρ-closed rays, 20 cones, multiply closes with 0 oracle fallback).

Native labels are **ray-keyed** (like `U1A1AoddKAlg`): `(factors, e_X01)` with
`factors` a sorted tuple of `(ray_id, exp)` and `e_X01 ∈ Z` the `X_{0,1}` torus
power.  `X_{0,1}` is the one clean Laurent torus direction; `X_{1,0}` (magnetic
't Hooft) is a one-directional *conventional* ray (its inverse threads the
matter), and its negative-magnetic tower is generated by the ρ-image rays.

Output: `DevenConeTables`, a plain data holder the `U1A1DevenConeData`
(`FiniteConeData`) wraps.  Built once; no per-multiply oracle call.
"""
from __future__ import annotations

import sys, os
_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

import itertools
from zplus_ring import SU2ZPlusRing, RLaurent

# Torus sentinels (X_{0,1} Laurent direction); conventional rays are ints 0..R-1.
# Large ints (not tuples) so cone gens are uniformly sortable — needed by the
# generic trace tools' `sorted(cone)` (smart_trace_bootstrap) — and they sort
# AFTER the rays (rays < E), preserving the canonical cone order.
E_GEN = 1_000_000
E_INV = 1_000_001


def _modT(section):
    """Ray identity mod the `X_{0,1}` torus: `(chord, c1, kappa)` (drop `c2`)."""
    (chord, (c1, _c2)), kappa = section
    return (chord, c1, kappa)


def _c2_of(section):
    (_chord, (_c1, c2)), _kappa = section
    return c2


def _is_pure_x01(section):
    """A pure `X_{0,1}^m` power (the torus) — excluded from conventional rays."""
    (chord, (c1, _c2)), kappa = section
    return chord == () and c1 == 0 and kappa == 0


class DevenConeTables:
    """Self-contained cone tables for `U1A1DevenRGKAlgebra(k)`."""

    def __init__(self, oracle=None, decode_degree: int = 4, frozen=None):
        if frozen is not None:                       # spine-free load (no oracle)
            self.__dict__.update(frozen)
            from a1a2k_kalg import A1A2kKAlg
            self._B = A1A2kKAlg(self.k)
            return
        self.oracle = oracle
        self.R = SU2ZPlusRing()
        self.aux = oracle.auxiliary()
        B = oracle._gauge
        self.H = B.H
        self.k = getattr(B, "k", None)
        self._B = B
        self._decode_degree = decode_degree     # eager precompute degree
        self._build(decode_degree)
        self._precompute_torus_cocycles()       # so runtime is oracle-free

    def __getattr__(self, name):
        """Lazily rebuild the oracle-holders (`oracle`/`aux`) that the
        spine-free frozen load drops.  Only fires when one is genuinely
        missing — the fast paths (multiply/ρ/trace via precomputed tables +
        the BPS-free `_B`) never touch them, so the frozen path stays
        spine-free; this serves only off-path oracle comparisons / tests."""
        if name in ("oracle", "aux"):
            from u1a1deven_rgkalgebra import U1A1DevenRGKAlgebra
            self.oracle = U1A1DevenRGKAlgebra(self.__dict__["k"])
            self.aux = self.oracle.auxiliary()
            return self.__dict__[name]
        raise AttributeError(name)

    def _precompute_torus_cocycles(self):
        """Populate `_torus_coc_cache` for every (ray, X_01^±) pair, so
        `cocycle_gen` never needs the oracle at runtime (the torus cocycle is
        otherwise computed lazily via `_secmul`)."""
        self._torus_coc_cache = {}
        for i in range(len(self.rays)):
            for E in (E_GEN, E_INV):
                self._torus_coc_cache[(E, i)] = self._torus_cocycle(E, i)
                self._torus_coc_cache[(i, E)] = self._torus_cocycle(i, E)

    # -- oracle helpers ---------------------------------------------------
    def _sec(self, lab):
        return self.aux._label_section_decompose(lab)[0]

    def _nterms(self, elt):
        return sum(1 for c in elt.terms.values() if not c.is_zero())

    def _mrg(self, lab):
        return self._nterms(self.oracle.RG(lab))

    def _sec_terms(self, elt):
        """`elt` regrouped into su2=0 sections with `RLaurent[SU(2)]` coeffs."""
        out = {}
        for lab, c in elt.terms.items():
            s, rc = self.aux._label_section_decompose(lab)
            acc = out.get(s, RLaurent(self.R))
            for e, co in c._coeffs.items():
                acc = acc + RLaurent(self.R, {e: rc * co})
            out[s] = acc
        return {s: v for s, v in out.items() if not v.is_zero()}

    def _secmul(self, gs, hs):
        """Multiply two section labels; return `{section: RLaurent}`."""
        return self._sec_terms(self.oracle.multiply(gs, hs))

    def _secrho(self, s):
        return self._sec(self.oracle.rho(s))

    def _secrho_inv(self, s):
        return self._sec(self.oracle.rho_inverse(s))

    def _seed_sections(self):
        """Seed ray sections (overridable per oracle).  Legacy A1A2k⊗QT⊗SU(2):
        monomial-RG **clean** chords of all types (1..k) via the fast gauge `_B`
        (`make_clean` dresses by one X_{1,0} if the bare RG is not monomial) plus
        the clean QT gens.  A new-oracle subclass overrides this with its own
        chord enumeration + clean-frame logic."""
        from u1a1deven_cone_derivation import make_clean
        T, B, H = self.oracle, self._B, self.H
        kmax = self.k if self.k else 1
        seeds = set()
        for a in range(1, kmax + 1):
            for i in range(H):
                try:
                    chord = B.L((a, i))
                except Exception:
                    continue
                cl = make_clean(T, ((chord, (0, 0)), 0))
                if cl is not None:
                    seeds.add(self._sec(cl))
        for q in [(((), (1, 0)), 0), (((), (-1, 0)), 0),
                  (((), (0, 1)), 0), (((), (0, -1)), 0)]:
            if self._mrg(q) == 1:
                seeds.add(self._sec(q))
        return seeds

    # -- the build --------------------------------------------------------
    def _build(self, decode_degree):
        import time as _t
        _dbg = os.environ.get("DEVEN_BUILD_DEBUG")
        def _mark(msg, t0):
            if _dbg:
                print(f"  [build] {msg}: {_t.time()-t0:.2f}s", flush=True)
            return _t.time()
        _t0 = _t.time()
        kmax = self.k if self.k else 1

        # 1. seed rays (overridable per oracle): monomial-RG **clean** chords of
        #    ALL types + the clean QT gens.
        seeds = self._seed_sections()
        _t0 = _mark(f"seeds={len(seeds)}", _t0)

        # 2. ρ-closure (mod X_01): the rays.  X_{0,1}^± are the torus, not rays.
        #    ρ transports whole cones, so the ρ-orbit of the seed rays IS the
        #    full mult-gen set (user's recipe).  Bounded: D-even at fixed k has
        #    finitely many cluster variables mod the X_01 torus.
        MAX_RAYS = 4 * (2 * kmax + 4) ** 2 + 40   # generous safety bound
        ray_rep = {}    # modT -> canonical oracle section
        def add_ray(s):
            if _is_pure_x01(s):
                return
            ray_rep.setdefault(_modT(s), s)
        for s in seeds:
            add_ray(s)
        frontier = [s for s in seeds if not _is_pure_x01(s)]
        cap = 4 * (2 * kmax + 4) + 12
        for _ in range(cap):
            nxt = []
            for s in frontier:
                for img in (self._secrho(s), self._secrho_inv(s)):
                    if not _is_pure_x01(img) and _modT(img) not in ray_rep:
                        add_ray(img)
                        nxt.append(img)
                        if len(ray_rep) > MAX_RAYS:
                            raise RuntimeError(
                                f"ρ-closure exceeded {MAX_RAYS} rays — magnetic "
                                f"drift (seed set or modT quotient wrong?)")
            frontier = nxt
            if not nxt:
                break
        else:
            raise RuntimeError(f"ρ-closure did not terminate in {cap} sweeps")

        _t0 = _mark(f"rho-closure rays={len(ray_rep)}", _t0)
        # index the rays
        self.rays = sorted(ray_rep.values())          # ray_id = index
        self.ray_section = {i: s for i, s in enumerate(self.rays)}
        self.modT_to_id = {_modT(s): i for i, s in enumerate(self.rays)}
        self.ray_c2 = {i: _c2_of(s) for i, s in enumerate(self.rays)}
        self.mult_gens = tuple(range(len(self.rays))) + (E_GEN, E_INV)

        # 3. closed-form ρ on ray ids (+ X_01 drift) and on the X_01 torus —
        #    built BEFORE the q-graph/cocycle/cross so those can **ρ-fold**: ρ is
        #    an algebra automorphism ⇒ q_commute and the cocycle are ρ-invariant,
        #    and the cross ρ-translates (`_rho_apply_cross`).  Folding cuts the
        #    dominant cold-oracle multiplies by the ρ period (which grows with
        #    k) → the build is fast at every k, so no freeze is needed.
        self.rho_ray, self.rho_ray_drift = {}, {}
        self.rho_inv_ray, self.rho_inv_drift = {}, {}
        for rid, s in self.ray_section.items():
            sp = self._secrho(s)
            rid2 = self.modT_to_id[_modT(sp)]
            self.rho_ray[rid] = rid2
            self.rho_ray_drift[rid] = _c2_of(sp) - self.ray_c2[rid2]
            sm = self._secrho_inv(s)
            rid3 = self.modT_to_id[_modT(sm)]
            self.rho_inv_ray[rid] = rid3
            self.rho_inv_drift[rid] = _c2_of(sm) - self.ray_c2[rid3]
        x01 = (((), (0, 1)), 0)
        rx, rxi = self._secrho(x01), self._secrho_inv(x01)
        assert _is_pure_x01(rx) and _is_pure_x01(rxi), \
            f"ρ(X_01) not a pure torus power: {rx}, {rxi}"
        self.rho_x01 = _c2_of(rx)
        self.rho_inv_x01 = _c2_of(rxi)
        self._ray_period = self._compute_ray_period()
        # cocycle of X_{0,1} with each ray (half-exponent) — needed by the
        # cocycle drift-fold (the cocycle is NOT ρ-invariant: it drifts by the
        # X01-cocycle against the per-ray ρ drift).
        self._cx01_map = {r: self._coc_ray_x01(r, x01)
                          for r in range(len(self.rays))}
        _t0 = _mark(f"rho tables (period {self._ray_period})", _t0)

        # 4. q-commute graph among rays -> cones (maximal cliques).  q_commute is
        #    ρ-invariant, so learn it once per ρ-orbit of ordered pairs.
        ids = list(range(len(self.rays)))
        self._qcom = {}
        nb = {i: set() for i in ids}
        rep_qc = {}
        for i, j in itertools.combinations(ids, 2):
            r = self._pair_rho_rep(i, j)
            qc = rep_qc.get(r)
            if qc is None:
                # fast filter: if the chord product (fast A1A2k `_B`) is not
                # single-term, the rays cannot q-commute — no oracle needed.
                if self._monomial_section(tuple(sorted(r))) is None:
                    qc = False
                else:
                    qc = (len(self._secmul(self.rays[r[0]],
                                           self.rays[r[1]])) == 1)
                rep_qc[r] = qc
            self._qcom[(i, j)] = self._qcom[(j, i)] = qc
            if qc:
                nb[i].add(j)
                nb[j].add(i)
        self.cones = tuple(self._maximal_cliques(ids, nb))
        _t0 = _mark(f"q-graph ({len(rep_qc)} reps) + {len(self.cones)} cones", _t0)

        # 4. decode lookup: modT(section) -> (ray-word, sum_c2) for cone
        #    monomials up to `decode_degree` (single-term, q-commuting).
        self._decode = {}
        for cone in self.cones:
            cl = sorted(cone)
            for deg in range(1, decode_degree + 1):
                for combo in itertools.combinations_with_replacement(cl, deg):
                    sec = self._monomial_section(combo)
                    if sec is None:
                        continue
                    key = _modT(sec)
                    if key not in self._decode:
                        self._decode[key] = (tuple(combo), _c2_of(sec))
        _t0 = _mark(f"decode entries={len(self._decode)}", _t0)

        # 6. cocycle (ρ-invariant — learn per ρ-orbit rep) + cross_product
        #    (ρ-translates with a drift-phase — learn per rep, `_rho_fold_cross`).
        self._cocycle = {}
        rep_coc = {}
        for i, j in itertools.combinations(ids, 2):
            if not self._qcom[(i, j)]:
                continue
            r = self._pair_rho_rep(i, j)
            cr = rep_coc.get(r)
            if cr is None:
                cr = self._extract_cocycle(r[0], r[1])
                rep_coc[r] = cr
            c = self._rho_fold_cocycle(cr, r, (i, j))
            self._cocycle[(i, j)] = c
            self._cocycle[(j, i)] = -c
        _t0 = _mark(f"cocycles ({len(rep_coc)} reps)", _t0)
        self._cross = {}
        rep_cross = {}
        for i, j in itertools.permutations(ids, 2):
            if self._qcom[(i, j)]:
                continue
            r = self._pair_rho_rep(i, j)
            if r not in rep_cross:
                rep_cross[r] = self._extract_cross_sec(r[0], r[1])
            self._cross[(i, j)] = self._rho_fold_cross(rep_cross[r], r, (i, j))
        _t0 = _mark(f"cross ({len(rep_cross)} reps)", _t0)

    # -- closed-form ρ on ray-keyed native labels (factors, e_X01) --------
    def rho_native(self, native):
        return self._rho_native(native, self.rho_ray, self.rho_ray_drift,
                                 self.rho_x01)

    def rho_inv_native(self, native):
        return self._rho_native(native, self.rho_inv_ray, self.rho_inv_drift,
                                 self.rho_inv_x01)

    def _rho_native(self, native, rmap, rdrift, rx01):
        factors, e_X01 = native
        acc, new_e = {}, e_X01 * rx01
        for (rid, exp) in factors:
            rid2 = rmap[rid]
            acc[rid2] = acc.get(rid2, 0) + exp
            new_e += exp * rdrift[rid]
        new_factors = tuple(sorted((r, e) for r, e in acc.items() if e != 0))
        return (new_factors, new_e)

    # -- ρ-fold helpers (learn the mult table on ρ-orbit reps, ρ-translate) --
    def _compute_ray_period(self):
        """lcm of the ρ cycle lengths on ray ids — the period over which the
        ρ-orbit of an ordered ray pair closes."""
        import math
        seen, per = set(), 1
        for s in range(len(self.rays)):
            if s in seen:
                continue
            L, c = 0, s
            while c not in seen:
                seen.add(c); L += 1; c = self.rho_ray[c]
            per = per * L // math.gcd(per, L)
        return max(per, 1)

    def _pair_rho_rep(self, i, j):
        """Canonical (lex-min) representative of the ρ-orbit of the ordered ray
        pair `(i, j)` under simultaneous ρ.  q_commute and cocycle are
        ρ-invariant; the cross ρ-translates (`_rho_apply_cross`)."""
        best, ci, cj = (i, j), i, j
        for _ in range(self._ray_period - 1):
            ci, cj = self.rho_ray[ci], self.rho_ray[cj]
            if (ci, cj) < best:
                best = (ci, cj)
        return best

    def _word_to_label(self, word):
        acc, e = {}, 0
        for g in word:
            if g == E_GEN:
                e += 1
            elif g == E_INV:
                e -= 1
            else:
                acc[g] = acc.get(g, 0) + 1
        return (tuple(sorted((r, c) for r, c in acc.items() if c)), e)

    def _label_to_word(self, label):
        factors, e = label
        wl = []
        for (r, c) in factors:
            wl += [r] * c
        if e > 0:
            wl += [E_GEN] * e
        elif e < 0:
            wl += [E_INV] * (-e)
        return tuple(sorted(wl, key=_gen_sort_key))

    def _extract_cross_sec(self, i, j):
        """`L_i L_j` in **section form** `{section: rl_can}` (raw secmul, the
        canonical-basis coefficients) — before the literal-word conversion.  ρ
        acts phase-free on this form (canonical coeffs are ρ-invariant), so it
        ρ-translates without the literal-phase drift."""
        return self._secmul(self.rays[i], self.rays[j])

    def _sec_cross_to_literal(self, sec_terms):
        """`{section: rl_can}` → `((rl_lit, full_word), …)` literal-mult-gen form
        (the `_extract_cross` tail: decode + cone phase)."""
        terms = []
        for s, rl_can in sec_terms.items():
            word, eX01 = self._decode_section(s)
            full_word = self._word_with_torus(word, eX01)
            phase = self._cone_label_phase_full(full_word)
            rl_lit = RLaurent(self.R, {e + phase: co
                                       for e, co in rl_can.coeffs.items()})
            terms.append((rl_lit, full_word))
        return tuple(terms)

    def _rho_apply_cross_sec(self, sec_terms, i, j):
        """One ρ step on the section-form cross of `(i, j)` → `(ρi, ρj)`.  ρ is
        an algebra automorphism with `ρ(L_i) = L_{ρi}·X01^{drift_i}`:

            L_{ρi}L_{ρj} = q^{-2·d_i·cx01(ρj)} · X01^{-(d_i+d_j)} · ρ(L_i L_j)

        so each daughter section is ρ-relabelled, the overall X01 shift applied,
        and the coefficient drifts by the reorder phase `-2 d_i cx01(ρj)` (global)
        plus `2 s · cx01(ρ·d)` from moving X01^s past the daughter (s = -(d_i+d_j),
        cx01(ρ·d) = the half-cocycle of X01 with the daughter's ρ-image rays)."""
        di, dj = self.rho_ray_drift[i], self.rho_ray_drift[j]
        s = -(di + dj)
        ph = self._cross_step_phase(i, j)
        out = {}
        for section, rl_can in sec_terms.items():
            nat = self.native_of_oracle_section(section)
            rf, re = self.rho_native(nat)
            rsec = self.oracle_section_of_native((rf, re + s))
            add = RLaurent(self.R, {e + ph: co for e, co in rl_can.coeffs.items()})
            cur = out.get(rsec)
            out[rsec] = add if cur is None else cur + add
        return {k: v for k, v in out.items() if not v.is_zero()}

    def _cross_step_phase(self, i, j):
        """Global q-phase for one ρ step of the section-form cross
        `(i,j) → (ρi,ρj)` (uniform across daughters — charge is conserved):
        `L_{ρi}L_{ρj} = q^{G}·X01^{-(d_i+d_j)}·ρ(L_iL_j)` with
        `G = d_j·c1(i) − d_i·c1(j)` (antisymmetric in the two rays' X01 drift vs
        magnetic charge — cx01(r)=c1(r))."""
        di, dj = self.rho_ray_drift[i], self.rho_ray_drift[j]
        c1i, c1j = self.rays[i][0][1][0], self.rays[j][0][1][0]
        return dj * c1i - di * c1j

    def _rho_fold_cross(self, sec_at_rep, rep, target):
        """ρ-translate the rep's section-form cross to orbit member `target`,
        then convert to the literal-mult-gen form `multiply` consumes."""
        ci, cj = rep
        sec = sec_at_rep
        for _ in range(self._ray_period + 1):
            if (ci, cj) == target:
                return self._sec_cross_to_literal(sec)
            sec = self._rho_apply_cross_sec(sec, ci, cj)
            ci, cj = self.rho_ray[ci], self.rho_ray[cj]
        raise RuntimeError(f"_rho_fold_cross: {rep} → {target} unreachable")

    def _rho_fold_cocycle(self, c, rep, target):
        """ρ-translate the rep's cocycle to orbit member `target`.  The cocycle
        is NOT ρ-invariant: `ρ(L_i)=L_{ρi}·X01^{drift_i}` ⇒
        `cocycle(ρi,ρj) = cocycle(i,j) + cx01(ρi)·drift_j − cx01(ρj)·drift_i`
        (cx01 = the half-cocycle of X01 with a ray)."""
        ci, cj = rep
        for _ in range(self._ray_period + 1):
            if (ci, cj) == target:
                return c
            ri, rj = self.rho_ray[ci], self.rho_ray[cj]
            c = (c - self._cx01_map[ri] * self.rho_ray_drift[cj]
                 + self._cx01_map[rj] * self.rho_ray_drift[ci])
            ci, cj = ri, rj
        raise RuntimeError(f"_rho_fold_cocycle: {rep} → {target} unreachable")

    # -- native (ray-keyed) <-> oracle section ----------------------------
    def oracle_section_of_native(self, native):
        """Oracle κ=0 section of a ray-keyed cone monomial `(factors, e_X01)`,
        or None if its rays don't all q-commute (not a cone element)."""
        factors, e_X01 = native
        if not factors:
            return (((), (0, e_X01)), 0)
        ray_ids = []
        for (rid, exp) in factors:
            ray_ids += [rid] * exp
        sec = self._monomial_section(tuple(sorted(ray_ids)))
        if sec is None:
            return None
        (chord, (c1, c2)), kappa = sec
        return ((chord, (c1, c2 + e_X01)), kappa)

    def native_of_oracle_section(self, section):
        """Ray-keyed native label of an oracle κ=0 section (inverse decode)."""
        word, eX01 = self._decode_section(section)
        acc = {}
        for rid in word:
            acc[rid] = acc.get(rid, 0) + 1
        factors = tuple(sorted((r, e) for r, e in acc.items() if e != 0))
        return (factors, eX01)

    # -- ρ²-orbit canonical rep (X_{0,1} drift quotient) ------------------
    def rho2_canon(self, label):
        """Canonical representative of a mag-0 label's ρ²-orbit, with the
        `X_{0,1}` power drift-quotiented (ρ² shears the torus → infinite
        orbits; cf. `U1A1AoddKAlg._canonical_rho2_orbit_rep`).  The trace is
        ρ²-invariant, so `Tr(label) = Tr(rho2_canon(label))` — this collapses
        the seed set the (frozen) trace is keyed on."""
        factors, e = label
        if not factors:
            return ((), e)                       # X_01^e : ρ²-fixed
        seen, seq = {}, []
        cur = label
        for step in range(256):
            key = cur[0]
            seq.append(cur)
            if key in seen:
                i = seen[key]
                D = seq[step][1] - seq[i][1]     # X_01 drift over one period
                periodic = seq[i:]
                kmin = min(m[0] for m in periodic)
                emins = [m[1] for m in periodic if m[0] == kmin]
                if D == 0:
                    return (kmin, min(emins))
                return (kmin, min(emins) % abs(D))
            seen[key] = step
            cur = self.rho_native(self.rho_native(cur))
        return label

    def _maximal_cliques(self, ids, nb):
        out = []
        def bk(Rs, P, X):
            if not P and not X:
                out.append(frozenset(Rs)); return
            piv = max(P | X, key=lambda u: len(P & nb[u]))
            for v in list(P - nb[piv]):
                bk(Rs | {v}, P & nb[v], X & nb[v]); P = P - {v}; X = X | {v}
        bk(set(), set(ids), set())
        return [c for c in out if c]

    def _monomial_section(self, ray_ids):
        """Section of the (q-commuting) ray monomial — chord via the *fast*
        A1A2k `multiply`, QT charges added (no slow deven-oracle call).  None
        if the chord product is not single-term (rays don't all q-commute, so
        the monomial is not a cone element)."""
        B = self._B
        s0 = self.rays[ray_ids[0]]
        chord = s0[0][0]
        c1, c2 = s0[0][1]
        for r in ray_ids[1:]:
            rs = self.rays[r]
            prod = B.multiply(chord, rs[0][0])
            nz = [lab for lab, c in prod.terms.items() if not c.is_zero()]
            if len(nz) != 1:
                return None
            chord = nz[0]
            c1 += rs[0][1][0]
            c2 += rs[0][1][1]
        return ((chord, (c1, c2)), 0)

    def _extract_cocycle(self, i, j):
        """`c` with `L_i L_j = q^{2c} L_j L_i`, from single-term products."""
        gh = self._secmul(self.rays[i], self.rays[j])
        hg = self._secmul(self.rays[j], self.rays[i])
        (s, cgh), = gh.items()
        chg = hg[s]
        a = min(cgh.coeffs); b = min(chg.coeffs)
        assert (a - b) % 2 == 0, f"odd cocycle rays {i},{j}: {a},{b}"
        return (a - b) // 2

    def _extract_cross(self, i, j):
        """`L_i L_j` as `((RLaurent coeff, full-word), …)` daughters, where the
        full word is in mult-gens (ray ids + X_01 sentinels)."""
        terms = []
        for s, rl_can in self._secmul(self.rays[i], self.rays[j]).items():
            word, eX01 = self._decode_section(s)
            full_word = self._word_with_torus(word, eX01)
            # literal coeff: L_daughter = q^{phase} * (ordered mult-gen product),
            # phase = -Σ_{p<q} cocycle over the FULL word (rays + torus).
            phase = self._cone_label_phase_full(full_word)
            rl_lit = RLaurent(self.R, {e + phase: co
                                       for e, co in rl_can.coeffs.items()})
            terms.append((rl_lit, full_word))
        return tuple(terms)

    def _decode_section(self, section):
        """Section -> (ray-word, e_X01).  Eager cache (degrees ≤ decode_degree)
        with a lazy fallback for higher-degree cone monomials (k≥2 reductions
        reach them); raises only if genuinely undecodable (ray set incomplete)."""
        if _is_pure_x01(section):
            return ((), _c2_of(section))
        key = _modT(section)
        hit = self._decode.get(key)
        if hit is None:
            hit = self._lazy_decode(key)
        word, base_c2 = hit
        eX01 = _c2_of(section) - base_c2
        return word, eX01

    def _chord_nletters(self, chord):
        """Total letter multiplicity of a chord-word.  The exponent is the last
        component of each factor in both formats — legacy A1A2k `(a, i, e)` and
        A1Dodd `((a, p, i), exp)` — so this works for either oracle."""
        return sum(g[-1] for g in chord)

    def _lazy_decode(self, key):
        """Find a ray-word for `key=(chord, c1, kappa)` by searching cone
        monomials of degree > decode_degree, bounded by the chord's letter
        count (a cone monomial's letters are the union of its rays', so its
        degree can't exceed the total letter multiplicity + the |c1| magnetic
        rays).  Cached into `_decode`."""
        chord, c1, _kappa = key
        nletters = self._chord_nletters(chord)
        deg_bound = nletters + abs(c1) + 2
        for deg in range(self._decode_degree + 1, deg_bound + 1):
            for cone in self.cones:
                cl = sorted(cone)
                for combo in itertools.combinations_with_replacement(cl, deg):
                    sec = self._monomial_section(combo)
                    if sec is not None and _modT(sec) == key:
                        self._decode[key] = (tuple(combo), _c2_of(sec))
                        return self._decode[key]
        raise RuntimeError(
            f"decode failed for modT={key} up to degree {deg_bound} — ray set "
            f"incomplete")

    def _word_with_torus(self, ray_word, eX01):
        wl = list(ray_word)
        if eX01 > 0:
            wl += [E_GEN] * eX01
        elif eX01 < 0:
            wl += [E_INV] * (-eX01)
        return tuple(sorted(wl, key=_gen_sort_key))

    def _cone_label_phase_full(self, full_word):
        """`-Σ_{p<q} cocycle(word[p], word[q])` in canonical (`_gen_sort_key`)
        order over the full word — *including* ray↔X_01 torus cocycles.
        Consistent with `U1A1DevenConeData.cone_label_phase`."""
        order = sorted(full_word, key=_gen_sort_key)
        total = 0
        for p in range(len(order)):
            for q in range(p + 1, len(order)):
                total += self.cocycle_gen(order[p], order[q])
        return -total

    # -- cone-data primitive surface (consumed by U1A1DevenConeData) ------
    def q_commute_gen(self, g, h):
        if g == h:
            return True
        if g in (E_GEN, E_INV) or h in (E_GEN, E_INV):
            return True                       # X_01 torus q-commutes with all
        return self._qcom[(g, h)]

    def cocycle_gen(self, g, h):
        if g == h or {g, h} == {E_GEN, E_INV}:
            return 0
        if g in (E_GEN, E_INV) or h in (E_GEN, E_INV):
            return self._torus_cocycle(g, h)
        return self._cocycle[(g, h)]

    def _torus_cocycle(self, g, h):
        """Cocycle of a conventional ray with the `X_{0,1}` torus: extracted
        from the oracle (X_{0,1}^{±1} vs the ray's section)."""
        cache = getattr(self, "_torus_coc_cache", None)
        if cache is None:
            cache = self._torus_coc_cache = {}
        key = (g, h)
        if key in cache:
            return cache[key]
        x01 = (((), (0, 1)), 0)
        if g in (E_GEN, E_INV):
            ray, sgn = h, (1 if g == E_GEN else -1)
            c = sgn * self._coc_ray_x01(ray, x01)
            cache[key] = -c
        else:
            ray, sgn = g, (1 if h == E_GEN else -1)
            cache[key] = sgn * self._coc_ray_x01(ray, x01)
        return cache[key]

    def _coc_ray_x01(self, ray_id, x01):
        gh = self._secmul(self.rays[ray_id], x01)
        hg = self._secmul(x01, self.rays[ray_id])
        (s, cgh), = gh.items()
        a = min(cgh.coeffs); b = min(hg[s].coeffs)
        return (a - b) // 2

    def cross_gen(self, g, h):
        return self._cross[(g, h)]


def _gen_sort_key(g):
    """Sort conventional rays (ints) before torus sentinels, stably."""
    if isinstance(g, tuple):       # E_GEN / E_INV
        return (1, g)
    return (0, g)


# -- spine-free table freeze (the u1A1Aodd `freeze_tables` pattern) -------
_DROP = ("oracle", "aux", "_B",          # oracle-holders; `_B` rebuilt from k
         "_surv",                         # A1Dodd gauge factor (rebuilt on load)
         "_monsec_cache", "_survmul_cache")   # transient build caches (dodd builder)


def _frozen_tables_path(k):
    return os.path.join(_HERE, f"u1a1deven_tables_k{k}.pkl")


_TABLE_CACHE = {}


def build_tables(k, allow_frozen=False):
    """`DevenConeTables` for `k`, built (ρ-folded, fast) from the RG oracle —
    the closed-form way: q_commute/cocycle/cross are *learned* on ρ-orbit reps
    and ρ-translated (cocycle drift + the `d_j·c1(i) − d_i·c1(j)` cross step
    phase), so the build is fast at every k and **no freeze is needed**.  Built
    tables are memoized per process (a runtime cache, not a disk freeze).
    `allow_frozen=True` still loads a legacy pickle if present (compat only)."""
    if not allow_frozen and k in _TABLE_CACHE:
        return _TABLE_CACHE[k]
    if allow_frozen:
        p = _frozen_tables_path(k)
        if os.path.exists(p):
            import pickle
            with open(p, "rb") as f:
                frozen = pickle.load(f)
            if frozen.get("_oracle_kind") == "dodd":   # built on A1Dodd×QT oracle
                from u1a1deven_dodd_build import DevenDoddConeTables
                return DevenDoddConeTables(frozen=frozen)
            return DevenConeTables(frozen=frozen)
    from u1a1deven_rgkalgebra import U1A1DevenRGKAlgebra
    tb = DevenConeTables(U1A1DevenRGKAlgebra(k))
    _TABLE_CACHE[k] = tb
    return tb


def freeze_tables(k):
    """Build the tables from the oracle and pickle everything except the
    oracle-holders, so `build_tables(k)` later loads them spine-free."""
    import pickle
    from u1a1deven_rgkalgebra import U1A1DevenRGKAlgebra
    tb = DevenConeTables(U1A1DevenRGKAlgebra(k))
    frozen = {key: v for key, v in tb.__dict__.items() if key not in _DROP}
    with open(_frozen_tables_path(k), "wb") as f:
        pickle.dump(frozen, f)
    return _frozen_tables_path(k)


if __name__ == "__main__":
    import time
    from u1a1deven_rgkalgebra import U1A1DevenRGKAlgebra
    t0 = time.time()
    tb = DevenConeTables(U1A1DevenRGKAlgebra(1))
    print(f"DevenConeTables(k=1): {len(tb.rays)} rays + X01^± , "
          f"{len(tb.cones)} cones (sizes {sorted(set(len(c) for c in tb.cones))}), "
          f"decode entries {len(tb._decode)}  [{time.time()-t0:.2f}s]")
