"""uq_su2_kalgebra — `UqSU2KAlgebra`: the `U_𝖖(sl_2)` quantum group as an
SU(2)-flavoured `K_𝖖`-algebra, implemented DIRECTLY from the definition in the
user's `K_𝖖-algebras` draft (§"The `U_𝖖(sl_2)` quantum group as a flavoured
`K_𝖖`-algebra", label `sec:uqsl2`; the design record, 2026-09-21).

It is isomorphic, as an algebra, to the central quotient of `U_𝖖(sl_2)`, and
it is the algebra of SQED_2 (U(1) gauge theory with `T^*C²` matter).  The
certified `K_𝖖`-algebra isomorphism to the SU(2)-flavoured BPS chart of SQED_2
is `src/bps/uq_su2_bps_iso.py` (a `KAlgebraIso` against
`gf_bps_sqed_nf(2)`, verified by the full battery in both directions).

The definition (verbatim in content from the draft)
---------------------------------------------------
* Multiplicatively generated by the Cartan `K^{±1}` and the canonical basis
  elements `E`, `F`, with relations

      K E = 𝖖⁻² E K ,             K F = 𝖖² F K ,
      E F = χ₁ + 𝖖 K + 𝖖⁻¹ K⁻¹ ,  F E = χ₁ + 𝖖⁻¹ K + 𝖖 K⁻¹ ,

  so `[E,F] = (𝖖 − 𝖖⁻¹)(K − K⁻¹)`, and the quadratic Casimir is the fundamental
  SU(2) flavour character `χ₁` itself — an element of the COEFFICIENT RING
  `R(SU(2))` (the design record: Casimir / flavour in the coefficient ring).
* Canonical basis: `K^n`, `E_{a,b} = 𝖖^{−ab} E^a K^b`, `F_{a,b} = 𝖖^{ab} F^a K^b`
  (`a ≥ 1`, `b ∈ Z`), the powers of `𝖖` fixed by bar-invariance; times the
  characters `χ_k` of the flavour ring, carried in the label (the repo's
  flavour-in-labels convention, `L_{(s, χ_k)} = χ_k · L_s`).
* `ρ(K) = K⁻¹`, `ρ(E) = 𝖖⁻¹ F K⁻¹`, `ρ(F) = 𝖖 K E`, `ρ` fixing the `χ_k`
  (SU(2) irreps are self-dual, so the rep-ring duality `⋆` is the identity).
  On the canonical basis this is the sign-free label permutation

      ρ(K^n) = K^{−n},   ρ(E_{a,b}) = F_{a,−a−b},   ρ(F_{a,b}) = E_{a,a−b},

  of INFINITE order (`ρ²(E_{a,b}) = E_{a,b+2a}`): Lusztig's braid symmetry,
  covering the order-two Weyl reflection `K ↦ K⁻¹` but acting as the braid
  group `Z`.
* The trace vanishes on `E_{a,b}` and `F_{a,b}`; on the Cartan sector

      G(x, μ) := Σ_{n∈Z} Tr(K^n) x^n
               = (𝖖²;𝖖²)_∞² · E_𝖖(μx) E_𝖖(μ⁻¹x) E_𝖖(μx⁻¹) E_𝖖(μ⁻¹x⁻¹),

  with `χ₁ = μ + μ⁻¹` and `E_𝖖(x) = (−𝖖x; 𝖖²)_∞⁻¹` — the SQED_2 Schur index
  with a Wilson-line insertion.  `Tr(K^n)` is computed EXACTLY through `𝖖^K`
  (every factor is a power series in `𝖖` of non-negative valuation, so the
  truncated product is the truncation of the exact product — nothing is
  truncated early) and un-branched into SU(2) characters through the ring's
  own `from_abelian`.  The draft's `ρ²`-twisted-cyclicity recursion
  (`eq:uqsl2con`) is the INDEPENDENT check that the suite in the source repository
  runs against this `G`.

Two warnings the draft itself carries (false friends): the bar involution here
is antimultiplicative and FIXES `K`, whereas the conventional bar of
`U_𝖖(sl_2)` is an algebra automorphism sending `K ↦ K⁻¹`; and the canonical
basis here is NOT the canonical basis of Lusztig and Kashiwara.

Labels
------
A canonical label is a pair `(sector, w)`:

    sector ∈ { ('K', n) , ('E', a, b) , ('F', a, b) }     (a ≥ 1, n, b ∈ Z)
    w      = a basis key of the coefficient ring          (the character χ_k)

`identity() = (('K', 0), 1_R)`.  The flavour-lift coordinate is
`r_label_decompose((s, w)) = ((s, 1_R), w)`.

Coefficient ring
----------------
`SUNZPlusRing(2)` by default — the repo's `R(SU(N))` (key `()` is
the trivial character and `(k,)` is `χ_k`, the spin-`k/2` irrep of dimension
`k + 1`), the ring the SU(2)-flavoured BPS chart of SQED_2 carries.  The
older rank-1 ring `SU2ZPlusRing` (key `k` for `χ_k`) is accepted too; the two
are certified isomorphic under `(k,) ↔ k` (the suite in the source repository).
`chi(k)` returns the ring's key for `χ_k` whichever ring is in use.

Placement in the hierarchy — a DIRECT `KAlgebra` subclass
-------------------------------------------------------------------------
`UqSU2KAlgebra(KAlgebra)` implements the six primitives itself, on its own
straightening engine.  It is deliberately NOT a `ConeKAlgebra`, although the
PBW basis (`𝖖`-normalised monomials in `E`, `F`, `K^{±1}` with a cocycle) could
be presented as cone data: *"At the moment I'd like UqSU2KAlgebra to be a
direct KAlgebra subclass, even if it could be realized as a ConeKAlgebra
subclass, as I do not know what the correct 'shape' is going to be for the
higher g's."*  The intended eventual home is a **quantum-group contractual
subclass of `KAlgebra`** — *"Ultimately we will hopefully have a quantum group
contractual subclass"* — an ABC with its own primitives and
verifiers in the manner of `RGKAlgebra` / `AbeKAlgebra` / `ConeKAlgebra`, to
be designed once the examples (this one, then `U_𝖖(sl_3)`) have shown its
shape; until it exists this class stays a direct subclass.  Do not re-parent
it on your own.

Relation to `uq_sl2_pbw.UqSL2PBW` (2026-06-10): that interim module carries
the Casimir as a label coordinate `C^j` over `Z` and has no trace.  This class
supersedes it on the contract surface (A3: flavour in the ring, the full
trace); the straightening engine is the same set of relations and the two
agree term by term once `C^j` is expanded as `χ₁^j` — pinned in the tests.

Run:  `PYTHONPATH=$(ls -d src/* | paste -sd:) python3 src/samples/uq_su2_kalgebra.py`
"""
from __future__ import annotations

import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)
_ROOT = os.path.dirname(_HERE)
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from kalgebra import Element, KAlgebra
from laurent_poly import LaurentPoly
from zplus_ring import (
    AbelianZPlusRing, RElement, RPowerSeries, SU2ZPlusRing, SUNZPlusRing,
    ZPlusRing,
)


def _q(n: int) -> LaurentPoly:
    return LaurentPoly({n: 1})


def _add(out: dict, key, coeff: LaurentPoly) -> None:
    if coeff.is_zero():
        return
    cur = out.get(key)
    s = coeff if cur is None else cur + coeff
    if s.is_zero():
        out.pop(key, None)
    else:
        out[key] = s


# ---------------------------------------------------------------------------
# The straightening engine (PBW normal form of the central quotient)
# ---------------------------------------------------------------------------
#
# Internal monomial key: (side, p, k, w)
#   side 'K':  K^k                 (p stored as 0)
#   side 'E':  K^k E^p   (p ≥ 1)
#   side 'F':  F^p K^k   (p ≥ 1)
#   w:         the flavour-ring key of the character multiplying the monomial
# value: LaurentPoly in 𝖖.
#
# The relations used: KE = 𝖖⁻²EK (so EK = 𝖖²KE, K⁻¹E = 𝖖²EK⁻¹), KF = 𝖖²FK,
# EF = χ₁ + 𝖖K + 𝖖⁻¹K⁻¹, FE = χ₁ + 𝖖⁻¹K + 𝖖K⁻¹; whence
#   E F^p = χ₁ F^{p−1} + 𝖖^{2p−1} F^{p−1} K + 𝖖^{1−2p} F^{p−1} K⁻¹ ,
#   F E^p = χ₁ E^{p−1} + 𝖖^{1−2p} E^{p−1} K + 𝖖^{2p−1} E^{p−1} K⁻¹ .
# χ₁ is central and is FUSED into the ring key through `multiply_basis`.


class _Engine:
    """Left multiplication by the generators on internal monomials, with the
    Casimir `χ₁` fused into the flavour-ring key."""

    def __init__(self, ring: ZPlusRing, chi1) -> None:
        self.R = ring
        self.chi1 = chi1
        self._fuse_cache: dict = {}

    def fuse_chi1(self, w) -> dict:
        """`χ₁ · χ_w` as `{key: multiplicity}` (Clebsch–Gordan through the ring)."""
        got = self._fuse_cache.get(w)
        if got is None:
            got = dict(self.R.multiply_basis(w, self.chi1))
            self._fuse_cache[w] = got
        return got

    def _add_chi1(self, out: dict, side, p, k, w, coeff: LaurentPoly) -> None:
        for w2, m in self.fuse_chi1(w).items():
            _add(out, (side, p, k, w2), coeff * m if m != 1 else coeff)

    def lm_K(self, sign: int, mono, coeff: LaurentPoly) -> dict:
        """Left-multiply `K^{sign}` (sign = ±1)."""
        side, p, k, w = mono
        out: dict = {}
        if side == 'K':
            _add(out, ('K', 0, k + sign, w), coeff)
        elif side == 'E':                        # K^{±1}·K^k E^p
            _add(out, ('E', p, k + sign, w), coeff)
        else:                                    # K^{±1}·F^p K^k = 𝖖^{±2p} F^p K^{k±1}
            _add(out, ('F', p, k + sign, w), _q(sign * 2 * p) * coeff)
        return out

    def lm_E(self, mono, coeff: LaurentPoly) -> dict:
        side, p, k, w = mono
        out: dict = {}
        if side == 'K':                          # E·K^k = 𝖖^{2k} K^k E
            _add(out, ('E', 1, k, w), _q(2 * k) * coeff)
        elif side == 'E':                        # E·K^k E^p = 𝖖^{2k} K^k E^{p+1}
            _add(out, ('E', p + 1, k, w), _q(2 * k) * coeff)
        else:                                    # E·F^p K^k
            if p == 1:
                self._add_chi1(out, 'K', 0, k, w, coeff)                    # χ₁ K^k
                _add(out, ('K', 0, k + 1, w), _q(1) * coeff)                # 𝖖 K^{k+1}
                _add(out, ('K', 0, k - 1, w), _q(-1) * coeff)               # 𝖖⁻¹ K^{k−1}
            else:
                self._add_chi1(out, 'F', p - 1, k, w, coeff)                # χ₁ F^{p−1} K^k
                _add(out, ('F', p - 1, k + 1, w), _q(2 * p - 1) * coeff)    # 𝖖^{2p−1} F^{p−1} K^{k+1}
                _add(out, ('F', p - 1, k - 1, w), _q(1 - 2 * p) * coeff)    # 𝖖^{1−2p} F^{p−1} K^{k−1}
        return out

    def lm_F(self, mono, coeff: LaurentPoly) -> dict:
        side, p, k, w = mono
        out: dict = {}
        if side == 'K':                          # F·K^k
            _add(out, ('F', 1, k, w), coeff)
        elif side == 'F':                        # F·F^p K^k
            _add(out, ('F', p + 1, k, w), coeff)
        else:                                    # F·K^k E^p = 𝖖^{−2k} K^k (F E^p)
            base = _q(-2 * k) * coeff
            if p == 1:
                self._add_chi1(out, 'K', 0, k, w, base)                     # χ₁ K^k
                _add(out, ('K', 0, k + 1, w), _q(-1) * base)                # 𝖖⁻¹ K^{k+1}
                _add(out, ('K', 0, k - 1, w), _q(1) * base)                 # 𝖖 K^{k−1}
            else:
                # K^k E^{p−1} K = 𝖖^{2(p−1)} K^{k+1} E^{p−1};  … K⁻¹ = 𝖖^{−2(p−1)} K^{k−1} E^{p−1}
                self._add_chi1(out, 'E', p - 1, k, w, base)
                _add(out, ('E', p - 1, k + 1, w), _q(1 - 2 * p + 2 * (p - 1)) * base)
                _add(out, ('E', p - 1, k - 1, w), _q(2 * p - 1 - 2 * (p - 1)) * base)
        return out

    def left_mult_gen(self, g: str, X: dict) -> dict:
        out: dict = {}
        for mono, coeff in X.items():
            if g == 'K':
                part = self.lm_K(+1, mono, coeff)
            elif g == 'Ki':
                part = self.lm_K(-1, mono, coeff)
            elif g == 'E':
                part = self.lm_E(mono, coeff)
            else:
                part = self.lm_F(mono, coeff)
            for kk, cc in part.items():
                _add(out, kk, cc)
        return out

    @staticmethod
    def word(mono) -> list:
        """Generator word (left to right) of the monomial, flavour key aside."""
        side, p, k, _w = mono
        kw = (['K'] * k) if k >= 0 else (['Ki'] * (-k))
        if side == 'K':
            return kw
        if side == 'E':
            return kw + ['E'] * p
        return ['F'] * p + kw

    def mono_mult(self, m1, c1: LaurentPoly, m2, c2: LaurentPoly) -> dict:
        """`(χ_{w1} M1) · (χ_{w2} M2)`: apply M1's word onto `{M2: c1 c2}`, then
        fuse the two flavour keys (both central)."""
        X = {(m2[0], m2[1], m2[2], m2[3]): c1 * c2}
        for g in reversed(self.word(m1)):
            X = self.left_mult_gen(g, X)
        w1 = m1[3]
        if w1 == self.R.one_basis():
            return X
        out: dict = {}
        for (s, p, k, w2), c in X.items():
            for w3, m in self.R.multiply_basis(w1, w2).items():
                _add(out, (s, p, k, w3), c * m if m != 1 else c)
        return out


# ---------------------------------------------------------------------------
# The generating function G(x, μ) — Tr(K^n) exactly through 𝖖^K
# ---------------------------------------------------------------------------

def _eq_coeffs(K: int) -> list[dict]:
    """`[y^i] E_𝖖(y) = (−1)^i 𝖖^i / (𝖖²;𝖖²)_i` for `i = 0..K`, each a sparse
    `{𝖖-exponent: int}` truncated at `𝖖^K`.  `E_𝖖(y) = 1/(−𝖖y; 𝖖²)_∞`, and the
    𝖖-binomial theorem gives `1/(z;q)_∞ = Σ_n z^n/(q;q)_n` with `q → 𝖖²`,
    `z → −𝖖y`."""
    inv = {0: 1}                                 # 1/(𝖖²;𝖖²)_i, running
    out = []
    for i in range(K + 1):
        out.append({e + i: c * ((-1) ** i) for e, c in inv.items() if e + i <= K})
        step = 2 * (i + 1)                       # next: divide by (1 − 𝖖^{step})
        if step <= K:
            new: dict = {}
            for e, c in inv.items():
                t = 0
                while e + step * t <= K:
                    new[e + step * t] = new.get(e + step * t, 0) + c
                    t += 1
            inv = {e: c for e, c in new.items() if c}
    return out


def _qpoch_q2_sq(K: int) -> dict:
    """`(𝖖²;𝖖²)_∞²` truncated at `𝖖^K`, sparse."""
    base = {0: 1}
    n = 1
    while 2 * n <= K:
        for _ in range(2):
            nxt = dict(base)
            for e, c in base.items():
                ee = e + 2 * n
                if ee <= K:
                    nxt[ee] = nxt.get(ee, 0) - c
            base = {e: c for e, c in nxt.items() if c}
        n += 1
    return base


def _mul2(A: dict, B: dict, K: int) -> dict:
    """Product of two `{(𝖖-exp, μ-exp): int}` polynomials, truncated at 𝖖^K."""
    out: dict = {}
    for (e1, j1), c1 in A.items():
        for (e2, j2), c2 in B.items():
            e = e1 + e2
            if e > K:
                continue
            key = (e, j1 + j2)
            out[key] = out.get(key, 0) + c1 * c2
    return {k: v for k, v in out.items() if v}


def cartan_traces(K: int) -> dict[int, dict]:
    """`[x^n] G(x, μ)` for every `n` with `|n| ≤ K`, exactly through `𝖖^K`, as
    `{n: {(𝖖-exp, μ-exp): int}}`.

    `G = (𝖖²;𝖖²)_∞² · A(x) · A(x⁻¹)` with `A(x) = E_𝖖(μx)E_𝖖(μ⁻¹x) = Σ_p x^p A_p(μ)`,
    `A_p(μ) = Σ_{i+j=p} e_i e_j μ^{i−j}` of 𝖖-valuation `p`; so
    `[x^n]G = pref · Σ_{p−p'=n} A_p A_{p'}`, and only `p + p' ≤ K` contributes
    below `𝖖^{K+1}`.  Symmetric under `n ↦ −n` (swap `p ↔ p'`) and under
    `μ ↦ μ⁻¹` (swap `i ↔ j`), as the trace axioms require."""
    e = _eq_coeffs(K)
    A: list[dict] = []
    for p in range(K + 1):
        Ap: dict = {}
        for i in range(p + 1):
            j = p - i
            for e1, c1 in e[i].items():
                for e2, c2 in e[j].items():
                    ee = e1 + e2
                    if ee > K:
                        continue
                    key = (ee, i - j)
                    Ap[key] = Ap.get(key, 0) + c1 * c2
        A.append({k: v for k, v in Ap.items() if v})
    pref = {(ee, 0): c for ee, c in _qpoch_q2_sq(K).items()}
    out: dict[int, dict] = {}
    for p in range(K + 1):
        for pp in range(K + 1 - p):
            n = p - pp
            prod = _mul2(A[p], A[pp], K)
            acc = out.setdefault(n, {})
            for key, c in prod.items():
                acc[key] = acc.get(key, 0) + c
    for n in list(out):
        out[n] = _mul2(out[n], pref, K)
    return out


# ---------------------------------------------------------------------------
# The KAlgebra
# ---------------------------------------------------------------------------

class UqSU2KAlgebra(KAlgebra):
    """The `U_𝖖(sl_2)` quantum group as an SU(2)-flavoured `K_𝖖`-algebra —
    the draft's Definition (`sec:uqsl2`), implemented directly.  See the module
    docstring for the definition, the labels and the ring."""

    def __init__(self, ring: ZPlusRing | None = None) -> None:
        if ring is None:
            ring = SUNZPlusRing(2)
        if isinstance(ring, SUNZPlusRing):
            if ring.N != 2:
                raise ValueError(
                    f"UqSU2KAlgebra: the flavour ring is R(SU(2)); got {ring!r}")
        elif not isinstance(ring, SU2ZPlusRing):
            raise TypeError(
                "UqSU2KAlgebra: ring must be SUNZPlusRing(2) or SU2ZPlusRing, "
                f"got {ring!r}")
        self._R = ring
        self._chi1 = self.chi(1)
        self._engine = _Engine(ring, self._chi1)
        self._trace_table: dict[int, dict[int, dict]] = {}   # K → cartan_traces(K)
        self._tr_cache: dict[tuple[int, int], RPowerSeries] = {}

    # ----- ring keys ---------------------------------------------------
    def chi(self, k: int):
        """The coefficient-ring key of the character `χ_k` (spin `k/2`,
        dimension `k + 1`); `chi(0)` is the identity, `chi(1)` the fundamental."""
        if k < 0:
            raise ValueError(f"chi(k): k ≥ 0 required, got {k}")
        if isinstance(self._R, SUNZPlusRing):
            return () if k == 0 else (k,)
        return k

    def spin2(self, w) -> int:
        """Inverse of `chi`: the highest weight `k` of the ring key `w`."""
        if isinstance(self._R, SUNZPlusRing):
            w = tuple(w)
            return 0 if not w else int(w[0])
        return int(w)

    # ----- label constructors -------------------------------------------
    def K(self, n: int = 1, k: int = 0):
        """The label of `χ_k · K^n`."""
        return (('K', int(n)), self.chi(k))

    def E(self, a: int = 1, b: int = 0, k: int = 0):
        """The label of `χ_k · E_{a,b}`, `E_{a,b} = 𝖖^{−ab} E^a K^b` (`a ≥ 1`)."""
        if a < 1:
            raise ValueError(f"E_{{a,b}} needs a ≥ 1, got a={a}")
        return (('E', int(a), int(b)), self.chi(k))

    def F(self, a: int = 1, b: int = 0, k: int = 0):
        """The label of `χ_k · F_{a,b}`, `F_{a,b} = 𝖖^{ab} F^a K^b` (`a ≥ 1`)."""
        if a < 1:
            raise ValueError(f"F_{{a,b}} needs a ≥ 1, got a={a}")
        return (('F', int(a), int(b)), self.chi(k))

    @staticmethod
    def _check(label) -> tuple:
        try:
            sector, w = label
            kind = sector[0]
        except (TypeError, ValueError):
            raise ValueError(f"UqSU2KAlgebra: malformed label {label!r}")
        if kind == 'K':
            _, n = sector
            return (('K', int(n)), w)
        if kind in ('E', 'F'):
            _, a, b = sector
            if a < 1:
                raise ValueError(f"UqSU2KAlgebra: {kind}_{{a,b}} needs a ≥ 1: {label!r}")
            return ((kind, int(a), int(b)), w)
        raise ValueError(f"UqSU2KAlgebra: unknown sector {kind!r} in {label!r}")

    # ----- canonical ↔ internal ----------------------------------------
    @staticmethod
    def _to_internal(label):
        """canonical label ↦ (internal monomial key, internal coefficient):
        `E_{a,b} = 𝖖^{ab} K^b E^a`, `F_{a,b} = 𝖖^{ab} F^a K^b`."""
        (sector, w) = label
        kind = sector[0]
        if kind == 'K':
            return ('K', 0, sector[1], w), LaurentPoly.one()
        _, a, b = sector
        return (kind, a, b, w), _q(a * b)

    @staticmethod
    def _to_canonical(X: dict) -> dict:
        """internal `{(side, p, k, w): LaurentPoly}` ↦ `{canonical label: LaurentPoly}`
        (the E/F sides pick up `𝖖^{−pk}`)."""
        out: dict = {}
        for (side, p, k, w), c in X.items():
            if side == 'K':
                _add(out, (('K', k), w), c)
            else:
                _add(out, ((side, p, k), w), _q(-p * k) * c)
        return out

    # ----- the six primitives ------------------------------------------
    def coefficient_ring(self) -> ZPlusRing:
        return self._R

    def identity(self):
        return (('K', 0), self._R.one_basis())

    def multiply(self, a, b) -> Element:
        a, b = self._check(a), self._check(b)
        ma, ca = self._to_internal(a)
        mb, cb = self._to_internal(b)
        return Element(self._to_canonical(self._engine.mono_mult(ma, ca, mb, cb)))

    def rho(self, a):
        (sector, w) = self._check(a)
        ws = self._R.star_basis(w)               # the identity on SU(2)
        kind = sector[0]
        if kind == 'K':
            return (('K', -sector[1]), ws)
        _, p, k = sector
        if kind == 'E':
            return (('F', p, -p - k), ws)        # ρ(E_{a,b}) = F_{a,−a−b}
        return (('E', p, p - k), ws)             # ρ(F_{a,b}) = E_{a,a−b}

    def rho_inverse(self, a):
        (sector, w) = self._check(a)
        ws = self._R.star_basis(w)
        kind = sector[0]
        if kind == 'K':
            return (('K', -sector[1]), ws)
        _, p, k = sector
        if kind == 'F':
            return (('E', p, -p - k), ws)        # ρ⁻¹(F_{a,c}) = E_{a,−a−c}
        return (('F', p, p - k), ws)             # ρ⁻¹(E_{a,c}) = F_{a,a−c}

    def trace(self, a, K: int = 20) -> RPowerSeries:
        (sector, w) = self._check(a)
        if sector[0] != 'K':
            return RPowerSeries.zero(self._R, K)
        tr = self.trace_K(sector[1], K)
        if w == self._R.one_basis():
            return tr
        return tr * self._R.basis_element(w)

    # ----- the Cartan-sector trace ---------------------------------------
    def trace_K(self, n: int, K: int = 20) -> RPowerSeries:
        """`Tr(K^n) = [x^n] G(x, μ)` through `𝖖^K`, as an `RPowerSeries` over
        the flavour ring (the μ-Laurent polynomial at each order un-branched
        into characters through `from_abelian`, virtual characters allowed —
        Wilson-line indices are signed)."""
        n = int(n)
        key = (abs(n), K)                        # Tr K^{−n} = Tr K^n (x ↔ x⁻¹)
        got = self._tr_cache.get(key)
        if got is not None:
            return got
        table = self._trace_table.get(K)
        if table is None:
            table = cartan_traces(K)
            self._trace_table[K] = table
        poly = table.get(abs(n), {})
        by_q: dict[int, dict] = {}
        for (e, j), c in poly.items():
            by_q.setdefault(e, {})[(j,)] = c
        U1 = AbelianZPlusRing(rank=1)
        coeffs: dict[int, RElement] = {}
        for e, mu in by_q.items():
            r = self._R.from_abelian(RElement(U1, mu), allow_virtual=True)
            if not r.is_zero():
                coeffs[e] = r
        got = RPowerSeries(self._R, coeffs, K)
        self._tr_cache[key] = got
        return got

    # ----- the flavour-lift coordinate ---------------------------------
    def r_label_decompose(self, label):
        (sector, w) = self._check(label)
        return (sector, self._R.one_basis()), w

    def r_label_compose(self, section, r_basis_label):
        (sector, _one) = section
        return (sector, r_basis_label)

    def embed_R(self, r: RElement) -> Element:
        """`ι : R(SU(2)) ↪ A`, `χ_k ↦ χ_k · 1 = (('K', 0), χ_k)`."""
        if not isinstance(r, RElement) or r.ring != self._R:
            raise TypeError(
                "UqSU2KAlgebra.embed_R: argument must be an RElement over "
                "coefficient_ring()")
        out = Element.zero()
        for w, c in r.terms.items():
            if c:
                out = out + Element.basis((('K', 0), w)) * c
        return out

    # ----- conveniences --------------------------------------------------
    def basis_iter(self, max_a: int = 2, max_b: int = 2, max_k: int = 1):
        """Labels with `1 ≤ a ≤ max_a`, `|b| ≤ max_b` (E and F sectors), Cartan
        powers `|n| ≤ max_b`, characters `χ_k` with `k ≤ max_k`."""
        for k in range(max_k + 1):
            for n in range(-max_b, max_b + 1):
                yield self.K(n, k)
            for a in range(1, max_a + 1):
                for b in range(-max_b, max_b + 1):
                    yield self.E(a, b, k)
                    yield self.F(a, b, k)

    def __repr__(self) -> str:
        return f"UqSU2KAlgebra(ring={self._R!r})"


if __name__ == "__main__":
    A = UqSU2KAlgebra()
    E, F, K1 = A.E(), A.F(), A.K(1)
    print(A)
    print("  E*F   =", A.multiply(E, F))
    print("  F*E   =", A.multiply(F, E))
    print("  K*E   =", A.multiply(K1, E), "   E*K =", A.multiply(E, K1))
    print("  rho(E) =", A.rho(E), "  rho(F) =", A.rho(F), "  rho(K) =", A.rho(K1))
    print("  rho^2(E) =", A.rho(A.rho(E)), " (infinite order: b ↦ b + 2a)")
    for n in range(0, 3):
        print(f"  Tr K^{n} =", A.trace(A.K(n), K=8))
    print("  I(E,E) =", A.inner_product(E, E, K=6))
    print("  I(E,F) =", A.inner_product(E, F, K=6))
