"""K-theoretic Coulomb branch algebras over `Z[q^±]` -- abstract base.

A `KAlgebra` faithfully encodes A_𝖖[T] for a 4d N=2 SQFT T:

* An associative algebra over `Z[q, q^{-1}]`.  The canonical basis
  `{L_a}` is a **Z[q, q^{-1}]-basis**: every canonical-basis element
  gets its own label in the (full) index set, and structure constants
  are integer Laurent polynomials in `q`.
* A countable linear basis `{L_a}` indexed by an opaque `Label` type.
  The identity element is one of the `L_a`'s.
* Structure constants `C^c_{ab}(q) ∈ Z[q, q^{-1}]` from
  `L_a · L_b = Σ_c C^c_{ab}(q) L_c`.
* The "bar involution" on `Z[q^±]` is **q-flip**: `q ↔ q^{-1}`.
  Constraint:  `C^c_{ab}(q^{-1}) = C^c_{ba}(q)`.  Equivalently
  `A_q ≅ A_{q^{-1}}^op` via `L_a ↔ L_a`.
* A canonical algebra automorphism `ρ` permuting the basis labels and
  fixing the identity:  `ρ(L_a) = L_{ρ(a)}`,  `ρ(1) = 1`.  Its inverse
  `ρ^{-1}` is part of the contract since cyclicity references both
  directions.
* A `ρ²`-twisted trace `Tr : A_q → R((q))` valued in a layered
  R-module structure (see below).

R-module structure as a layered API
-----------------------------------

`A_𝖖[T]` *also* carries an `R[q^±]`-module structure for `R` a Z₊-ring
(typically `R = R(G_flavour)`, the rep-ring of the flavour symmetry).
`R` sits inside `A_𝖖[T]` as the central subalgebra generated by the
canonical-basis elements at flavour directions.  The R-module
structure is **not** part of the basis definition — there is no
canonical R-basis.  It is exposed as a layered API on top of the
Z-form:

* `coefficient_ring()` returns the Z₊-ring `R`.
* `trace(a, K) : Label → RPowerSeries` lands in `R((q))` because
  the trace is non-zero only on labels in central directions, and
  picks up μ-monomials there.
* `inner_product(a, b, K) : Label × Label → RPowerSeries` likewise.
* `to_R_form(z_elem) -> ElementOverR` converts a Z-form `Element` to
  the R-form presentation (smaller index set: a section of the centre
  quotient; coefficients in `RLaurent`).  The section choice is
  internal to each realisation (via the abstract hook
  `_label_section_decompose`); it is not a contract-level concept.

Concrete subclasses must implement the **six** abstract primitives:

    coefficient_ring, identity, multiply, rho, rho_inverse, trace

plus the **flavour-lift coordinate** of a canonical label, supplied as
the single-irrep hook `r_label_decompose` (the `(section, R-basis-label)`
coordinate, `L_label = χ_w · L_section`).  As of the 2026-06-19 migration
this is **the** flavour-lift primitive; the older `(section, RElement)`
form `_label_section_decompose` is now a derived legacy bridge (default =
lift `r_label_decompose`'s basis label to an `RElement`), retained — not
deleted — because `to_R_form` reads it and it is the honest fallback for
the deprecated *emergent* flavour diagnostics (whose `r_label_decompose`
raises) and the non-contract lattice scaffolds (`coefficient_ring()` is
`None`).

Everything else (multiplication of linear combinations, the bar map
on linear combinations, the inner product, axiom verifiers,
`to_R_form`) is derived.

Module-internal dependencies: `zplus_ring` for the R-side types and
`laurent_poly` for `LaurentPoly` (the Z[q^±] type used for Element
coefficients).  Both are core modules imported by bare name.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Hashable

import sys, os
_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(_HERE)
if _REPO not in sys.path:
    sys.path.insert(0, _REPO)
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from zplus_ring import (
    ZPlusRing, RElement, RLaurent, RPowerSeries, RingHom, TrivialZPlusRing,
    BasisElement,
)
from laurent_poly import LaurentPoly


# ---------------------------------------------------------------------------
# Linear combinations  Σ_a c_a · L_a   over Z[q^±]
# ---------------------------------------------------------------------------

Label = Hashable


class Element:
    """A linear combination `Σ_a c_a · L_a` with coefficients in
    `Z[q, q^{-1}]` (= `LaurentPoly`).

    Stored as `dict[Label, LaurentPoly]` with zero LaurentPoly
    coefficients dropped on construction.

    This is the **Z-form** of the canonical basis: every distinct
    canonical-basis element gets its own label, structure constants
    are integer Laurent polynomials in `q`.  The R-module-form
    presentation is `ElementOverR`, obtained from `Element` via
    `KAlgebra.to_R_form`.

    The only involution exposed at the Element level is `bar()`
    (q-flip on each LaurentPoly coefficient).  ρ acts on labels;
    the linear extension `KAlgebra.rho_element` is plain (no twist),
    since coefficients are over Z and Z's "star" (rep-ring duality)
    is identity.
    """

    __slots__ = ("terms",)

    def __init__(
        self,
        terms: "dict[Label, LaurentPoly | RLaurent] | None" = None,
    ):
        self.terms: "dict[Label, LaurentPoly | RLaurent]" = {}
        if not terms:
            return
        for a, c in terms.items():
            if not isinstance(c, (LaurentPoly, RLaurent)):
                raise TypeError(
                    f"Element: coefficient must be LaurentPoly or "
                    f"RLaurent, got {type(c).__name__}"
                )
            if not c.is_zero():
                self.terms[a] = c

    @classmethod
    def zero(cls) -> "Element":
        return cls()

    @classmethod
    def basis(cls, label: Label) -> "Element":
        """The basis element `L_label` with coefficient 1 ∈ Z[q^±]."""
        return cls({label: LaurentPoly({0: 1})})

    def is_zero(self) -> bool:
        return not self.terms

    # ------- arithmetic -------

    def __add__(self, other: "Element") -> "Element":
        if not isinstance(other, Element):
            return NotImplemented
        out = dict(self.terms)
        for a, c in other.terms.items():
            out[a] = out[a] + c if a in out else c
        return Element({a: c for a, c in out.items() if not c.is_zero()})

    def __sub__(self, other: "Element") -> "Element":
        return self + (-other)

    def __neg__(self) -> "Element":
        return Element({a: -c for a, c in self.terms.items()})

    def __mul__(self, scalar) -> "Element":
        """Scalar multiplication by an int, LaurentPoly, or RLaurent.

        Element × Element multiplication goes through
        `KAlgebra.multiply_elements`."""
        if isinstance(scalar, int):
            if scalar == 0:
                return Element.zero()
            return Element({a: c * scalar for a, c in self.terms.items()})
        if isinstance(scalar, (LaurentPoly, RLaurent)):
            return Element({a: c * scalar for a, c in self.terms.items()})
        return NotImplemented

    __rmul__ = __mul__

    # ------- bar involution -------

    def bar(self) -> "Element":
        """q-flip on each Z[q^±] coefficient.  This is the
        KAlgebra's bar involution at the Element level."""
        out: dict[Label, "LaurentPoly | RLaurent"] = {}
        for a, c in self.terms.items():
            if isinstance(c, RLaurent):
                barred = c.bar()        # q-flip; μ untouched (bar ≠ ⋆)
            else:
                barred = LaurentPoly({-e: v for e, v in c._coeffs.items()})
            if not barred.is_zero():
                out[a] = barred
        return Element(out)

    # ------- comparison -------

    def __eq__(self, other) -> bool:
        if not isinstance(other, Element):
            return NotImplemented
        if self.terms.keys() != other.terms.keys():
            return False
        for a, c1 in self.terms.items():
            c2 = other.terms[a]
            if type(c1) is type(c2):
                if c1 != c2:
                    return False
                continue
            # Mixed LaurentPoly / RLaurent (#231 widening): compare
            # semantically by lifting the LaurentPoly into R[q^±].
            rl, lp = (c1, c2) if isinstance(c1, RLaurent) else (c2, c1)
            if not (isinstance(rl, RLaurent) and isinstance(lp, LaurentPoly)):
                return False
            R = rl.ring
            one_b = R.one_basis()
            lifted = {n: RElement(R, {one_b: c})
                      for n, c in lp._coeffs.items() if c != 0}
            if rl.coeffs != lifted:
                return False
        return True

    def __hash__(self):
        raise TypeError("Element is unhashable")

    def __repr__(self) -> str:
        if not self.terms:
            return "0"
        parts = []
        for a in sorted(self.terms.keys(), key=str):
            c = self.terms[a]
            c_repr = repr(c)
            if c_repr == "1":
                parts.append(f"L_{a}")
            elif c_repr == "-1":
                parts.append(f"-L_{a}")
            else:
                parts.append(f"({c_repr})*L_{a}")
        s = parts[0]
        for p in parts[1:]:
            if p.startswith("-"):
                s += " - " + p[1:]
            else:
                s += " + " + p
        return s


# ---------------------------------------------------------------------------
# ElementOverR — the R-module-form presentation
# ---------------------------------------------------------------------------


class ElementOverR:
    """The R-form presentation of an Element: `dict[Label, RLaurent]`
    with R-Laurent coefficients over a Z₊-ring `R`.

    Returned by `KAlgebra.to_R_form(z_elem)`.  Index labels are
    section reps of the central quotient; flavour shifts are
    absorbed into μ-monomial coefficients.  Useful when the user
    wants the smaller R-module-basis presentation (e.g., for
    refined Schur indices, real Schur quantization).

    The R-form is *not* the canonical basis — it is a derived view
    that depends on the realisation's section choice.
    """

    __slots__ = ("ring", "terms")

    def __init__(
        self,
        ring: ZPlusRing,
        terms: dict[Label, RLaurent] | None = None,
    ):
        self.ring = ring
        self.terms: dict[Label, RLaurent] = {}
        if not terms:
            return
        for a, c in terms.items():
            if not isinstance(c, RLaurent):
                raise TypeError(
                    f"ElementOverR: coefficient must be RLaurent, "
                    f"got {type(c).__name__}"
                )
            if c.ring != ring:
                raise ValueError("ElementOverR: ring mismatch in coefficient")
            if not c.is_zero():
                self.terms[a] = c

    @classmethod
    def zero(cls, ring: ZPlusRing) -> "ElementOverR":
        return cls(ring)

    @classmethod
    def basis(cls, ring: ZPlusRing, label: Label) -> "ElementOverR":
        return cls(ring, {label: RLaurent.one(ring)})

    def is_zero(self) -> bool:
        return not self.terms

    def __add__(self, other: "ElementOverR") -> "ElementOverR":
        if not isinstance(other, ElementOverR):
            return NotImplemented
        if other.ring != self.ring:
            raise ValueError("ElementOverR: ring mismatch in __add__")
        out = dict(self.terms)
        for a, c in other.terms.items():
            out[a] = out[a] + c if a in out else c
        return ElementOverR(
            self.ring,
            {a: c for a, c in out.items() if not c.is_zero()},
        )

    def __sub__(self, other: "ElementOverR") -> "ElementOverR":
        return self + (-other)

    def __neg__(self) -> "ElementOverR":
        return ElementOverR(
            self.ring, {a: -c for a, c in self.terms.items()},
        )

    def __eq__(self, other) -> bool:
        if not isinstance(other, ElementOverR):
            return NotImplemented
        return self.ring == other.ring and self.terms == other.terms

    def __hash__(self):
        raise TypeError("ElementOverR is unhashable")

    def __repr__(self) -> str:
        if not self.terms:
            return "0_R"
        parts = []
        for a in sorted(self.terms.keys(), key=str):
            c = self.terms[a]
            parts.append(f"({c})*L_{a}")
        return " + ".join(parts)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------



def _coeff_min_exp(c):
    """Minimal q-exponent of an Element coefficient (LaurentPoly or
    RLaurent — both legal since the #231 widening)."""
    d = c.coeffs if isinstance(c, RLaurent) else c._coeffs
    return min(d.keys())

def _laurentpoly_times_rpowerseries(
    L: "LaurentPoly | RLaurent", P: RPowerSeries,
) -> RPowerSeries:
    """`L(q) · P(q, μ)` as an `RPowerSeries` truncated at `P.K`.

    L is either a Z[q^±]-Laurent polynomial (each integer q-coefficient
    embedded as `c · 1_R`) or an `RLaurent` over `P.ring` (R-valued
    q-coefficients used directly — `Element` admits RLaurent
    coefficients since the #231 contract widening, and the derived
    trace path must follow suit).
    """
    R = P.ring
    K = P.K
    out: dict[int, RElement] = {}
    if isinstance(L, RLaurent):
        if L.ring != R:
            raise ValueError(
                "_laurentpoly_times_rpowerseries: RLaurent ring mismatch")
        items = [(el, cl) for el, cl in L.coeffs.items()
                 if not cl.is_zero()]
        lift = lambda c: c
    else:
        items = [(el, cl) for el, cl in L._coeffs.items() if cl != 0]
        lift = lambda c: RElement(R, {R.one_basis(): c})
    for el, cl in items:
        rl = lift(cl)
        for ep, cp in P.coeffs.items():
            e = el + ep
            if e > K:
                continue
            p = rl * cp
            if p.is_zero():
                continue
            out[e] = out[e] + p if e in out else p
    return RPowerSeries(P.ring, {n: c for n, c in out.items() if not c.is_zero()}, K)


def _laurentpoly_to_rlaurent(lp: LaurentPoly, ring: ZPlusRing) -> RLaurent:
    """Lift a `LaurentPoly` (Z[q^±]) to `RLaurent` over `ring`.  Each
    integer q-coefficient embeds at `ring.one_basis()`."""
    return RLaurent(ring, dict(lp._coeffs))


# ---------------------------------------------------------------------------
# KAlgebra ABC
# ---------------------------------------------------------------------------


class KAlgebra(ABC):
    """A K-theoretic Coulomb branch algebra `A_𝖖[T]` over `Z[q^±]`,
    with a layered R-module structure for `R` a Z₊-ring."""

    # -------- on freeness over R (a convention, NOT a contract) ----------
    #
    # **Invariant (always):** `multiply` returns **Z-valued** coefficients
    # — `LaurentPoly` over `Z[q^±]` on canonical labels, flavour carried
    # *in the labels*.  `RLaurent` (`R[q^±]`) lives only in the *derived*
    # R-form view (`to_R_form`) and in Layer-1 / trace auxiliaries, never
    # at the `multiply` boundary.
    #
    # A flavoured `A_𝖖` is *always* free over `R = coefficient_ring()`,
    # but freeness is a *mathematically convenient* fact, not a physical
    # property, and in general **not canonical** (an R-basis is a choice
    # of section; two sections differ by *unit* characters).  We therefore
    # **do not contract it** — there is no `free_over_R` flag.  Instead a
    # realisation that finds the R-form convenient simply implements the
    # optional representation hooks `section_decompose` / `embed_R` (and
    # gets `to_R_form` / `from_R_form` / `rho_R_form` for free); the base
    # defaults treat the algebra as Z-form (flavour in labels).
    #
    # The handling generalises factor-by-factor when `R = R₁ ⊗ ⋯ ⊗ R_k`:
    # peel the *non-unit* (free) factors' characters into the canonical
    # section, keep the *unit* (torus) factors' charges in the labels —
    # the split is at the unit boundary.  Worked examples: a1d3, all-free;
    # a1deven, SU(2) free / U(1) in labels.

    # -------- six abstract primitives --------
    # (the flavour-lift coordinate `r_label_decompose` is the seventh
    # *primitive* but is optional/derived — not @abstractmethod — and
    # `_label_section_decompose` is now a derived legacy bridge; see the
    # module docstring's 2026-06-19 retirement note.)

    @abstractmethod
    def coefficient_ring(self) -> ZPlusRing:
        """The Z₊-ring `R` of the layered R-module structure.  For
        unflavoured theories, returns `TrivialZPlusRing()`."""

    @abstractmethod
    def identity(self) -> Label:
        """The label of the identity basis element."""

    @abstractmethod
    def multiply(self, a: Label, b: Label) -> Element:
        """Structure constants `L_a · L_b = Σ_c C^c_{ab}(q) · L_c` as
        an `Element` over `Z[q^±]` (zero LaurentPoly coefficients
        dropped)."""

    @abstractmethod
    def rho(self, a: Label) -> Label:
        """`ρ(L_a)`: the canonical algebra automorphism on basis
        labels."""

    @abstractmethod
    def rho_inverse(self, a: Label) -> Label:
        """`ρ^{-1}(L_a)`."""

    @abstractmethod
    def trace(self, a: Label, K: int = 20) -> RPowerSeries:
        """The `ρ²`-twisted trace `Tr(L_a) ∈ R((q))` truncated to
        `q^K`.  Picks up R-module content (μ-monomials) from labels
        in the centre of the algebra."""

    def _label_section_decompose(
        self, label: Label,
    ) -> "tuple[Label, RElement]":
        """Decompose a Z-form label into `(section_rep, r_coefficient)`
        for the layered R-module presentation.

        `r_coefficient` is an `RElement` over `coefficient_ring()`
        encoding the R-side multiplier such that, in the R-form view,
        `L_label  =  r_coefficient · L_{section_rep}`.

        Construction convention (push the API into `ZPlusRing`):
        each subclass constructs the `RElement` using its ring's own
        `basis_element(...)` / `one()` / arithmetic.  The KAlgebra
        layer never inspects the ring's basis-element key shape.

        * Unflavoured realisations (`coefficient_ring() ==
          TrivialZPlusRing()`): return `(label, R.one())`.
        * Abelian-flavoured realisations with SNF section: return
          `(section_label, R.basis_element(tuple(flav_coords)))`.
        * Non-abelian-flavoured realisations historically could return
          virtual-character coefficients (a signed sum of irreps).  Per
          the flavour re-axiomatization (Plan 32) the target is a single
          irrep `χ_r` (the section ambiguous only up to a 1-dim rep of
          `G_f`); realisations needing a non-unit cover use the cover
          instead (SO(3) ⟶ SU(2), where the half-integer sector is the
          single irrep `χ_{odd}`).

        Used by the default `to_R_form` implementation; realisations
        may override `to_R_form` for performance.

        **Default (the lift-coordinate sharpening).**  This is **no longer
        abstract**: the default derives it from the optional
        `r_label_decompose` hook by lifting that hook's `BasisElement`
        second component to an `RElement` via the canonical
        `coefficient_ring().basis_element`, i.e.
        `(s, w) ↦ (s, R.basis_element(w))`.  A realisation supplies the
        flavour-lift coordinate by implementing **either** this method
        directly — required for the general / virtual-character `RElement`
        form — **or** `r_label_decompose` (the single-irrep lift
        coordinate) and inheriting this default.  Implementing neither
        raises at call time (via `r_label_decompose`'s default).

        **Retired to a derived legacy bridge (migration complete,
        2026-06-19).**  `r_label_decompose` is now *the* flavour-lift
        primitive; this `(section, RElement)` form is **no longer the surface
        to implement** — new realisations implement `r_label_decompose` and
        inherit this default.  It is deliberately **not deleted**: it stays
        structurally load-bearing (`to_R_form` reads its `RElement` second
        component) and is the honest fallback for the cases that genuinely
        cannot supply a single-irrep coordinate — the deprecated *emergent*
        flavour diagnostics (whose `r_label_decompose` raises; their `_lsd`
        carries the base Cartan coordinate) and the non-contract internal
        lattice scaffolds (`coefficient_ring()` is `None`).  Any remaining
        explicit subclass overrides are redundant legacy (each derives
        identically from `r_label_decompose`) and may be stripped at will."""
        sec, r_basis = self.r_label_decompose(label)
        return sec, self.coefficient_ring().basis_element(r_basis)

    def r_label_decompose(
        self, label: Label,
    ) -> "tuple[Label, BasisElement]":
        """The **flavour-lift coordinate** of the canonical label `label`:
        a pair `(section_label, r_basis_label)` whose second component is a
        **single** canonical-basis element of `coefficient_ring()` (a
        `BasisElement` — an irrep label, *not* a general `RElement`), with

            L_label  =  χ_{r_basis_label} · L_{section_label}.

        Why the section matters more than it first appears
        --------------------------------------------------
        A flavoured `A_𝖖[T]` is **always an enrichment of an unflavoured
        `A_𝖖[T]`**, and that unflavoured algebra has its own canonical
        basis `{M_s}`.  The **section is a lift of that basis**:
        `L_{section_label}` is a *choice* of flavoured canonical basis
        element projecting onto the unflavoured canonical basis element
        `M_{section_label}` (the projection is `forget()`).  That lift is
        canonical **only up to a 1-dimensional representation of the
        flavour group**: two admissible sections differ by a unit
        (group-like) character `μ^f ∈ Λ = coefficient_ring().one_dim_reps()`
        (`dim 1`, invertible).  So `(section_label, r_basis_label)` *is*
        the lift coordinate — the section names which unflavoured canonical
        is being lifted, `r_basis_label` names the flavour character
        dressing it, and the **only** non-canonical freedom lives in `Λ`.

        This is exactly the data consumed by the methods that **change or
        eliminate the flavouring** of the algebra:

        * `forget()` — drop `G_f`: `χ_w · M_s ↦ dim(w)·M_s`, so a 1-dim
          rep (`dim 1`) lands *on* an unflavoured canonical (norm 1) and a
          higher `χ_w` (`dim>1`) on a multiple;
        * `lower_flavour(φ)` — push `r_basis_label` through an
          augmentation-compatible hom, **splitting** a canonical where `φ`
          grows `Λ` (e.g. SU(2)→U(1));
        * `base_change(φ)` — restrict the flavour symmetry.

        It is the `(section, single-irrep)` sharpening of
        `_label_section_decompose`, whose `RElement` second component is
        the general (possibly virtual) form; the two are related by the
        canonical `BasisElement → RElement` lift
        (`coefficient_ring().basis_element`), which is precisely how
        `_label_section_decompose` defaults to this hook.

        **Optional.**  The default raises `NotImplementedError`; a
        realisation opts in when its section is a single irrep (the
        physically expected case — the lift of a single unflavoured
        canonical).  No verification is performed here: the single-irrep
        form is a modelling guarantee of the realisation, not a checked
        gate.

        **End-state reached (migration complete, 2026-06-19).**  This is now
        *the* flavour-lift primitive: every faithful realisation implements it
        (directly, or via the trivial-flavour universal default below), the
        flavour-changing wrappers (`forget` / `lower_flavour` / `base_change`)
        consume it, and `_label_section_decompose` is demoted to a derived
        legacy bridge.  `_lsd` is **retained but not to be implemented in new
        code** — it stays only because it is load-bearing for `to_R_form` and
        is the honest fallback for the two kinds of object that *cannot* supply
        a single-irrep coordinate: the deprecated **emergent** flavour
        diagnostics (`r_label_decompose` raises — a base weight is one weight
        of a multiplet, not an irrep) and the non-contract lattice scaffolds
        (`coefficient_ring()` is `None`).  The single-irrep form suffices for
        every genuine realisation precisely because the section is a lift
        canonical up to 1-dim reps, so the general / virtual-character
        `RElement` second component is no longer needed there.

        **Universal treatment of trivial flavour.**  When `coefficient_ring()`
        is `TrivialZPlusRing` (an *unflavoured* theory) the lift coordinate is
        trivial — the label is its own section, dressed by the unique character
        `χ₀` — so the default returns `(label, R.one_basis())` here.  Unflavoured
        realisations therefore need implement *neither* `r_label_decompose` nor
        `_label_section_decompose`: both derive from this universal default."""
        R = self.coefficient_ring()
        if isinstance(R, TrivialZPlusRing):
            return label, R.one_basis()
        raise NotImplementedError(
            f"{type(self).__name__} does not implement r_label_decompose "
            f"(the (section, R-basis-label) flavour-lift coordinate); "
            f"implement it, or implement _label_section_decompose directly."
        )

    def r_label_compose(
        self, section: Label, r_basis_label: "BasisElement",
    ) -> Label:
        """Inverse of `r_label_decompose`: the canonical label `a` with
        `r_label_decompose(a) == (section, r_basis_label)` — equivalently the
        unique label such that `L_a = χ_{r_basis_label} · L_section`
        (`section` a label of the unflavoured / `forget()` basis,
        `r_basis_label` a single irrep / `BasisElement` of
        `coefficient_ring()`).

        This is the **label-producing** partner of `r_label_decompose` — the
        direction the flavour-changing methods and section-factored
        `KAlgebraIso` maps use to rebuild a full label from its lift
        coordinate.

        **Default — derived from the existing `embed_R` + native multiply.**
        `embed_R(coefficient_ring().basis_element(r_basis_label)) · L_section`,
        which by the faithfulness axiom (`verify_embed_section_roundtrip`) is
        the single canonical `L_a` — so any realisation that already supplies
        `embed_R` gets this for free.  A realisation may **override** with a
        direct construction (e.g. a quantum torus: `section + γ_f`, no
        multiply); that override is the "more natural" method this is
        expected to be implemented by, the default being the bridge (same
        playbook as `r_label_decompose` vs `_label_section_decompose`).

        Raises `ValueError` if the product is not a single canonical — i.e.
        `(section, r_basis_label)` is not a valid lift coordinate, or the
        realisation needs the override.

        **Universal treatment of trivial flavour.**  When `coefficient_ring()`
        is `TrivialZPlusRing` the only character is `χ₀`, so the label *is* the
        section — returned directly (no `embed_R` / multiply needed), the
        partner of the trivial `r_label_decompose` default above."""
        R = self.coefficient_ring()
        if isinstance(R, TrivialZPlusRing):
            return section
        central = self.embed_R(R.basis_element(r_basis_label))
        prod = self.multiply_elements(central, Element.basis(section))
        terms = list(prod.terms.items())
        if len(terms) == 1:
            return terms[0][0]
        raise ValueError(
            f"{type(self).__name__}.r_label_compose: "
            f"embed_R(chi_{r_basis_label!r}) · L_{section!r} is not a single "
            f"canonical (got {len(terms)} term(s)); (section, r_basis_label) "
            f"may not be a valid lift coordinate — override r_label_compose "
            f"for a direct construction."
        )

    # -------- bilinear / linear extensions --------

    def multiply_elements(self, x: Element, y: Element) -> Element:
        """Bilinear extension of `multiply` to Element × Element."""
        out: dict[Label, "LaurentPoly | RLaurent"] = {}
        for a, ca in x.terms.items():
            for b, cb in y.terms.items():
                scalar = ca * cb
                if scalar.is_zero():
                    continue
                for lbl, c in (self.multiply(a, b) * scalar).terms.items():
                    out[lbl] = out[lbl] + c if lbl in out else c
        return Element({l: c for l, c in out.items() if not c.is_zero()})

    def rho_element(self, x: Element) -> Element:
        """Linear extension of `rho` to Element.  At the Z-form
        level there is no twist (Z's star is identity); ρ acts on
        labels with coefficients carried along.
        """
        out: dict[Label, LaurentPoly] = {}
        for a, c in x.terms.items():
            ra = self.rho(a)
            out[ra] = out[ra] + c if ra in out else c
        return Element({l: c for l, c in out.items() if not c.is_zero()})

    def rho_inverse_element(self, x: Element) -> Element:
        """Linear extension of `rho_inverse` to Element."""
        out: dict[Label, LaurentPoly] = {}
        for a, c in x.terms.items():
            ra = self.rho_inverse(a)
            out[ra] = out[ra] + c if ra in out else c
        return Element({l: c for l, c in out.items() if not c.is_zero()})

    def trace_element(self, x: Element, K: int = 20) -> RPowerSeries:
        """Linear extension of `trace`:  `Tr(Σ c_a · L_a) =
        Σ c_a · Tr(L_a)`.  Each Z-coefficient is lifted into R on
        the fly."""
        R = self.coefficient_ring()
        result = RPowerSeries.zero(R, K)
        for a, c in x.terms.items():
            if c.is_zero():
                continue
            result = result + _laurentpoly_times_rpowerseries(c, self.trace(a, K))
        return result

    def inner_product(
        self, a: Label, b: Label, K: int = 20,
    ) -> RPowerSeries:
        """The **trace pairing** — the second face of the trace:

            I_{a, b}(q, μ) = Tr(L_{ρ(a)} · L_b) = Tr(L_b · L_{ρ⁻¹(a)}) ∈ R((q))

        (the two ways of writing it are ρ²-twisted cyclicity in pairing
        form; see `verify_trace_pairing_faces`).  This is the Schur
        index with line insertions and the inner product of **Schur
        quantization** (Goal 2.2); orthonormality (Goal 2.1) says the
        canonical basis is orthonormal to leading order in this pairing.

        **Overridable.**  The default computes multiply-then-trace, but
        concrete realisations often have sharper direct methods — e.g.
        `BPSKAlgebra.inner_product` evaluates the single-Habiro-path
        Schur formula with no Element multiplication, and the urq-torus
        realisation uses the ρ-free §6b formula.  An override must agree
        with this default (`verify_inner_product_consistent`); for an
        overriding realisation that agreement is a genuine cross-check,
        not a tautology.
        """
        return self.trace_element(self.multiply(self.rho(a), b), K)

    # -------- R-form view --------

    def to_R_form(self, x: Element) -> ElementOverR:
        """Convert a Z-form `Element` to the R-form `ElementOverR`.

        Default implementation: for each `(label, lp)` term in `x`,
        decompose `label` via `_label_section_decompose` into
        `(sec_label, r_coef)` (with `r_coef ∈ RElement[R]`); the
        contribution at `sec_label` becomes `lp · r_coef` in
        `RLaurent` over `R`.

        Realisations may override for performance (e.g., if they
        cache an internal R-form already).

        **Derived view, not a second presentation.**  The R-form holds the
        *same* data as the Z-form — the quadruples `(section, irrep, q-power,
        Z-coeff)` regrouped by section — so this is a regroup, not arithmetic
        (when the label is literally `(section, R-basis)`).  The Z-form is the
        efficient representation for all core ops; reach for the R-form only
        when a clear need arises (e.g. recognising flavour enhancement), never
        for core arithmetic.  **Consistency is the realisation's
        responsibility:** `from_R_form(to_R_form(L_a)) == L_a` is the condition
        that this view is faithful — checked inline where realisations exercise
        the R-form, but *not* enforced contract-wide (there is deliberately no
        `verify_R_form_roundtrip`)."""
        R = self.coefficient_ring()
        out: dict[Label, RLaurent] = {}
        for label, lp in x.terms.items():
            sec_label, r_coef = self._label_section_decompose(label)
            if r_coef.is_zero():
                continue
            if r_coef.is_one():
                rl = _laurentpoly_to_rlaurent(lp, R)
            else:
                r_terms: dict[int, RElement] = {}
                for q_exp, q_coeff in lp._coeffs.items():
                    scaled = q_coeff * r_coef
                    if not scaled.is_zero():
                        r_terms[q_exp] = scaled
                rl = RLaurent(R, r_terms)
            if rl.is_zero():
                continue
            if sec_label in out:
                out[sec_label] = out[sec_label] + rl
            else:
                out[sec_label] = rl
        return ElementOverR(
            R, {l: c for l, c in out.items() if not c.is_zero()},
        )

    # -------- unflavoured specialisation: forget = base_change(ε) + collapse --------

    def forget(self) -> "KAlgebra":
        """The **unflavoured scaffold** `K_𝖖[T]` of this (possibly flavoured)
        algebra: `base_change(ε)` *plus* the collapse of the flavour-in-labels
        onto sections (`ε = coefficient_ring().augmentation()`, the rep-ring
        augmentation `χ_r ↦ dim r`; Plan 32 T1).  Returns a `KAlgebra` over `Z`
        whose canonical basis is the section image `{M_s}` (the unflavoured
        canonical basis): `forget(L_a) = dim(r_a)·M_{s_a}` for
        `_label_section_decompose(a) = (s_a, χ_{r_a})`.

        This is **strictly more than `base_change(ε)`**, which is
        coefficient-only and keeps the flavoured labels (so its `multiply` still
        distinguishes flavour).  `forget` additionally collapses labels to
        sections and `dim`-weights, giving the genuine unflavoured product —
        `_ForgetKAlgebra` *extends* `_BaseChangeKAlgebra` to add exactly that.

        Default: `self` if already unflavoured, else `_ForgetKAlgebra(self)` —
        the unflavoured KAlgebra is *produced on demand*, not carried.  A
        subclass *may* override only with a genuine native realisation of the
        **same theory with `G_f` forgotten** (certify with a `KAlgebraIso`).
        NB a flow's pure-gauge RG base (`…OverPure`'s `self._pure`) is **not**
        this — `forget` drops the `G_f` flavour but keeps the matter; the
        pure-gauge base is a different theory.

        Flavoured orthonormality axiom: on sections `I_{s,s'} = δ_{s,s'} + O(𝖖)`;
        a canonical dressed by a 1-dim rep lands on an unflavoured canonical
        (norm 1), dressed by `χ_w` (dim>1) on `dim(w)·M_s`, so
        `forget().inner_product(d, d)` is `(dim w)²` to leading order.
        """
        if isinstance(self.coefficient_ring(), TrivialZPlusRing):
            return self
        return _ForgetKAlgebra(self)

    def lower_flavour(self, phi: RingHom) -> "KAlgebra":
        """Reduce the flavour group via an augmentation-compatible ring hom
        `phi : coefficient_ring() -> R'` (`ε_{R'}∘phi = ε`, carrying the
        1-dim reps `Λ → Λ'`).  Returns the `R'`-flavoured KAlgebra obtained by
        **identifying sections and pushing the R-elements through `phi`**: each
        canonical `(s, χ)` transports to `(s, phi(χ))`, re-expanded over the
        `R'`-irreps.  Where `phi` grows `Λ` (e.g. SU(2)→U(1)) a canonical
        **splits** (`χ_j·M_s ↦ Σ_k μ^k·M_s`); where it kills flavour
        (`phi = augmentation() → Z`) it **merges** — that case is `forget()`.

        Requires the sharpened `(section, single-irrep)` form
        (`verify_section_is_single_irrep`); that is what makes the transport
        well-defined.  `trace` transports too — it is R-linear over the centre
        (`Tr((s,χ)) = χ·Tr(M_s)`), so `Tr'((s,w)) = w·φ(Tr(M_s))` — and
        `inner_product` follows (multiply-then-trace).
        """
        if phi.source != self.coefficient_ring():
            raise ValueError(
                f"lower_flavour: phi.source {phi.source} != "
                f"this algebra's coefficient_ring {self.coefficient_ring()}"
            )
        return _LoweredFlavourKAlgebra(self, phi)

    # -------- central embedding R ↪ A and the R-module coordinate --------
    #
    # A flavoured `A_𝖖` is free over `R = coefficient_ring()` but *not
    # canonically*: an R-basis is a choice of section, and two sections
    # differ by unit characters.  The free-but-non-canonical structure is
    # encoded faithfully by exactly two pieces of independent data — the
    # R-module coordinate (`section_decompose`, = the `_label_section_
    # decompose` hook) and the central embedding (`embed_R`) — bound by
    # the faithfulness axiom `embed_R(r_coeff(a)) · L_{section(a)} == L_a`.
    # Everything else (the lift `from_R_form`, ρ on the R-form) is derived.

    def section_decompose(self, label: Label) -> "tuple[Label, RElement]":
        """The R-module coordinate of the canonical basis element
        `L_label`: a pair `(section_rep, r_coeff)` with
        `r_coeff ∈ RElement` over `coefficient_ring()`, such that in the
        R-module `L_label = embed_R(r_coeff) · L_{section_rep}`.

        Public face of the realisation hook `_label_section_decompose`;
        it makes the *non-canonical* free-R-module structure (an R-basis
        is a choice of section) visible in the abstract API.  `r_coeff`
        is a single character for abelian flavour and may be a virtual
        character for non-abelian flavour.
        """
        return self._label_section_decompose(label)

    def embed_R(self, r: RElement) -> Element:
        """The central embedding `ι : R ↪ A_𝖖` of the flavour rep-ring
        `R = coefficient_ring()` as the central subalgebra — a **map of
        canonical bases**: each character `χ_w` (a basis element of `R`)
        maps to the central canonical basis element `χ_w` of `A_𝖖`,
        extended `Z`-linearly to `RElement → Element`.

        Default implementation: embeds only the trivial character
        `1_R ↦ identity` (so unflavoured algebras, and the `1_R`
        component of any `R`, are covered).  Flavoured realisations MUST
        override to embed the non-trivial characters — the realisation
        is the only place that knows which canonical label each `χ_w`
        is.  (For abelian flavour `μ^f ↦ L_{γ_f}`; for non-abelian,
        `χ_w ↦ L_{χ_w}`, with fusion handled by `multiply`.)
        """
        R = self.coefficient_ring()
        if not isinstance(r, RElement) or r.ring != R:
            raise TypeError(
                "embed_R: argument must be an RElement over coefficient_ring()"
            )
        ob = R.one_basis()
        non_trivial = [b for b in r.terms if b != ob]
        if non_trivial:
            raise NotImplementedError(
                f"{type(self).__name__}.embed_R: the default only embeds "
                f"the trivial character 1_R; override embed_R to embed "
                f"the non-trivial characters {non_trivial!r}."
            )
        n = r.terms.get(ob, 0)
        if n == 0:
            return Element.zero()
        return Element.basis(self.identity()) * n

    def from_R_form(self, x: ElementOverR) -> Element:
        """Lift an R-form `ElementOverR` back to the Z-form `Element` — the
        exact inverse of `to_R_form`, transparently and entirely over `Z`.

        An element is freely interconvertible between its two presentations:
        the **R-linear-over-sections** form (coefficients in `R`, on section
        labels) and the **Z-linear-over-`(section, R-basis)`** form
        (coefficients in `Z[q^±]`, on full canonical labels).  Each R-form
        term `c_w(q)·χ_w·L_section` is just the Z-form canonical
        `c_w(q)·L_a` with `a = r_label_compose(section, χ_w)` — so the lift
        is a relabelling, no `R`-side arithmetic required.

        `to_R_form` reads the lift coordinate (`r_label_decompose`); this is
        its partner (`r_label_compose`).  For realisations that supply only
        the older `embed_R`, `r_label_compose`'s default bridges to it, so
        this stays backward-compatible without needing `embed_R` on the new
        lift-coordinate surface.
        """
        if not isinstance(x, ElementOverR):
            raise TypeError("from_R_form: argument must be an ElementOverR")
        out = Element.zero()
        for sec, rl in x.terms.items():
            for q_exp, r_coef in rl.coeffs.items():
                for w, c_w in r_coef.terms.items():   # r_coef = Σ_w c_w·χ_w, c_w ∈ Z
                    if c_w == 0:
                        continue
                    lab = self.r_label_compose(sec, w)
                    out = out + Element({lab: LaurentPoly({q_exp: c_w})})
        return out

    def rho_R_form(self, x: ElementOverR) -> ElementOverR:
        """ρ acting on the R-form, **derived** (not a primitive) as
        `to_R_form ∘ rho_element ∘ from_R_form`.  The `⋆`/`δ` corrections
        of the non-canonical R-basis fall out automatically: ρ on the
        embedded centre *is* the rep-ring duality `⋆`, and re-sectioning
        the permuted lift supplies the section μ-shift.  No bespoke
        `rho_delta` is needed.
        """
        return self.to_R_form(self.rho_element(self.from_R_form(x)))

    # -------- axiom verifiers (return bool) --------

    def verify_identity_in_basis(self) -> bool:
        """`e · e = e` where `e = identity()`."""
        e = self.identity()
        return self.multiply(e, e) == Element.basis(e)

    def verify_unit_law(self, a: Label) -> bool:
        """Full two-sided unit law `e · L_a = L_a = L_a · e`
        (`e = identity()`).  `verify_identity_in_basis` only checks the
        idempotent `e·e = e`; this checks the identity acts as a unit on an
        arbitrary basis element (the unit axiom of a unital algebra)."""
        e = self.identity()
        La = Element.basis(a)
        return self.multiply(e, a) == La and self.multiply(a, e) == La

    def verify_associativity(self, a: Label, b: Label, c: Label) -> bool:
        """Associativity `(L_a · L_b) · L_c = L_a · (L_b · L_c)` — the
        defining axiom of an *associative* algebra, asserted in the class
        docstring but not previously checked (repo_audit finding A7).
        Evaluated on basis elements through the bilinear extension
        `multiply_elements` (structure constants are exact in `q`)."""
        ab = self.multiply(a, b)
        bc = self.multiply(b, c)
        lhs = self.multiply_elements(ab, Element.basis(c))
        rhs = self.multiply_elements(Element.basis(a), bc)
        return lhs == rhs

    def verify_rho_fixes_identity(self) -> bool:
        """`ρ(1) = 1`."""
        return self.rho(self.identity()) == self.identity()

    def verify_rho_inverse(self, a: Label) -> bool:
        """`ρ⁻¹(ρ(a)) = a` and `ρ(ρ⁻¹(a)) = a`."""
        return (
            self.rho_inverse(self.rho(a)) == a
            and self.rho(self.rho_inverse(a)) == a
        )

    def verify_rho_is_automorphism(
        self, a: Label, b: Label,
    ) -> bool:
        """`ρ(L_a · L_b) = ρ(L_a) · ρ(L_b)`.  ρ is an algebra
        automorphism; on the centre it acts by the rep-ring duality `⋆`,
        so for a flavour-in-coefficients realisation `ρ(L_a)` is a genuine
        *element* (`⋆`-twisted, with the per-letter μ-shift), not just the
        permuted label.  We therefore extend both sides through
        `rho_element` — which equals the plain label permutation when the
        coefficients are `⋆`-invariant (Z / self-dual R), so this is
        identical to `multiply(rho(a), rho(b))` for un-twisted ρ and
        correct for the twisted one."""
        lhs = self.rho_element(self.multiply(a, b))
        rhs = self.multiply_elements(
            self.rho_element(Element.basis(a)),
            self.rho_element(Element.basis(b)),
        )
        return lhs == rhs

    # Backward-compatibility alias for the previous twisted-automorphism
    # name (Plan 10 dropped the twist since Element is over Z).
    verify_rho_is_twisted_automorphism = verify_rho_is_automorphism

    def verify_bar_involution(self, a: Label, b: Label) -> bool:
        """`C^c_{ab}(q^{-1}) = C^c_{ba}(q)`."""
        return self.multiply(a, b).bar() == self.multiply(b, a)

    def verify_rho_twisted_trace(
        self, a: Label, b: Label, K: int = 5,
    ) -> bool:
        """`Tr(L_a · L_b) = Tr(ρ²(L_b) · L_a)` up to order `q^K`.
        Negative q-power coefficients in structure constants shift
        the trace down, so we widen the internal `K` to absorb them."""
        ab = self.multiply(a, b)
        rho2b = self.rho(self.rho(b))
        rho2b_a = self.multiply(rho2b, a)
        neg = 0
        for x in (ab, rho2b_a):
            for c in x.terms.values():
                if c.is_zero():
                    continue
                emin = _coeff_min_exp(c)
                if emin < neg:
                    neg = emin
        K_int = K - neg
        lhs = self.trace_element(ab, K_int)
        rhs = self.trace_element(rho2b_a, K_int)
        diff = lhs - rhs
        for e, c in diff.coeffs.items():
            if e <= K and not c.is_zero():
                return False
        return True

    def verify_orthonormality(self, a: Label, b: Label, K: int = 5) -> bool:
        """`I_{a, b} == δ_{a, b} + O(𝖖)` (Goal 2.1), checked as:
        (i) no nonzero coefficient at any negative q-exponent — the
        trace codomain `R((q))` is Laurent, so the negative window is
        part of the claim, not automatic — and (ii) `I_{a, b}[q⁰]`
        equals `R.one()` for `a == b`, `0` otherwise."""
        I = self.inner_product(a, b, K)
        for e, c in I.coeffs.items():
            if e < 0 and not c.is_zero():
                return False
        const = I[0]
        R = self.coefficient_ring()
        # The paper's flavoured orthonormality is on the **identity
        # summand**: I^(1)_{a,b}[q⁰] = δ_{a,b} — the χ₀-component of
        # the R-valued coefficient, NOT the whole series.  This is exactly
        # faithful on canonical labels read as pairs (section label,
        # R element): by Schur orthogonality the χ₀-component of
        # r_a⋆ · r_b is δ_{r_a, r_b}, abelian and non-abelian alike.
        # Unflavoured algebras reduce to the previous strict check.
        expected = 1 if a == b else 0
        return const.terms.get(R.one_basis(), 0) == expected

    def verify_trace_pairing_faces(
        self, a: Label, b: Label, K: int = 5,
    ) -> bool:
        """The two faces of the trace pairing agree up to `q^K`:
        `Tr(L_{ρ(a)} · L_b) == Tr(L_b · L_{ρ⁻¹(a)})` — ρ²-twisted
        cyclicity in pairing form (and the reason `rho_inverse` is a
        contract primitive).  Widens the internal window to absorb
        negative q-powers in structure constants, as in
        `verify_rho_twisted_trace`."""
        x = self.multiply(self.rho(a), b)
        y = self.multiply(b, self.rho_inverse(a))
        neg = 0
        for el in (x, y):
            for c in el.terms.values():
                if c.is_zero():
                    continue
                emin = _coeff_min_exp(c)
                if emin < neg:
                    neg = emin
        K_int = K - neg
        diff = self.trace_element(x, K_int) - self.trace_element(y, K_int)
        for e, c in diff.coeffs.items():
            if e <= K and not c.is_zero():
                return False
        return True

    def verify_inner_product_consistent(
        self, a: Label, b: Label, K: int = 5,
    ) -> bool:
        """When a realisation overrides `inner_product` with a sharper
        direct formula, it must agree with the **nearest base-class
        implementation** — the principled reference: the certified RG
        pairing for `RGKAlgebra` realisations, multiply-then-trace at
        the `KAlgebra` root.  Trivially True when not overridden; a
        genuine cross-validation of the realisation when it is."""
        cls = type(self)
        own = cls.inner_product
        if own is KAlgebra.inner_product:
            return True
        ref = None
        for base in cls.__mro__[1:]:
            cand = base.__dict__.get("inner_product")
            if cand is not None and cand is not own:
                ref = base
                break
        if ref is None:
            return True
        direct = self.inner_product(a, b, K)
        default = ref.inner_product(self, a, b, K)
        return (direct - default).is_zero()

    def verify_embed_section_roundtrip(self, label: Label) -> bool:
        """Faithfulness axiom of the free-R-module encoding:
        `embed_R(r_coeff(a)) · L_{section(a)} == L_a`, where
        `(section(a), r_coeff(a)) = section_decompose(a)`."""
        sec, r_coef = self.section_decompose(label)
        lhs = self.multiply_elements(self.embed_R(r_coef), Element.basis(sec))
        return lhs == Element.basis(label)

    def verify_embed_intertwines_rho(self, r: RElement) -> bool:
        """Faithfulness: the central embedding intertwines the Z₊-ring
        `⋆` with the algebra `ρ` — `embed_R(r⋆) == ρ(embed_R(r))`."""
        lhs = self.embed_R(r.star())
        rhs = self.rho_element(self.embed_R(r))
        return lhs == rhs

    def verify_section_is_single_irrep(self, label: Label) -> bool:
        """Sharpened flavour contract (Plan 32): `_label_section_decompose(label)`
        returns `(section, χ)` with `χ` a **single** R-canonical-basis-element —
        exactly one basis term, coefficient `+1` (not a virtual / multi-term
        character).  This `(section, single-irrep)` form is what lets
        `forget()` / `lower_flavour()` transport cleanly: the canonical is a
        `Λ`-torsor over the unflavoured canonical basis, certified by the
        section.  Unflavoured / abelian labels satisfy it trivially
        (`r = R.one()` / a single `μ`-monomial)."""
        _sec, r = self._label_section_decompose(label)
        terms = [(b, n) for b, n in r.terms.items() if n != 0]
        return len(terms) == 1 and terms[0][1] == 1

    # -------- ρ²-orbit canonicalisation (optional trace utility) --------

    def rho_squared_is_identity(self) -> bool:
        """Optional structural flag: True iff ρ² = id on all canonical-
        basis labels.  When True, ρ²-orbits are all singletons and
        ρ²-canonicalisation is a no-op.  Trace pipelines can use this
        to skip the canonicalisation step entirely.

        Default: False.  Subclasses where ρ has order ≤ 2 (e.g.
        `TrivialKAlg`, `QuantumTorusZ2KAlg`) should override to True.
        """
        return False

    def _canonical_rho2_orbit_rep(self, label: Label) -> Label:
        """Return the canonical representative of `label`'s ρ²-orbit.

        Optional utility method, usable by any trace-evaluation pipeline
        that needs to fold ρ²-orbits (e.g.
        `ConeData.simplify_trace_via_cone_data` for ConeKAlgebra-style
        algebras; also potentially any custom trace recursion that
        wants to canonicalise input labels by ρ²-cyclicity before
        applying a Layer-2 plug-in).

        Not tied to cones: ρ²-cyclicity (`Tr(ρ²(x)) = Tr(x)`) is a
        general KAlgebra contract axiom, so any KAlgebra subclass MAY
        provide a closed-form canonical representative for trace
        evaluation, regardless of whether it has cone-data structure.

        Default impl: **orbit walk** (apply ρ² repeatedly until the
        orbit closes; return `min(orbit)` by Python sort).  Works for
        algebras where ρ² has finite order on every label (Pentagon,
        Heptagon, A1A2k, ...).  Guarded with a `MAX_ORBIT_LEN` safety
        bound that raises a clear error rather than hanging.

        Algebras with infinite ρ²-orbits (e.g. U(1)-gauged theories
        where ρ² shifts torus directions linearly: Sqed1, U1Square,
        U(1)Hex, ...) MUST override with a closed-form drift-quotient
        canonicalisation.  Typical shape for Sqed1:

            def _canonical_rho2_orbit_rep(self, label):
                # ρ²((m, n)) = (m, n + m).  Orbit = {(m, n + km) : k}.
                # Canonical: (m, n mod |m|) for m ≠ 0; (0, n) for m = 0.
                m, n = label
                if m == 0:
                    return (0, n)
                return (m, n % abs(m))
        """
        # Short-circuit when ρ² = id on the whole algebra.
        if self.rho_squared_is_identity():
            return label
        MAX_ORBIT_LEN = 1_000
        orbit = [label]
        seen = {label}
        cur = self.rho(self.rho(label))
        steps = 0
        while cur not in seen:
            steps += 1
            if steps > MAX_ORBIT_LEN:
                raise RuntimeError(
                    f"{type(self).__name__}._canonical_rho2_orbit_rep: "
                    f"ρ²-orbit of {label!r} did not close within "
                    f"{MAX_ORBIT_LEN} steps.  Override "
                    f"_canonical_rho2_orbit_rep with a closed-form "
                    f"drift-quotient canonicalisation if this algebra "
                    f"has infinite ρ²-orbits (e.g. U(1)-gauged theories)."
                )
            seen.add(cur)
            orbit.append(cur)
            cur = self.rho(self.rho(cur))
        return min(orbit)

    # -------- optional cone-filtration structure --------

    def cone_data(self) -> "ConeData | None":
        """Optional `ConeData` sidecar describing the q-commuting-cone
        structure of this K-algebra (multiplicative generators, cones,
        cocycle, cross-products, and the bijection to native labels).

        Default: `None`, meaning the structure is not exposed.
        Subclasses with this structure should override to return a
        concrete `ConeData` instance; doing so makes
        `_multiply_via_cone_data` and `cone_data().derived_multiply`
        available for use as the subclass's `multiply` (or as an
        internal speed-up / verifier).

        See `cone_data.py` for the contract.
        """
        return None

    def _multiply_via_cone_data(self, a: Label, b: Label) -> "Element":
        """Convenience: delegate `multiply(a, b)` to
        `self.cone_data().derived_multiply(a, b)`.  Raises
        `NotImplementedError` if `cone_data()` is `None`.

        Subclasses with cone-data structure can override `multiply` to
        a one-liner `return self._multiply_via_cone_data(a, b)` to opt
        in to the generic reducer.
        """
        cd = self.cone_data()
        if cd is None:
            raise NotImplementedError(
                f"{type(self).__name__}.cone_data() returned None; "
                f"either override multiply() or expose cone_data()."
            )
        return cd.derived_multiply(a, b)

    # -------- base ring change --------

    def base_change(self, phi: RingHom) -> "KAlgebra":
        """Reinterpret this KAlgebra as one over `phi.target` by pushing
        the *trace's R-coefficients* through the Z₊-ring hom `phi`.

        At the Z-form Element level no change is needed (Element is
        over Z[q^±], no R-coefficients).  Only `coefficient_ring()`,
        `trace()`, `inner_product()`, and `to_R_form()` change.
        """
        if phi.source != self.coefficient_ring():
            raise ValueError(
                f"base_change: phi.source {phi.source} != "
                f"this algebra's coefficient_ring {self.coefficient_ring()}"
            )
        return _BaseChangeKAlgebra(self, phi)

    def add_flavour(self, flavour) -> "KAlgebra":
        """Adjoin a spectator flavour symmetry, returning a new KAlgebra over
        `R_self ⊗ R(flavour)`.

        `flavour` is the flavour symmetry's representation ring: either an int
        `n` (shorthand for `AbelianZPlusRing(n) = R(U(1)^n)`) or any
        `ZPlusRing` `R` (e.g. `SU2ZPlusRing` / `SU3ZPlusRing` for non-abelian
        flavour).  Operators gain a flavour-irrep label coordinate; products
        Clebsch-Gordan via `R.multiply_basis`, `ρ` dualizes via
        `R.star_basis`, and the trace is weighted by the flavour character
        `R.basis_element`.  The base may itself be flavoured (the rings
        tensor).  See `flavoured_kalgebra.py`.

        **Aspirationally obsolete (Plan 32) — prefer the flavour-growing ring
        homs.**  This construction encodes flavour as an extra *label
        coordinate* `f` (Clebsch-Gordan in products at the label level).  The
        Plan-32-canonical encoding instead carries flavour in the *coefficient
        ring* — "free over `R(G_f)`" — reached functorially by `base_change`
        through a flavour-growing hom (`zplus_ring.unit_hom(R)` to flavour an
        unflavoured algebra, `tensor_inclusion_hom(R⊗R', slot)` to adjoin a
        factor).  The two present the **same** flavoured algebra under
        `(L_a, f) ↔ χ_f·L_a` (trace-compatible: `Tr(L_{(a,f)}) = χ_f·Tr(L_a)`),
        and `forget() = base_change(augmentation)` inverts both.  Retained, not
        retired: matter-dressing RG flows still use `add_flavour` as their
        auxiliary until they migrate to the coefficient encoding."""
        from flavoured_kalgebra import AddFlavourKAlgebra
        return AddFlavourKAlgebra(self, flavour)


# ---------------------------------------------------------------------------
# _BaseChangeKAlgebra
# ---------------------------------------------------------------------------


def _section_split_via_lift(source: "KAlgebra", label):
    """`(section, source-R coefficient)` of `label`, **consuming the new
    flavour-lift coordinate** `r_label_decompose` (the single-irrep key `w` is
    lifted to the RElement `R.basis_element(w)`), and **falling back** to the
    to-be-retired `_label_section_decompose` for sources that do not yet
    implement the lift coordinate.

    The flavour-change wrappers (`_BaseChangeKAlgebra` / `_ForgetKAlgebra` /
    `_LoweredFlavourKAlgebra`) route their per-label section reads through here,
    so once every source they are applied to implements `r_label_decompose`,
    `_label_section_decompose` is no longer consumed (only the fallback path
    touches it).  For an already-migrated source the result is identical to
    `_label_section_decompose` (the forward bridge guarantees
    `_lsd = (section, R.basis_element(w))`)."""
    try:
        sec, w = source.r_label_decompose(label)
    except NotImplementedError:
        return source._label_section_decompose(label)
    return sec, source.coefficient_ring().basis_element(w)


class _BaseChangeKAlgebra(KAlgebra):
    """A KAlgebra over `phi.target` obtained by base-changing `source`
    along `phi`.  Same Label set, same multiply (Z-form, unaffected by
    R-side change); coefficient_ring / trace / inner_product / R-form
    pushed through `phi`.

    NB this is **coefficient-only** — it keeps the flavoured labels, so it is
    *not* the unflavoured algebra.  For the genuine forget (labels collapsed to
    sections, `dim`-weighted) use `KAlgebra.forget()` / `_ForgetKAlgebra`, which
    *extends* this with that collapse."""

    __slots__ = ("_source_alg", "_phi")

    def __init__(self, source_alg: KAlgebra, phi: RingHom):
        self._source_alg = source_alg
        self._phi = phi

    def coefficient_ring(self) -> ZPlusRing:
        return self._phi.target

    def identity(self) -> Label:
        return self._source_alg.identity()

    def multiply(self, a: Label, b: Label) -> Element:
        # Z-form Element is unchanged; just delegate.
        return self._source_alg.multiply(a, b)

    def rho(self, a: Label) -> Label:
        return self._source_alg.rho(a)

    def rho_inverse(self, a: Label) -> Label:
        return self._source_alg.rho_inverse(a)

    def trace(self, a: Label, K: int = 20) -> RPowerSeries:
        src_trace = self._source_alg.trace(a, K)
        return self._phi.apply_RPowerSeries(src_trace)

    def r_label_decompose(self, label: Label):
        """Flavour-lift coordinate of the base-changed algebra: the source's
        section, with its single irrep `χ_w` pushed through `φ`.

        This **consumes** the source's `r_label_decompose` and is available
        exactly when `φ` carries that irrep to a *single* target irrep
        (coefficient 1) — the flavour-growing / restriction homs
        (`unit_hom`, `tensor_inclusion_hom`, a sub-torus `restriction_hom`)
        do.  The augmentation does not (it lands on `dim(w)·χ₀`), which is why
        `forget()` (`_ForgetKAlgebra`) overrides with the section-collapse
        instead.  Raises `NotImplementedError` when the source has no lift
        coordinate, or when `φ` does not land on a single irrep."""
        sec, w_src = self._source_alg.r_label_decompose(label)
        pushed = self._phi.apply_RElement(
            self._source_alg.coefficient_ring().basis_element(w_src)
        )
        terms = [(k, c) for k, c in pushed.terms.items() if c]
        if len(terms) == 1 and terms[0][1] == 1:
            return sec, terms[0][0]
        raise NotImplementedError(
            f"_BaseChangeKAlgebra.r_label_decompose: phi sends source irrep "
            f"{w_src!r} to {dict(pushed.terms)!r}, not a single target irrep; "
            f"no single-irrep lift coordinate over phi.target."
        )

    def _label_section_decompose(
        self, label: Label,
    ) -> "tuple[Label, RElement]":
        # Section structure depends on the target R; defer to source for the
        # section labels — **consuming** the source's r_label_decompose lift
        # coordinate (falling back to the obsolete-to-be section method for
        # un-migrated sources) — and apply phi to push the source's RElement
        # coefficient through to the target ring.
        #
        # Obsolete-to-be (Plan 32): superseded by r_label_decompose above; kept
        # only for the general / virtual-character RElement form (e.g. the
        # augmentation case, where a dressed label lands on dim(w)·χ₀, which is
        # not a single irrep).
        sec, src_coef = _section_split_via_lift(self._source_alg, label)
        # phi.apply_RElement maps RElement[source_R] -> RElement[target_R].
        target_coef = self._phi.apply_RElement(src_coef)
        return sec, target_coef

    def __repr__(self) -> str:
        return f"_BaseChangeKAlgebra({self._source_alg!r}, {self._phi!r})"


def _rlaurent_over_Z_to_laurentpoly(rl: RLaurent) -> LaurentPoly:
    """`RLaurent` over `TrivialZPlusRing` → `LaurentPoly` (read off the `()`
    coefficient of each q-graded `RElement`)."""
    return LaurentPoly({
        q: c.terms.get((), 0)
        for q, c in rl.coeffs.items()
        if c.terms.get((), 0)
    })


class _ForgetKAlgebra(_BaseChangeKAlgebra):
    """The unflavoured scaffold `K_𝖖[T]` returned by `KAlgebra.forget()`:
    a **base-change along the augmentation `ε`** (handled by the
    `_BaseChangeKAlgebra` half — coefficient_ring `Z`, trace `ε∘source.trace`)
    **plus the collapse of the flavour-in-labels onto sections** (added here).
    Canonical basis = the section labels (unflavoured canonical basis);
    `multiply` = the genuine unflavoured product `ε∘to_R_form(source.multiply)`
    (`dim`-weighted on dressed inputs); `ρ` = the section-ρ.

    The unflavoured KAlgebra is produced *on demand* here, not carried; a
    subclass may override `KAlgebra.forget()` only with a genuine native
    realisation of the same theory with `G_f` forgotten (certify via
    `KAlgebraIso`) — *not* a flow's pure-gauge base.

    *Partial-forget generalisation (not built here).*  Base-changing along any
    hom `φ` compatible with augmentation (`ε_target ∘ φ = ε_source`) lowers
    `G_f` rather than forgetting it.  Unlike this `φ = ε → Z` case (a *merge*:
    `χ_r·M_s ↦ dim(r)·M_s`), a general `φ` must **re-section relative to
    `φ.target`** and can **split** canonicals where `φ` grows `Λ` (1-dim reps):
    e.g. SU(2)→U(1) sends `χ_j·M_s ↦ Σ_k μ^k·M_s = Σ_k M_{s+k}`.  So partial
    forget is a basis-changing functor, materially more than `base_change`.
    """

    __slots__ = ()

    def __init__(self, source: "KAlgebra"):
        super().__init__(source, source.coefficient_ring().augmentation())

    def _section_of(self, label: Label) -> Label:
        # Consume the source's r_label_decompose lift coordinate (fall back to
        # the obsolete-to-be section method for un-migrated sources).
        return _section_split_via_lift(self._source_alg, label)[0]

    def identity(self) -> Label:
        return self._section_of(self._source_alg.identity())

    def multiply(self, a: Label, b: Label) -> Element:
        # Z-form, over the lift coordinate (no R-form / ElementOverR): each
        # product term `c(q)·L_label` decomposes as `(section, χ_w)`, and the
        # augmentation `ε` sends `χ_w ↦ dim(w)`, contributing `dim(w)·c(q)` on
        # the section.  (Same result as `ε∘to_R_form(source.multiply)`, computed
        # per term — `to_R_form` itself only reads this lift coordinate.)
        out: "dict[Label, LaurentPoly]" = {}
        for label, lp in self._source_alg.multiply(a, b).terms.items():
            sec, r_coef = _section_split_via_lift(self._source_alg, label)
            z = self._phi.apply_RElement(r_coef).terms.get((), 0)  # ε-augmented coeff
            if z == 0:
                continue
            contrib = lp * LaurentPoly({0: z})
            out[sec] = contrib if sec not in out else out[sec] + contrib
        return Element({l: c for l, c in out.items() if not c.is_zero()})

    def rho(self, a: Label) -> Label:
        return self._section_of(self._source_alg.rho(a))

    def rho_inverse(self, a: Label) -> Label:
        return self._section_of(self._source_alg.rho_inverse(a))

    def inner_product(self, a: Label, b: Label, K: int = 20) -> RPowerSeries:
        return self._phi.apply_RPowerSeries(
            self._source_alg.inner_product(a, b, K)
        )

    def r_label_decompose(self, label: Label):
        """`forget()` is unflavoured (coefficient ring `Z`): the lift
        coordinate is trivial — section = the label itself, irrep = `χ₀`."""
        return label, self._phi.target.one_basis()

    def r_label_compose(self, section: Label, r_basis_label) -> Label:
        # Unflavoured: the only irrep is χ₀, so the label is the section.
        return section

    def _label_section_decompose(
        self, label: Label,
    ) -> "tuple[Label, RElement]":
        # Obsolete-to-be (Plan 32): derivable from r_label_decompose via the
        # forward bridge (χ₀ ↦ R.one()).  forget() is unflavoured: trivial
        # decomposition over Z.
        return label, self._phi.target.one()

    def __repr__(self) -> str:
        return f"_ForgetKAlgebra({self._source_alg!r})"


class _LoweredFlavourKAlgebra(_BaseChangeKAlgebra):
    """Flavour reduction along an augmentation-compatible hom `phi: R -> R'`
    (`KAlgebra.lower_flavour`).  Unlike `_BaseChangeKAlgebra` (coefficient-only,
    same labels) this transports the **section engine**: canonical labels are
    `(section, R'-irrep)` pairs, and the operations identify sections and push
    the R-elements through `phi` — so a canonical *splits* where `phi` grows
    `Λ`.  `_ForgetKAlgebra` is the `phi = ε` (merge) special case.

    `multiply((s1,w1),(s2,w2))` = (fuse `w1·w2` in `R'`) · `phi`(section product
    `M_{s1}·M_{s2}`), re-expanded onto `(section, R'-irrep)` labels.  `ρ` keeps
    the section-ρ and dualises the char (`⋆`).  `trace` is R-linear over the
    centre, so `Tr'((s,w)) = w·φ(source.trace(M_s))`; `inner_product` follows
    from multiply-then-trace.
    """

    __slots__ = ()

    def __init__(self, source: "KAlgebra", phi: RingHom):
        super().__init__(source, phi)

    def _section_of(self, label: Label) -> Label:
        # Consume the source's r_label_decompose lift coordinate (fall back to
        # the obsolete-to-be section method for un-migrated sources).
        return _section_split_via_lift(self._source_alg, label)[0]

    def identity(self) -> Label:
        s_id = self._section_of(self._source_alg.identity())
        return (s_id, self._phi.target.one_basis())

    def multiply(self, a: Label, b: Label) -> Element:
        # Z-form, over the lift coordinate (no R-form / ElementOverR): each
        # section-product term `c(q)·L_label` decomposes as `(s_c, χ_w)`; push
        # `χ_w` through `φ` and fuse with the input chars `w1·w2` onto
        # `(s_c, R'-irrep)` labels.  (Same result as the previous
        # `to_R_form(section product)` fold, computed per term.)
        (s1, w1), (s2, w2) = a, b
        Rp = self._phi.target
        src = self._source_alg
        w12 = Rp.multiply_basis(w1, w2)                    # {w: n}
        out: "dict[Label, LaurentPoly]" = {}
        for label, lp in src.multiply(s1, s2).terms.items():
            s_c, r_coef = _section_split_via_lift(src, label)   # (section, RElement over R)
            pushed = self._phi.apply_RElement(r_coef)          # RElement over R'
            for wi, ni in w12.items():
                for wp, npp in pushed.terms.items():
                    for wd, m in Rp.multiply_basis(wi, wp).items():
                        coeff = ni * npp * m
                        if coeff == 0:
                            continue
                        lab = (s_c, wd)
                        t = lp * LaurentPoly({0: coeff})
                        out[lab] = t if lab not in out else out[lab] + t
        return Element({l: c for l, c in out.items() if not c.is_zero()})

    def _rho_transport(self, s: Label, w, source_rho) -> Label:
        # ρ on the lowered algebra: ρ(s) generally lands on a *different
        # section* carrying an induced unit character χ (sections differ by
        # unit chars — `ρ` restricts to `⋆` on the centre).  That χ must be
        # **pushed through φ into the R′-irrep**, not dropped: the lowered
        # ρ-image is `(section(ρ s), ⋆w · φ(χ))`.  (The previous code took only
        # `section_of(ρ s)` + `⋆w`, silently discarding χ — so ρ lost the
        # charge that ρ induces on a section, e.g. on a wrapped chord.)
        Rp = self._phi.target
        s2, chi = _section_split_via_lift(self._source_alg, source_rho(s))
        pushed = self._phi.apply_RElement(chi)            # RElement over R'
        new_terms: "dict" = {}
        sw = Rp.star_basis(w)
        for wp, npp in pushed.terms.items():
            for wd, m in Rp.multiply_basis(sw, wp).items():
                new_terms[wd] = new_terms.get(wd, 0) + npp * m
        nz = {b: c for b, c in new_terms.items() if c}
        if len(nz) != 1 or next(iter(nz.values())) != 1:
            raise ValueError(
                "lower_flavour.rho: ρ-induced character is not a single unit "
                f"(got {nz}); ρ is not a label permutation on this reduction")
        return (s2, next(iter(nz)))

    def rho(self, a: Label) -> Label:
        s, w = a
        return self._rho_transport(s, w, self._source_alg.rho)

    def rho_inverse(self, a: Label) -> Label:
        s, w = a
        return self._rho_transport(s, w, self._source_alg.rho_inverse)

    def embed_R(self, r: RElement) -> Element:
        Rp = self._phi.target
        if not isinstance(r, RElement) or r.ring != Rp:
            raise TypeError("embed_R: argument must be an RElement over R'")
        s_id = self._section_of(self._source_alg.identity())
        out: "dict[Label, LaurentPoly]" = {}
        for w, n in r.terms.items():
            if n == 0:
                continue
            lab = (s_id, w)
            t = LaurentPoly({0: n})
            out[lab] = t if lab not in out else out[lab] + t
        return Element({l: c for l, c in out.items() if not c.is_zero()})

    def r_label_decompose(self, label: Label):
        """Lift coordinate of the lowered algebra.  Its labels are already
        `(section, R'-irrep)` pairs `(s, w)`, so the coordinate is read off
        directly: section `(s, χ₀)` (the same section dressed by the trivial
        R'-irrep), single irrep `w`."""
        s, w = label
        return (s, self._phi.target.one_basis()), w

    def r_label_compose(self, section: Label, r_basis_label) -> Label:
        # Inverse of r_label_decompose: re-dress the section's gauge part by w.
        (s, _one) = section
        return (s, r_basis_label)

    def _label_section_decompose(
        self, label: Label,
    ) -> "tuple[Label, RElement]":
        # Obsolete-to-be (Plan 32): derivable from r_label_decompose via the
        # forward bridge ((s,w) ↦ ((s,χ₀), R'.basis_element(w))).
        s, w = label
        Rp = self._phi.target
        return (s, Rp.one_basis()), Rp.basis_element(w)

    def trace(self, a: Label, K: int = 20) -> RPowerSeries:
        # `Tr` is R-linear over the central embedding, so it is fully determined
        # by its value on sections: `Tr((s, χ)) = χ·Tr(M_s)`.  Transport:
        # `Tr'((s, w)) = w · φ(source.trace(M_s))`.  (`inner_product` then
        # follows from the default multiply-then-trace.)
        s, w = a
        Rp = self._phi.target
        pushed = self._phi.apply_RPowerSeries(self._source_alg.trace(s, K))
        w_elt = Rp.basis_element(w)
        coeffs = {q: w_elt * relem for q, relem in pushed.coeffs.items()}
        return RPowerSeries(
            Rp, {q: c for q, c in coeffs.items() if not c.is_zero()}, pushed.K,
        )

    def __repr__(self) -> str:
        return f"_LoweredFlavourKAlgebra({self._source_alg!r}, {self._phi!r})"
